### ISSUE TITLE
How to easily catch the raw event?

### ISSUE THREAD

**Issue by suntong** [middyjs/middy#1001]
Hi,

In normal AWS Lambda, I can use

```js
export const handler = async(event) => {
    console.log(JSON.stringify(event))
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
}
```

To catch the raw event, so that I can put the request in Lambda test. 

However, when using middy, I tried both using `.use(inputOutputLogger())` and/or --

```js
const postHandler = middy()
  .handler((event, context) => {
    console.log(JSON.stringify(event))
    return {
      statusCode: 200,
      body: '{...}'
    }
  })
```

However, in both cases, if I put the request in Lambda test, I'll get:

        ERROR	Error: [http-router] Unknown http event format
        at file:///opt/nodejs/node_modules/@middy/http-router/index.js:23:19
        at runRequest (file:///opt/nodejs/node_modules/@middy/core/index.js:85:17)

This is what I caught using middy, which cause the above `Unknown http event format` Error. I don't know what's missing:

```js
    "requestContext": {
      "accountId": "anonymous",
        "http": {
            "method": "POST",
            "path": "/user",
            "protocol": "HTTP/1.1",
            "userAgent": "curl/7.68.0"
        },
      "routeKey": "$default",
      "stage": "$default",
      "time": "01/Feb/2023:02:59:02 +0000",
      "timeEpoch": 1675220342118
    },
```

**Comment by willfarrell** [comment]
Please see AWS documentation https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html

**Comment by suntong** [comment]
> Please see AWS documentation https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html

Sorry I've read it several times but am still not sure how to catch the event json to put the request in Lambda test when using [middy](https://github.com/middyjs/middy).

With vanila/normal AWS Lambda (without using middy), I can do just fine.

**Comment by willfarrell** [comment]
The docs contain the data structure of the event

```
.use(before(request) => { console.log(request.event) })
```

**Comment by suntong** [comment]
> `.use(before(request) => { console.log(request.event) })`

Thanks

why I'm getting the following?

![image](https://user-images.githubusercontent.com/422244/216164540-86a199fe-efd2-4570-93c6-b9444c29d7f7.png)

**Comment by willfarrell** [comment]
oops, updated above
