### ISSUE TITLE
async handler support

### ISSUE THREAD

**Issue by suntong** [middyjs/middy#1002]
Does [middy](https://github.com/middyjs/middy) support async handlers? 

I wasn't able to make mine working. Here is my `routes`:

```js
const routes = [
  {
    method: 'GET',
    path: '/search',
    handler: middy(search).use(errorLogger())
  },
```

The `search` function is basically in the form of:

```js
async function search(event) {
myPromise
.then((message) => { 
    console.log("ret", message);
}).then(this).then(that)
.catch((message) => { 
    console.log(message);
})
}
```

However, the `search` will take a long time, and from the log I found that neither the `then` nor the `catch` messages are printed on console, which let me suspect that the async handler was returned before the `myPromise` is finished. Maybe wrapping another level of asyn/await would help? 

Sorry for such basic question, which from the historical questions I can tell that nobody needs help on such simple issue. thanks.

**Comment by willfarrell** [comment]
Middy only uses async/await. You're missing a `return` or `await` in your handler.

**Comment by suntong** [comment]
thanks for the reply.

> You're missing a `return` or `await` in your handler.

I'm omitting all `return`s for the simplicity, because either the `then` or the `catch` messages _should be_ printed on console . and,

```js
myPromise
.then((message) => { 
    console.log("ret", message);
}).then(this).then(that)
.catch((message) => { 
    console.log(message);
})
```

make calling like above is equivalent of using `await` right?

Sorry for being confused for such basic question.

**Comment by suntong** [comment]
Alright, I've prepared a repeatable and minimized example at:
https://gist.github.com/suntong/c3241d9d8339e3c87d49573f142a4618#file-index-mjs

neither the then nor the catch messages are printed on console

**Comment by suntong** [comment]
```
Response
{
  "statusCode": 200,
  "body": "{.. search ..}"
}

Function Logs
START RequestId: 1d2c5679-fd74-480e-80e2-5ac36a662828 Version: $LATEST
END RequestId: 1d2c5679-fd74-480e-80e2-5ac36a662828
REPORT RequestId: 1d2c5679-fd74-480e-80e2-5ac36a662828	Duration: 58.09 ms	Billed Duration: 59 ms	Memory Size: 128 MB	Max Memory Used: 66 MB	Init Duration: 221.37 ms
```

_Duration: 58.09 ms_

shall we reopen the issue until resolved?

**Comment by suntong** [comment]
> Alright, I've prepared a repeatable and minimized example

> shall we reopen the issue until resolved?

I'm still waiting for a reply...

**Comment by willfarrell** [comment]
```
async function search(event) {
await myPromise
.then((message) => { 
    console.log("ret", message);
}).then(this).then(that)
.catch((message) => { 
    console.log(message);
})
}
```

or

```
async function search(event) {
return myPromise
.then((message) => { 
    console.log("ret", message);
}).then(this).then(that)
.catch((message) => { 
    console.log(message);
})
}
```

**Comment by suntong** [comment]
Oh, just like that! I feel sorry to bother you with such simple problem. Thanks!
