### ISSUE TITLE
http-json-body-parser | Error message when body is undefined

### ISSUE THREAD

**Issue by afrittella** [middyjs/middy#1003]
**Describe the bug**
I have an issue with http-json-body-parser. When I call an endpoint and I put `Content-Type: application/json` with an empty body, I receive a `422 - Invalid or malformed JSON was provided` error.

**To Reproduce**
Create a lambda that uses middy and `jsonBodyParser`.
Call it with the header: `Content-Type: application/json` and no `body`.

**Expected behaviour**
IMHO the middleware should ignore undefined and null bodies, and not raise the 422 error.

I'm not sure if this is the right way to submit an issue, so please be patient with me. It's the first time here :D 

I would be happy to submit a PR, but need approval before proceeding :)

My proposal is the following:
Instead of this code:
```
try {
      const data = request.event.isBase64Encoded ? Buffer.from(body, 'base64').toString() : body;
      request.event.rawBody = body;
      request.event.body = JSON.parse(data, reviver);
} catch (cause) {
      const error = createError(422, 'Invalid or malformed JSON was provided');
      error.cause = cause;
      throw error;
}
```

This one:
```
try {
      const data = request.event.isBase64Encoded ? Buffer.from(body, 'base64').toString() : body;
      if (data === undefined || data === null) {
         return
      }
      request.event.rawBody = body;
      request.event.body = JSON.parse(data, reviver);
} catch (cause) {
      const error = createError(422, 'Invalid or malformed JSON was provided');
      error.cause = cause;
      throw error;
}
```

**Comment by willfarrell** [comment]
Thank for reporting. Having `if (typeof body === 'undefined') {return}` before the try/catch would make more sense and be faster. Do you have a use case when `null` would be passed in? 

If you can put a PR together with a new unit test, that would be great.

**Comment by afrittella** [comment]
Hi @willfarrell thanks for your reply.

I have a use case, when using 'serverless-offline' (https://github.com/dherault/serverless-offline). But I want to further investigate, to understand if `null` is coming from Buffer or not.

I will start a PR ASAP then :)

**Comment by willfarrell** [comment]
If `null` is coming from `serverless-offline` only, it should be fixed there and not in middy. Looking forward to it.

**Comment by afrittella** [comment]
I started working on the PR.

Some questions:
1. in my project, I'm using middy version 3, but we have the same "issue" in the current one (4). Am I supposed to work on version 3 too?
2. I found a test case that is explicitly mentioning "undefined", so I guess it's (or it was) a wanted behavior:
```
test('It should handle undefined as an UnprocessableEntity', async (t) => {
  const handler = middy((event) => {
    return event.body // propagates the body as a response
  })

  handler.use(jsonBodyParser())

  // invokes the handler
  const event = {
    headers: {
      'Content-Type': 'application/json'
    },
    body: undefined
  }

  try {
    await handler(event, defaultContext)
  } catch (e) {
    t.is(e.statusCode, 415)
    t.is(e.message, 'Invalid or malformed JSON was provided')
    t.is(e.cause.message, 'Unexpected token u in JSON at position 0')
  }
})
```

Sorry, asking before making a wrong PR... :D

**Comment by willfarrell** [comment]
Sorry, busy week.

Glad you noticed and asked. If there is a test, there is a good reason for it. Can you more about your use case that is causing the body to be `undefined`. This middleware should only be applied to endpoints that support `body` like `POST`, is that the case?

**Comment by afrittella** [comment]
Yep, applying it only to endpoints that support `body` is the simplest way to avoid problems in the future, I would agree with you, and I probably do this to avoid the issue with my API users. :) 

While it is not explicitly forbidden to include a `body` in a GET request, it could be semantically not correct.

But, depending on the API implementation, it might be that this middleware is applied to all endpoints of a REST API (and this is my case 😺 ).

The problem comes when you call any endpoint (that is using this middleware), and you specify `Content-Type: application/json` with an undefined body.

Maybe my approach is not correct, but IMHO, if I'm an API user and I forget to remove `Content-Type` for a GET request and the server replies to me with an "invalid JSON" error, I would be confused and disappointed. That's why probably the middleware should be smart enough to consider as acceptable, or ignore a `Content-Type` header with an undefined body.

WDYT?

**Comment by willfarrell** [comment]
You summarized it perfectly. It's all about balancing all the use cases. It this case I think opting for enforcing strict user inputs to ensure a predictable handler event will the best overall.

few things we can do is have better error message and/or documentation to help developers implementing the API or using that implemented API waste less time. Open to putting a PR together to update?

**Comment by afrittella** [comment]
Sure! Just let me understand if I should open it or you :)

**Comment by willfarrell** [comment]
Go for it
