### ISSUE TITLE
@middy/http-router HEAD method

### ISSUE THREAD

**Issue by alharirihamzah** [middyjs/middy#1006]
Hello there, I just wanna say what a great job you have done so far!
I have been enjoying using Middy with my Serverless Application, nicely done 👍

I am using `@middy/http-router` package to handle http routes in my application and now I am adding a new route to handle `HEAD` method but I noticed that `@middy/http-router` doesn't support that

Looking in code @ https://github.com/middyjs/middy/blob/main/packages/http-router/index.js#L62-L70:
```ts
export const Method = {
  Get: 'GET',
  Post: 'POST',
  Put: 'PUT',
  Patch: 'PATCH',
  Delete: 'DELETE',
  Options: 'OPTIONS',
  Any: 'ANY'
}
```

Head is not included in the Method object!

Is there any reason why isn't supported? am I missing something here?

I am happy to create a PR to add `HEAD` method

Thanks in advance ☺️

**Comment by willfarrell** [comment]
Hey, thanks for reporting. Complete oversight, a PR is most welcome.
