### ISSUE TITLE
processCache doesn't follow its type definition

### ISSUE THREAD

**Issue by dobeerman** [middyjs/middy#1007]
**Describe the bug**
The processCache's function interface is defined here [index.d.ts](https://github.com/middyjs/middy/blob/3147c6a919/packages/util/index.d.ts#L33) and its `fetch` argument's function supposes to have only one argument.

All official middlewares use two. For example, [index.js](https://github.com/middyjs/middy/blob/main/packages/s3/index.js#L29).

**To Reproduce**

```ts
const fetch = (request: LambdaRequest, cachedValues: Record<string, unknown> = {}) => {
  // ...
}

processCache(options, fetch); // Argument of type '(request: LambdaRequest, cachedValues?: Record<string, unknown>) => Values' is not assignable to parameter of type '(request: Request<any, any, Error, Context>) => any'.
```

**Environment (please complete the following information):**
 - Node.js: 18
 - Middy: 4.2.3
 - AWS SDK 3.267.0

**Comment by willfarrell** [comment]
A PR to update the types is welcome.
