### ISSUE TITLE
Appconfig middleware swallows underlying sdk client exception 

### ISSUE THREAD

**Issue by mju-spyrosoft** [middyjs/middy#1008]
**Describe the bug**
It seems that appconfig middleware swallows exception coming from AWS sdk client and it's throwing somewhat non descriptive error. Is this by design? This makes it really difficult to debug any configuration errors.

**To Reproduce**
How to reproduce the behaviour:
1. Sample code 
```ts
import middy from '@middy/core';
import appConfig from '@middy/appconfig';

async function baseHandler(event: any, context: any) {
  console.log(context.appconfig.config);
}

//This has to throw internally error for whatever reason
export const handler = middy(baseHandler).use(
  appConfig({
    fetchData: {
      config: {
        Application: 'xxx',
        ClientId: 'yyy',
        Configuration: 'www',
        Environment: 'zzz'
      }
    },
    setToContext: true
  })
);

```
2. Thrown error
```
{
    "errorType": "Error",
    "errorMessage": "Failed to resolve internal values",
    "stack": [
        "Error: Failed to resolve internal values",
        "    at getInternal (/var/task/dist/index.js:26269:11)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async appConfigMiddlewareBefore (/var/task/dist/index.js:26409:20)",
        "    at async runMiddlewares (/var/task/dist/index.js:26124:17)",
        "    at async runRequest (/var/task/dist/index.js:26081:5)"
    ]
}
```

**Expected behaviour**
Exception should expose underlying AWS SDK exception message

**Environment:**
 - Node.js: 18.13.0
 - Middy: ^4.2.3
 - AWS SDK - "@aws-sdk/client-appconfig": "^3.267.0" 

**Context**
Dont think it matters but In this specific case after calling aws sdk directly error was
```
{
    "errorType": "BadRequestException",
    "errorMessage": "Feature flag configurations must be accessed via AWS AppConfig Data's GetLatestConfiguration API.",
    "name": "BadRequestException",
    ...
}
```

**Comment by willfarrell** [comment]
Thanks for reporting. That `Failed to resolve internal values` error should have `cause` connected with it, but lambda doesn't log out `cause` yet. I've reported this issue to AWS: https://github.com/aws/aws-lambda-base-images/issues/75).

A work around would be to set `disablePrefetch:true` and logs errors yourself using `error-loggger`.

I'm going to close in favour of the AWS issue.
