### ISSUE TITLE
http-cors origins

### ISSUE THREAD

**Issue by neveenatik** [middyjs/middy#1010]
**Is your feature request related to a problem? Please describe.**
We have multiple domains that consumes our service therefore I need to configure CORS for multiple origins and one that has a dynamic part which would be easier to handle using a regex.

Reading the code I see that origins is tested using Array.includes method which does not cater for regex.

**Describe the solution you'd like**
It would be great if we can support regex values of origins which adds more flexibility to test origin against patterns rather than full strings.

**Describe alternatives you've considered**
I have to add a long list of strings and would need to update every now and then when a new origin would need to consume our service.

**Additional context**
I am happy to give it a try and open a PR.

**Comment by willfarrell** [comment]
There is an option to set `getOrigin` which is a function you can override with custom logic. Would that suit your needs?

```
const getOrigin = (incomingOrigin, options = {}) => {
  if (options.origins.length > 0) {
    if (incomingOrigin && options.origins.includes(incomingOrigin)) {
      return incomingOrigin
    } else {
      return options.origins[0]
    }
  } else {
    if (incomingOrigin && options.credentials && options.origin === '*') {
      return incomingOrigin
    }
    return options.origin
  }
}
```

**Comment by neveenatik** [comment]
Yes it would very well. Sorry I completely missed that option. Thank you @willfarrell for pointing that out I will resolve this issue.
