### ISSUE TITLE
Cannot read property 'Content-Type' of undefined

### ISSUE THREAD

**Issue by bayurzxsmtp** [middyjs/middy#1014]
**Describe the bug**
Returns the error "Cannot read property 'Content-Type' of undefined" when I try to invoke a lambda "get-method" function.

The module is autogenerated with the serverless framework boilerplate(aws-nodejs-typescript). I assume that at some point i am suppose to add the headers. I have added it at every possible point I can think of. 
**To Reproduce**
How to reproduce the behaviour:
1. Sample code:
 ```
const getGroups: APIGatewayProxyHandler = async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
  console.log('Processing event:', event)

  const result = await docClient.scan({
    headers: { 'Content-Type': 'application/json' },
    TableName: groupsTable
  }).promise()

  const items = result.Items
  return formatJSONResponse({
    headers: { 'Content-Type': 'application/json' },
    items,
    event,
  });
};

export const formatJSONResponse = (response: Record<string, unknown>) => {
  return {
    headers: { 'Content-Type': 'application/json' },
    statusCode: 200,
    body: JSON.stringify(response)
  }
}

 ```
4. Thrown error
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'Content-Type' of undefined",
    "trace": [
        "TypeError: Cannot read property 'Content-Type' of undefined",
        "    at httpJsonBodyParserMiddlewareBefore (/node_modules/@middy/http-json-body-parser/index.js:14:29)",
        "    at runMiddlewares (/node_modules/@middy/core/index.js:118:27)",
        "    at runRequest (/node_modules/@middy/core/index.js:78:15)",
        "    at Runtime.middy2 (/node_modules/@middy/core/index.js:32:16)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)"
    ]
}

```
**Expected behaviour**
A 200 status code response message

**Environment (please complete the following information):**
 - Node.js: [14]
 -     "@middy/http-json-body-parser": "^3.4.0"
    "@middy/http-json-body-parser": "^3.4.0"

 - AWS SDK [v3 ]
@aws-sdk/client-dynamodb": "^3.271.0"

**Additional context**

**Comment by willfarrell** [comment]
`@middy/http-json-body-parser` checks the header before it parses. It's impossible for an REST/HTTP Event to not have headers, so we purposely don't check for them. The error you're getting means it's looking at the source event to be properly structured and contain headers. If you're triggering manually, this is the source if the error.

https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html
