### ISSUE TITLE
Question: Using middy with step functions

### ISSUE THREAD

**Issue by lxhunter** [middyjs/middy#1022]
Hi,

again, i hope this is okay... 

Do you have any best practices of using middy with step functions? 

Cannot find anything on middy with step functions. 

Maybe it is a bad idea to use the combination as step functions have a whole different structure regarding the events, but also i could see a lot of benefit using middy.

Hope i am not wasting your time, may the force be with you,

Alex

**Comment by willfarrell** [comment]
I used middy with Step Functions all the time. They're the simplest because you're sending in a custom event. See https://middy.js.org/docs/events/intro

If you're interested in putting a Step Function event page together, the PR is welcome

**Comment by lxhunter** [comment]
Thank you that helped! I will have a look, if I can pile up something useful!
