### ISSUE TITLE
Global middleware

### ISSUE THREAD

**Issue by tmitchellgcio** [middyjs/middy#1025]
**Is your feature request related to a problem? Please describe.**
Not really related to a problem

**Describe the solution you'd like**
We need middleware on all handlers and we have a lot of them. It'd be easier to have this as some kind of global middleware handler rather than on each individual handler.

**Describe alternatives you've considered**
The alternative I tried was a different package but they don't support callbacks and we use them on every handler for some reason

**Comment by willfarrell** [comment]
You can create a wrapper function:
```
export default (handler) => middy().use(...).handler(handler)
```
This can be put in a private packge or a shared folder.

Is this what you're asking for?

**Comment by tmitchellgcio** [comment]
Not sure how that would attach to every handler without wrapping every handler in it unless I'm missing something I'm not familiar with.

**Comment by willfarrell** [comment]
You would have to import and wrap each handler that share the logic.

You want to to auto apply to all lambda without adding code? That would have to be a custom runtime with a bootstrap script that includes middy. We have no plans to create this, it would be a lot of work to do and maintain.

**Comment by tmitchellgcio** [comment]
Understood. Thanks for your help
________________________________
