### ISSUE TITLE
Use with reactive programming with the rxjs library

### ISSUE THREAD

**Issue by alopezvega** [middyjs/middy#1026]
I'm using the latest version of middy with the latest version of the rxjs library

I have the following method
```
@tracer.captureMethod()
  public getLead(documentNumber: string) {
    const params: GetCommand = new GetCommand({
      TableName: DynamoDbUtil.tableName,
      Key: {
        dni: documentNumber,
      },
    });

    console.log('Entra aca')
    return from(DynamoDbUtil.ddbDocClient.send(params)).pipe(
      tap(item => console.log(item)),
      map(result => result.Item as {})
    )
  }
```
and when I call it in my main middy function
```
const leadEvents = new DynamoDbUtil();
const leadEvent = async (event: any) => {
  logger.info(`Event: ${JSON.stringify(event)}`);

  return await lastValueFrom(leadEvents.getLead(event.documentNumber));
};

export const main = middy(leadEvent)
  .use(
    validator({
      eventSchema: transpileSchema(schema),
    })
  )
  .use(captureLambdaHandler(tracer))
  .use(logMetrics(metrics, { captureColdStartMetric: true }))
  .use(injectLambdaContext(logger, { clearState: true }))
  .use(errorLogger());
```
I have the following error
Error: Lambda function (lmb-dev-matrix-update-lead-01) returned error: ({"errorType":"TypeError","errorMessage":"source.subscribe is not a function","trace":["TypeError: source.subscribe is not a function","    at /var/task/node_modules/rxjs/dist/cjs/internal/lastValueFrom.js:10:16","    at new Promise (<anonymous>)","    at lastValueFrom (/var/task/node_modules/rxjs/dist/cjs/internal/lastValueFrom.js:7:12)","    at /var/task/events/leads.js:41:43","    at Generator.next (<anonymous>)","    at /var/task/events/leads.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/var/task/events/leads.js:4:12)","    at leadEvent (/var/task/events/leads.js:39:30)","    at runRequest (/var/task/node_modules/@middy/core/index.cjs:93:17)"]})

so rxjs is not compatible with middy?

**Comment by willfarrell** [comment]
I'm not familiar with rxjs, but from a quick skim of the docs, I don't see why it wouldn't work with Middy. Your error message points to an error inside the handler. Does the handler work without middy?

From a middy perspective, everything looks fine. None of the `@middy` middlewares touch your response. 

I do see that you're using AWS powertools which support older versions of Node.js and suggest using an older, unsupported, version of middy. Once Node.js is deprecated by AWS, they'll be updating.
