### ISSUE TITLE
Bundling documentation for cdk NodeJSFunction

### ISSUE THREAD

**Issue by everett1992** [middyjs/middy#1027]
The [NodeJSFunction cdk](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html) construct uses esbuild under the hood. It adds `aws-sdk` or `@aws-sdk/*` to `externals` by default to exclude the lambda runtime's built in sdk. 

Given your advice to "Always bundle the @aws-sdk/* with your project eventhough the Lambda runtime already includes it by default" the documentation should call this out and give an example of how to include the sdk

```

new nodejs.NodejsFunction(this, 'my-handler', {
 bundling: {
    externalModules: [], // pass empty array to disable default of @aws-sdk/*
  },
});

**Comment by willfarrell** [comment]
Like to open a PR to include in the docs?
