### ISSUE TITLE
Docs update for validator example

### ISSUE THREAD

**Issue by erolabzait** [middyjs/middy#1031]
**Is your feature request related to a problem? Please describe.**
The validator doesn't work without **httpJsonBodyParser** in front of it.

**Describe the solution you'd like**
Update the docs example.
```
export const handler = middy(originalHandler)
	.use(httpJsonBodyParser())
	.use(validator({ eventSchema: transpileSchema(schema) }))
	.use(httpErrorHandler())
	.use(cors());`
```

**Additional context**
Thanks for your great work 🎉

**Comment by willfarrell** [comment]
Would you like to submit a PR?
