### ISSUE TITLE
Middy http-router not working in ES5

### ISSUE THREAD

**Issue by nareshprajapatitatva** [middyjs/middy#1033]
**TypeError: httpRouterHandler is not a function**
Getting TypeError error when using http-router in ES5 .js file.

**To Reproduce**

Here is the sample code

```const middy = require('@middy/core');
const httpRouterHandler = require('@middy/http-router');

const getHandler = middy().handler((event, context) => {
  console.log('call from route');
  return {
    statusCode: 200,
    body: '{}'
  };
});

const routes = [
  {
    method: 'GET',
    path: '/health',
    handler: getHandler
  }
];

exports.health = middy().handler(httpRouterHandler(routes));
```

Thrown error
![image](https://user-images.githubusercontent.com/34063489/225225839-5c58f350-f99b-4954-9266-a86c4f8a1a3d.png)

**Expected behaviour**
It should call given route instead of giving an error

**Environment (please complete the following information):**
 - Node.js: nodejs16.x
 - Middy: 4.1.0
 - AWS SDK: 2.1293.0

**Comment by willfarrell** [comment]
Thanks for reporting, I've updated the dep and added in new tests. Seems to have resolved itself. See v4.2.8

**Comment by nbusser** [comment]
@willfarrell I encountered the same exact bug, even in v4.2.8
@nareshprajapatitatva Thank you for providing this workaround
