### ISSUE TITLE
Method in @middy/http-router not working

### ISSUE THREAD

**Issue by prembankerquicko** [middyjs/middy#1035]
**Describe the bug**
When using the @middy/http-router, I was laying out my routehandler and was using the import 'Method' for assigning the method
for which the API would be invoked. However, when running the test, it gives the following error.

`method: Method.Get,
                       ^
TypeError: Cannot read properties of undefined (reading 'Get')`

Previously the code was working fine but the issue arose suddenly while I was changing dependencies. I changed to different versions  but that also did not work.

**To Reproduce**
How to reproduce the behaviour:
1. Sample code. Below is a sample dummy code: 
`
const basePath = "/base-path";
const routes: Route<APIGatewayProxyEvent>[] = [
    {
        method: Method.Get,
        path: basePath,
        handler: getABC
    },
    {
        method: Method.Post,
        path: basePath,
        handler: postABC
    },
]

export const handleRoutes: MiddyfiedHandler = middy()
    .handler(httpRouterHandler(routes))
`
    

2. Input: Below is the test file. 

`const event: APIGatewayProxyEvent = {
    "resource": "/basepath",
    "path": "/basepath",
    "httpMethod": "GET",
    "headers": {
        "accept-encoding": "gzip",
        "Authorization": "",
        "content-type": "application/json; charset=utf-8",
        "Host": "",
        "User-Agent": "Dart/2.19 (dart:io)",
        "X-Amzn-Trace-Id": "",
        "X-Forwarded-For": "",
        "X-Forwarded-Port": "",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "accept-encoding": [
            "gzip"
        ],
        "Authorization": [
            ""
        ],
        "content-type": [
            "application/json; charset=utf-8"
        ],
        "Host": [
            ""
        ],
        "User-Agent": [
            "Dart/2.19 (dart:io)"
        ],
        "X-Amzn-Trace-Id": [
            ""
        ],
        "X-Forwarded-For": [
            ""
        ],
        "X-Forwarded-Port": [
            ""
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "queryStringParameters": {

    },
    "multiValueQueryStringParameters": {

    },
    "pathParameters": {

    },
    "stageVariables": {
        "api_username": "",
        "host": ""
    },
    "requestContext": {
        "resourceId": "",
        "authorizer": {
            "principalId": "",
            "integrationLatency": 0,
            
            
        },
        "resourcePath": "",
        "httpMethod": "GET",
        "extendedRequestId": "",
        "requestTime": "",
        "path": "",
        "accountId": "",
        "protocol": "HTTP/1.1",
        "stage": "",
        "domainPrefix": "",
        "requestTimeEpoch": 0,
        "requestId": "",
        "identity": {
            "cognitoIdentityPoolId": null,
            "accountId": null,
            "cognitoIdentityId": null,
            "caller": null,
            "sourceIp": "",
            "principalOrgId": null,
            "accessKey": null,
            "cognitoAuthenticationType": null,
            "cognitoAuthenticationProvider": null,
            "userArn": null,
            "userAgent": "Dart/2.19 (dart:io)",
            "user": null,
            "apiKey": null,
            "apiKeyId": null,
            "clientCert": null
        },
        "domainName": "",
        "apiId": ""
    },
    "body": null,
    "isBase64Encoded": false
}

async function test() {
    const result = await handleRoutes(event, {} as Context, {} as Callback)

    console.info(result);
}

test();
`

3. Thrown error : 
`method: Method.Get,
                       ^
TypeError: Cannot read properties of undefined (reading 'Get')`

**Expected behaviour**
The httpRouteHandler should redirect to the function 'getABC' and it would execute to give the result.

**Environment (please complete the following information):**
 - Node.js: 18.12.1
 - Middy: 4.2.7 & 4.0.2 (tried both) 
 - AWS SDK 2.1334.0

**Additional context**
I was able to implement a patch fix where I changed 
`method: Method.Get` to `method: "GET" as Method` (directly assigning the enum) and it was working so probably the issue is something related to middy not being able to recognise the input event.

**Note**
Apologies for not being able to format the code properly.

**Comment by nbusser** [comment]
@prembankerquicko I encountered the exact same bug, using the same middy versions.

Thank you for providing your useful workaround

**Comment by robdobtob** [comment]
Another workaround is to set package.json to exclude specifically this package version. Assuming that this is regression and will be fixed if another package is released

```"@middy/core": "^4.2.5 <4.2.8  || ^4.2.5 >4.2.8"```
would recommend doing this for all the middy modules you are using.

**Comment by willfarrell** [comment]
If someone can put a PR together to update the TS, I can release a new version.

**Comment by cpuccino** [comment]
Getting this `No matching export in "node_modules/@middy/http-router/index.js" for import "Method"` ^4.3.0
