### ISSUE TITLE
Add in npm package provenance (sigstore)

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#1044]
https://github.blog/2023-04-19-introducing-npm-package-provenance/
https://docs.npmjs.com/generating-provenance-statements

> Note: At this time, lerna and yarn are not supported tools for publishing your packages with provenance.

https://github.com/lerna/lerna/issues/3657

**Comment by JamesHenry** [comment]
FYI https://github.com/lerna/lerna/issues/3657#issuecomment-1535284598

**Comment by willfarrell** [comment]
Thanks!
