### ISSUE TITLE
onError middlewares being called out of order. 

### ISSUE THREAD

**Issue by jtoronto** [middyjs/middy#1048]
**Describe the bug**

I want the messages from `validator`'s `request.error.cause` in my http response, so I wrote a middleware inserted before `httpErrorHandler` that inserts a string of the causes into `request.error.message`. 

The problem is that it seems like `httpErrorHandler` is being called before my custom middleware even though it's the last middleware in the chain. 

I inserted a console.log statement in the beginning of the `httpErrorHandler` and confirmed that it's logging the (unmodified) request before my middleware gets a hold of it. 

**To Reproduce**
```
const errorTransformer: MiddlewareObj = {
  onError: async (request) => {
    if (request.error) {
      let errorMessage = '';
      Object.values(request.error.cause).map((entry) => (errorMessage += '\n' + entry.message));
      request.error.message = errorMessage;
    }
    logger.debug(request, 'Request after treatment.');
    return Promise.resolve();
  },
};
```
```
handler
  .use(jsonBodyParser())
  .use(validator(validatorSchema))
  .use(errorTransformer)
  .use(
    httpErrorHandler({
      logger(_error) {
        logger.error(_error);
      },
    }),
  );
```
In `httpErrorHandler`
```
 const httpErrorHandlerMiddlewareOnError = async (request)=>{
        console.log(JSON.stringify(request), 'incoming request')
        if (request.response !== undefined) return;
        if (typeof options.logger === 'function') {
            options.logger(request.error);
.... truncated.

  ``` 

The log from the above console.log statement is

```
  "error": {
        "name": "BadRequestError",
        "statusCode": 400,
        "status": 400,
        "expose": true
    },
```
This is the first log message: 

Then the log message from my middleware

```
"error": {
        "type": "HttpError",
        "message": "\nmust have required property 'lastName'\nmust have required property 'companyName'\nmust have required property 'jobTitle'\nmust have required property 'source'\nmust have required property 'timeZone'",
        "stack": "BadRequestError: Event object failed validation\n    at createError ...truncated
        "name": "BadRequestError",
        "statusCode": 400,
        "status": 400,
        "expose": true
    },
```
**Expected behaviour**

The `request` object in httpErrorHandler should have the additional properties (message mostly) that my middleware inserted into it because it's supposed to be called _after_ my middleware. All indications point to that it's being called before. 

**Environment (please complete the following information):**
 - Node.js: v17.9.0
 - Middy: 3.13
 - AWS SDK aws-cli/2.11.12 Python/3.11.2 Darwin/22.4.0 exe/x86_64 prompt/off

**Additional context**

**Comment by jtoronto** [comment]
Update: 

It turns out doing it backwards worked. 

```
handler
  .use(jsonBodyParser())
  .use(validator(validatorSchema))
  .use(
    httpErrorHandler({
      logger(_error) {
        logger.error(_error);
      },
    }),
  )
  .use(errorTransformer);
```
That's counterintuitive to how this graphic explains it. It should only go backwards on the `after` hook but the onError track should go in the same order as `before` no? 

![Screenshot 2023-04-27 at 4 19 28 PM](https://user-images.githubusercontent.com/4776935/234981564-e1417b90-2a13-4677-8498-883fc252ee97.png)

**Comment by willfarrell** [comment]
`onError` runs in the same order as `after`. I think that image in the docs is outdated (I'll update shortly, sorry about that), it should be this one (which is a little better, but still room for improvement).

![middy-middleware-engine](https://user-images.githubusercontent.com/1097020/234990112-f31dcd78-261b-4963-b041-4e567ac7cd30.png)

This show an error happening in `before` skips the rest and starts on `onError`.

In your example above `errorTransformer` needs to be last as you discovered because of how it's written. `httpErrorHandler` takes the error and creates a response based on it and sets `request.response`. If you wanted to have `errorTransformer` included earlier you would need to override `request.response.body` with your change.
