### ISSUE TITLE
I keep getting TypeError: eventSchema is not a function

### ISSUE THREAD

**Issue by basselabbara** [middyjs/middy#1050]
**Describe the bug**
I get this error every time I try to hit an endpoint while running serverless offline.
Stack: NX, typescript, serverless.

**To Reproduce**
How to reproduce the behaviour:
1. run 'sls offline'
2. hit an endpoint that uses validator

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: ^4.3.0

**Comment by willfarrell** [comment]
I need more information to help. However, it sounds like you're using `@middy/validator` and passing in a JSON Schema without first transpiling it into a javascript function.

**Comment by basselabbara** [comment]
@willfarrell I'm passing a typescript object actually. Please let me know what info can help you.

**Comment by basselabbara** [comment]
@willfarrell and here's the middyWrapper function:
```
import middy from '@middy/core'
import jsonBodyParser from '@middy/http-json-body-parser';
import httpErrorHandler from '@middy/http-error-handler';
import validator from '@middy/validator';
import { Context,  } from 'aws-lambda';

type handler = (event: unknown, context: Context) => Promise<{statusCode: number, body: string}>;

export const middyWrapper = (handler: handler, eventSchema: unknown) => {
  return middy(handler)
    .use(jsonBodyParser())
    .use(validator({ eventSchema }))
    .use(httpErrorHandler());
}
```

**Comment by willfarrell** [comment]
Thanks. As I mentioned above:

> it sounds like you're using @middy/validator and passing in an object formatted to JSON Schema without first transpiling it into a javascript function.

Your `createSchema` needs to be wrapped in `transpileSchema`. Take a look at this example: https://middy.js.org/docs/middlewares/validator#sample-usage
