### ISSUE TITLE
eventNormalizer doesn't export a function under CommonJS

### ISSUE THREAD

**Issue by kitsunde** [middyjs/middy#1052]
For whatever reason in 4.4.1 the `@middy/event-normalizer` export doesn't export a middleware, instead it's under `default`. Meanwhile `input-putput-logger` does, which is confusing.

```js
const { default: eventNormalizer } = require('@middy/event-normalizer');
const inputOutputLogger = require('@middy/input-output-logger');

console.log(eventNormalizer, inputOutputLogger)
```

Produces:

> [Function: eventNormalizerMiddleware] [Function: inputOutputLoggerMiddleware]

It would be nice if the exports under CJS could be made consistent.

**Comment by willfarrell** [comment]
I see the issue. They both are setup the same way, except `eventNormalizerMiddleware` has an additional export for a helper function. Releasing what I think should fix it now. Re-open if it needs more attention

**Comment by kitsunde** [comment]
I can confirm it's working, thanks!
