### ISSUE TITLE
Error while trying to return a S3 client ReadableStream on streamifyResponse

### ISSUE THREAD

**Issue by razvan-kg** [middyjs/middy#1053]
**Describe the bug**
Trying to return the streamify Body from S3 client response on **GetObjectCommand**
The Body property of S3 response is a **SdkStreamMixin** interface that has a **transformToWebStream** function which returns a  **ReadableStream**

Based on the doc https://github.com/middyjs/middy/blob/90eb919b0664ab772ef750fb45c73193c043bc72/website/docs/intro/06-streamify-response.md the handler body response can be a string or **ReadableStream** bun when returning the s3 Body it throws a error.
Did try as well with **transformToWebStream** that returns a **ReadableStream** as well throws a error 

Look like is failing on calling the the global **awslambda.HttpResponseStream.from** function, with the new **responseStream** and the current **handlerResponse** metadata. I dont know what the global function do under the hood. There is any way to get the aws documentation for it ?

On trying to debug the issue if i return directly the S3 Body response and not calling the transformToWebStream and remove the body property from **handlerResponse** before calling the **HttpResponseStream.from** on this line https://github.com/middyjs/middy/blob/main/packages/core/index.js#L55 , everything is working as expected. The body stream is store as well in the **handlerBody**, don't know what HttpResponseStream.from dose but feels like it dose not need to body property and only the statusCode and the headers to be required

**To Reproduce**
How to reproduce the behaviour:
1. Sample code '...'  
```
export const handler = middy({ streamifyResponse: true }).handler(
  (event, context) => {
          const command = new GetObjectCommand(s3Input)
          const response = await s3Client.send(command)
          const { Body, ContentType } = response

          return {
            statusCode: 200,
            headers: {
              "Content-Type": ContentType
            },
            body: Body
          }
  }
)         

```

Thrown error when returning the directly the S3  Body response
`Invoke Error    {"errorType":"TypeError","errorMessage":"Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle","stack":["TypeError: Converting circular structure to JSON","    --> starting at object with constructor 'Socket'","    |     property 'parser' -> object with constructor 'HTTPParser'","    --- property 'socket' closes the circle","    at JSON.stringify (<anonymous>)","    at HttpResponseStream.from (file:///var/runtime/index.mjs:862:38)","    at Runtime.handler (/var/task/node_modules/@middy/core/index.cjs:58:59)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1119:26)"]}`

Thrown error when returning S3 Body with transformToWebStream
` Invoke Error    {"errorType":"Error","errorMessage":"handler response not a ReadableStream","stack":["Error: handler response not a ReadableStream","    at Runtime.handler (/var/task/node_modules/@middy/core/index.cjs:76:19)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1119:26)"]}`

**Expected behaviour**
To return the stremify response 

**Environment (please complete the following information):**
 - Node.js: 18.16.0
 - Middy: 4.4.2
 - AWS SDK: v3
 - S3Client: 3.332.0

**Additional context**

**Comment by willfarrell** [comment]
What you have is right, the issue is that the SDK S3 response Body isn't a proper Node.js ReadableStream. You need to turn it into a Readable using `Readable.from()`. Super frustrating, I know. That's why I created `@datastream/aws/s3`, to always have consistent and interoperable streams that can just snap together.

```js
import { pipejoin } from '@datastream/core'
import { awsS3GetObjectStream } from '@datastream/aws/s3'
...
   const streams = [
      await awsS3GetObjectStream({
        Bucket: bucket,
        Key: key
      })
      // ...
    ]
    return {
      statusCode: 200,
      headers: {
        'Content-Type': `image/...`,
        'Cache-Control': 'public, max-age=31536000, immutable'
      },
      body: pipejoin(streams)
    }
```

See https://github.com/willfarrell/datastream/blob/main/packages/aws/s3.js#L24-L33 for source if you don't want to use the lib (docs in the works).

**Comment by razvan-kg** [comment]
Hi @willfarrell, yes was a bit confusing and frustrating that the ReadableStream are not the same, did end up using just the Readable.from() and passing the S3 body, and everything is working 
Thank you so much for your response
