### ISSUE TITLE
http-json-body-parser gives 415 error for unprocessable entity

### ISSUE THREAD

**Issue by ChangoFoster** [middyjs/middy#1054]
**Describe the bug**
When parsing bad JSON the middleware throws a 415 error code ([Unsupported media type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415)) but with the correct error message of "Invalid or malformed JSON was provided". This should have a 422 code of [Unprocessable content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)

**To Reproduce**
This test has the example: https://github.com/middyjs/middy/blob/main/packages/http-json-body-parser/__tests__/index.js#L116

**Expected behaviour**
It should throw the same error but with 422 status code

**Environment (please complete the following information):**
 - Any

**Additional context**
I believe this line needs to be changed and the related tests to fix this issue: https://github.com/middyjs/middy/blob/main/packages/http-json-body-parser/index.js#L34

**Comment by ChangoFoster** [comment]
Reading the nitty gritty I think you're correct and also thanks for the ridiculously quick response! I think it might be worth changing this line in the docs as I think that's where I got confused:

>  Also handles gracefully broken JSON as UnprocessableEntity (422 errors) if used in combination with httpErrorHandler.

**Comment by willfarrell** [comment]
Good catch one the docs, I'll update now.
