### ISSUE TITLE
http-error-handler failing for `createError.InternalServerError`

### ISSUE THREAD

**Issue by uttrasey** [middyjs/middy#1055]
**Describe the bug**
`@middy/http-error-handler` does not work with `InternalServiceError` from 'http-errors'

**To Reproduce**

Example 1
```
import createError from 'http-errors'

const handler = () => {
    throw createError(500, 'Bad things.')     
}
```

Example 2
```
import createError from 'http-errors'

const handler = () => {
    throw new createError.InternalServerError('Bad things.')
}
```

**Expected behaviour**
Response code of lambdas should be 
```
{
    statusCode: 500,
    body: 'Internal service error,
    ...
}
```

**Actual Behaviour**

- Exception propogates

**Environment (please complete the following information):**

-     "@middy/http-error-handler": "^4.4.2",
 -  "http-errors": "^2.0.0",
 -    node 18

**Additional context**
This code works for other createError things such as BadRequest. 500 doesn't seem to get caught

**Comment by willfarrell** [comment]
This is by design to prevent leaking details to attackers. Try adding in the `fallbackMessage` option. See unit test below.

```javascript
test('It should not send error to user', async (t) => {
  const expectedError = createError(500, 'InternalError')

  const handler = middy(() => {
    throw expectedError
  })

  handler.use(
    httpErrorHandler({ logger: false, fallbackMessage: 'Error: unknown' })
  )

  const response = await handler(event, context)
  t.deepEqual(response, {
    statusCode: 500,
    body: 'Error: unknown',
    headers: {
      'Content-Type': 'text/plain'
    }
  })
})
```

**Comment by uttrasey** [comment]
Got it, thanks @willfarrell

**Comment by uttrasey** [comment]
Docs are not really that clear

> fallbackMessage (default to null) - When non-http errors occur you can catch them by setting a fallback message to be used. These will be returned with a 500 status code.

I'm catching business exceptions and throwing `createError.InternalServerError('Bad things.')` which IMO is a HTTP error, no?

**Comment by willfarrell** [comment]
Thanks for the feedback, I'll push an update for the docs.
