### ISSUE TITLE
Docs search returns broken links

### ISSUE THREAD

**Issue by jcelmeta14** [middyjs/middy#1057]
**Describe the bug**

Links from search results on middy.js.org are broken

**To Reproduce**
How to reproduce the behaviour:
1. Go to middy.js.org
2. Search for anything (in my case execution order)
3. Nothing happens and error is shown in console (it seems that url concat is wrong?)
<img width="441" alt="image" src="https://github.com/middyjs/middy/assets/22294784/70a37508-a282-4c4b-a439-85bb442e5988">

**Expected behaviour**
Redirected to correct docs page

**Environment (please complete the following information):**
 - Any browser

**Additional context**
Just trying to search the docs for stuff.

**Comment by willfarrell** [comment]
Thanks for reporting! Interested in putting a PR together?

**Comment by harish-lifex** [comment]
I tried reproducing it in local but could not. I noticed the code for handling link click is different in production and local

<img width="328" alt="Screenshot 2023-05-31 at 11 21 02 AM" src="https://github.com/middyjs/middy/assets/97011940/9d66b033-489c-44bf-8da4-016f8308a134">
<img width="346" alt="Screenshot 2023-05-31 at 11 20 53 AM" src="https://github.com/middyjs/middy/assets/97011940/831297f0-6634-4a0b-93eb-43f8af8e93c5">

**Comment by harish-lifex** [comment]
Updating `docusaurus-lunr-search` should fix issue. Should I create a PR for this ?

**Comment by willfarrell** [comment]
Yes, please!
