### ISSUE TITLE
Improve compatibility with Remix loaders/actions

### ISSUE THREAD

**Issue by CSFlorin** [middyjs/middy#1062]
**Is your feature request related to a problem? Please describe.**
As some background, Remix is a popular full-stack React framework built on React Router to include file-based routing and server-side rendering. Each route file has an optional `loader` that runs on the server to fetch any data that the default exported component uses. A route file may also include an `action` which is executed when a form is submitted to that route. However, Remixers have to repeat common tasks like getting the user from the session cookie in every single loader and action they want it in and could really use middleware. Check out the RFC to implement middleware in Remix here for some idea of the problems they need to solve for: https://github.com/remix-run/react-router/discussions/9564

I found middy and thought it might actually have everything needed. I've made a demo of middy used for a Remix loader here https://stackblitz.com/edit/remix-run-remix-uconqh?file=app%2Froot.tsx and I was pleasantly surprised it mostly just works, even the types get successfully passed through. The only thing I notice is the following error happening after everything for some reason:

```
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/node:stream/promises"',
  error: Error: No route matches URL "/node:stream/promises"
      at getInternalRouterError (/home/projects/remix-run-remix-uconqh/node_modules/@remix-run/router/router.ts:4013:5)
      at Object.query (/home/projects/remix-run-remix-uconqh/node_modules/@remix-run/router/router.ts:2637:19)
      at handleDocumentRequestRR (/home/projects/remix-run-remix-uconqh/node_modules/@remix-run/server-runtime/dist/server.js:163:35)
      at requestHandler (/home/projects/remix-run-remix-uconqh/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
      at eval (/home/projects/remix-run-remix-uconqh/node_modules/@remix-run/express/dist/server.js:39:28)
}
No routes matched location "/node:stream/promises" 
GET /node:stream/promises 404 - - 1.790 ms
```

**Describe the solution you'd like**
Twofold,
1. I'd like a direct solution for that error message because even though it doesn't seem to cause the app to crash, there must be something wrong.
2. I would love it if we could complete the story of full-featured middleware for Remix loaders and actions with middleware, addressing all the concerns in the aforementioned RFC and add it to the docs here and even submit it as a potential solution for that RFC.

**Comment by willfarrell** [comment]
`node:stream/promises` used by `@middy/core` and is built into Node.js 16+. Are you using the latest runtime version?
I can't speak to why an http request is being made to `/node:stream/promises`, the only think I can think of is a build process that isn't aware of the new syntax.

**Comment by CSFlorin** [comment]
Cool could be the node version. Can close this. Thanks
