### ISSUE TITLE
[@middy/secrets-manager] Add conditional caching based on Rotation Window

### ISSUE THREAD

**Issue by KillDozerX2** [middyjs/middy#1063]
Using the secrets manager middleware feels amazing however a very common scenario with Secrets is the fact that they get rotated, and the current caching support for them only allows us to cache for a certain amount of time.

We would like to be able to specify a rotation window and the plugin will then set the cache expiry based on the time left from the last rotated timestamp.

Technically we could create another middleware that serves this use case, but secret rotation is fairly common.

**Comment by willfarrell** [comment]
The [GetSecretValueCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-secrets-manager/classes/getsecretvaluecommand.html) doesn't return the details, but [DescribeSecretCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-secrets-manager/classes/describesecretcommand.html) does. I'll have to think on the best way to opt-in to it, and how to connect to the internal cache.

**Comment by willfarrell** [comment]
Question: Should it handle changes in the rotation rules during the life cycle of a lambda?

**Comment by KillDozerX2** [comment]
> Question: Should it handle changes in the rotation rules during the life cycle of a lambda?

I don't think that would be a good idea, but there are situations where the key could be rotated while the lambda is running. We should think about it.

**Comment by KillDozerX2** [comment]
> The [GetSecretValueCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-secrets-manager/classes/getsecretvaluecommand.html) doesn't return the details, but [DescribeSecretCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-secrets-manager/classes/describesecretcommand.html) does. I'll have to think on the best way to opt-in to it, and how to connect to the internal cache.

And sometimes, there are not rotations details available and the secret rotation is done manually using some other process, does it make sense to use Last Updated Time in this situation?

**Comment by KillDozerX2** [comment]
Hi @willfarrell I just noticed that the documentation site hasn't been updated.

**Comment by willfarrell** [comment]
Thanks, publishing now
