### ISSUE TITLE
Unable to use 'streamifyResponse' attribute due to TypeScript type error

### ISSUE THREAD

**Issue by dobeerman** [middyjs/middy#1069]
**Describe the bug**
When trying to use the `streamifyResponse` attribute as documented in the [Middy documentation](https://middy.js.org/docs/intro/streamify-response/), TypeScript throws an error stating that object literal may only specify known properties, and 'streamifyResponse' does not exist in type 'MiddyInputHandler<unknown, any, Context>'.

**To Reproduce**
Use the code example from the [documentation page](https://middy.js.org/docs/intro/streamify-response/#lambda-invokewithresponsestream-example) 

**Expected behaviour**
I expected to be able to use the `streamifyResponse` attribute as documented without any TypeScript errors.

**Environment (please complete the following information):**
- Node.js: 18
- Middy: 4.5.2
- AWS SDK: 3.358.0

**Additional context**
This issue prevents the use of the `streamifyResponse` attribute as documented, and it seems like the TypeScript types might not be updated or in sync with the documentation.

**Comment by willfarrell** [comment]
Would you like to submit a PR to update the type to resolve this?

**Comment by agilanigp** [comment]
I am facing the same issue. The documentation says to pass `{ streamifyResponse: true }` as options to `middy()` but the typescript throws an error.

![Screenshot 2023-06-28 at 01 05 11](https://github.com/middyjs/middy/assets/100960465/d248c19c-73a6-4e30-941c-39dc5ecf51bf)

**Comment by naorpeled** [comment]
@willfarrell would love to take this :)

**Comment by willfarrell** [comment]
@naorpeled Go for it. I think the issue is because there isn't a handler passed in as the first argument. The types expect 2, while middy allows the handler to be optional now.
