### ISSUE TITLE
Fetch logger from request context or internal storage in http error handler middleware

### ISSUE THREAD

**Issue by rathourarv** [middyjs/middy#1076]
**Potential problem**

I am trying to set values like logger in request context which is required across my custom middlewares or handlers. A simple example would be like -
```javascript
export const LoggerMiddleware = (): middy.MiddlewareObj<APIGatewayProxyEvent, APIGatewayProxyResult> => {
    const before: middy.MiddlewareFn<APIGatewayProxyEvent, APIGatewayProxyResult> = async (request): Promise<void> => {
        const logger: Logger = winston.createLogger({
            level: 'info',
            format: winston.format.json(),
            transports: [new winston.transports.Console()]
        });
        Object.assign(request.context, logger)
    }
    return {
        before
    }
}
```

And I can access the logger from context without any extra imports or variables.  I am also using http error handler middleware which needs logger as an option otherwise defaults to `console.error` which defeats the purpose of what I am trying to achieve here. 

**Potential solution**

I would like to fetch logger from context first then options else fallback to console.error or whatever order is preferred based on the discussion. 

**Potential alternate solution**

Probably, We can also utilize internal storage to store these values. Based on docs, internal storage should be used where caching is required.

**Comment by willfarrell** [comment]
I would say, use internal for sharing anything between middlewares, it just happens caching is the most likely use case. `context` should be used to pass anything to the handler.

Few options:
a) Add your logger is in internal as well, you can pass in a wrapper function to the http error handler options that gets the logger function, then passes the arguments into it.
b) Fork the httpErrorHandler to pull the logger from context or internal
c) export the logger by itself, and pass it into other middlewares as needed

I think `c` is the best option, this is the approach AWS Powertools uses as well.
