### ISSUE TITLE
jsonBodyParser shouldn't be case-sensitive

### ISSUE THREAD

**Issue by theburningmonk** [middyjs/middy#108]
A bunch of tools encode the content-type header using different casing, and this causes the endpoint to fail as the body is not JSON decoded before handing it over to my function code.

**Comment by vladgolubev** [comment]
That's what https://github.com/middyjs/middy/pull/89 was created for!

Should be as easy as `.use(httpHeaderNormalizer())`

**Comment by theburningmonk** [comment]
aha, didn't realise that, thanks!
