### ISSUE TITLE
Can't access to the base Handler

### ISSUE THREAD

**Issue by cdominguezg** [middyjs/middy#1083]
**Is your feature request related to a problem? Please describe.**
I can't access to the base handler. It would be nice if I were able to access to baseHandler for integration testing, for example.

**Describe the solution you'd like**
A method for cleaning the handler middlewares.

**Describe alternatives you've considered**
Regarding [to this issue](https://github.com/middyjs/middy/issues/724) I tried to set the after, before and the rest of methods as undefined, but still executes the middlewares.

**Comment by willfarrell** [comment]
Have you tried: https://github.com/middyjs/middy/issues/724#issuecomment-1276493271

**Comment by cdominguezg** [comment]
Thanks for the reply! Yeah, I'm doing this way, but I don't know if makes sense to have two exports in the same just for this case

**Comment by willfarrell** [comment]
I guess you could `handler.__baseHander = baseHandler` if you didn't want the export ...

**Comment by cdominguezg** [comment]
Hey @willfarrell  we tried, but since we are using Typescript, linter give us an error. Can I do this feature? I can open a PR with a removeMiddlewares method for testing purposes.
