### ISSUE TITLE
TypeScript improvement: `@middy/http-json-body-parser` should support API Gateway V2 events

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#1085]
As discussed in #1023 and suggested by @apalchys:

---

List of issues my team see (I'm going to keep it up to date):

- `@middy/http-json-body-parser` defines event using legacy `APIGatewayEvent` which describes event payload format v1. No Payload format v2 support.

_Originally posted by @apalchys in https://github.com/middyjs/middy/issues/1023#issuecomment-1484228944_

**Comment by willfarrell** [comment]
This is now merged into the v5 branch
