### ISSUE TITLE
TypeScript improvement: `Context` should keep track of changes made by middleware(s)

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#1088]
As suggested by @ben-eb in #1023:

---

Hello, thank you for your work on Middy 🙂 

It would definitely be nice if the internal types kept track of extensions made by the middleware(s) to the `Context` object. Whilst the following type checks nicely;

```typescript
import {Context as LambdaContext} from "aws-lambda";
import middy from "@middy/core";
import secretsManager from "@middy/secrets-manager";

type MyContext = LambdaContext & {
    mySecret: { key: string }
};

export const handler = middy<unknown>()
    .use(secretsManager({
        fetchData: {
            mySecret: 'mySecret'
        },
        setToContext: true
    }))
    .handler(async (event: unknown, context: MyContext) => {
        // don't log your actual secrets in production :)
        console.log(context.mySecret.key);
    });
```

Trying to use this `handler` in test code will result in the following TypeScript error:

```
TS2345: Argument of type 'Context' is not assignable to parameter of type 'Context & Record<"mySecret", any>'.  
Property 'mySecret' is missing in type 'Context' but required in type 'Record<"mySecret", any>'
```

The test code looks like this:

```typescript
import {Context as LambdaContext} from "aws-lambda";
import {handler} from "./handler.js";

const context: LambdaContext = {
    awsRequestId: 'testId',
    callbackWaitsForEmptyEventLoop: false,
    functionName: 'test-lambda',
    functionVersion: '1',
    invokedFunctionArn: 'a',
    memoryLimitInMB: '1',
    logGroupName: 'myloggroup',
    logStreamName: 'mystream',
    getRemainingTimeInMillis: () => 1,
    done() {
        /* deprecated method that is required in the type */
    },
    fail() {
        /* deprecated method that is required in the type */
    },
    succeed() {
        /* deprecated method that is required in the type */
    }
}

await handler({}, context);
```

We can put a `// @ts-expect-error` comment here but it would be great not to have to use this!

_Originally posted by @ben-eb in https://github.com/middyjs/middy/issues/1023#issuecomment-1677086198_

**Comment by m-radzikowski** [comment]
Maybe I'm missing something, but I think this is already working? Middlewares enrich the `Context` type if you define `setToContext=true`.

https://github.com/middyjs/middy/blob/a080562bbc6cbb238d4471b50ea6da9743a8c478/packages/secrets-manager/index.d.ts#L12-L16

This is working for me in TypeScript:

```ts
import secretsManager from "@middy/secrets-manager";
import middy from "@middy/core";

export const handler = middy()
    .use(secretsManager({
        fetchData: {
            mySecret: 'mySecret'
        },
        setToContext: true
    }))
    .handler(async (event, context) => {
        context.mySecret // type: any
        context.notdefined // error: TS2339: Property  notdefined  does not exist on type  Context & Record<"mySecret", any> 
    });
```

**Comment by ben-eb** [comment]
@m-radzikowski Problem occurs when testing the lambda function, you have to pass an input context object with all of the same properties that the middleware will extend the context with. I wrote in my original post that we can use `@ts-expect-error` to work around this but then that can mask other errors from your lambda function.

**Comment by lmammino** [comment]
This should have been completed in the work happening in the `release/5.0` branch
