### ISSUE TITLE
Middy handler always requires an async handler

### ISSUE THREAD

**Issue by minjie0501** [middyjs/middy#1096]
**Describe the bug**
The middy handler always expects the lambda handler to return `void` or `Promise<any>`. Now i have to make my handlers async even if they don't do any async tasks. I would like to use it with a synchronous handler.

**To Reproduce**
How to reproduce the behaviour:
Sample code:
```
import middy from "@middy/core";
import { APIGatewayProxyEvent, Context } from "aws-lambda";

const lambdaHandler = (event: APIGatewayProxyEvent, context: Context) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: "Hello world!",
      input: event,
    }),
  };
};

export const handler = middy(lambdaHandler);

```

Thrown error:
`Type '{ statusCode: number; body: string; }' is not assignable to type 'void | Promise<any>'.`

**Expected behaviour**
Middy should allow sync handlers

**Environment (please complete the following information):**
 - Node.js: 18
 - Middy: 4.6.1

**Comment by willfarrell** [comment]
Sounds like the types need to be updated. Like to put a PR together?

**Comment by cjbt** [comment]
Took a stab at this: https://github.com/middyjs/middy/pull/1102. Let me know if I'm missing anything.

**Comment by minjie0501** [comment]
> Took a stab at this: #1102. Let me know if I'm missing anything.

Haven't really had time to take a look myself, thanks for the PR! 🙌
