### ISSUE TITLE
Cannot read properties of undefined (reading 'Content-Type')

### ISSUE THREAD

**Issue by RaiSaugat** [middyjs/middy#1099]
**Describe the bug**
Error when trying to hit the lambda API.

**To Reproduce**
How to reproduce the behaviour:
1. Sample code 
This is what I have used as middy.
![image](https://github.com/middyjs/middy/assets/19557538/371ec7e0-5002-4f41-8a75-55bdfe1fc4a0)

2. Input
   There is lambda authorizer function that add policy and then the function is passed to the middy.
   `export const main = middyfy(authorizer);`
   
   The function is quite long but what is returns is something like this.
   
   {"principalId":"some id","policyDocument":{"Version":"2012-10-17","Statement":[{"Action":"execute-api:Invoke","Effect":"Allow","Resource":"*"}]}}
 
3. Thrown error

![image](https://github.com/middyjs/middy/assets/19557538/ac234f77-7810-45dc-86ae-8ffb31a8df81)

**Expected behaviour**
It was working fine on node 14, but I then upgrade the version to node 18 along with serverless and middy.

**Environment (please complete the following information):**
 - Node.js: 18.16.0
 - Middy: 4.6.1
 - AWS SDK 3.58.0
 - Serverless 3.34.0
 - Serverless-offline ^12.0.4,

**Additional context**
Also when I try to send the content-type: 'application/json' from postman, it give me this error
![image](https://github.com/middyjs/middy/assets/19557538/fb3c07af-7bba-4148-81fa-e3a2abc4bfd5)

**Comment by willfarrell** [comment]
This error purposely not handled in middy because it means that your input event is missing headers ... which is impossible. As you see, adding in `content-type` gives you a new error because indicating that your your request is missing details that are expected when `content-type`, in this case a JSON body.

**Comment by RaiSaugat** [comment]
I tried to work without wrapping the handler function with middy, and it seems to be working fine. Is there any workaround when using '@middy/http-json-body-parser'?

**Comment by RaiSaugat** [comment]
I seem to get the solution by commenting the useCors()
![image](https://github.com/middyjs/middy/assets/19557538/323d398e-721b-47f3-a3fb-bd4db638a3ab)

Was there any external thing I miss when using useCors()?

**Comment by RaiSaugat** [comment]
I have also already set CORS on serverless functions, so is it necessary to set on middy too?

**Comment by naorpeled** [comment]
Hey @RaiSaugat,
you can use the `disableContentTypeError` option on the jsonBodyParser middleware.

**Comment by naorpeled** [comment]
> I tried to work without wrapping the handler function with middy, and it seems to be working fine. Is there any workaround when using '@middy/http-json-body-parser'?

Hey @RaiSaugat,
AFAIK you can use the `disableContentTypeError` option on the jsonBodyParser middleware.

**Comment by naorpeled** [comment]
> I seem to get the solution by commenting the useCors() ![image](https://user-images.githubusercontent.com/19557538/266201305-323d398e-721b-47f3-a3fb-bd4db638a3ab.png)
> 
> Was there any external thing I miss when using useCors()?

I think you need to use the cors middleware before the rest because in the preflight request, you don't specify the content-type header as far as I remember

**Comment by RaiSaugat** [comment]
For now, I'm working on version 2.5.7. It's working as usual now. I'll update to the latest later on and check again with the issue.

**Comment by willfarrell** [comment]
Pushed an update to throw a 415 or skip based on options.
Will be released soon.
