### ISSUE TITLE
Type-fest error while using @middy/http-json-body-parser

### ISSUE THREAD

**Issue by pradeepan7899** [middyjs/middy#1101]
**Describe the bug**
I am facing the below typescript error when I am trying to build / tsc my cdk code.

`node_modules/type-fest/source/jsonify.d.ts:22:19 - error TS2589: Type instantiation is excessively deep and possibly infinite.
22  ? FilterNonNever<[Jsonify<F>, ...JsonifyList<R>]>`

`// Handles tuples and arrays
type JsonifyList<T extends unknown[]> = T extends [infer F, ...infer R]
	? FilterNonNever<[Jsonify<F>, ...JsonifyList<R>]>
	: Array<Jsonify<T[number]>>;`

**To Reproduce**
How to reproduce the behaviour:
1. Sample code 
`import middy from '@middy/core';
import { Logger, injectLambdaContext } from '@aws-lambda-powertools/logger';
import validator from '@middy/validator'
import jsonBodyParser from '@middy/http-json-body-parser';
import { transpileSchema } from '@middy/validator/transpile'

const logger = new Logger();

const lambdaHandler = async (event: any) => {
    logger.info('This is an info message');

    return {
        statusCode: 200,
        body: 'Lambda executed successfully',
    };
};

const schema = {
    type: 'object',
    required: ['body'],
    properties: {
        body: {
            type: 'object',
            required: ['name', 'email'],
            properties: {
                name: { type: 'string' },
                email: { type: 'string', format: 'email' }
                // schema options https://ajv.js.org/json-schema.html#json-data-type
            },
        },
    }
}

export const handler = middy(lambdaHandler)
    .use(validator({
        eventSchema: transpileSchema(schema)
    })).use(injectLambdaContext(logger, { clearState: true }))`
2. Input
`TSC`
3. Thrown error
`node_modules/type-fest/source/jsonify.d.ts:22:19 - error TS2589: Type instantiation is excessively deep and possibly infinite.
22  ? FilterNonNever<[Jsonify<F>, ...JsonifyList<R>]>`

**Expected behaviour**
wanted to check Input validation using @middy/validator, /core, /http-json-body-parser with logger in CDK typescript environment.

**Environment (please complete the following information):**
 - Node.js: NODEJS_16_X
 - @aws-lambda-powertools/logger": "^1.11.0",
 - @middy/core": "^4.6.1",
 - @middy/http-json-body-parser": "^4.6.1",
 - @middy/util": "^4.6.1",
 - @middy/validator": "^4.6.1",
 - "@types/aws-lambda": "^8.10.119",
 -  "aws-cdk-lib": "2.93.0",
 - "aws-lambda": "^1.0.7",
 - "constructs": "^10.0.0",
 - "source-map-support": "^0.5.21",
 - "type-fest": "^4.3.1"

**Comment by willfarrell** [comment]
Like to submit a PR to fix this?

**Comment by willfarrell** [comment]
If you do decide to open a PR, please make it against the release/5.0 branch

**Comment by willfarrell** [comment]
cc @naorpeled

**Comment by lmammino** [comment]
Hey @pradeepan7899 , we have actually seen that issue a few times ourselves. For middy v5 we think we have found a way to get rid of type-fest entirely and even be have to provide more specific types (as a replacement for the generic JSONValue provided by type-fest).

Most of the work is already in progress here #1093 in case you want to contribute (even a review would be highly appreciated).

**Comment by willfarrell** [comment]
Closing, in v5 alpha.
