### ISSUE TITLE
Middyfied handler function type signature is incorrect

### ISSUE THREAD

**Issue by zzantozz** [middyjs/middy#1116]
**Describe the bug**

The type signature of the function returned by `middy(handler).use(middyJsonBodyParser())` is incorrect. A valid lambda function should accept two arguments of type `APIGatewayProxyEvent` and `Context`. The function returned by the above instead expects the event to be of type `Omit<APIGatewayProxyEvent, "body"> & { body: JsonValue; }"` in middy 4.6.5. The body has to be a string. Because `JsonValue` is a union including `string`, there are no compile-time failures, but the type is too broad. If you pass anything other than a string as the body, the json parser fails.

**To Reproduce**

This is a Jest test that intentionally fails to compile to show the type. I've omitted the rather lengthy code that creates the test context.

```typescript
import { APIGatewayProxyEvent, Context } from "aws-lambda";
import * as utils from "../mock-utils";
import middy from "@middy/core";
import middyJsonBodyParser from "@middy/http-json-body-parser";

test("middy type test", () => {
  const handler = (event: APIGatewayProxyEvent, _context: Context) => {
    console.log(event.body);
  };
  const wrapped = middy(handler).use(middyJsonBodyParser());
  wrapped({}, utils.sampleMiddifiedContext());
});
```

The full error:

```
test/unit/middy.test.ts:11:11 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'Omit<APIGatewayProxyEvent, "body"> & { body: JsonValue; } & APIGatewayProxyEvent'.
  Type '{}' is missing the following properties from type 'Omit<APIGatewayProxyEvent, "body">': headers, multiValueHeaders, httpMethod, isBase64Encoded, and 7 more.

11   wrapped({}, utils.sampleMiddifiedContext());
```

**Expected behaviour**

I expect the type signature of the function returned by middy to be the same as a lambda function that hasn't been processed by middy.

**Environment:**

 - Node.js: 18.18.0
 - Middy: 4.6.5

**Comment by willfarrell** [comment]
Is this issue addressed in https://github.com/middyjs/middy/pull/1119#issuecomment-1785281655 ?

**Comment by zzantozz** [comment]
It doesn't appear to be fixed. With middy `5.0.0-alpha.2`, it still gives approximately the same error:
```
    test/unit/middy.test.ts:11:11 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'Omit<VersionedApiGatewayEvent, "body"> & { body: JsonValue; } & APIGatewayProxyEvent'.
      Type '{}' is missing the following properties from type 'Omit<VersionedApiGatewayEvent, "body">': headers, isBase64Encoded, requestContext

    11   wrapped({}, utils.sampleMiddifiedContext());
```
I'm unable to re-open this issue, though.

**Comment by willfarrell** [comment]
@lmammino Are you able to take a quick look?

**Comment by zzantozz** [comment]
Ok, I've looked at this harder and found that the type in Middy 4 and 5 is technically correct. It requires `body` to be a `string` because of the final union with `APIGatewayProxyEvent`. It's just a confusing type because it starts from `APIGatewayProxyEvent`, overrides `body` to be a `JsonValue`, and then re-overrides it to be a `string`, as it was in the first place. So, it's no longer really a bug, per se, but just a messy type definition: `Omit<APIGatewayProxyEvent, "body"> & { body: JsonValue; } & APIGatewayProxyEvent` instead of simply `APIGatewayProxyEvent`.

Here's a complete, standalone test showing that `body` can't be a `JsonValue` as proof. It fails to compile with
```
        Types of property 'body' are incompatible.
          Type 'JsonObject' is not assignable to type 'string'.
```

```typescript
import { APIGatewayProxyEvent, Context } from "aws-lambda";
import middy from "@middy/core";
import middyJsonBodyParser from "@middy/http-json-body-parser";
import { JsonValue } from "type-fest";

test("middy type test", () => {
  const handler = (event: APIGatewayProxyEvent, _context: Context) => {
    console.log(event.body);
  };
  const wrapped = middy(handler).use(middyJsonBodyParser());
  const value: JsonValue = { "hello": "world" };
  const event = {
    body: value,
    headers: undefined,
    httpMethod: undefined,
    path: undefined,
    resource: undefined,
    multiValueHeaders: undefined,
    multiValueQueryStringParameters: undefined,
    isBase64Encoded: false,
    pathParameters: undefined,
    queryStringParameters: undefined,
    requestContext: undefined,
    stageVariables: undefined,
  };
  wrapped(event, context());
});

function context(): Context {
  return {
    awsRequestId: "",
    callbackWaitsForEmptyEventLoop: false,
    done(_error: Error | undefined, _result: any): void {
    },
    fail(_error: Error | string): void {
    },
    functionName: "",
    functionVersion: "",
    getRemainingTimeInMillis(): number {
      return 0;
    },
    invokedFunctionArn: "",
    logGroupName: "",
    logStreamName: "",
    memoryLimitInMB: "",
    succeed(_messageOrObject: any, _object?: any): void {
    },
  };
}
```

**Comment by lmammino** [comment]
Hello @zzantozz and sorry for the slight delay in replying to this issue.

I think you are right, the current type definition does not seem correct.

This is how I think the type system should work here:

- the handler should receive an event with a JSON body (object)
- the wrapped handler should expect and event with a JSON string body

So when you wrap the handler, the returning type should be changed to expect a string body...

I'll try to have a look into this during the weekend and see if i can fix it, but feel free to submit a PR if you have more time.

**Comment by willfarrell** [comment]
Update will be in the v5 release. See PR #1131

**Comment by zzantozz** [comment]
Thanks for taking a look!
