### ISSUE TITLE
Add missing typescript definitions

### ISSUE THREAD

**Issue by Juanelorganelo** [middyjs/middy#112]
I noticed this package doesn't have TypeScript definitions for the `middy/middlewares` submodule which makes it a little bit painful to use with TypeScript. Can I interest you in a pull request?

**Comment by lmammino** [comment]
Hello @Juanelorganelo, thanks for your message.

Having typescript definition for the middlewares would definitely be great! Would you like to contribute with a PR?

**Comment by Juanelorganelo** [comment]
Sorry for the delay. Yes, absolutely I would like to contribute with a PR. I'm kind of busy right now but I expect to be able to make it in the next 2 or 3 days :).
