### ISSUE TITLE
Json body parser unusable with typescript, typing errors within the package

### ISSUE THREAD

**Issue by piotrwalczak1** [middyjs/middy#1128]
**Describe the bug**
There are typing errors in the package:

**To Reproduce**
Just try using this with typescript
```
node_modules/type-fest/ts41/get.d.ts:93:37 - error TS2344: Type 'BaseType' does not satisfy the constraint 'Record<string | number, any>'.

93  : Key extends keyof WithStringKeys<BaseType>
                                       ~~~~~~~~

  node_modules/type-fest/ts41/get.d.ts:79:17
    79 type PropertyOf<BaseType, Key extends string> =
                       ~~~~~~~~
    This type parameter might need an `extends Record<string | number, any>` constraint.

node_modules/type-fest/ts41/get.d.ts:94:19 - error TS2344: Type 'BaseType' does not satisfy the constraint 'Record<string | number, any>'.

94  ? WithStringKeys<BaseType>[Key]
                     ~~~~~~~~

  node_modules/type-fest/ts41/get.d.ts:79:17
    79 type PropertyOf<BaseType, Key extends string> =
                       ~~~~~~~~
    This type parameter might need an `extends Record<string | number, any>` constraint.


Found 2 errors in the same file, starting at: node_modules/type-fest/ts41/get.d.ts:93
```

**Expected behaviour**
Should not throw compliation errors.

**Environment (please complete the following information):**
 - Node.js: 18.x
 - Middy: 3.x
 - AWS SDK 2.x

**Additional context**

**Comment by willfarrell** [comment]
I notice you're using Middy v3. Have you tried the newer types in the latest version. There is also a v5 alpha with a lot of improvements to types.

**Comment by naorpeled** [comment]
@willfarrell +1

I can also dig into fixing the issue in v3 if needed, although it's not recommended imo

**Comment by willfarrell** [comment]
Only the current version is maintained at this time. If this isn't an issue in v5, we can close.

**Comment by piotrwalczak1** [comment]
@willfarrell  @naorpeled  I made a mistake in version, I have ^4.6.5 installed.. and the issue is there as well
