### ISSUE TITLE
http-response-serializer documentation incorrect

### ISSUE THREAD

**Issue by karmaniverous** [middyjs/middy#1141]
**Describe the bug**

The `http-response-serializer` documentation page [Content Type Negotiation section](https://github.com/middyjs/middy/blob/main/website/docs/middlewares/http-response-serializer.md#content-type-negotiation) is incorrect.

**Additional context**

This section states:

> The content type is determined in the following order:
>
> * `context.requiredContentType` -- allows the handler to override everything else
> * The `Accept` header via [accept](https://www.npmjs.com/package/accept)
> * `context.preferredContentType` -- allows the handler to override the default, but lets the request ask first
> * `defaultContentType` middleware configuration

If you look at [the code](https://github.com/middyjs/middy/blob/d80216c8e620ceb92605f592102644d21889e3b0/packages/http-response-serializer/index.js#L25-L35), the `context` properties listed above are actually `event` properties.

**Comment by willfarrell** [comment]
Thanks for reporting! I see the issue. I should be able to put together an update before the end of the week.
