### ISSUE TITLE
Response validation not working

### ISSUE THREAD

**Issue by MohamedYehia1998** [middyjs/middy#1144]
**Describe the bug**
When I return my response as a JSON (so that it is compatible with the response validator), I get a 502 bad gateway error.
CloudWatch does not show the exact error.
When I stringify my response, then the response validator fails (obviously because it expects an object response body).
CloudWatch also reflects this error.

**To Reproduce**
How to reproduce the behaviour:
1. Have a lambda function which returns a response as JSON not string
2. Apply the response validator middleware

**Expected behaviour**
I expect that when I return my response as a JSON, the response validator would process my response then stringify it.

**Environment**

- Node.js: [18]
- Middy: lastest
- AWS SDK: ;atest

**Lambda Function**

```
import middlewareWrapper from '../../utils/middlewareWrapper.js'
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { PutCommand, DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";
import { v4 as uuid } from 'uuid';
import { eventSchema, responseSchema } from '../../specifications/createTodo.js';

const createTodo = async (event) => {
  const client = new DynamoDBClient({});
  const docClient = DynamoDBDocumentClient.from(client);

  const todo = event.body;
  const user = JSON.parse(event.requestContext.authorizer.user);

  const params = {
    TableName: process.env.TODOS_TABLE,
    Item: {
      userId: user.sub,
      todoId: uuid(),
      createdAt: new Date().toISOString(),
      name: todo.name,
      dueDate: todo.dueDate,
    }
  };

  const command = new PutCommand(params);

  // global error handler in middleware catches error cases
  await docClient.send(command);

  return {
    statusCode: 201,
    body: {...params.Item},
  }
}
export const handler = middlewareWrapper({handler: createTodo, eventSchema, responseSchema})

```

**Schemas**

```import { transpileSchema } from '@middy/validator/transpile'

const eventSchema = transpileSchema({
  type: 'object',
  required: ['body'],
  properties: {
    body: {
      type: 'object',
      required: ['name', 'dueDate'],
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        dueDate: { type: 'string' }
        // schema options https://ajv.js.org/json-schema.html#json-data-type
      }
    }
  }
})

const responseSchema = transpileSchema({
  type: 'object',
  required: ['body', 'statusCode'],
  properties: {
    body: {
      type: 'object',
      required: ['name', 'dueDate', 'userId', 'todoId', 'createdAt'],
      properties: {
        name: { type: 'string' },
        dueDate: { type: 'string' },
        userId: { type: 'string' },
        todoId: { type: 'string' },
        createdAt: { type: 'string' }
        // schema options https://ajv.js.org/json-schema.html#json-data-type
      } 
    },
    statusCode: {
      type: 'number'
    }
  }
})

export {eventSchema, responseSchema}
```

**Middleware Wrapper**

```
import middy from '@middy/core'
import cors from '@middy/http-cors'
import httpJsonBodyParser from '@middy/http-json-body-parser'
import validator from '@middy/validator'

const middleware = (config) => {
    const {handler, eventSchema, responseSchema, parseJSON} = config

    const middlewares = []
    
    if(parseJSON || parseJSON===undefined){
        middlewares.push(httpJsonBodyParser())
    }
    
    middlewares.push(cors())
    
    if (eventSchema) {
        middlewares.push(validator({ eventSchema }))
    }

    if (responseSchema) {
        middlewares.push(validator({ responseSchema }))
    }
    
    return middy()
        .use(middlewares)
        .handler(handler)
}

export default middleware;

```

**Comment by willfarrell** [comment]
You don't need two `validator` middleware, event and response can be handled by one. I would suggest adding in `http-error-handler` to properly catch the error. Everything else looks fine otherwise.

**Comment by MohamedYehia1998** [comment]
@willfarrell 
Thank you for your input.

Unfortunately the issue still remains. I updated my middlewareWrapper to eliminate any uncertainties.

**Problematic Endpoint**
```
import middlewareWrapper from '../../utils/middlewareWrapper.js'
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { PutCommand, DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";
import { v4 as uuid } from 'uuid';
import { eventSchema, responseSchema } from '../../specifications/createTodo.js';

const createTodo = async (event) => {
  const client = new DynamoDBClient({});
  const docClient = DynamoDBDocumentClient.from(client);

  const todo = event.body;
  const user = JSON.parse(event.requestContext.authorizer.user);

  const params = {
    TableName: process.env.TODOS_TABLE,
    Item: {
      userId: user.sub,
      todoId: uuid(),
      createdAt: new Date().toISOString(),
      name: todo.name,
      dueDate: todo.dueDate,
      done: false,
    }
  };

  const command = new PutCommand(params);

  await docClient.send(command);

  return {
    statusCode: 201,
    body: {item:{...params.Item}},
  }
}
export const handler = middlewareWrapper({handler: createTodo, eventSchema, responseSchema})

```

**Middleware Wrapper**

```
import middy from '@middy/core'
import cors from '@middy/http-cors'
import httpErrorHandler from '@middy/http-error-handler'
import httpJsonBodyParser from '@middy/http-json-body-parser'
import validator from '@middy/validator'

const middleware = (config) => {
    const {handler, eventSchema, responseSchema} = config
    
    return middy()
        .use(httpJsonBodyParser())
        .use(cors())
        .use(validator({eventSchema, responseSchema}))
        .use(httpErrorHandler())
        .handler(handler)
}

export default middleware;
```

**Schemas**

```
import { transpileSchema } from '@middy/validator/transpile'

const eventSchema = transpileSchema({
  type: 'object',
  required: ['body'],
  properties: {
    body: {
      type: 'object',
      required: ['name', 'dueDate'],
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        dueDate: { type: 'string' }
        // schema options https://ajv.js.org/json-schema.html#json-data-type
      }
    }
  }
})

const responseSchema = transpileSchema({
  type: 'object',
  required: ['body', 'statusCode'],
  properties: {
    body: {
      type: 'object',
      properties: {
        item: { 
          type: 'object' ,
          required: ['name', 'dueDate', 'userId', 'todoId', 'createdAt'],
          properties: {
            name: { type: 'string' },
            dueDate: { type: 'string' },
            userId: { type: 'string' },
            todoId: { type: 'string' },
            createdAt: { type: 'string' }
            // schema options https://ajv.js.org/json-schema.html#json-data-type
          } 
        },

      },

    },
    statusCode: {
      type: 'number'
    }
  }
})

export {eventSchema, responseSchema}
```


Despite using `http-error-handler`, this error does not show up in cloud watch.
![image](https://github.com/middyjs/middy/assets/25740825/b23764b4-40e9-4193-b42f-b4c6e73cba7c)



When I return my response body as a string, the validation error shows up on cloud watch nonetheless
![image](https://github.com/middyjs/middy/assets/25740825/8600eeed-e227-452c-896d-c7db1486ea6f)


I am not sure the http-error-handler does not behave as expected as well.
Postman returns in the 2 cases
![image](https://github.com/middyjs/middy/assets/25740825/15c0a9a9-8058-4761-820f-55ae16eefd09)

**Comment by MohamedYehia1998** [comment]
**Issue Resolved**

To validate the response I had to use the validator middleware AND the httpResponseSerializer.
The lambda function should return an object (not a string).

The sequence of the middleware below dictates that those operations take place after the the lambda function returns a response in JSON not string in this sequece:

1) The response is validated with the middy middleware (it receives it as JSON).
2) The http response is serialized
3) The relevant headers for CORS are inserted.

Without the http response serialization, it does not work.
@willfarrell please confirm this and if that's the case please update the documentation :)

**lambda response**

```
  return {
    statusCode: 201,
    body: Object({item:{...params.Item}}),
  }
``
**middleware**
```
const middleware = (config) => {
    const { handler, eventSchema, responseSchema, parseJSON } = config

    const middlewares = []

    if (parseJSON || parseJSON === undefined) {
        middlewares.push(httpJsonBodyParser())
    }

    if (eventSchema || responseSchema) {
        const validatorObject = {};
        if (eventSchema) {
            validatorObject.eventSchema = eventSchema;
        }
        if (responseSchema) {
            validatorObject.responseSchema = responseSchema;
        }
        middlewares.push(validator(validatorObject))
    }

    return middy()
        .use(cors())
        .use(httpResponseSerializer({
            serializers: [
                {
                    regex: /^application\/xml$/,
                    serializer: ({ body }) => `<message>${body}</message>`
                },
                {
                    regex: /^application\/json$/,
                    serializer: ({ body }) => JSON.stringify(body)
                },
                {
                    regex: /^text\/plain$/,
                    serializer: ({ body }) => body
                }
            ],
            defaultContentType: 'application/json'
        }))
        .use(middlewares)
        .use(globalErrorHandler())
        .handler(handler)
}
```
