### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED error

### ISSUE THREAD

**Issue by jobuit** [middyjs/middy#1163]
**Describe the bug**
When upgrading to the v5 I started getting the error ERR_PACKAGE_PATH_NOT_EXPORTED

**To Reproduce**
Upgrade from v4 to v5 using node v20

**Expected behaviour**

**Environment (please complete the following information):**

- Node.js: v20.2.0
- Middy: ^5.2.3

<img width="672" alt="image" src="https://github.com/middyjs/middy/assets/28201079/4bd8af0d-5f6a-4f17-87b5-5902d7695036">

**Comment by willfarrell** [comment]
v5 of Middy only supports ESM, your logs show you're trying to load it as a CJS.
