### ISSUE TITLE
dead links on getting started page 

### ISSUE THREAD

**Issue by jcollum-nutrien** [middyjs/middy#1168]
**Describe the bug**

On the page: https://middy.js.org/docs/intro/getting-started#inline-middlewares

![image](https://github.com/middyjs/middy/assets/99687439/08aa7856-455a-4e2d-b7c1-91afa6667824)

The links: 

https://middy.js.org/docs/intro/getting-started/#inline-middlewares 

https://middy.js.org/docs/intro/getting-started/#writing-a-middleware

But those two just land you on the getting-started page, which doesn't have anchor tags for those.

**Comment by lmammino** [comment]
Thanks a mill for reporting this, @jcollum-nutrien!

Just submitted a PR that should address this issue!


Thanks again
