### ISSUE TITLE
Restrict types to `APIGatewayProxyResultV2` or `APIGatewayProxyResult`

### ISSUE THREAD

**Issue by jlarmstrongiv** [middyjs/middy#1175]
**Describe the bug**

The TypeScript types indicate properties exist in Middy handlers that do not.

**To Reproduce**
How to reproduce the behaviour:

1. With a [function url](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-payloads) that uses the [payload version format v2](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format) with middy

**Expected behaviour**
If I specify `APIGatewayProxyEventV2` and `APIGatewayProxyResultV2` in `export const middy = middyCore<APIGatewayProxyEventV2, APIGatewayProxyResultV2>()`, then the handlers should only use the v2 types.

**Environment (please complete the following information):**

- Node.js: v20.11.0
- Middy: 5.2.4
- AWS SDK 2.1551.0

**Additional context**
The actual types include the old event formats 
```
MiddyfiedHandler<APIGatewayProxyEventV2 & Omit<APIGatewayProxyEvent, "body"> & { body: JsonValue; } & APIGatewayProxyEvent & ... 4 more ... & { ...; }, APIGatewayProxyResultV2, Error, Context, {}>.handler: <unknown>(handler: MiddyInputHandler<APIGatewayProxyEventV2 & Omit<APIGatewayProxyEvent, "body"> & {
    body: JsonValue;
} & APIGatewayProxyEvent & ... 4 more ... & {
    ...;
}, APIGatewayProxyResultV2, Context>) => MiddyfiedHandler<...>
```

**Comment by b3nk3** [comment]
I'm running into some errors that are very similar to this, when using the `http-router` and it stems from using a middleware on the handlers, as the handler changes the types, rightly so, but the typing of the `routes` variable is unable to pick this up...

The code works, but I kinda have to ignore the typescript on that level.

Given the number of different middlewares, and their various outputs - this is not an easy thing to fix.

[TS Playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCYATJBPOAzKERwOQACiKqA9AMbQCmeA3AFCiSxwAWMMYAShAK4xUoACQCGAOyQAbQQBo4Abzg9+VOAF9M2XIWJpS7TgFpsKqHUbho8RQEEACgEkA4iIEB3EajvYAHqgCiAG5UYjAAagBMcvbOrlQeXr6oXFQAzryS4RHqmjj4Im6phpIiIABGSCLmTFZsHGAAqlCS-mKUSFQAQhBodiJQqYK52kTIegZghrzNIe1UhmU9qIZg-YNmDPSUYqnwAOZUMKIS0lBwALwIY6gAPDEu7p7eEH5BIVnRjg-xT0kp6ZlIgA+AAUAEp6HA4AA6XiDEETJotNo9LpLPoDQTgiFQ6GscRSLEgqjBUJybYCHwwMEXIEKSFQuBQQ7TMT0xmM3auOEAYVRAC44BEAAzCmQMjmLNCCvDyaHytR4cUctQMKFqMGbba7OCQXbHQlnS66W73OIJZ6vUkfOBmx6JF7JNIZLKgnEwuFUBH1JGtObdXprLFg914gmnEHE63kiChKhUmnnOnyCVMllQNkpjlQrkwXkCoWi5XZqWoGVyhVK1OqhkarWxnUmASpQXKAR3L7m36Ot6hYEAbQAuhc4P2GVnGSBDqwejKnP4ACpVjmrGCsGWkT1QUjyZCK4tQ-EnQSCg5HcOyWvFidQqdr2f4OwAeQAykuD7rXOv8Jv1svGUehqCnq57HlAxZqOKg6bPGzDwNq8CAacI4mh2sT2paATWpEnzoT8Dp+P8LrAt6nBtoIBoRk2aQhgwQA)

**Comment by naorpeled** [comment]
Hey @willfarrell,
should I take a look at this?

**Comment by willfarrell** [comment]
@naorpeled sure
