### ISSUE TITLE
Lambda throwing `Failed to resolve internal values` in secretsManagerMiddlewareBefore

### ISSUE THREAD

**Issue by gfreecs0510** [middyjs/middy#1177]
Here is what my lambda is throwing

`{
  "errorType": "Error",
  "errorMessage": "Failed to resolve internal values",
  "trace": [
    "Error: Failed to resolve internal values",
    "    at getInternal (/.yarn/cache/@middy-util-npm-4.7.0-12e05d3721-8c8f4bdc39.zip/node_modules/@middy/util/index.js:68:15)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at secretsManagerMiddlewareBefore (/.yarn/cache/@middy-secrets-manager-npm-4.7.0-2736027c1d-e18fbd1496.zip/node_modules/@middy/secrets-manager/index.js:60:26)",
    "    at runMiddlewares (/.yarn/cache/@middy-core-npm-4.7.0-2203442028-fdced61b3b.zip/node_modules/@middy/core/index.js:160:21)",
    "    at runRequest (/.yarn/cache/@middy-core-npm-4.7.0-2203442028-fdced61b3b.zip/node_modules/@middy/core/index.js:114:9)"
  ]
}`

We encountered the error sometimes when we forgot to add permissions to the lambda, but this time we are still getting the error

Below is my serverless.yml.
`
testLambda:
  handler: src/handlers/eventBridge/testLambda.handler
  timeout: 60

  iamRoleStatements:
    - Effect: Allow
      Resource: !Ref SecretsConfig
      Action:
        - secretsmanager:GetSecretValue
    - Effect: Allow
      Resource: !GetAtt ElastiCacheCluster.ARN
      Action:
        - elasticache:DescribeCacheClusters
        - elasticache:DescribeCacheParameters
        - elasticache:DescribeCacheSubnetGroups
        - elasticache:DescribeEngineDefaultParameters
        - elasticache:ListTagsForResource
        - elasticache:ListAllowedNodeTypeModifications`

**Comment by willfarrell** [comment]
It looks like you're using Middy v4.7.0. Can you re-test using the latest version?

**Comment by gfreecs0510** [comment]
i upgraded all my package, but im still getting an issue

"@middy/core": "^5.2.4",
"@middy/input-output-logger": "^5.2.4",
"@middy/secrets-manager": "^5.2.4"

<img width="1444" alt="image" src="https://github.com/middyjs/middy/assets/78189510/a84d8a22-34c4-4a1e-aad7-f0602e7a2462">

Below is my lambda permission

<img width="1316" alt="image (5)" src="https://github.com/middyjs/middy/assets/78189510/aba2c2ea-5dcf-43d6-b284-ee99f3ef0de7">

**Comment by gfreecs0510** [comment]
hi @willfarrell ! it seems like we figured out the issue, 

<img width="497" alt="image" src="https://github.com/middyjs/middy/assets/78189510/96a672de-cd08-4889-9e25-c6a67fe1a32c">


`
export const handler = middy(lambdaHandler)
  .use(secretsManager({
    cacheExpiry: 10 * 60 * 1000,
    setToContext: true,
    fetchData: {
      configs: process.env.CONFIGS_NAME ?? ''
    }
  }))
  .use(injectLambdaContext(logger))
`

because the env variable `CONFIGS_NAME` doesnt really have a value, the middleware is failing and its throwing an error.

if i find some time, i can check on the code and make a PR for this to make a better message handling. but i think we can close this issue.
