### ISSUE TITLE
Simple lib import fails with both `tsx` and `ts-node`

### ISSUE THREAD

**Issue by uqee** [middyjs/middy#1179]
**Describe the bug**

```
node:internal/modules/esm/resolve:303
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/@middy/core/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:593:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at a._resolveFilename (.../node_modules/.pnpm/tsx@4.7.1/node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at <anonymous> (/Users/dz/Documents/more/moreai/back-users/f.ts:1:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**To Reproduce**
+ [CodeSandBox](https://codesandbox.io/p/devbox/serene-allen-5z69hm?workspaceId=3965da8f-5eb2-41f6-91b4-ae0904901c1f&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsuzf05400073b6ggjmxk9th%2522%252C%2522sizes%2522%253A%255B22.03883495145631%252C77.96116504854369%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsuzf05400033b6gop07qeh3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsuzf05400053b6ggk0wej6s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsuzf05400063b6gn3yewe3g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsuzf05400033b6gop07qeh3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsuzf05400023b6g0o43g19y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsuzf05400033b6gop07qeh3%2522%252C%2522activeTabId%2522%253A%2522clsuzf05400023b6g0o43g19y%2522%257D%252C%2522clsuzf05400063b6gn3yewe3g%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsuzf05400063b6gn3yewe3g%2522%257D%252C%2522clsuzf05400053b6ggk0wej6s%2522%253A%257B%2522id%2522%253A%2522clsuzf05400053b6ggk0wej6s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsuzimy300cl3b6f9owwaqv6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsuzin6p00ajd9g650p6cpv8%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsuzimy300cl3b6f9owwaqv6%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
+ npm install
+ npm start

**Expected behaviour**
+ no error

**Environment (please complete the following information):**

- Node.js: 20.9.0 (also tested on 20.11.1)
- Middy: 5.2.4
- AWS SDK: none

**Additional context**
+ `ts-node` shows the same error
+ this bug blocks CDK deploy

**Comment by willfarrell** [comment]
`No "exports" main defined in` usually means you're trying to use ESM with CJS. Middy v4.x does support CJS, v5 does not.

**Comment by uqee** [comment]
Ok, will migrate to ESM and test again, thank you!
