### ISSUE TITLE
TypeScript error when using `S3Handler` type

### ISSUE THREAD

**Issue by garysassano** [middyjs/middy#1182]
**Describe the bug**

**To Reproduce**
How to reproduce the behaviour:

```ts
const lambdaHandler: S3Handler = async (event: S3Event): Promise<void> => {
  await Promise.all(event.Records.map(processRecord));
};

export const handler = middy().use(eventNormalizer()).handler(lambdaHandler);
```

```sh
Argument of type 'S3Handler' is not assignable to parameter of type 'MiddyInputHandler<S3Event, any, Context>'.
  Types of parameters 'callback' and 'opts' are incompatible.
    Type 'MiddyHandlerObject' is not assignable to type 'Callback<void>'.
      Type 'MiddyHandlerObject' provides no match for the signature '(error?: string | Error | null | undefined, result?: void | undefined): void'.
```

**Expected behaviour**

**Environment (please complete the following information):**

- Node.js: [e.g. 20]
- Middy: [e.g. 5.0.0]
- AWS SDK [e.g. 3.0.0]

**Additional context**

**Comment by garysassano** [comment]
@willfarrell If by "last release" you mean `middy@5.2.5`, [that's not available on npm](https://github.com/middyjs/middy/issues/1183).

**Comment by garysassano** [comment]
Duplicate of #1176

**Comment by garysassano** [comment]
Duplicate of #1176

**Comment by naorpeled** [comment]
On it 🙏

**Comment by garysassano** [comment]
I still get the error in 5.4.0

![image](https://github.com/middyjs/middy/assets/10464497/b395df3e-1af7-4aad-963c-5043457859d7)

**Comment by naorpeled** [comment]
Hey @garysassano,
using the current implementation the following two ways would work:
```typescript
middy(lambdaHandler).use(eventNormalizer())

// OR

const lambdaHandler = async (event: S3Event, context: Context) => {
  await Promise.all(event.Records.map(async () => await Promise.resolve()))
}

const handler = middy<S3Event, void>().use(eventNormalizer()).handler(lambdaHandler)
```

regarding a fix for the above syntax that you've mentioned, I'm on it but it will take some time.

**Comment by naorpeled** [comment]
Hey @garysassano,
I've created a PR to properly resolve this.
Waiting for Will to review and hopefully we'll merge this within the next few days.
