### ISSUE TITLE
middy 5.2.5 isn't available on npm

### ISSUE THREAD

**Issue by garysassano** [middyjs/middy#1183]
**Describe the bug**

**To Reproduce**
How to reproduce the behaviour:

I think there was a problem with the publishing of the package.

![image](https://github.com/middyjs/middy/assets/10464497/7d3faa72-8358-4287-a624-22eb9a473de2)

![image](https://github.com/middyjs/middy/assets/10464497/f40e69ef-46d5-4004-ae2e-a487e69bc6ec)

**Expected behaviour**

**Environment (please complete the following information):**

- Node.js: [e.g. 20]
- Middy: [e.g. 5.0.0]
- AWS SDK [e.g. 3.0.0]

**Additional context**

**Comment by willfarrell** [comment]
I know. CI issue.
