### ISSUE TITLE
http-error-handler : set custom test to return error instead of `statusCode`

### ISSUE THREAD

**Issue by throrin19** [middyjs/middy#1197]
**Is your feature request related to a problem? Please describe.**

Others libraries return error with statusCode but their are not HTTP-Errors and return many internal details (example : objection.js with mySqlError)

Actually, it's not possible to change how the test is made to return the error or use custom field/test to go to fallback

**Describe the solution you'd like**

- Use directly method `isHttpError` from `http-errors` or set a custom function to test if our function is a corect http-error or not

```js
import middy from '@middy/core'
import httpErrorHandler from '@middy/http-error-handler'
import createError from 'http-errors'
import { isHttpError } from 'http-errors'

const lambdaHandler = (event, context) => {
  throw new createError.UnprocessableEntity()
}
export const handler = middy()
    .use(httpErrorHandler({ 
        fallbackMessage : JSON.stringify({ message : 'Internal Server Error' }),
        test: (err) => isHttpError(err)
    }))
    .handler(lambdaHandler)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by willfarrell** [comment]
Sounds like it would best handled by a custom error handler or a middleware to modify the non-http errors into ones.
