### ISSUE TITLE
http-error-handler: guidance/bug on using lambda-authorizer with v5

### ISSUE THREAD

**Issue by grant-d** [middyjs/middy#1201]
We have a middy `APG` (Api Gateway) / `lambda` stack that has been working great for a couple of years. 
I upgraded the stack a couple of days ago, from `@middy 4 -> 5`
In doing so, the Custom/Lambda-Authorizer in `APG` does not handle `Unauthorized` properly anymore.

I realize that `5` is a breaking change, but I am not sure what the guidance is. 
_Everything works fine in other lambdas,_ but `APG` has [specific patterns](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html#api-gateway-lambda-authorizer-lambda-function-create) and expectations for [lambda authorizer 401 errors](https://stackoverflow.com/a/60280752), and that pattern now seems broken.

My understanding is that the internals of `APG` contractually expect to get a message shaped _exactly_ like this `{ message: "Unauthorized" }` (which worked in `v4`) but I am guessing `v5` now sends `{ body: ..., statusCode: ...}`, which `APG` doesn't know how to bind to.

Please advise.

BEFORE (using `middy@4`):
```typescript
  // import @middy@4.0
  if { userIsNotAuthorized } throw Error('Unauthorized')
  // callback("Unauthorized") // ... or this

  middy(handler).use(httpErrorHandler()) // etc

  // APG CloudWatch logs (everything looks GOOD)
  Gateway response type: UNAUTHORIZED with status code: 401 // Take note of this log line
  Gateway response body: 
  {
      "message": "Unauthorized"
  }

  // Postman response
  {
      "message": "Unauthorized"
  }
```

AFTER (upgrade to `middy@5`):
```typescript
  // import @middy@5.0 // This is the only change
  if { userIsNotAuthorized } throw Error('Unauthorized')
  // I also tried `throw createError.Unauthorized()` per docs, but similar result to below

  middy(handler).use(httpErrorHandler()) // etc

  // APG CloudWatch logs (BAD)
  Authorizer result body before parsing:
  {
      "statusCode": 500,
      "headers": {}
      // Note the lack of a { message: "Unauthorized" } property
  }
  Execution failed due to configuration error: Invalid JSON in response: Unrecognized field "statusCode" , not marked as ignorable

  // Postman response
  {
      "message": null
  }
```

AFTER (removed `httpErrorHandler`):
```typescript
  // import @middy@5.0
  if { userIsNotAuthenticated } throw Error('Unauthenticated')

  middy(handler) // etc
  // .use(httpErrorHandler()) // Removed this handler

  // APG CloudWatch logs (kinda GOOD)
  ~Gateway response type: UNAUTHORIZED with status code: 401~ // Weird, this line is MISSING in logs now
  Gateway response body: 
  {
      "message": "Unauthorized"
  }

  // Postman response
  {
      "message": "Unauthorized"
  }
```

_Originally posted by @grant-d in https://github.com/middyjs/middy/issues/1117#issuecomment-2026388758_

**Comment by willfarrell** [comment]
Sounds like there is an issue on how you're creating the error. Check out https://github.com/middyjs/middy/blob/main/packages/http-error-handler/__tests__/index.js

There was a change in v5 that non-http-errors throw a 500. https://middy.js.org/docs/upgrade/4-5#http-error-handler
