### ISSUE TITLE
@middy/http-content-encoding not awaiting onError

### ISSUE THREAD

**Issue by londonod** [middyjs/middy#1211]
**Describe the bug**
`onError` function calls `after` function but it doesn't await for it to resolve, so the response object doesn't get updated when needed.

**To Reproduce**
1. Add http-content-encoding middleware
3. Throw an error. It won't be encoded

**Expected behaviour**
Error response also be encoded

**Environment (please complete the following information):**

- Node.js: 20.x
- Middy: 5

**Additional context**

If I add an await on this line it works: https://github.com/middyjs/middy/blob/1f0afb7b29cd22569fffb1cba1270397fafbb511/packages/http-content-encoding/index.js#L94

**Comment by willfarrell** [comment]
Thanks for reporting. A fix will be in next release, later today.
