### ISSUE TITLE
Consistent multipart body parser response format

### ISSUE THREAD

**Issue by thesobercoder** [middyjs/middy#1214]
**Is your feature request related to a problem? Please describe.**
Currently, there are three different formats when uploading files.

With key single file -
```JSON
{
  "aaaa": {
    "filename": "image.png",
    "mimetype": "image/png",
    "encoding": "7bit",
    "truncated": false,
    "content": "<Buffer...>"
  }
}
```

Without key single file -
```JSON
{
  "": {
    "filename": "image.png",
    "mimetype": "image/png",
    "encoding": "7bit",
    "truncated": false,
    "content": "<Buffer...>"
  }
}
```

With key multiple files -
```JSON
{
  "aaaa": {
    "filename": "image.png",
    "mimetype": "image/png",
    "encoding": "7bit",
    "truncated": false,
    "content": "<Buffer...>"
  },
  "bbbb": {
    "filename": "image.png",
    "mimetype": "image/png",
    "encoding": "7bit",
    "truncated": false,
    "content": "<Buffer...>"
  }
}
```

Without key multiple files -
```JSON
{
  "": [
    {
      "filename": "image.png",
      "mimetype": "image/png",
      "encoding": "7bit",
      "truncated": false,
      "content": "<Buffer...>"
    },
    {
      "filename": "image.png",
      "mimetype": "image/png",
      "encoding": "7bit",
      "truncated": false,
      "content": "<Buffer...>"
    }
  ]
}
```

It would so much easier if the structure of the JSON were consistent across all three scenarios. I had to do a lot of TypeScript wresting to cater to all three scenarios.

**Describe the solution you'd like**
The response format should be an array of files, with each file object having the `fieldname` inside the object.

```JSON
[
  {
    "filename": "image.png",
    "mimetype": "image/png",
    "encoding": "7bit",
    "truncated": false,
    "content": "<Buffer...>",
    "fieldname": "...."
  },
  {
    "filename": "image.png",
    "mimetype": "image/png",
    "encoding": "7bit",
    "truncated": false,
    "content": "<Buffer...>",
    "fieldname": "...."
  }
]
```

This format will be so much easier to parse and work with.

**Comment by willfarrell** [comment]
Under the hood middy uses `@fastify/busboy` (based off `busboy`) for parsing, we don't modify it in any way. I like your proposed format, might be worth asking at https://github.com/fastify/busboy and see if they're open to a change like this.
