### ISSUE TITLE
`ws-response`: Invalid URL format gave to `ApiGatewayManagementApiClient`

### ISSUE THREAD

**Issue by nbusser** [middyjs/middy#1218]
**Describe the bug**
When uysing `ws-response` and giving no `awsClientOptions`, a default `endpoint` option is given to `ApiGatewayManagementApiClient`.

[Regarding code](https://github.com/middyjs/middy/blob/2def335cf53414b3bbe836533a31ba7f6b8ebe81/packages/ws-response/index.js#L37), the URL is created from the api endpoint and domain. However, the **protocol is left unspecified**, which leads to:

```
{
    "errorType": "TypeError",
    "errorMessage": "Invalid URL",
    "code": "ERR_INVALID_URL",
    "input": abcdefg.execute-api.eu-central-1.amazonaws.com/dev",
    "stack": [
        "TypeError [ERR_INVALID_URL]: Invalid URL",
        "    at new NodeError (node:internal/errors:405:5)",
        "    at new URL (node:internal/url:676:13)",
        "    at parseUrl (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)",
        "    at toEndpointV1 (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:41)",
        "    at customEndpointProvider (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)"
    ]
}
```

Using the following options works:

```javascript
.use(
    wsResponseMiddleware({
      awsClientOptions: {
        endpoint:
          'https://abcdefg.execute-api.eu-central-1.amazonaws.com/dev',
      },
    }),
  )
```

**Environment (please complete the following information):**

- Node.js: 20
- Middy: 4.7.0
- AWS SDK 3

**Comment by nbusser** [comment]
If this issue is fixed, would it be possible to also fix it in middy 4.x?

Since we are using `serverless-typescript`, which only supports CJS, we cannot actually use ESM...

**Comment by willfarrell** [comment]
Thanks for reporting! I'll should have a fix out shortly.

Sorry, no plans to ship any bug or feature updates to v4.x. I would imagine the maintainers for `serverless-typescript` would be open to an update to `esm` as the cold start improvements when running lambda are notable.

**Comment by nbusser** [comment]
It makes sense. I just created a fixed local version of the middleware at the moment.

Also, shouldn't the `Data` property being `JSON.stringify`, or is it responsibility of the lambda?

**Comment by willfarrell** [comment]
Responsibility of the lambda, as `Data` can be non-json.
