### ISSUE TITLE
 `ws-response`: Invalid `request.response` given to API Gateway

### ISSUE THREAD

**Issue by nbusser** [middyjs/middy#1219]
# Description

[At the end of `ws-response` middleware](https://github.com/middyjs/middy/blob/6c9fcc7fa22fc70a60e7db39a5e43c3d09a79c3f/packages/ws-response/index.js#L42), we set `request.response.statusCode` to `200`, so API Gateway knows that everything went well.

However, it actually wants an object containing **ONLY** statusCode. Otherwise, it will send an **Internal Error** message to the client.

## Example:

In my lambda:
```javascript
const handler = () => {
     return {
         Data: 'Hello',
    };
}
```

Here is the content of `request.response` at the end of the middleware:
`{ ConnectionId: 'ZmDx-dJ4FiACFkQ=', Data: '"Hello"', statusCode: 200 }`

I receive the following error message on the client:
```
Message from the server: "Hello"
Message from the server: {"message": "Internal server error", "connectionId":"ZmDx-dJ4FiACFkQ=", "requestId":"ZmDyDGyFliAFhVQ="}
```

# Fix:

Replace [line 42](https://github.com/middyjs/middy/blob/6c9fcc7fa22fc70a60e7db39a5e43c3d09a79c3f/packages/ws-response/index.js#L42) by:

```javascript
request.response = {
    statusCode: 200
}
```

By doing this, with the same lambda code, I receive the following message on the client:
```
Message from the server: "Hello"
```

# Environment:

- Node.js: 20
- Middy: 4.x
- AWS SDK 3.x

**Comment by willfarrell** [comment]
Thanks for reporting. I should be able to get a fix out before the end of the weekend.
