### ISSUE TITLE
Latest version of @middy/core breaks types in the handler function

### ISSUE THREAD

**Issue by vidarc** [middyjs/middy#1221]
**Describe the bug**
The 5.4.2 release of `@middy/core` breaks typing that works fine in version 5.4.1. Have tried it with TypeScript `5.4.x` and `5.5.x` and encounter the same issue.

**To Reproduce**
You can see this issue with the sample TypeScript in the documentation. The `req` and `context` variables in the handler function are now no longer correctly typed, but instead return as `any`. Downgrading back to 5.4.1 fixes the issue and now `req` and `context` are correctly typed again.

```typescript
import middy from "@middy/core";
import secretsManager from "@middy/secrets-manager";
import type { APIGatewayProxyEvent, APIGatewayProxyResult } from "aws-lambda";

export const handler = middy<APIGatewayProxyEvent, APIGatewayProxyResult>()
  .use(
    secretsManager({
      fetchData: {
        apiToken: "dev/api_token",
      },
      awsClientOptions: {
        region: "us-east-1",
      },
      setToContext: true,
    }),
  )
  .handler(async (req, context) => {
    // The context type gets augmented here by the secretsManager middleware.
    // This is just an example, obviously don't ever log your secret in real life!
    console.log(context.apiToken);
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: `Hello from ${req.path}`,
        req,
      }),
    };
  });
```

**Expected behaviour**
Above example should work with TypeScript

**Additional context**

**Comment by tim-helloquickly** [comment]
I'm also experiencing this!

**Comment by naorpeled** [comment]
Hey,
you're right, the type defs indeed changed.
Wasn't sure how to properly document this.

What you need to do is to provide the generic type to the `.handler` function.
In your case it would be:

```typescript
import middy from "@middy/core";
import secretsManager from "@middy/secrets-manager";
import type { APIGatewayProxyEvent, APIGatewayProxyResult } from "aws-lambda";

export const handler = middy()
  .use(
    secretsManager({
      fetchData: {
        apiToken: "dev/api_token",
      },
      awsClientOptions: {
        region: "us-east-1",
      },
      setToContext: true,
    }),
  )
  .handler<APIGatewayProxyEvent, APIGatewayProxyResult>(async (req, context) => {
    // The context type gets augmented here by the secretsManager middleware.
    // This is just an example, obviously don't ever log your secret in real life!
    console.log(context.apiToken);
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: `Hello from ${req.path}`,
        req,
      }),
    };
  });
```

**Comment by willfarrell** [comment]
Please reopen if this needs more attention.

**Comment by jlarmstrongiv** [comment]
Related discussion in https://github.com/middyjs/middy/pull/1217

**Comment by naorpeled** [comment]
> Related discussion in #1217

Will be able to further investigate in few hours, will keep you posted. Sorry for the inconvenience.

**Comment by naorpeled** [comment]
Hey guys,
first of all, sorry for the inconvenience.

I've created a PR to partially revert those changes,
need to figure out how to support plain AWS Lambda types (such as `S3Handler`) properly.

If anyone has an idea please let me know 🙏

**Comment by jlarmstrongiv** [comment]
@naorpeled wouldn’t it look something like:
```
import middyCore from "@middy/core";
import type { S3Event } from "aws-lambda";

export const middy = middyCore<S3Event, void>();

export const handler = middy.handler(({ Records }) =>
  console.log({
    body: JSON.stringify(Records, undefined, 2),
    statusCode: 200,
  })
);
```

Must be version `5.4.1` though

**Comment by iainlane** [comment]
I couldn't resist fiddling with the type definitions a bit. I came up with this: https://github.com/middyjs/middy/commit/a66f3583aaf3bf963fd044fba58f1adb877782e3.

In there we add a couple of new generic parameters which exist to propagate along the types from `after()` and `before()`, and modify the type of `handler()`.

It's _not_ a proposal right now. Partly because it breaks existing programs and partly because I'm not sure it's all correct. It does seem to improve things for me, though.

I wanted to share it to get feedback and see if folks thing it's a valuable direction to try to move in.
