### ISSUE TITLE
Handler return is not type-checked.

### ISSUE THREAD

**Issue by canassa** [middyjs/middy#1228]
When using TypeScript, the return of a handler is not being validated by the type checker.

**To Reproduce**

Add this file

```typescript
import type {APIGatewayProxyEvent, APIGatewayProxyResult} from "aws-lambda";
import middy from "@middy/core";


export const handler = middy<APIGatewayProxyEvent, APIGatewayProxyResult>()
    .handler(async (req, context) => {
        return 123
    })
```

- Run the type checker.
- Observe that no error is detected.

**Expected behaviour**
The type checker should have throw an error since `123` does not match the `APIGatewayProxyResult`.

**Note:** I know that this can be workaround by manually adding the return type to the handler function, but that's more error prone.

**Environment (please complete the following information):**

- Node.js: 20
- Middy: 5.4.5

**Comment by canassa** [comment]
This seems to be a regression with Middy 5. Middy 4 is able to correctly validate the type:

```
error TS2345: Argument of type '(req: APIGatewayProxyEvent, context: Context) => Promise<number>' is not assignable to parameter of type 'MiddyInputHandler<APIGatewayProxyEvent, APIGatewayProxyResult, Context>'.
  Type 'Promise<number>' is not assignable to type 'void | APIGatewayProxyResult | Promise<APIGatewayProxyResult>'.
    Type 'Promise<number>' is not assignable to type 'Promise<APIGatewayProxyResult>'.
      Type 'number' is not assignable to type 'APIGatewayProxyResult'.

8     .handler(async (req, context) => {
               ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by willfarrell** [comment]
A PR is welcome for this.
