### ISSUE TITLE
Support for AsyncLocalStorage store.run

### ISSUE THREAD

**Issue by gp-jameskyburz** [middyjs/middy#1232]
Is there a way to support wrapping a handler using store.run from 'node:async_hooks'?

Currently I have it working wrapping the handler, but would prefer a middleware implementation.

store.run is the only stable way to do it so my solution looks like below

```javascript
 return middy((event: APIGatewayProxyEvent, context: Context, callback: Callback<APIGatewayProxyResult>) => {
    const handlerContext = {
      apiRequestId: event.requestContext?.requestId,
      awsRequestId: context.awsRequestId,
      callChain: 1,
      correlationId: randomUUID(),
      lambda: `${context.functionName}:${context.functionVersion}`,
      logStream: `${context.logGroupName}/${context.logStreamName}`,
      xrayTraceId: process.env._X_AMZN_TRACE_ID,
    };
    return store.run(handlerContext, handler, event, context, callback);
  })
  ```

**Comment by willfarrell** [comment]
Thanks for the feature request!

I haven't used `AsyncLocalStorage` personally yet. I did a quick read of the docs. Can you share the use case for this so I can better understand why other should need/want it. Based on your example, this might need to run in `core` or be a handler wrapper like our router middlewares (like you're showing).

> Each instance of AsyncLocalStorage maintains an independent storage context. Multiple instances can safely exist simultaneously without risk of interfering with each other's data. ~https://nodejs.org/api/async_context.html#class-asynclocalstorage

Because of how lambda is executed, I don't think this is needed. Middy `core ` has `internal` that might be similar to this.

Another consideration, We're hoping to have middy be functional with LLRT. I'm not sure this API is part of the WinterCG Spec.

**Comment by gp-jameskyburz** [comment]
AsyncLocalStorage is handy to have a context bound to the async.run entry point (it's callback) that can be read without passing it from function to function. It appears global but isn't.

// context.ts

```typescript
import { AsyncLocalStorage } from 'node:async_hooks';

export type Store = {
  logStream: string;
  lambda: string;
  awsRequestId: string;
  apiRequestId?: string;
  xrayTraceId?: string;
  correlationId: string;
  callChain: number;
};

export const store = new AsyncLocalStorage<Store>();
export const current = () => store.getStore();
```

middy file

```typescript
import { store } from './context.js;

 return middy((event: APIGatewayProxyEvent, context: Context, callback: Callback<APIGatewayProxyResult>) => {
    const handlerContext = {
      apiRequestId: event.requestContext?.requestId,
      awsRequestId: context.awsRequestId,
      callChain: 1,
      correlationId: randomUUID(),
      lambda: `${context.functionName}:${context.functionVersion}`,
      logStream: `${context.logGroupName}/${context.logStreamName}`,
      xrayTraceId: process.env._X_AMZN_TRACE_ID,
    };
    return store.run(handlerContext, handler, event, context, callback);
  })

```

// dynamodb middleware (could be any random file run from the handler function)

```typescript
import { current as getCurrentStore } from './context';

client.middlewareStack.add(
  (next, context) => (args) => {
    const store = getCurrentStore();
    // now has access to the values created in the middleware function
    ...
```

**Comment by gp-jameskyburz** [comment]
LLRT support is supercool :) Not sure about the WinterCG Spec.

In either case I think this middleware initially would be a very node specific thing 😄

**Comment by willfarrell** [comment]
Thanks for sharing in more detail. I'll need to make some time to playaround with AsyncLocalStorage, not sure when I'll be able to. Would it make more sense to put the full event and context (excluding functions) into the store?

Optionally you could build a community middleware to prove out it's usefulness.

**Comment by willfarrell** [comment]
@gp-jameskyburz Something like this?

```javascript
import { AsyncLocalStorage } from 'node:async_hooks'

const defaults = {
  asyncLocalStorage: new AsyncLocalStorage()
}

const asyncLocalStorageMiddleware = (opts = {}) => {
  const { asyncLocalStorage } = {
    ...defaults,
    ...opts
  }

  const asyncLocalStorageMiddlewareBefore = async (request) => {
    asyncLocalStorage.enterWith({
      event: request.event,
      context: request.context
    })
  }
  const asyncLocalStorageMiddlewareAfter = async (request) => {
    asyncLocalStorage.exit()
  }
  const asyncLocalStorageMiddlewareOnError = async (request) => {
    if (request.response === undefined) return
    await asyncLocalStorageMiddlewareAfter(request)
  }
  return {
    before: asyncLocalStorageMiddlewareBefore,
    after: asyncLocalStorageMiddlewareAfter,
    onError: asyncLocalStorageMiddlewareOnError
  }
}
export default asyncLocalStorageMiddleware
```
