### ISSUE TITLE
Support CommonJS (again)

### ISSUE THREAD

**Issue by eyalroth** [middyjs/middy#1233]
Please bring back support for CommonJS.

We have a lot of serverless projects (dozens) in NodeJS. They are all written in CommonJS.

There is very little chance that we will migrate to ESM, since it will require a lot of work. Most notably, we rely heavily on Jest, which doesn't support ESM properly.

If Middy won't support CommonJS, we may have to migrate away from it at some point.

**Comment by willfarrell** [comment]
We have no plans to re-induce cjs support. However, the nodejs team may have a solution for you in version 22 with the new `--experimental-require-module` flag. From my understanding this would address the issue you're experience. If you do end up experimenting with it, please share your finding for others.

**Comment by willfarrell** [comment]
It just landed in Node 20.17 https://nodejs.org/en/blog/release/v20.17.0

**Comment by eyalroth** [comment]
@willfarrell It doesn't seem to help.

Running:
```bash
node --experimental-require-module node_modules/.bin/jest
```

And getting the same error:
```
Cannot find module '@middy/core' from '../../src/foo.ts'
```

And `foo.ts`:
```ts
import middy from '@middy/core';
```

NodeJS: 20.17.0
Jest: 29.7.0
Middy (core): 5.4.6

`jest.config.js`:
```js
module.exports = (testsType) => ({
  preset: "ts-jest",
  testEnvironment: "node",
  modulePathIgnorePatterns: ['dist'],
  testMatch: ['<rootDir>/**/*.test.ts'],
  resetMocks: true,
  transform: {
    '^.+test/.*\\.ts$': ['ts-jest', {
      tsconfig: "<rootDir>/tsconfig.json",
    }]
  },
});
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "commonjs",
    "lib": ["ES2019", "es2020"],
    "allowJs": true,
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true
  },
  "include": ["src/**/*", "test/**/*"],
  "exclude": ["node_modules/**/*"]
}
```

**Comment by willfarrell** [comment]
Thanks for testing. Based on the node release notes this should have allowed middy to be imported using require based on how it's currently configured. I ran a quick test to confirm:

```js
const { default: middy } = require('@middy/core')

const baseHandler = async (event, context, { signal }) => {
  console.log('success')
}
middy(baseHandler)()
```

```bash
node --experimental-require-module index.cjs
```

Which, as expected, passed. This leads me to believe that there is an issue somewhere in your build process, likely typescript. I would recommend opening an issue for typescript to support transpiling to vanilla CommonJS so `--experimental-require-module` can be leveraged.

**Comment by willfarrell** [comment]
Thanks for the additional testing. I know Jest has been working on ESM support, curious how close they are.

> however, this is only relevant to provisioned concurrency

In my experience this is not true. The platform I maintain has a high cold start hit rate (>80%), migrating to ESM had a notable improvement for us at the time. We don't use provisioned concurrency because, as you mentioned, it is a very costly solution. We do take advantage of the `warmup` middleware on a few select endpoints, worth checking out if you don't already use it.

**Comment by eyalroth** [comment]
@willfarrell It's strange that you saw any change without provisioned concurrency.

Without provisioned concurrency, the top-level code of the lambda will start running only on the first request to the container, so it doesn't really matter if it runs in the top-level or inside the handler itself.

Maybe there's a general improvement of imports/requires, but I haven't seen any post about it from AWS.

**Comment by willfarrell** [comment]
Closing, 6.0.0-alpha.0 is now released. https://github.com/middyjs/middy/blob/release/6.0.0/website/docs/upgrade/5-6.md#notable-changes

**Comment by mbret** [comment]
Why is this closed ? the v6 still does not compile on serverless.

**Comment by willfarrell** [comment]
Running the following `node --experimental-require-module index.cjs` where `index.cjs` is

```javascript
const { default: middy } = require('@middy/core')

const baseHandler = async (event, context, { signal }) => {
  console.log('success')
}
middy(baseHandler)()
```

returns `success`. This uses a new feature in nodejs, you may need to open a issue with your build tool provider.
