### ISSUE TITLE
`@datastream/core`  is a production dependency

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1243]
**Describe the bug**
The [`@datastream/core`](https://github.com/willfarrell/datastream/tree/main/packages/core) package is a production dependency.

https://github.com/middyjs/middy/blob/4ad95ba8bc44657d5d9a83af99204abe1b530a61/packages/core/package.json#L65

However, it [only seems to be used](https://github.com/search?q=repo%3Amiddyjs%2Fmiddy%20%22%40datastream%2Fcore%22&type=code) in tests, i.e. should be a development dependency.

**Comment by willfarrell** [comment]
Thanks for reporting. To start off #NotALawyer. Technically, `@datastream/core` is a dependency, a portion of it's code is copied into `@middy/core` but `import` is not used to keep the bundle a little lighter. Thus, for SCA it is marked as a dependancy to ensure the license is preserved. If a copyright lawyer would like to chime in or you have an article by one that advises differently, I'm happy to review and adjust my stance on this.

**Comment by ehmicky** [comment]
Hi @willfarrell,

Thanks for answering. Also, thanks for your hard work in both Middy and `@datastream/core`! Middy is a very well designed library.

For additional context, the main issue here is that, since `@datastream/core` is a production dependency (although it is technically used as a development dependency only), it increases the package size of `@middy/core`. This might go against the following design goal:

> Middy has been engineered to keep your lambda as fast as possible. The minimal core keeps your lambda size small and your cold starts under control. Add only what you need!

Thankfully, the [MIT license](https://github.com/willfarrell/datastream/blob/main/LICENSE) does not require including the full source code when a portion of it being copied. Instead, it requires the following:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So the requirement here is to copy the `LICENSE` file or its contents, not the full source code.

**Comment by willfarrell** [comment]
Thanks for this, very helpful. I've opted to make a change in v6 (full release sometime next month) so that I'm not required to keep track of sub-dep license files manually.

**Comment by ehmicky** [comment]
Thanks @willfarrell!
