### ISSUE TITLE
Using multiple plugins

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1245]
**Is your feature request related to a problem? Please describe.**
Running multiple [plugins](https://github.com/middyjs/middy/blob/main/plugin/) at once does not currently seems to be possible.

**Describe the solution you'd like**
Any implementation that allows running multiple plugins at once works.

For example, optionally passing an array of plugins instead of a single plugin.

Thanks!

**Comment by ehmicky** [comment]
Thanks for your response @willfarrell.

Yes, it makes sense. Sometimes, one needs to take features away to keep the project focused and high quality. :+1: 

---

> 1. increased complexity in the core package

From a pure implementation standpoint, I think it might be possible to build it with something like:	

```js

const middy = (lambdaHandler = defaultLambdaHandler, plugins = []) => {
  // ...
  plugins = Array.isArray(plugins) ? plugins : [plugins]

  // `plugin` is used for non-hooks, e.g. `timeoutEarly`
  const plugin = Object.assign({ ...defaultPlugin }, ...plugins)
  plugin.timeoutEarly = plugin.timeoutEarlyInMillis > 0

  // `plugins` is used for hooks
  runHook(plugins, 'beforePrefetch')
  // ...
}

const runHook = (plugins, hookName, ...args) => {
  for (const plugin of plugins) {
    plugin[hookName]?.(...args)
  }
}
```

That being said, there might some additional logic needed, like:
- When using multiple hooks, the ones in `beforeHandler` should be run in reverse order from the ones from `afterHandler`.
- Maybe some additional error handling might be needed (not sure about this). 
- `requestEnd` can be async. 

 
Anyway, it's easy to see how this might become more complicated, as you are saying.

---

Another approach would be to separate options like `timeoutEarlyInMillis` from hooks, for example:

```js
middy({
  timeoutEarlyInMillis: 10,
  plugins: [
    {beforePrefetch() { /* ... */ }, beforeHandler() { /* ... */ }},
    {beforeHandler() { /* ... */ }},
  ],
})
```

---

One other idea would be to create a separate package to combine multiple plugins into one.

```js
import combinePlugins from '@middy/combine-plugins'

middy(combinePlugins([hrtimePlugin, memoryPlugin]))
```

Implemented with something like this:

```js
export default combinedPlugins = (plugins) => Object.assign(
  {},
  ...plugins,
  {
    beforePrefetch: runHook.bind(undefined, plugins, 'beforePrefetch'),
    beforeMiddleware: runHook.bind(undefined, plugins, 'beforeMiddleware'),
    // ...
  },
)

const runHook = (plugins, hookName, ...args) => {
  for (const plugin of plugins) {
    plugin[hookName]?.(...args)
  }
}
```

Like this, users have a way to combining plugins, without having to change anything with `@middy/core`.

---

> 2. potential for reduced performance
> 3. Allows for anti-patterns to be easier, and we didn't want to promote them

Yes, I can see how hooks/plugins can easily promote bad patterns in terms of performance in a serverless environment.

On the other hand, they could also provide with some positive patterns. What I especially have in mind is the capability to measure the amount of resources spent not only on the whole Lambda function (which is something that one can already do with CloudWatch metrics) but inside smaller parts of it. 

By providing a middleware pattern, Middy encourages users to break down their serverless functions into smaller parts. This allows measuring each of those parts in terms of: memory, CPU, duration, file I/O, network I/O. What would be especially relevant for AWS Lambda is: 
 - Memory, since that can be used to scale up/down the Function's `MemorySize`
 - Duration, due to Lambda timeouts

---

That being said, it definitely looks like a bigger feature, so that sounds perfectly reasonable to reject it, considering the goal of Middy is to remain small.

So please feel free to close this issue, I just wanted to bring those ideas, in case any of it was interesting. Thanks for reading! :)

**Comment by willfarrell** [comment]
Thanks for the detailed comment.

I've pushed an implementation of multi-plugins (https://github.com/middyjs/middy/blob/release/6.0.0/plugin/multi.js). Hopefully you find it helpful.

**Comment by ehmicky** [comment]
Thanks @willfarrell! :+1:
