### ISSUE TITLE
Typo in documentation of `http-router` for v6

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1247]
The `notFoundHandler` option's name is `notFoundResponse` instead.

https://github.com/middyjs/middy/blob/6.0.0-alpha.0/website/docs/routers/http-router.md#options

https://github.com/middyjs/middy/blob/abe40588d3fde646780bae4582e3248d037570d0/packages/http-router/index.js#L16

**Comment by willfarrell** [comment]
Thanks! Docs updated

**Comment by ehmicky** [comment]
This is also in `ws-router`:

https://github.com/middyjs/middy/blob/abe40588d3fde646780bae4582e3248d037570d0/website/docs/routers/ws-router.md?plain=1#L20
