### ISSUE TITLE
`Report-To` HTTP header is deprecated

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1249]
**Is your feature request related to a problem? Please describe.**
`@middy/security-http-headers` is using the `Report-To` HTTP header, which [has been deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Report-To) in favor of the [`Report-Endpoints`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Reporting-Endpoints) header. 

**Describe the solution you'd like**
Use the new syntax for this header. This would also simplify the code, since that header is simpler (having fewer features).

**Comment by willfarrell** [comment]
I've added in support into v6. I wasn't able to find a monitoring service (ie https://report-uri.com/) that supports the new header. Because of this, both will be supported for v6.

**Comment by ehmicky** [comment]
Thanks! Good to know the new header is now yet well supported. :+1:
