### ISSUE TITLE
`Cache-Control: no-transform`

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1252]
**Is your feature request related to a problem? Please describe.**
In `@middy/http-content-encoding`, if the `Cache-Control: no-transform` request header is set, the response should not be compressed. 

**Additional context**
The [standard](https://httpwg.org/specs/rfc9111.html#cache-request-directive.no-transform).
Implementations in [Cloudflare](https://developers.cloudflare.com/cache/concepts/cache-control/#gzip-and-other-compression) and [Express](https://github.com/expressjs/compression/issues/51).

**Comment by willfarrell** [comment]
I added in a little more. if the header exists in the request it will add to the response if the header isn't already set. then check if the response has the header set as expected before existing out early

**Comment by ehmicky** [comment]
Thanks.

Please note the current implementation does not work when the `Cache-Control` header contains several directives.

If the `Cache-Control` header in the _request_ is `no-transform, no-cache`, the following condition will fail.

https://github.com/middyjs/middy/blob/eaa4f2112a8ad5691a9d81d709e334f7af8edb94/packages/http-content-encoding/index.js#L50

Also, if the `Cache-Control` header in the _response_ is `no-cache`, the following line will be ignored, instead of appending it as `no-cache, no-transform`.

https://github.com/middyjs/middy/blob/eaa4f2112a8ad5691a9d81d709e334f7af8edb94/packages/http-content-encoding/index.js#L51

**Comment by willfarrell** [comment]
Good catch!
