### ISSUE TITLE
`Vary: Accept-Encoding`

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1253]
**Describe the bug**
If a request has no `Accept-Encoding` request header, the response will not be compressed by `@middy/http-content-encoding`. If that response is cached, then another request with an `Accept-Encoding` request header will receive that cached response, uncompressed even though the client asked for a compressed response.

The reverse is true too, which might lead for clients which do not decompress responses to receive a compressed response. 

This is a bigger problem when the server cache is shared by multiple clients, with potentially different preferences for compression.

**Expected behaviour**
The `Vary: Accept-Encoding` response header should be set. 

`Vary` should be set regardless of whether `Accept-Encoding` is set, since setting it or not both influence the response.

However, if the response is not compressible (i.e. its compressed size is larger than not compressed), `Vary` should probably not be set. For example, it would wasteful to cache one copy of a big `image/png` response for each `Accept-Encoding` possible value, if that response is never compressed and always the same.

**Additional context**
Link to code in [Express](https://github.com/expressjs/compression/blob/63b134fd94f0bf3f949f32433eea2144386a3e52/index.js#L154).

**Comment by willfarrell** [comment]
Thanks for all the detailed issues you opened last week. I've set aside time today to review them all. Expect all to be included into v6 unless otherwise noted.

**Comment by ehmicky** [comment]
Thanks @willfarrell
