### ISSUE TITLE
Problem with multiValueQueryStringParameters and queryStringParameters when Array are indexed

### ISSUE THREAD

**Issue by throrin19** [middyjs/middy#1255]
**Describe the bug**
When we try to send Data to our API using query String with indexed array (default in axios), We don't have same thing than non indexed array : 

### Query parameters without indexed array : 

   ```
   http://localhost:8000?lite=true&measures[]=[%22TE%22,%22lavabo%22]&measures[]=[%22FL%22,%22lavabo%22]&measures[]=[%22VO%22,%22lavabo%22]&measures[]=[%22TE%22,%22lavab%22]
   ``` 

- Result in Middy: 
    - queryStringParameters : 
       ```
       {"lite":"true", "measures[]":"[\"TE\",\"lavab\"]"}
       ```
    - multiValueQueryStringParameters :
       ```
       {"lite":["true"],"measures[]":["[\"TE\",\"lavabo\"]","[\"FL\",\"lavabo\"]","[\"VO\",\"lavabo\"]","[\"TE\",\"lavab\"]"]}
       ```

### Query parameters with indexed array :

   ```
   http://localhost:8000?lite=true&measures[0][0]=TE&measures[0][1]=lavab&measures[1][0]=VO&measures[1][1]=lavabo
   ```

- Result in Middy: 
    - queryStringParameters :
       ```
       {"lite":"true","measures[0][0]":"TE","measures[0][1]":"lavabo","measures[1][0]":"FL","measures[1][1]":"lavabo" }
       ```
    - multiValueQueryStringParameters : 
       ```
       {"lite":["true"],"measures[0][0]":["TE"],"measures[0][1]":["lavabo"],"measures[1][0]":["FL"],"measures[1][1]":["lavabo"]}
       ```

**To Reproduce**
How to reproduce the behaviour:

1. Launch a request with non indexed array
2. Launch a request with indexed array

**Expected behaviour**
Same result between indexed and non indexed array : multiValueQueryStringParameters with correct values.

**Environment (please complete the following information):**

- Node.js: 20.18.0
- Middy: 5.5.1
- AWS SDK: 3.682.0

**Additional context**
In local we launch it with serverless-offline

**Comment by willfarrell** [comment]
Without middy, do you get the expected results from requests to lambda & serverless-offline? As far as I know, middy never modifies `multiValueQueryStringParameters`.
