### ISSUE TITLE
Default multi-value headers 

### ISSUE THREAD

**Issue by florianbepunkt** [middyjs/middy#1256]
**Describe the bug**
https://github.com/middyjs/middy/blob/f50d2352be04a92ce8e6352d70d218242f714633/packages/http-header-normalizer/index.js#L85C28
This line copies the default headers to multi-value headers, regardless of whether they are multi-value or not. Is this intended?

**Expected behaviour**
Depends on the input. Either they should not be copied at all or only multi-value headers should be copied.

**Comment by willfarrell** [comment]
Good catch, I think the following changes are needed:

1. The `defaultHeaders` should be included, but need to be update to be arrays if not already when updating `multiValueHeaders`
2. The `defaultHeaders` should only include the last item if the value is an array when updating `headers`

I can make some time to put a PR together for this.

**Comment by willfarrell** [comment]
Fix pushed and released with 6.0.0-beta.1
