### ISSUE TITLE
httpErrorHandler not working correctly

### ISSUE THREAD

**Issue by mafrosis** [middyjs/middy#127]
Hey @middyjs. Love the project. I'll keep an eye on tickets and chip in where I can help.

It appears to me that `httpErrorHandler` isn't working correctly. Serverless is returning a 200 when I throw an Error. Consider the code in the middleware:

https://github.com/middyjs/middy/blob/master/src/middlewares/httpErrorHandler.js#L5

And this test code:

    import HttpError from 'http-errors';
    import createError from 'http-errors';

    console.log( new createError.UnprocessableEntity() instanceof HttpError );
    // false
    console.log( new createError.UnprocessableEntity() instanceof createError.HttpError );
    // true

Which to me suggests a bug.. But I may just be misusing the library. (Warning: I am not a node guy).

Cheers!

**Comment by mafrosis** [comment]
I take it all back :) The module in `middy` works just fine.

I copied the source of `httpErrorHandler` to customise it for my app, and changed the import to an ES6 style instead of using `require`:

    import HttpError from 'http-errors';
    // handler.error instanceof HttpError => false

The original looks like:

    const { HttpError } = require('http-errors')
    // handler.error instanceof HttpError => true

However if import `createError`, then I can make the ES6 style import work:

    import createError from 'http-errors';
    handler.error instanceof createError.HttpError => true

Which may indicate that either A) I don't know nodejs, B) I'm using Babel wrong or C) probably both.

If anyone has read this far, thanks for your time! 💯

**Comment by lmammino** [comment]
Hey @mafrosis, thanks for your time and for using middy :)

I have to say that these kind of errors with the new module syntax are normal, I spent a decent amount of time myself with similar issues when I started using them (and still I get something wrong from time to time), so don't be too hard on yourself!

I look forward to seeing your first contribution to this project!
