### ISSUE TITLE
The middleware type definition is missing in the latest release (0.10.2)

### ISSUE THREAD

**Issue by nnyegaard** [middyjs/middy#132]
Hey,

Typescript will complain when the tsconfig setting "noImplicitAny" is set to true.

It's because the latest release 0.10.2 does not include the middlewares.d.ts file

Workaround is adding the  middlewares.d.ts file from the repo or change noImplicitAny to false

**Comment by lmammino** [comment]
Hello @nnyegaard, thanks for submitting this issue. It would be amazing if you could open a PR with a fix 😉

**Comment by nnyegaard** [comment]
Sure @lmammino created PR: https://github.com/middyjs/middy/pull/135
