### ISSUE TITLE
SSM middleware not mentioned in main README

### ISSUE THREAD

**Issue by garyhollandxyz** [middyjs/middy#140]
Hi!

First of all, thank you for the extremely useful library! We've recently been able to streamline a lot of our code thanks to Middy :-)

I've just implemented the SSM middleware, but almost missed that it existed because it doesn't appear in the main README at https://github.com/middyjs/middy#available-middlewares (but it _does_ appear in the dedicated middleware page at https://github.com/middyjs/middy/blob/master/docs/middlewares.md#ssm).

Is there a specific reason that it's omitted from the main README? If not, I'd be very happy to throw up a quick PR with it added.

Thanks!

**Comment by lmammino** [comment]
Great finding @garyhollandxyz!
I would definitely love a PR, so we can keep the attribution and have a new contributor 🎉
