### ISSUE TITLE
Support for node.js 8.10 - returning promises instead of calling callback

### ISSUE THREAD

**Issue by tommy5dollar** [middyjs/middy#148]
Hello,

AWS [recently started supporting node.js 8.10](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/) and alongside this released new functionality where you can simply return a promise from your handler instead of calling into the callback function.

Is this something we'd like to support in middy? If so, I can look into creating a pull request. Any obvious pitfalls I should be aware of?

This also raises a separate question. Will middy be planning to support 6.10 for the foreseeable future or will you be looking to move to 8.10 ASAP?

**Comment by lmammino** [comment]
Hey @tommy5dollar, thanks for raising this discussion.

Middy already supports [promises and async handlers](https://github.com/middyjs/middy#asyncawait-support), so I am not really sure we have to do something special to adapt to the new native feature.

I'll do some tests later this weekend to make sure about it, but let me know if you have more specific ideas about things that are missing and might be worth implementing.

Regarding keeping compatibility with version 6.10 I would honestly try to keep it for now, but I have to admit I haven't formed a strong opinion on this subject yet.

**Comment by lmammino** [comment]
If you have time to invest on improving the current doc, that would be awesome :)
