### ISSUE TITLE
Secrets Manager middleware

### ISSUE THREAD

**Issue by dschep** [middyjs/middy#151]
In the same vein as the SSM middleware, a middleware for [the newly anounced Secrets Manager](https://aws.amazon.com/blogs/aws/aws-secrets-manager-store-distribute-and-rotate-credentials-securely/) would be really useful.

Here are the `aws-sdk` docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#getSecretValue-property

**Comment by dankelleher** [comment]
Hi @hsz I added a PR to switch from ES6 exports to node module.exports so that it works out of the box with lambda + middy without having to use any transpilers:

https://github.com/hsz/middy-secrets/pull/2

**Comment by hsz** [comment]
@dankelleher Thanks! I've merged it and published with `v.0.2.1`

**Comment by hsz** [comment]
@lmammino I think that this issue can be successfuly closed.
@dschep `secretsMiddleware` has been added to the `middy`

FYI - just marked my `middy-secrets` as deprecated.
