### ISSUE TITLE
Interest in a Language Middleware?

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#162]
Is there interest in me submitting this as a PR, or shall I create a separate repo for it?

Basically, parses the request `Accept-Language` headers, and adds to `handler.event.meta.locale` then adds `Content-Language` to the response.

```js
/**
 * Middleware for language headers
 * @param allowedLocales    first value in array treated as default. Default: `['en']`
 * @returns {{before(*, *): void, after(*, *)}}
 */
module.exports = (allowedLocales = ['en']) => {
  const acceptLanguage = require('accept-language')
  acceptLanguage.languages(allowedLocales)

  return {
    before (handler, next) {
      handler.event.headers = Object.assign({}, handler.event.headers)
      const locale = handler.event.headers['Accept-Language']
        ? acceptLanguage.get(handler.event.headers['Accept-Language'])
        : allowedLocales[0]

      if (!handler.event.meta) handler.event.meta = {}
      handler.event.meta.locale = locale

      next()
    },
    after: withHttpResponseHeaders,
    onError: withHttpResponseHeaders
  }
}

const withHttpResponseHeaders = (handler, next) => {
  handler.response = handler.response || {}
  handler.response.headers = Object.assign(
    {},
    {
      'Content-Language': handler.event.meta.locale
    },
    handler.response.headers
  )
  next()
}
```

**Comment by lmammino** [comment]
Hello (again :) ) @willfarrell, thanks for opening this issue!

I think we already have something similar in the [httpContentNegotiation](https://github.com/middyjs/middy/blob/master/docs/middlewares.md#httpcontentnegotiation) middleware.

Let me know if you see some additional value in adding a dedicated middleware for language negotiation.

**Comment by willfarrell** [comment]
I missed that one while going through the docs. Not the clearest or most familiar name. I'll update my PR to take advantage of it. Thanks.

The only difference I see is the one above response adds `Content-Language`, something worth adding to `httpContentNegotiation`?
