### ISSUE TITLE
Create GitHub Issues / PR templates to simplify contributions and adoption of common practices

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#167]
We should create [Issue and Pull Request templates
](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) for this project to ensure that new contributors will follow as much as possible the standards and best practices we would like to enforce over this project.

One thing I would suggest, for instance, is to have a PR template that offers the user a pre-compiled checklist that looks like the follows:

```markdown
### PR checklist

  - [ ] I added tests for my changes
  - [ ] I updated the documentation to reflect my changes
  - [ ] I updated the Typescript typings to reflect my changes
```

which, once rendered, will look like:

### PR checklist

  - [ ] I added tests for my changes
  - [ ] I updated the documentation to reflect my changes
  - [ ] I updated the Typescript typings to reflect my changes

This way we should be able to enforce best practices in a more intuitive way

**Comment by vladgolubev** [comment]
See https://github.com/devspace/awesome-github-templates and https://github.com/stevemao/github-issue-templates for inspiration 🧐

**Comment by lmammino** [comment]
Done
