### ISSUE TITLE
Find a way to maintain a structured CHANGELOG.md file

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#172]
As middy becomes "officially stable" we should make sure we have a `CHANGELOG` file per every release, especially to track bug fixes and breaking changes.

It would be great to find some tool that can provide a bit of automation

**Comment by vladgolubev** [comment]
I haven't used it yet, but https://github.com/zeit/release might be the one

**Comment by ossareh** [comment]
https://github.com/marionebl/commitlint

I'm using this, it seems pretty slick. I'm using it as part of a lerna monorepo. The combination of the two make it really easy to generate changelogs

**Comment by pvdlg** [comment]
You can check out [semantic-release](https://github.com/semantic-release/semantic-release). That's a more advanced version of the auto-publish script that you are running (it can generate a `CHANGELOG.md`, create a GitHub release, publish on npm, comment issues/PR when they are released etc...).
Full disclosure I'm the maintainer of `semantic-release`.
I can help with the config if you'd like.

**Comment by ChristianMurphy** [comment]
`lerna version` includes a conventional commit option that can automatically update the version and the changelog https://github.com/lerna/lerna/tree/master/commands/version#--conventional-commits

Or for a more manual approach, keep a changelog has some good guidelines https://keepachangelog.com/en/1.0.0/

**Comment by zoellner** [comment]
Until this happens, I'd like to suggest to at least make it easier to follow the version changes by adding the version to the commit message. Instead of "bump version" use something like "version v0.25.0" - that way one can at least glance at the commit logs to see what was going on.

**Comment by ematipico** [comment]
`lerna version`, as already suggested, is the perfect tool to maintain the changelogs around each package. It supports conventional commits for stable and beta versions.
