### ISSUE TITLE
docs/examples

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#173]
It would be amazing to have a section of the documentation with structured examples like the following:

  - how to build an API (body parser / validation / content negotiation / response serialization / dealing with headers / dealing with HTTP errors / CORS)
  - how to process files from s3 with s3 normalizer
  - connection pooling and event loop
  - configuration manager (ssm / secret store)
  - Cold start problem (warmup)

**Comment by vladgolubev** [comment]
🤔 What about considering https://docusaurus.io/? I wouldn't say it becomes a standard, but definitely more & more common in JS community.

**Comment by lmammino** [comment]
@vladgolubev, never tried but I am definitely open to this option :)

**Comment by DavidWells** [comment]
Here is an example of using custom auth middleware https://github.com/netlify-labs/movie-app/blob/master/functions/auth-via-middleware.js#L1-L17

Middleware is here: https://github.com/netlify-labs/movie-app/blob/7470d8cbc3f953bfbd7b4795b69302a39be5e21c/functions/middleware/auth.js

It checks for valid JWT token issued by auth0 https://github.com/netlify-labs/movie-app/blob/7470d8cbc3f953bfbd7b4795b69302a39be5e21c/functions/utils/checkAuth.js
