### ISSUE TITLE
InputOutputLogger middleware

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#174]
We should have a middleware that, once attached, logs the input (event) and the output (response) once attached.

By default, it should use `console.log`, but the logging function should be customisable by an option.

We might also consider merging this with the Error Logger discussed in #170

**Comment by dkatavic** [comment]
Do you maybe see this as a part of `debug` middleware you have discussed in the roadmap thread #159 ?

**Comment by lmammino** [comment]
Not sure yet, but it might be an option :)

**Comment by kevinrambaud** [comment]
Hey, it's been a long time! 

I think it may be separate from the `debug` middleware we were talking about. I was personally thinking about the `debug` middleware as something that could provide us details about what happens under the hood when running our lambda function such as logging the middleware calls, transformation that happened during the flow.

We personally use this kind of middleware in my company and use it on some of services to send "info" level logging to our logging platform.

I think it can definitely be a single middleware with a custom logger option as prop.

**Comment by lmammino** [comment]
Great point @kevinrambaud.
It seems you already implemented something like this, would you like to contribute with a PR?

**Comment by kevinrambaud** [comment]
Sure, I'll do it

**Comment by lmammino** [comment]
Closed by #205
