### ISSUE TITLE
Feature: helmet middleware

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#187]
A middleware to add in security headers. I expect this will have a lot of bedate - would you like this included here or as a separate repo?

Example - Apply these headers
- `Server`: ``
- `X-Content-Type-Options`: `nosniff`
- `Referrer-Policy`: `no-referrer`
- `Strict-Transport-Security`: `max-age=31536000; includeSubdomains; preload`
- `X-Frame-Options`: `DENY`
- `X-XSS-Protection`: `1; mode=block`
- `X-UA-Compatible`: `ie=edge`

Ideal approach being a port of [`helmet`](https://helmetjs.github.io)

**Comment by lmammino** [comment]
Personally I'd love that and I have been more than happy to have this as an official middy middleware

**Comment by willfarrell** [comment]
What if we did `middyjs/helmet` w/ npm `middy-helmet`

**Comment by lmammino** [comment]
I would prefer to have a more generic name (even though we should explicitly mention a reference to helmet in the readme as source of inspiration). 

How does something like `http-security-headers` sounds to you?

In the work in progress 1.0.0 version of middy it will be it's own package under `@middy/http-security-headers`.

What do you think? :)

**Comment by willfarrell** [comment]
Works for me. I'll commit to the alpha branch when I find some time. Does v1 assume node8.10?

**Comment by lmammino** [comment]
not strictly @willfarrell, I'd love to still keep support for 6.10 as it hasn't been deprecated neither in Node.js nor in Lambda. In the master branch we just merged CI changes to run the tests in both environments. I'll try to update the 1.0.0 branch with this change soon.
