### ISSUE TITLE
Feature Request: Cors middleware should allow multiple possible origins

### ISSUE THREAD

**Issue by thejuan** [middyjs/middy#193]
If you have an api that is used by multiple origins you need to dynamically determine the origin against a whitelist and return the matching origin or a default.

At the moment the cors middleware only supports a static or wildcard origin.

happy to submit a PR

**Comment by lmammino** [comment]
I believe you are not the first one who asked for this, a PR would definitely be appreciated :)

**Comment by thejuan** [comment]
Submitted https://github.com/middyjs/middy/pull/194

**Comment by lmammino** [comment]
This has been addressed in 6314616, but I am going to leave this open and mark it for 1.0.0 as we need to backport (or in this case forward-port ) the changes to the work in progress future version.

**Comment by thejuan** [comment]
This was backported.
