### ISSUE TITLE
Use with custom authorizers

### ISSUE THREAD

**Issue by tommy5dollar** [middyjs/middy#196]
Hello,

Has anyone has any success using middy with custom authorizers?

It seems to me (I'm happy to be corrected if I'm wrong) that you cannot throw a 401 from a custom authorizer using the callback, you have to call `context.fail('Unauthorized')`. Middy (I believe) only supports using the callback?

Thanks in advance

**Comment by vladgolubev** [comment]
Hi @tommy5dollar 

I don't use middy with custom authorizer Lambda yet, but you definitely can use callback! Here is the example:

```js
if (!policy) {
  return callback('Unauthorized');
}
```

Are you throwing 401 error using `http-errrors` npm package? If so, then middy will handle such errors and return them as response in 2nd callback argument. 

What kind of error object do you throw?

**Comment by willfarrell** [comment]
Personally I use the following (running v1)

```
if (!isPublic && !handler.event.jsonwebtoken.sub) {
        throw new createError.Unauthorized()
      }
```
Let `http-errrors` or other catch it from there.
