### ISSUE TITLE
Async before middleware causes re-entrancy

### ISSUE THREAD

**Issue by thejuan** [middyjs/middy#211]
I just added an async before middleware. And now in some circumstances (haven't found them) the middlewares run again from the beginning. I've found it as the jsonBodyParser blows up the second time.

There's a pull-request for success and failure re-entrancy https://github.com/middyjs/middy/pull/210/files
But i think the problem is bigger than the PR deals with.

```
export function middleware(): middy.IMiddyMiddlewareObject {
  return {
    before: async (handler: middy.IHandlerLambda<any, APIGatewayProxyResult>, next: middy.IMiddyNextFunction) => {
       await doSomeWork();
    }
  };
}
```

**Comment by thejuan** [comment]
This is happening with Serverless-Offline, the handler is stored and re-used. It looks like maybe something isn't being cleared on the next call. Or it could be an unexpected concurrency that doesn't happen in AWS

**Comment by lmammino** [comment]
Hello @thejuan, this is probably related to #210. Can you test if the code in this PR fixes your issue?

**Comment by lmammino** [comment]
@thejuan, #210 has been merged. Let me know if the latest version of middy (branch 0.x) solves your issue.

**Comment by thejuan** [comment]
Thanks sorry I missed the first message. Our issue was due to a rogue test adding unexpected concurrency. It's hard to simulate on purpose :)
My issue doesn't exist anymore.

I think there is a larger issue where middy isn't thread-safe in environments like serverless-offline with concurrent requests. However, it may not be a use case you want to support.
