### ISSUE TITLE
Naming convention for third party middleware?

### ISSUE THREAD

**Issue by alexdrans** [middyjs/middy#214]
Hi,

I have created a third-party middleware which isn't useful enough to go into core, and named it [middy-middleware-warmup](https://github.com/alexdrans/middy-middleware-warmup).

I couldn't find any other third-party middlewares, so just checking if my naming convention is cool?

Alex

**Comment by willfarrell** [comment]
I've been using `middy-{name}` ex https://github.com/willfarrell/middy-jsonapi

**Comment by willfarrell** [comment]
PS checkout https://github.com/middyjs/middy/blob/master/src/middlewares/warmup.js
