### ISSUE TITLE
Module initialization error

### ISSUE THREAD

**Issue by Tacklebox** [middyjs/middy#216]
Hi, If I try to use any of the middy middlewares I get 

START RequestId: <rqid> Version: $LATEST
module initialization error: Error
    at Function.instance.use (/var/task/node_modules/middy/src/middy.js:200:13)
    at Object.<anonymous> (/var/task/handler.js:77:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: <rqid>
REPORT RequestId: <rqid>  Duration: 46.78 ms      Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 25 
module initialization error
Error

I tried the separately and together the httpErrorHandler, httpEventNormalizer, and the validator module, all give the same result.

Just wrapping the handler with middy(...) works correctly.

I am using node 8.10 on lambda and using async arrow function handler.

**Comment by lmammino** [comment]
hey @Tacklebox, can you post some code examples that generate the failure you mentioned?

Also, why did you close the issue?

**Comment by Tacklebox** [comment]
Ah, it was my mistake, I am fairly new to serverless and was able to figure it out with x-ray. A different endpoint in the same file had a misspelled middleware. I didn't realize that could cause the other endpoints to fail. Everything is working really well now, Thanks for the cool software!

**Comment by lmammino** [comment]
Great to know you figure it out! I look forward to knowing more about your use cases for middy :)
