### ISSUE TITLE
Constructing middleware before use

### ISSUE THREAD

**Issue by dupkey** [middyjs/middy#220]
I'm using the cors middleware and I'm trying to add my origins once so that I don't have to do it in every Lambda. If I import and use the following script in my function will it screw up middleware execution order?

`
const { cors } = require('middy/middlewares');

module.exports.cors = (options) => cors({
  origins: ['http://localhost:8080'],
  options
});
`

**Comment by lmammino** [comment]
Hello @dupkey and sorry for the very late reply.

So, if I get your question, you are on the right track and what you can do is the following:

## 1. Create a module with your customized middleware

```javascript
# src/middlewares/myCors.js

const { cors } = require('middy/middlewares')

module.exports.myCors = cors({
  origins: ['http://localhost:8080']
})
```

This will create an (already configured) instance of a CORS middleware that you can reuse across your app.

## 2. Import and attache your CORS middleware

```javascript
# src/someHandler.js
const middy = require('middy')
const { myCors } = require('./middlewares/myCors')

const handler = middy((event, context, cb) => {
  // ...
})
handler.use(myCors)
module.exports.handler = handler
```

Please let me know if this is clear enough and if you need further help

**Comment by dupkey** [comment]
Thanks @lmammino and no worries.

Below is a link to what I ended up doing. It seems to work fine. If you see any issues I may have feel free to re-open this issue. I appreciate the feedback!

[https://gitlab.com/dupkey/serverless-examples/tree/master/aws-node-rest-api-with-dynamodb-and-offline/src](https://gitlab.com/dupkey/serverless-examples/tree/master/aws-node-rest-api-with-dynamodb-and-offline/src)

**Comment by lmammino** [comment]
Glad it was useful and happy to see another usage of middy @dupkey  :)

I actually like your solution better as you are creating a high order function that allows you to still pass extra options if you need them in a given handler.

I look forward to seeing more from you!

Regards
