### ISSUE TITLE
Port changes from #233 in 1.0.0 branch

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#234]
@sdomagala, would you like to help with this? 😉

**Comment by sdomagala** [comment]
Can do ;) Just the changes from #233?

**Comment by lmammino** [comment]
It would great to make sure we also have changes from #235. @hsz interested in contributing? :)

**Comment by sdomagala** [comment]
@lmammino Pull request for those changes #236 - I had some troubles with Node 6.10.0 in there, and when it comes to #235, looks like it's already there 😉

@hsz No siema 😄

**Comment by lmammino** [comment]
Done in #236
