### ISSUE TITLE
Problem with serverless-webpack

### ISSUE THREAD

**Issue by JakubMatejka** [middyjs/middy#243]
I have a problem with Serverless and `serverless-webpack` plugin. As soon as I include the plugin in `serverless.yml` config and deploy, the handler fails with:

```
module initialization error: TypeError 
         at Module.<anonymous> (/var/task/src/lambda.js:174:16) 
         at Module../src/lambda.js (/var/task/src/lambda.js:177:30) 
         at __webpack_require__ (/var/task/src/lambda.js:20:30) 
         at /var/task/src/lambda.js:84:18 
         at Object.<anonymous> (/var/task/src/lambda.js:87:10) 
         at Module._compile (module.js:652:30) 
         at Object.Module._extensions..js (module.js:663:10) 
         at Module.load (module.js:565:32) 
         at tryModuleLoad (module.js:505:12) 
         at Function.Module._load (module.js:497:3)
```

 The handler is just this:

```js
const middy = require('middy');

const handlerFunction = async (event, context, callback) => {
  return { statusCode: 200, body: JSON.stringify({ status: "ok" })};
};

const handler = middy(handlerFunction);
module.exports = { handler };
```

Here is the `lambda.js` file after compilation: https://gist.github.com/JakubMatejka/a0601f4092b5ef52b89ddf9f27abe9a4

And my `webpack.config.js` looks like this:

```js
const nodeExternals = require('webpack-node-externals');
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
  mode: process.env.STAGE === 'prod' ? 'production' : 'development',
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'source-map',
  externals: [nodeExternals({
    modulesFromFile: true,
  })],
  module: {
    rules: [
      {
        test: /\.js$/,
        include: __dirname,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/env', '@babel/flow'],
          },
        },
      },
    ],
  },
  plugins: [],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
};
```

The `externals` section with `webpack-node-externals` ensures that dependencies from `package.json` (including Middy) will be bundled as they are (without webpacking).

I use 
- middy 0.19.1
- serverless 1.32.0
- serverless-webpack 5.2.0
- babel 7.1.2
- webpack 4.20.2

Would you have any idea what is wrong? When I disable the `serverless-webpack` (by removing it from `plugins` section of `serverless.yml`), then the handler work fine. Here is whole source code: https://github.com/keboola/graph/tree/0.0.1

**Comment by JakubMatejka** [comment]
I'm sorry but it looks that somewhere during the deployment appeared some weird delay and Lambda run an old version of the code instead of the current I deployed. The factual error looks a little bit differently, I open a new ticket with proper description.

**Comment by jscontreras** [comment]
I had the same issue with `middy` and `serverless`.
I started receiving `Webpack` compilations errors the moment I use `middy()`

In my case, the culprit was the plugin `- serverless-bundle`

I disabled it and everything worked again.

**Comment by willfarrell** [comment]
@jscontreras can you open a new issue if you're running into this with Middy v3.
