### ISSUE TITLE
CORS Access-Control-Allow-Headers meant to be Access-Control-Expose-Headers?

### ISSUE THREAD

**Issue by thejuan** [middyjs/middy#245]
The Access-Control-Allow-Headers header is to specify which headers are allowed to be sent to the endpoint and is a response header on the OPTIONS request.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

Access-Control-Expose-Headers is sent back on the response of the actual call to tell the client which headers can be passed to client code. I think this is the one that makes more sense in Middy's use case as the pre-flight is usually handled by APIG?

**Comment by lmammino** [comment]
Would you like to submit a PR for that?

**Comment by thejuan** [comment]
Can do, do you agree? Add a new configuration item exposeHeaders? Check the http method for which headers to return in case people are using it for options calls?

**Comment by willfarrell** [comment]
@thejuan still interested in submitting a PR for this?

**Comment by thejuan** [comment]
Yep, are you happy with the analysis?

**Comment by lmammino** [comment]
> Add a new configuration item exposeHeaders? Check the http method for which headers to return in case people are using it for options calls?

We should probably have both, possibly in a configurable way. What do you think @willfarrell ?

**Comment by willfarrell** [comment]
I would suggest, extending the middleware to include the new header, with the default to `*`. In the docs be sure to mention `Note that the 'Authorization' header can't be wildcarded and always needs to be listed explicitly.`

**Comment by willfarrell** [comment]
Added in all missing cors headers into the v2 alpha - https://github.com/middyjs/middy/pull/587
If you'd like them included in v1, please open a PR. Happy to merge in.
