### ISSUE TITLE
Cannot throw from middleware 'before'

### ISSUE THREAD

**Issue by tsmith123** [middyjs/middy#247]
Just trying out Middy and have a small issue with returning early from a `before` middleware. I'm using Node 8.10 with `async`.

My middleware looks like this:

```
const validate = (config) => {
  return ({
    before: async (handler, next) => {
      throw new Error('This is not a booking')
    }
  })
}
```

This does not return early with an error though I thought it would do. It seems to return to the function and continue executing it instead.

If I change before to after (which is of course not what I want):

```
const validate = (config) => {
  return ({
    after: async (handler, next) => {
      throw new Error('This is not a booking')
    }
  })
}
```

then this returns the actual error, I assume because it's the last piece of code that is run.

How can I get the before part to return with an error before the Lambda itself is called?

**Comment by willfarrell** [comment]
Can you please re-test this using the v1 branch using node >= v10. CLosing for now, please re-open if necessary.
