### ISSUE TITLE
Broken link in the website docs

### ISSUE THREAD

**Issue by andreafalzetti** [middyjs/middy#260]
Hi guys,

I think the repo of the website `middy.js.org` is private otherwise I would have sent a PR! 

There's a broken link in the docs:

```
More details on creating middlewares
Check the ------> code for existing middlewares <------- to see more examples on how to write a middleware.
```

<img width="830" alt="screen shot 2018-12-04 at 18 42 11" src="https://user-images.githubusercontent.com/2318450/49465034-701f9900-f7f4-11e8-9e9a-a401f9caef05.png">

Currently pointing to:
```
https://middy.js.org/src/middlewares
```

instead of:
```
https://github.com/middyjs/middy/blob/master/docs/middlewares.md
```

Thanks!

**Comment by vladgolubev** [comment]
Hey @andreafalzetti! Good catch!

Actually the website source is in this file: https://github.com/middyjs/middy/blob/master/README.md.hb 

Waiting for a PR ;)

**Comment by andreafalzetti** [comment]
Done! https://github.com/middyjs/middy/pull/261

thanks
