### ISSUE TITLE
Any reason that you can't pass modified request/response object to next() to avoid mutating? 

### ISSUE THREAD

**Issue by iDVB** [middyjs/middy#269]
I have my middleware working on Lambda without middy, and excited to try porting it over. However, I've implemented it so that there is no mutation. 

my code Ex:
`callback(null, newResponse);`

Would be great if one could....

`next(newResponse);`

Any reason this wasn't factored into this library?

**Comment by willfarrell** [comment]
This will be address in v2, but even better `return { ...response...}`
