### ISSUE TITLE
httpErrorHandler not handling optimized code

### ISSUE THREAD

**Issue by nec286** [middyjs/middy#271]
As a result of the `handler.error.constructor.super_.name` check in the `httpErrorHandler` middleware, optimized code isn't handled. Would it be safer to check for a valid `statusCode`?

## not optimized

```
{ [Function: BadRequestError]
super_: 
{ [Function: HttpError]
super_: 
{ [Function: Error]
stackTraceLimit: 10,
prepareStackTrace: [Function: customPrepareStackTrace] } } }
```

## optimized

```
{ [Function: BadRequestError]
super_: 
{ [Function: e]
super_: 
{ [Function: Error]
stackTraceLimit: 10,
prepareStackTrace: [Function: customPrepareStackTrace] } } }
```

**Comment by lmammino** [comment]
Hello @nec286, sorry for the late reply.

What are you using here to optimize the code?

Also, any reason for closing the issue? Did you figure out a solution?

**Comment by nec286** [comment]
Hi @lmammino. Thanks for the follow up.

I'm using `serverless-webpack` to bundle my artefacts. I was hoping that a smaller zip file would result in more performant cold starts and faster deployment times. In the end I decided to disable [minimize](https://webpack.js.org/configuration/optimization/) in webpack since it's very likely overkill.

One option I was thinking of, to ensure the error never re-occurs, is to validate `statusCode` instead of checking the constructor name: 

```JavaScript
    onError: (handler: IHandlerLambda, next: IMiddyNextFunction) => {
      const error = handler.error as HttpError
      if(/^[1-5][0-9][0-9]$/.test(error.statusCode)) {
        handler.response = strategy(error)
        return next()
      }
      return next(handler.error)
    }
  })
```

Let me know what you think, and I'd be happy to open a PR.
