### ISSUE TITLE
Strange behaviour of async middlewares (maybe need docs)

### ISSUE THREAD

**Issue by MaxVinogradov** [middyjs/middy#274]
Hi!
Yesterday we got next error (maybe bug - I don't know).
If we call `next()` in the `async` middleware, our handler run twice.
It's fully my bad, and I don't know what it exactly, but I think it will be great to mention this in docs.

**Comment by iDVB** [comment]
UPDATE [SOLVED]:
Looks like we needed to read the docs closer.
With async middleware... you need to either return the promise OR in the case of async/await just `return`. 

We we're unfortunately `return next()` which I can see now would call twice.

**Comment by MaxVinogradov** [comment]
@iDVB The same situation. I think this text should be camel case, in red color =)

**Comment by andykenward** [comment]
@iDVB partly solved my issue when using `async` you can just `return` in your middleware `before` `after` async functions, no need for `next()`. 

I had to switch from `middy:0.25.0` to `@middy/core:1.0.0-alpha.29` to ultimately solve my issue. Which is the way the handler functions are being invoked only in my tests and not in production.

```
const viaHandler = async (event, functionName) => {
  const handler = require(`${APP_ROOT}/functions/${functionName}`).handler;
  console.log(`invoking via handler function ${functionName}`); // eslint-disable-line no-console
  const context = {};
  try {
    const response = await handler(event, context);
    const contentType = _.get(
      response,
      "headers.content-type",
      "application/json"
    );
    if (response.body && contentType === "application/json") {
      response.body = JSON.parse(response.body);
    }
    return response;
  } catch (error) {
    throw error;
  }
};
```

node `8.10`.
