### ISSUE TITLE
[TypeScript] Context type with ssm middleware injecting in context

### ISSUE THREAD

**Issue by JuHwon** [middyjs/middy#275]
I would like to use the ssm middleware to inject parameters into context like the following

```typescript
export const handler = middy(handlerFunction)
    .use(ssm({
        cache: true,
        cacheExpiryInMillis: 3 * 60 * 1000,
        setToContext: true,
        names: {
            user_table: '/nobox/dev/user_table'
        }
    }))
```

When  using typescript i am not allowed to access `context.user_table` since it is not defined in the `Context` type of the aws-lambda types package obviously. 

So i thought to enhance the context interface like that:

```typescript
interface HandlerContext extends Context { user_table: string }
type HandlerFunction = (event: APIGatewayProxyEvent, context: HandlerContext) => Promise<APIGatewayProxyResult>

const handlerFunction: HandlerFunction = async (event, context) => {
    console.log("user_table: ", context.user_table)
    return {
        statusCode: 500,
        body: JSON.stringify({ message: "Not Implemented yet." })
    }
}
```

Though when doing that i do get the following typescript error at `middy(handlerfunction)`
```
Argument of type 'HandlerFunction' is not assignable to parameter of type 'Handler<any, any> | AsyncHandler'.
  Type 'HandlerFunction' is not assignable to type 'Handler<any, any>'.
    Types of parameters 'context' and 'context' are incompatible.
      Property 'user_table' is missing in type 'Context' but required in type 'HandlerContext'.
```

The only fix i came up with is `middy(handlerFunction as unknown as APIGatewayProxyHandler)` which kinda feels wrong ¯\_(ツ)_/¯

Is there any better solution? I guess i am not the only one using the ssm middleware with context and typescript.

**Comment by lmammino** [comment]
Hello @JuHwon, would you like to submit a PR with this fix? :)

**Comment by pocesar** [comment]
the typings should rely on using generics, I tried adding them but they might break some people that are relying on non generic types like

```ts
declare type AsyncHandler<T, R> = ((event: T, context: Context, callback: Callback<R>) => void) | ((event: T, context: Context) => Promise<R>);
declare const middy: <C extends AsyncHandler<T extends infer T ? T : any, R extends infer R ? R : any>, T = APIGatewayProxyEvent, R = APIGatewayProxyResult>(handler: C) => middy.IMiddy<T, R>;
```
defaulting to API gateway (guess that's what most people use with serverless)

**Comment by pocesar** [comment]
I'm trying to create proper types to infer from the context created automatically (and pass-on to all underlying functions), but since it uses generics, it would break existing TS code

```ts
declare type EventType<T, Fallback> =
  T extends (event: infer EventArgType, context: Context, callback: Callback<any>) => void ? EventArgType :
  T extends (event: infer EventArgType, context: Context) => Promise<any> ? EventArgType :
  Fallback
declare type HandlerReturnType<T, Fallback> =
  T extends (event: any, context: Context) => Promise<infer RetType> ? RetType :
  T extends (event: any, context: Context, callback: Callback<infer RetType>) => void ? RetType :
  Fallback
declare type AsyncHandler = ((event: any, context: Context, callback: Callback<any>) => void) | ((event: any, context: Context) => Promise<any>);
declare const middy: <C extends AsyncHandler>(handler: C) => middy.IMiddy<
  EventType<C, APIGatewayProxyEvent>,
  HandlerReturnType<C, APIGatewayProxyResult>
>;
```
it fallbacks to API gateway stuff if not typed (instead of any)

**Comment by willfarrell** [comment]
I'm going to close for now. All ts definitions will be redone in middy v2. I will need help, as I don't know TS, please post on https://github.com/middyjs/middy/pull/587 if you can.

**Comment by iDVB** [comment]
@willfarrell was this ever handled for v2?
I'm getting the TS error in v2 that...
`Property 'defaults' does not exist on type 'Context'`
for
```javascript
const handler = 
  middy(baseHandler)
    .use(
      ssm({
        fetchData: {
          defaults: '/thingy/thing',
        },
        cacheKey: 'ssm-defaults',
      }),
    )
    .use(jsonBodyParser())
    .use(httpErrorHandler())
    .before((request) => {
      globalDefaults = request.context.defaults.global
    }
```

**Comment by willfarrell** [comment]
@iDVB Please see the examples at https://github.com/middyjs/middy/tree/main/packages/ssm#sample-usage
All fetch responses are cached as a promise and need to be resolved before accessing nested values
