### ISSUE TITLE
Support passing more than 1 config at a time into use()

### ISSUE THREAD

**Issue by tomhughes-invento** [middyjs/middy#277]
Alongside the current functionality of being able to chain `.use()` I find myself wanting to be able to pass more than 1 config into use at once. The use-case for this is when I have middleware "groups" set up elsewhere, and would rather import that onto handlers, than have to remember everything in the group every time I set up a new handler, for example:
```javascript
const middy = require('middy');
const middlewareGroup = [middleware1(), middleware2(), middleware3()];

exports.handler = middy((event, context, callback) => callback(null, 'foo'))
    .use(...middlewareGroup);
```

**Comment by lmammino** [comment]
This sounds like a good idea. I marked it as a potential feature for v1.0.0 (currently in alpha)

**Comment by lmammino** [comment]
This was actually done in #288. Closing
