### ISSUE TITLE
Can I add my middy middleware to the list?

### ISSUE THREAD

**Issue by iDVB** [middyjs/middy#278]
Hey @lmammino!
I've recently released a middyjs middleware for Lambda@Edge to handle `redirects`, `rewrites`, `proxies` and `custom 404s` in a simple config file you put in the root of your s3 bucket.
https://www.npmjs.com/package/middy-reroute

I'm happy to put in a PR updating your readme, but I thought you might want 3rd Party middlewares to go somewhere else.

BTW, Love middyjs! 🚀

**Comment by lmammino** [comment]
Sorry for the very late reply.
This is a brilliant middleware :) thanks for taking the time to open this issue.

I'll take of creating a section in the README for 3rd party middlewares and make sure to include yours as well

**Comment by lmammino** [comment]
Et [voilá](https://github.com/middyjs/middy#3rd-party-middlewares) 😝
