### ISSUE TITLE
Port support for multiValueHeaders and multivalueQueryStringParameters to branch 1.0.0-alpha

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#279]
Port changes introduced in #276 by @bwinant to branch 1.0.0-alpha

Take into account that compared to the changes in #276, version 1.0.0-alpha has 2 major breaking changes:

- It's a monorepo (every middleware is essentially it's own npm package)
- Header normalization is changed to lowercase as most famouse http framework do (express, fastify, etc.)

**Comment by willfarrell** [comment]
This looks to be done.
