### ISSUE TITLE
[Discussion] Move middy into dedicated organisation

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#30]
What do you think about moving middy to a dedicated middy organisation on GitHub?

I am personally up for it and I can provide few good reasons for it:

  1. An independent organisation might seem more attractive to other contributors and the project could potentially reach a broader adoption (which, as a side effect, will also have a positive impact on Planet 9 in terms of validation and support)
  2. We might use the new middy organisation to host related middy projects (external middlewares, benchmarks, website source, etc.)
  3. We might be encouraged to spend some time even outside Planet 9

As a downside, of course, we might lose the support from Planet 9 which might not want to keep investing (a bit of) our time in developing it. 

Let me know your view and vote 👍  or 👎  to this main comment if you are in favour or not to this idea.

CC: @padraigobrien @dkatavic @acambas @peterjcaulfield @techfort @codecrunchers @augeva @daveanderson-ie

**Comment by techfort** [comment]
i don't know that Planet9 should lose interest in supporting middy when our turnaround time on cards and the quality of our lambdas is improved thanks to it. It's only a matter of ROI, if middy takes 10 hours a month to develop and saves Planet9 20 hours of development manhours, then it's a no brainer.

**Comment by lmammino** [comment]
Thanks for your comment @joe!

I see also @dkatavic gave a :+1:

I'd love to know also what the rest of the crew thinks before moving forward! @padraigobrien @peterjcaulfield @codecrunchers @augeva @daveanderson-ie .

Meanwhile look at this beautiful deal 😆 

<img width="1181" alt="screen shot 2017-09-15 at 10 28 35" src="https://user-images.githubusercontent.com/205629/30476104-e4699f02-9a00-11e7-8598-89da26542743.png">

**Comment by daveanderson-ie** [comment]
Have we tried inviting contributions and not gotten a result? If we're only guessing that people won't contribute, I'd suggest testing that. Planet9 seems to have a good reputation, so you might find that people want to help our mission.

**Comment by lmammino** [comment]
@daveanderson-ie I invited some developers to have a look (hence why we have some stars in the repo already) and they told me the project looks cool and that they will try to use it.

Nobody explicitly mentioned contribution, but of course this might not necessarily be related with the usage of Planet9 namespace.

Anyway I have been talking with a couple of famous open source developers recently about this issue and they told me that most of the time they prefer to create dedicated organisations (see [fastify](https://github.com/fastify) or [Prosemirror](https://github.com/prosemirror)).

No mathematical proof from them, but they also feel that it's easier to have the project(s) evolve from shared community efforts this way. This of course doesn't stop companies to keep promoting/sponsoring those projects. Actually it might even lead more companies to be involved in supporting the project (see fastify)

**Comment by acambas** [comment]
I'm more for moving it to a specific organization because we can use tools to improve it that are free if you are an organization that deals with open source. Tools like greenkeeper, circle ci...

**Comment by padraigobrien** [comment]
I would be on for moving it to a specific organisation as well

**Comment by techfort** [comment]
@lmammino i think we have a quorum (Saša, Dom, you, me, Podge).

**Comment by lmammino** [comment]
I would suggest to tackle this at standup tomorrow morning to discuss any possible blocker from @augeva and @daveanderson-ie.

Meanwhile, I already created the org [middyjs](https://github.com/middyjs) and I'll start to send invitations to all of you

**Comment by lmammino** [comment]
Moved :)
