### ISSUE TITLE
httpSecurityHeaders doesn't work with Lambda@Edge

### ISSUE THREAD

**Issue by iDVB** [middyjs/middy#305]
Want to make sure I've not missed something here, but it appears the `httpSecurityHeaders` middleware does not work in a Lambda@edge function.

I'm going to set out to fork this one to [work with Lambda@Edge like this](https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/).

@lmammino does it make more sense to PR the core extending it.... or to fork it as a thirdparty?

**Comment by vladgolubev** [comment]
@iDVB take a look at [lambit](https://github.com/jsonmaur/lambit), it has Lambda@Edge-specific middlewares, maybe `httpSecurityHeaders` can become one of them

**Comment by iDVB** [comment]
Thanks @vladgolubev but I've already got middyjs working great as my middleware engine for [middy-reroute](https://www.npmjs.com/package/middy-reroute) which works perfectly with Lambda@Edge functions. No need to go to another engine. Just a choice between forking the core `httpSecurityHeaders` middleware or PRing it.

**Comment by lmammino** [comment]
I am not familiar with lambda edge, unfortunately. How much work do you think is necessary to make the `httpSecurityHeaders` middleware more flexible to work also with Lamda Edge? Would that be preferable to having a dedicated Lambda Edge equivalent middleware?

**Comment by iDVB** [comment]
Are you a core contributor for middyjs?
I’d have to take a closer look at the middleware to see how it can be
extended.

Right now it assumes it’s always going to output the raw headers in
response. However with Lambda@edge you need to return the whole response
object and the headers need to be a specific key/value type. Other then
that, they’d be the exact same. So I think it’s worth extending rather then
duplicating.

Just want a core member to green light the idea before I invest more time
into extending it but I think it’s veru doable.

**Comment by willfarrell** [comment]
I never thought to use middy in Lambda@Edge. This is how I did it, forever ago, and still using it. https://github.com/willfarrell/terraform-public-static-assets-module/blob/master/docs/lambda-viewer-response/index.js . Maybe it's time to update, not having any dependencies feels good :).

I don't think it should be inside the specific middleware. If you have other middleware that modify the headers, they would also need the same transform logic.

I suggest an `edgeTransform` middleware that would be at the top of the stack. If you're interested, I can whip something up this week. Let me know.
