### ISSUE TITLE
Adding middy to a simple handler results in error 'Unable to import module'

### ISSUE THREAD

**Issue by duro** [middyjs/middy#308]
I am at the early stages of architecting a serverless application, and have been playing with middy as part of the stack. I just ran into a super odd issue.

I have a super simple handler that looks like this (and works):

```
import { APIGatewayProxyHandler, APIGatewayEvent, Context, APIGatewayProxyResult } from 'aws-lambda'
import ResponseOutput from '@freebird/response-output'

export const hello: APIGatewayProxyHandler = async (event: APIGatewayEvent, _context: Context): Promise<APIGatewayProxyResult> => {
    const rOutput = new ResponseOutput()
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: rOutput.output('Hello'),
        input: event,
      }),
    }
  }
```

And then when I do a very simple `middy` wrap, like this:

```
import middy from 'middy'
import { APIGatewayProxyHandler, APIGatewayEvent, Context, APIGatewayProxyResult } from 'aws-lambda'
import ResponseOutput from '@freebird/response-output'

export const hello: APIGatewayProxyHandler = middy(
  async (event: APIGatewayEvent, _context: Context): Promise<APIGatewayProxyResult> => {
    const rOutput = new ResponseOutput()
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: rOutput.output('Hello'),
        input: event,
      }),
    }
  },
)
```

The function starts erroring when executed with `"Unable to import module"`

Can anyone spot what I'm doing wrong?

**Comment by lmammino** [comment]
Hello @duro, did you enable esmoduleinterop as specified here: https://github.com/middyjs/middy/blob/master/README.md#typescript ?

**Comment by duro** [comment]
@lmammino Yep. Here is the tsconfig for the service:

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src"],
  "references": [{ "path": "../../packages/response-output" }, { "path": "../../packages/logger" }]
}
```

Which extends from this base tsconfig:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "lib": ["es2017"],
    "composite": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "sourceMap": true
  },
  "exclude": ["node_modules", "**/*.test.ts"]
}
```

**Comment by duro** [comment]
Ooof...figured this one out, and it was user error. I am leveraging Yarn Workspaces, which in local development using `serverless-offline` essentially leverages you laptop's execution runtime. So when serverless executes locally, the node runtime is able to look up the tree for dependecies in the parent node_modules.

However, when packaging for deployment, we use a plugin called `serverless-plugin-monorepo` which will inspect your projects package.json, and hoist up the dependencies your package uses that are declared in the `dependencies` definition, so that they are all packaged properly for deployment to lambda.

I had not declared middy as a dep in this particular service, but had in another service. So locally it was being found, but when de-hoisted, it was not there.

Leaving this here for the next bozo (me) who stumbles onto this edge case.
