### ISSUE TITLE
httpErrorHandler breaks if code is minimized / mangled

### ISSUE THREAD

**Issue by akleiber** [middyjs/middy#325]
# Problem

httpErrorHandler compares error's constructor name - but the check fails if code is minimized

There already was an issue open but was closed by the autor: https://github.com/middyjs/middy/issues/271

The problem still exists.
If code is optimized, for example via webpack than the constructor.name value is changed and the check will fail. Therefor the middleware will do nothing for http errors.
See https://github.com/middyjs/middy/blob/0.25.0/src/middlewares/httpErrorHandler.js#L10

Webpack optimization infos: https://webpack.js.org/configuration/optimization/

## Solution 1

Do not check for the constructor to check if the error is an http error.

##  Solution 2

Disable code minification

### Disable minification

```
module.exports = {
  //...
  optimization: {
    minimize: false
  }
};
```

### Do not mange classnames

```
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  optimization: {
    minimizer: [
      new TerserPlugin({
        cache: true,
        parallel: true,
        sourceMap: true, // Must be set to true if using source-maps in production
        terserOptions: {
          // https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
            keep_classnames: true
        }
      }),
    ],
  }
```

**Comment by lmammino** [comment]
Not sure if this option was discussed already, but the following might be a solution:

```javascript
const { HttpError } = require('http-errors')

// ...

if (someError instanceof HttpError) {
  // ...
}
```

What do you think?

cc @dkatavic

**Comment by lmammino** [comment]
From version `0.27.0` (and shortly also from `1.0.0-alpha.33`) any error object containing the fields `statusCode` and `message` will be considered valid to run the middleware.
This solves any minification issue, but also makes you more flexible to use other libraries for error management, or simply allows you not to depend on a library for http errors.
