### ISSUE TITLE
SecretsManager expects a stringified JSON response.SecretString

### ISSUE THREAD

**Issue by simontegg** [middyjs/middy#329]
This line in the secretsmanager expects scerets to be stored as stringified JSON. There's a use case where the secret is a plain string and the call to JSON.parse errors

https://github.com/middyjs/middy/blob/1.0.0-alpha/packages/secrets-manager/index.js#L39``

```js
          .then(resp => {
         // expects SecretString to be  "{"key": "value"}"
            const secret = JSON.parse(resp.SecretString || '{}')
            const object = {}
            object[key] = secret
            return object
})
```

**Comment by lmammino** [comment]
Very good point @simontegg, we should make this more flexible.

One backward compatible way to do that is to provide a configuration option called `parseFn` which is set to `JSON.parse` by default. In cases where you don't need to parse the content you can just use an identity parser function `(x) => x`. Or even use different parsing approaches in more bespoke cases.

What do you think? Would you like to submit a PR to address this?

**Comment by HistoireDeBabar** [comment]
Hey 👋 
 
> One backward compatible way to do that is to provide a configuration option called `parseFn` which is set to `JSON.parse` by default. In cases where you don't need to parse the content you can just use an identity parser function `(x) => x`. Or even use different parsing approaches in more bespoke cases.

If this is still a desirable solution, I can raise a PR if no one else is working on it?

**Comment by simontegg** [comment]
I made #330 but its probably quite stale

**Comment by HistoireDeBabar** [comment]
Ah, I see - Sorry, I missed that PR @simontegg - I was just looking to help out, but I'll leave you to it 🙂

**Comment by simontegg** [comment]
@HistoireDeBabar please fork if you wish. I think its just failing the test coverage

**Comment by chris-heathwood-uoy** [comment]
I've continued this in https://github.com/middyjs/middy/pull/542 hope that helps :)
