### ISSUE TITLE
Issue with IURLEncodeBodyParserOptions definition

### ISSUE THREAD

**Issue by gabmontes** [middyjs/middy#336]
The type `IURLEncodeBodyParserOptions` is defined with prop `extended` of type `false` instead of `boolean`.

https://github.com/middyjs/middy/blob/7fdee7876c095f1e1f58fe2966199da2f63fb514/middlewares.d.ts#L74

**Comment by lmammino** [comment]
Oops, seems definitely wrong :)

Thanks for reporting it @gabmontes, would you like to submit a PR to fix this and become one of the contributors to this project?

**Comment by willfarrell** [comment]
This can be closed now.
