### ISSUE TITLE
Getting "Malformed Lambda proxy response" with upgrade to new node10.x runtime

### ISSUE THREAD

**Issue by duro** [middyjs/middy#339]
I changed nothing about my code, other than upgrade to new runtime, and now I am getting the error in API gateway:

"Malformed Lambda proxy response"

I am using middy 1.0.0-alpha.30

**Comment by lmammino** [comment]
Hello @duro! Sorry to hear about the issue.

Which version were you using before?  Can you provide a little bit more context and maybe an example of how to reproduce the issue?

**Comment by duro** [comment]
I'm closing this one, as I resolved it, but I can't even remember what I did to fix.
