### ISSUE TITLE
Auto-stringify JSON Body

### ISSUE THREAD

**Issue by baileytincher** [middyjs/middy#347]
All bodies have to be stringified before being sent back to the client according to standards. However, this becomes tedious to implement when you have a lot of different callback functions and want to maintain consistency in your code. 

Consider the following:
```
const sampleCallback = (data) => ({
    statusCode: 200,
    headers: {},
    isBase64Encoded: false,
    body: {
      message: 'OK.',
      data: data,
    },
);
```

Now sure, you could just add the `JSON.stringify` call inside that function, however when you have a lot of callbacks that is ugly, verbose, and does not add any value/understanding to your code while it is being read.

There should be a way to ad a middleware to detect the body type and auto-encode this for you. However, when I tried to do this, an error was thrown before it had a chance to be executed.

```
Serverless: According to the API Gateway specs, the body content must be stringified. Check your Lambda response and make sure you are invoking JSON.stringify(YOUR_CONTENT) on your body object
```

Is there a way to do this?

**Comment by lmammino** [comment]
Hello @baileytincher, if you are using version 1.0.0-alpha you can probably do this with the [`http-response-serializer`](https://github.com/middyjs/middy/tree/1.0.0-alpha/packages/http-response-serializer) middleware.

Alternatively, if you don't need flexible serialization logic it should be fairly easy to create a middleware for this.

Something like this (untested) should work:

```javascript
// ensureJsonBody.js
module.exports = () => {
  return ({
    after: (handler, next) => {
      if (typeof handler.response.body !== 'string') {
        handler.response.body = JSON.stringify(handler.response.body)
      }

      return next()
    }
  })
}
```

Sample usage (untested):

```javascript
const middy = require('@middy/core')
const ensureJsonBody = require('./ensureJsonBody')

const handler = middy((event, context, cb) => {
  const response = {
    statusCode: 200,
    headers: {},
    body: { message: 'hello world' }
  };

  callback(null, response)
})

handler
  .use(ensureJsonBody())
```

Let me know if this is what you were looking for.

**Comment by baileytincher** [comment]
> Alternatively, if you don't need flexible serialization logic it should be fairly easy to create a middleware for this.
> 
> Something like this (untested) should work:


That was effectively what I had written as my initial attempt at a solution, and it resulted in the error above from serverless without having the chance to execute.

I will try your first recommendation later this week though.

**Comment by lmammino** [comment]
That's interesting, did you try to debug the middleware to make sure it is actually doing the transformation as expected?

**Comment by willfarrell** [comment]
@baileytincher Everything work out alright? Re-Open if you still need assistance.
