### ISSUE TITLE
only problems with node10

### ISSUE THREAD

**Issue by srep2512** [middyjs/middy#367]
would be nice if the examples and code work with node 10  lambda functions :(

**Comment by lmammino** [comment]
Hello, first of all thanks for trying middy and for opening this issue.

Can you please copy here the code you tried and the error you got?

**Comment by srep2512** [comment]
Sorry, I was just completely stupid. Everything is fine :D

**Comment by lmammino** [comment]
Lol, thanks for letting me know! Feel free to open new issues if you have any trouble with middy and happy *middying* :D
