### ISSUE TITLE
http-security-header(s) naming discrepancy 

### ISSUE THREAD

**Issue by estrattonbailey** [middyjs/middy#372]
Hey there 👋 thanks for Middy, so great.

Might have found a typo. Not sure which is the intended package name, but currently it's published as `@middy/http-security-header` but referred to in the the docs as `@middy/http-security-headers` (plural).

I can open a PR for the docs, unless the plural form is the intended package name.

**Comment by lmammino** [comment]
Whoops, that's a great finding. I think the package name should be fixed. This is generally not ok, but since we are still in alpha it shouldn't be a big deal. I will flag this as a bug and as a necessary change before v.1.0.0 is finally shipped.

Thanks a lot for letting us know about this :)

**Comment by willfarrell** [comment]
Thanks for catching this!

**Comment by lmammino** [comment]
Closed in #431
