### ISSUE TITLE
Regex support in the CORs module

### ISSUE THREAD

**Issue by wcauchois** [middyjs/middy#374]
Hi,

Does the CORs middleware allow you to specify a regex for the allowed origin domains?

I also have one other comment: I believe it's best practice to set `Vary: Origin` for CORs requests but from my reading of the code the middleware doesn't seem to do that.

Thanks.

**Comment by lmammino** [comment]
Regarding the first question. Can you make an example? You can use asterisks, but i have a feeling that's not what you mean...

On the vary header, you can always add the header yourself. If there's a strong case for this to be added as part of the middleware i am supportive but at the moment i don't see this as something too generic to make sense as a default. Can you elaborate a bit more on why you think this would be useful?

**Comment by thejuan** [comment]
Our use case is we are starting to play with https://linc.sh for generating preview environments of our builds. They use generated domains like https://myapp-34kl4545--develop.release.linc.sh where the middle token changes (34kl4545) it would be good to allow a function (or regex) to determine if the origin is allowed then echo it back.

**Comment by lmammino** [comment]
I think I am understanding this a little bit better now. Thanks for providing more context @thejuan!

Essentially you would want any request with the `Origin` header matching `https://myapp-*--develop.release.linc.sh` to respond with header `Access-Control-Allow-Origin` equal to the actual `Origin` header. Therefore you would want the `origin` option of the middleware to support also a regex.

This could make sense and it shouldn't be too hard to implement.

As far as I can see right now, you should be able to achieve that by adding some extra logic in the [`getOrigin`](https://github.com/middyjs/middy/blob/master/src/middlewares/cors.js#L8-L22) function of the middleware (around [lines 17-19](https://github.com/middyjs/middy/blob/master/src/middlewares/cors.js#L17-L19)), basically checking if the option is a regex and in that case trying to match the regex against the current `Origin` header.

Do you want to propose these changes through a dedicated PR?

**Comment by thejuan** [comment]
We have cloned the middleware and made getOrigin a function passed into the config which gives us more flexibility. Happy to submit that, but its a breaking change.

**Comment by lmammino** [comment]
I actually like the idea of a function and i would be more than happy to see a PR for that. I am also quite positive we could find ways to make it backward compatible. What do you think?

**Comment by thejuan** [comment]
Sounds good. I've forgotten what the process is for PR's and v1. Just do the v1 branch?

**Comment by lmammino** [comment]
Yes ;)

**Comment by lmammino** [comment]
Closed by #385
