### ISSUE TITLE
Middleware Reacting to Original Event

### ISSUE THREAD

**Issue by JordanSinko** [middyjs/middy#384]
This is just a question, but is there planned support to include the original event on the handler object, such as `originalEvent`? I want to create a middleware that does certain actions based on the original event, not the transformed, such as retrying/sending to a queue if failures occur. I could create a middleware that stores this but then there is a tight coupling of two middleware.

**Comment by lmammino** [comment]
Hello @JordanSinko, thanks for your question and for using Middy.

You could easily create your own `retainOriginalEvent` middleware to do this and attach it as the first `before` middleware.

Something like this could work (untested):

```javascript
// retainOriginalEvent.js

const clone = require('clone-deep') // from npm

const retainOriginalEvent = () => {
  return ({
    before: (handler, next) => {
      const originalEvent = clone(handler.event)
      handler.event.originalEvent = originalEvent
      next()
    }
  })
}

module.exports = retainOriginalEvent
```

usage:

```javascript
const retainOriginalEvent = require('./retainOriginalEvent')

const originalHandler = (event, context, cb) => {
  // can access `event.originalEvent`
  // ...
}

const handler = middy(originalHandler)
  .use(retainOriginalEvent())

module.exports = handler
```

Let me know if this helps :)

**Comment by lmammino** [comment]
I would generally prefer to avoid to have to clone the event at every execution. At the moment I feel that yours is a very specialized case but if it other people express the same need I am happy to consider formalising this feature as one of the supported middlewares.

Does it make sense?

**Comment by lmammino** [comment]
You are most welcome :) enjoy Middy!
