### ISSUE TITLE
async / await early exit middleware

### ISSUE THREAD

**Issue by stavros-zavrakas** [middyjs/middy#392]
I wrote this middleware but I'm unable to exit early if there is a warming event. It seems that this is about the async/await because in a middleware without async/await the execution stops normally. Any ideas? The middy version that I'm using is 0.28.2
 
```
'use strict';

const warmer = require('lambda-warmer');

module.exports = () => {
  return ({
    before: async (handler) => {
      if (await warmer(handler.event)) {
        console.log('I am just warming up and connection has been established successfully.');
        
        handler.callback(null, 'warming_up');
      }
    }
  });
};
```

**Comment by lmammino** [comment]
Hello @stavros-zavrakas,
did you try with just returning early within the `if` statement?

Basically replacing your:

```javascript
handler.callback(null, 'warming_up');
``` 

with:

```javascript
return 'warming_up';
``` 

Please, let me know if this helps you!

**Comment by stavros-zavrakas** [comment]
Hi @lmammino - I've tried that in the past and I've just tried it one more time now but it didn't work. I can see the next middleware being executed. I'll switched to promises and use the handler.callback for the time being. At some point I might try with a much simpler lambda function just to find out if I do something wrong in this project.

**Comment by lmammino** [comment]
Thanks for the clarification @stavros-zavrakas.

Yes it would be great to have a simple example that replicates the issue so we can file a proper bug and find time to address it.

Thanks again for your efforts on reporting this so far.

**Comment by stavros-zavrakas** [comment]
@lmammino I've created this example for you:
https://github.com/stavros-zavrakas/middy-example

For a reason it has a bit of a different behaviour from what I get in my current project. Whenever I `return 'warming_up'` it's like the middleware is throwing an error. Let me know if the instructions to deploy the lambda functions are quite sufficient.

**Comment by mcjfunk** [comment]
@stavros-zavrakas what does your promise-based code look like? I can't get Middy to exit early without it calling the lambda handler, even with promises.  For example:
```js
module.exports = {
    before: (handler) => {
        return new Promise((resolve) => {
            setTimeout(resolve, 100);
        }).then(() => {
            return handler.callback(null, 'Warm, baby!');
        });
    }
};
``` 
OR
```js
return new Promise((resolve) => {
    setTimeout(() => {
        resolve(handler.callback(null, 'Warm, baby!'));
    }, 100);
});
``` 
All flavors of promise resolution still call the handler after the timeout.

**Comment by mcjfunk** [comment]
I found a workaround for my case. If I don't return the promise, it will skip the handler and next middleware and still finish executing the async process. This won't work for all use cases, but satisfies my needs for the moment.

**Comment by luqezman** [comment]
News? Im having the same issue :(

**Comment by TheKnightCoder** [comment]
> handler and next middleware and still finish executing the async process. This won't work for all use cases, but satisfies my needs for the moment.

Thanks @mcjfunk. This worked really well for me. Here is an example of how I used an async function and end the execution early with a http response.

``` javascript
const beforeAsync = async (handler) => {
  const authHeader = handler.event.headers.Authorization

  if (!authHeader) {
    // This will Interrupt middleware execution early. 
    // It will not run the main handler and return this http reponse
    return { 
      statusCode: 401,
      headers: {
        'Content-Type': 'application/json'
      }
    }
  }

  return // by returning undefined (or any falsy value), main handler will execute as normal
}

export default () => ({
  before: (handler, next) => {
    beforeAsync(handler).then((response) => response ? handler.callback(null, response) : next())
  }
})
```
So whenever you return a falsy value from your async function it will continue as normal. If you return an object, the lambda will end early and return the object as a http response (pass the object to the callback)

**Comment by Dartv** [comment]
What's the status on this? This is such a must have feature.
