### ISSUE TITLE
Question: Guidelines for inclusion of middleware in Middy vs 3rd party

### ISSUE THREAD

**Issue by jhecking** [middyjs/middy#393]
I would like to know what the guidelines are for including a new middleware in the Middy package itself vs. distributing it as stand-alone 3rd-party package?

I have implemented a striptags middleware, which uses the npm package of the same name to remove anything that looks like a HTML tag from any part of the event payload that is user controlled, e.g. query parameters, HTTP headers, the request body, etc. This is meant to prevent XSS attacks.

Should I submit a PR to have this middleware included in Middy or would it be better to release this as a separate package instead?

**Comment by lmammino** [comment]
Hello @jhecking, sorry for the slightly delayed reply (busy times!)

To be totally honest, we don't have a set of official guidelines. This is probably one of those things that we should figure out and make more explicit.

At the moment the guidance I would give is to try to keep the core small and only include middlewares that the core team is willing to maintain and test with every new release.

I personally don't feel your middleware should be included in the core (sounds very specific to me).

In any case, you are more than welcome to submit a PR to the README to add your middleware to the list of 3rd party ones.

**Comment by jhecking** [comment]
Ok, I understand your concern about having to maintain a bunch of middlewares that are not widely applicable. Though I think the striptags middleware would be fairly generic and useful for any API that takes user input and may have to render that input back in an HTML context.

In any case, I'll close this issue, as you have addressed my question.
