### ISSUE TITLE
Middy secretsManager using process.env as secret name + jest

### ISSUE THREAD

**Issue by laurentrivard** [middyjs/middy#397]
I'm running unit tests with Jest and using the `secretsManager` middleware to fetch a secret before my handler runs. 
```
module.exports.handler = middy(taskName)
  .use(secretsManager({
    cache: true,
    cacheExpiryInMillis: 1 * 60 * 1000,
    secrets: {
      postmatesCreds: process.env.SECRET_NAME
    }
  }))
```

I need to use `process.env.SECRET_NAME` for the secret name since it differs based on the stage I'm in. When running the jest test, I set `process.env` to have a value in `beforeEach`, but the value is undefined when the test runs. Example: 

```
describe('test handler, () => {
  beforeEach(() => {
    Object.assign(process.env, { SECRET_NAME: 'testName'})
  }

  it('should call the handler...., () => {
    const result = handler(mockEvent, mockContext, mockCallback)
  })


});
```

This is the error I encounter
`failed to refresh secrets from Secrets Manager: Missing required key 'SecretId' in params`

**Comment by lmammino** [comment]
hello @laurentrivard,

Which version of Middy are you using?

Can you try in your example to invert key and value in the `secrets` hashmap and change it to the following? 

```
SECRET_NAME: 'postmatesCreds'
```

**Comment by willfarrell** [comment]
@laurentrivard Any luck with this?

**Comment by LarsBuur** [comment]
For anyone searching for this error. I got the error and the cause was that I had not created the secret in secrets manager with the correct id (which had been renamed)
