### ISSUE TITLE
handler.callback taking the wrong arguement from generic function type

### ISSUE THREAD

**Issue by amwill04** [middyjs/middy#398]
Given the following type definitions in `aws lambda`

```ts
export type Handler<TEvent = any, TResult = any> = (
    event: TEvent,
    context: Context,
    callback: Callback<TResult>,
) => void | Promise<TResult>;
```

`callback` take the type from `TResult` however in `middy` we have the following type decleration

```ts
  interface HandlerLambda<T = any, V = {}> {
    event: T;
    context: Context;
    response: V;
    error: Error;
    callback: Callback<T>;
  }
}
```

callback seems to be taking the wrong type and unable to use `APIGatewayProxyResult`

**Comment by lmammino** [comment]
hello @amwill04! Thanks for spotting this. Would you mind sending a PR to address this?

**Comment by amwill04** [comment]
Pull request created in #402
