### ISSUE TITLE
Possible to get slimmed middyjs

### ISSUE THREAD

**Issue by rymndhng** [middyjs/middy#408]
First off, I'm a big fan of the abstraction presented in the library.

My problem is that I'd like to avoid pulling in unused dependencies into my `node_modules` folder. 

I noticed there's quite a few dependencies which are tied to one specific middleware. Is it possible to mark these as optional? i.e. `json-mask`, `negotiator`, `busboy`

**Comment by lmammino** [comment]
Hey @rymndhng, thanks for your comment.

Did you see already [version 1.0.0-alpha](https://github.com/middyjs/middy/tree/1.0.0-alpha)? This upcoming version is using the "mono-repo" pattern to decouple every single middleware and middy core into their own packages. That should help to reduce the number of dependencies to the very minimum.

Let me know if this helps or if you had something different in mind :)

**Comment by willfarrell** [comment]
I think we can [close] this one now that v1 is in beta.
