### ISSUE TITLE
1.0 - Shipping @types/aws-lambda as a dep (and not peer-dep) is breaking our builds

### ISSUE THREAD

**Issue by duro** [middyjs/middy#409]
After the latest update of our dependencies where both our own @types/aws-lambda version was updated to `8.10.33` and we upgraded to @middy/core `1.0.0-alpha.45`.

Now we are getting errors like so:

```
The inferred type of 'myMiddleware' cannot be named without a reference to '@middy/core/node_modules/@types/aws-lambda'. This is likely not portable. A type annotation is necessary.
```

I think you are better off shipping @types/aws-lambda as a peer-dep. When I remove @middys version of aws-lambda, my build starts working again.

**Comment by lmammino** [comment]
Thanks a lot for reporting this @duro! Could you submit a fix for this?

**Comment by duro** [comment]
@lmammino done and done
