### ISSUE TITLE
XML Body Parser

### ISSUE THREAD

**Issue by philipodev** [middyjs/middy#41]
I have a lambda running which receives XML in the body, parses it and does a few things with it.
I think it would be nice to have an `xmlBodyParser` middleware (like the json one).

Im using [`jindw/xmldom`](https://github.com/jindw/xmldom) for parsing the xml and it work great on lambda as well.

But instead of this repo holding the dependency of `xmldom` maybe require the user to install it by themselves if they ever use the xmlBodyParser? (so, kind of peerDependency)

I would love to create a PR on this if you feel its appropriate to have as a middleware.

**Comment by lmammino** [comment]
Sure, that would be great!

**Comment by philipodev** [comment]
Hmm, this gets tricky when testing. If [`jindw/xmldom`](https://github.com/jindw/xmldom) is not installed the tests will fail.
maybe this middleware should reside in its own repo instead? 
like `middyjs/middy-middleware-xml-body-parser`?

alternative: we make [`jindw/xmldom`](https://github.com/jindw/xmldom) a dependency of this repo?

**Comment by lmammino** [comment]
It's definitely a good point to move middlewares to external packages. Anyway I don't want to overcomplicate the project in this initial phase, so I am ok for now to have `jindw/xmldom` as a dependency of this project.

When we'll be ready to release `1.0.0` maybe we can reconsider this assumption and decide whether it makes sense or not to move middlewares outside the core.

**Comment by lmammino** [comment]
Hey @philipodev, are you still working on xml support?

**Comment by willfarrell** [comment]
@philipodev Is there still a need for this? We'd be happy to have an `xmlBodyParser` middleware if you'd like to make a PR to the v1 branch.

**Comment by willfarrell** [comment]
Please submit a PR if you're still interested in adding this functionality in.
