### ISSUE TITLE
Timeout caused when used with 'Sequelize'

### ISSUE THREAD

**Issue by niallmc** [middyjs/middy#420]
When I use Sequelize and middy together the function will timeout. I have narrowed down the issue to the event loop, as if I set my connection pool as follows:

```
pool: {
    max: 10,
    min: 1,
    idle: 10000,
    handleDisconnects: true
  },
```

The idle time will need to complete before anything is returned.

I did see a similar issue #165 posted here regarding the use of 'knex' and the resolution was to use the doNotWaitForEmptyEventLoop middleware.

I have tried using that middleware but it doesnt seem to resolve my issue.

The function is as follows:

```
const middy = require("middy");
const { doNotWaitForEmptyEventLoop } = require("middy/middlewares");

let { getOrders} = require("../../repositories/orderRepository");

const originalHandler = async (event: any) => {
  try {
    // DB query with sequelize
    const res = await getOrders(
      event.multiValueQueryStringParameters
    );

    return {
      statusCode: 200,
      body: JSON.stringify(res, null, 2)
    };
  } catch (err) {
    return { statusCode: 404, message: err };
  }
};

export const handler = middy(originalHandler).use(doNotWaitForEmptyEventLoop());
```

**Comment by lmammino** [comment]
Hello @niallmc and thanks for opening the issue.

I haven't tried to use Lambda and Sequelize.

Some generic questions first:

  - Which version of Node.js are you using in your Lambda?
  - Which version of Middy?

We could try the following things to debug the problem a bit more:

  -  Could you add the `context` argument to your handler and log `context.callbackWaitsForEmptyEventLoop`? This value should be false, thanks to the `doNotWaitForEmptyEventLoop` middleware. If that's not the case there's something interfering with the work of this middleware (basically resetting the parameter)
  - Could you try to rewrite the function to use the callback rather than async await? If that option works there might be a bug in middy or some weird behaviour in the Lambda runtime.

I look forward to hearing more from you and I hope we can find a quick resolution!

**Comment by niallmc** [comment]
Hi @lmammino thanks for the prompt response.

Node version: 10.16.3
Middy version: 0.30.3

I have logged `context.callbackWaitsForEmptyEventLoop` which returns false.

I have rewritten the function using a callback as follows:

```
const middy = require("middy");
const { doNotWaitForEmptyEventLoop } = require("middy/middlewares");

const { order } = require("../../db/db");

const originalHandler = (event: any, context: any) => {
  try {
    console.log("Context :", context.callbackWaitsForEmptyEventLoop);
    console.log("Node version: ", process.version);

    return order
      .findAll()
      .then(res => {
          callback(null, {
            statusCode: 200,
            body: JSON.stringify(res, null, 2)
           });
      });
  } catch (err) {
    return { statusCode: 404, message: err };
  }
};

export const handler = middy(originalHandler).use(doNotWaitForEmptyEventLoop());
```

The issue is still persisting.

I am relatively new to Serverless so it may well be something to do with my configuration but I am a bit stumped at the moment.

**Comment by lmammino** [comment]
Can you try this way?

```javascript
const middy = require("middy");
const { doNotWaitForEmptyEventLoop } = require("middy/middlewares");

const { order } = require("../../db/db");

const originalHandler = (event: any, context: any) => {
    console.log("Context :", context.callbackWaitsForEmptyEventLoop);
    console.log("Node version: ", process.version);

    return order
      .findAll()
      .then(res => {
          return callback(null, {
            statusCode: 200,
            body: JSON.stringify(res, null, 2)
           });
      })
     .catch(err => {
        console.error(err)
        return callback(null, { statusCode: 404, message: err })
     })
};

module.exports.handler = middy(originalHandler).use(doNotWaitForEmptyEventLoop());
```

**Comment by niallmc** [comment]
The issue is still remaining after trying that function.

**Comment by lmammino** [comment]
I'll try to take some time in the next week to try to replicate the issue, please keep me posted in case you figure out the problem meanwhile.

**Comment by niallmc** [comment]
no problem, I'll keep you posted. Thanks for taking a look.

**Comment by niallmc** [comment]
Hi @lmammino I beleive I have found the issue.

If I have serverless setup for monitoring the timeout issue will occur.

When I disable the monitoring, everything works as expected.

**Comment by lmammino** [comment]
Hello @niallmc, thanks a lot for reporting that you found the root cause. Can you describe a little bit more your monitoring setup? Maybe there's something we can do to make the middleware work with this setup as well, or at least to warn the users about this possible issue.

**Comment by niallmc** [comment]
Hi @lmammino, if I run the `serverless` command to connect my project to the Serverless Framework Dashboard account to enable the monitoring then the issue will occur.
