### ISSUE TITLE
Middleware: RDS Auth Token

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#428]
Recently built a middleware that automatically creates an IAM auth token to allow DB connection without a hardcoded password. Is this something we would like in the project? Or a separate module? Let me know, I can submit a PR with Docs.

Ways of setting the DB password, quick comparison:
- `process.env`: Password is in plain text
- `ssm`: Password encrypted, requires round trip to fetch, has to be rotated with an external process (additional cost)
- `secretManager`: Password encrypted, Rotates password, requires round trip to fetch, adds additional cost
- `authToken`: No password in the DB, based on IAM (15min access rotation), generated at the instance, no additional cost

Using the RDS AuthToken as you can see is more secure, free, and can be faster.

Docs:
- DB Setup: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.DBAccounts.html
- IAM Policy: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html
- RDS Signer: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS/Signer.html
- Step by Step: https://aws.amazon.com/blogs/database/use-iam-authentication-to-connect-with-sql-workbenchj-to-amazon-aurora-mysql-or-amazon-rds-for-mysql/

```js
// example use
module.exports = (
  app,
  { dbUsername = 'iam_api', dbConcurrency = 0 }
) =>
  middy(app)
    .use(doNotWaitForEmptyEventLoop())
    .use(ssm({
      cache: true,
      setToContext: true,
      names: {
        rdsHostname: '/database/postgres/hostname',
        rdsDatabase: '/database/postgres/database',
        rdsPort: '/database/postgres/port'
      }
    }))
    .use(rdsAuthToken({
      username: dbUsername
    }))
```
Middleware:
```js
const AWS = require('aws-sdk')

const defaultNames = {
  hostname:'rdsHostname',
  port:'rdsPort',
  username:'rdsUsername',
  password:'rdsPassword'
}

let authToken = null
module.exports = (options = {}) => {
  const map = Object.assign(defaultNames, options.names)
  return {
    before: (handler, next) => {
      const chooseVar = (name) => {
        return handler.context[map[name]] || options[name] || process.env[name] || ''
      }

      handler.context[map['hostname']] = chooseVar('hostname')
      handler.context[map['username']] = chooseVar('username')
      handler.context[map['port']] = chooseVar('port')

      // warmup
      if (!authToken) {
        const signer = new AWS.RDS.Signer({
          region: chooseVar('region') || process.env.AWS_REGION,
          hostname: handler.context[map['hostname']],
          port: Number.parseInt(handler.context[map['port']]),
          username: handler.context[map['username']]
        })

        signer.getAuthToken({}, (err, token) => {
          if (err) {
            console.error(err)
            return
          }
          authToken = token
          handler.context[map['password']] = authToken
          next()
        })
      } else {
        handler.context[map['password']] = authToken
        next()
      }
    }
  }
}
```

**Comment by sdomagala** [comment]
Hey @willfarrell,
This RDS auth token looks like a great feature and extending it in dbManager from #407 would certainly help someone.
That said, in my projects I currently use SSM for password managment so I wouldn't feel comfortable implementing it, but if you're willing to set it up I would definitely try it out in future projects!

One thing regarding this code, you mentioned that this auth token is regenerated every 15 minutes but it looks like you cache token just once.

Cheers

**Comment by willfarrell** [comment]
@sdomagala Just thinking you see value moving from ssm or secret manager to iam might have value. My goal was to eliminate the round trip time to SSM. I don't think it should be built into dbManager. Having it outside allows for more flexibility.

You are right, I'm just in the process of migrating from ssm to the above. IAM token generally has a 15min lifecycle. Not 100% sure it also applies to this type of token, lot of testing still to do. Depending on the results from testing will determine caching options. This feature is not the most well documented, couldn't find a single blog post on it yet :(. SSM is easier to setup and is secure enough for almost all use cases.

Will send a PR once it's a little more polished and battle-tested, will likely have similar params as `ssm` when finished.

**Comment by sdomagala** [comment]
@willfarrell Agreed about not adding this to db package. dbManager should probably be tweaked to handle regenerating db connection every x minutes. Just have to keep in mind that you have to invalidate token `15 minutes - lambda timeout` so you don't end up with failed calls during lambda invocation. For lambda function with 900 sec timeout that would mean 1 call = 1 token, that can't be good when you need your lambda at scale, in that case you would use password and keep connection infinitely

**Comment by willfarrell** [comment]
So, early testing shows that the token only needs to be valid when a connection is made. This is confirmed by the blurb I found below.

```
With IAM database authentication, you use an IAM authentication token when you connect to your DB instance or DB cluster. An IAM authentication token is a string of characters that you use instead of a password. After you generate an IAM authentication token, it’s valid for 15 minutes before it expires. If you try to connect using an expired token, the connection request is denied. MySQL doesn’t recheck existing connections, so your established connection is not dropped when the token expires.
~ https://aws.amazon.com/blogs/database/use-iam-authentication-to-connect-with-sql-workbenchj-to-amazon-aurora-mysql-or-amazon-rds-for-mysql/
```

This means you don't have to keep reconnecting every 15min. Every new lambda uses a new token to setup their connections. This means those that leave their connection open between calls (in my case) for low volume, high performance it works for now.

I'll add in token rotation for those that need it. It's not hard to do. Maybe adding the same mechanism to `ssm` may be in order as well to ensure changed values are caught. Could be as simple as:
```
{
  cache: 15,  // false, integer, true
}
```

@lmammino What are your thoughts on middleware cache rotation?

**Comment by willfarrell** [comment]
Just ran into this: https://github.com/aws/aws-cli/issues/4613 (Expired token can be created if the root on is already created). Not sure if this applies to cli only, will test.
