### ISSUE TITLE
Improve CORS middleware to support other CORS headers

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#43]
It would be great to have support to other common CORS headers like the follows:

 - `Access-Control-Allow-Methods`
 - `Access-Control-Allow-Headers`
 - `Access-Control-Max-Age`
 - `Access-Control-Allow-Credentials`

More info [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

**Comment by akshitgrover** [comment]
@lmammino can I work on this?

**Comment by lmammino** [comment]
Sure thing @akshitgrover

**Comment by abdullateef97** [comment]
can i work on this
#38

**Comment by lmammino** [comment]
@akshitgrover, what's the current status? Do you want to coordinate/pair with @abdullateef97?

**Comment by abdullateef97** [comment]
please do let me know if i can proceed

**Comment by abdullateef97** [comment]
@lmammino  can i

**Comment by lmammino** [comment]
@abdullateef97 go ahead for now ;)

**Comment by akshitgrover** [comment]
Sorry, I was stuck with something. Maybe I can help if work is still not done? @lmammino @abdullateef97

**Comment by lmammino** [comment]
I would be happy this to be a collaborative effort. Can you discuss this between yourself and figure out how to collaborate? 

If you need a discussion channel, you can join the middy official chat on gitter: https://gitter.im/middyjs .

Once you have a first PR, I will be happy to support the process with a formal reviews and advices if needed.

CC: @akshitgrover @abdullateef97

**Comment by akshitgrover** [comment]
I am working on Access-Control-Max-Age. @lmammino  @abdullateef97

**Comment by abdullateef97** [comment]
@lmammino  ive u tried using the cors middleware, if you have what were the issues

**Comment by akshitgrover** [comment]
@lmammino I am not able to run the tests, It is not returning undefined instead of objects.

**Comment by lmammino** [comment]
@abdullateef97 @akshitgrover I am not sure what are you trying to do. Please join the [gitter chat](https://gitter.im/middyjs) where I guess it would be easier to discuss interactively your issues.

**Comment by omryhay1** [comment]
@lmammino - Are you going to add the following any time soon?

- ```Access-Control-Max-Age```
- ```Access-Control-Allow-Methods```

**Comment by camiloaz** [comment]
I see this issue is closed but there is no solution yet if you want to be able to set the `Access-Control-Allow-Methods` header.

**Comment by willfarrell** [comment]
It's been added to v2, see `release/2.x` branch
