### ISSUE TITLE
[Docs] warmup can be replaced by Provisioned Concurrency

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#435]
There is a new feature with Lambda that allows for a lambda to stay warm, deprecating the need for a `warmup` trigger. 
- https://aws.amazon.com/blogs/compute/new-for-aws-lambda-predictable-start-up-times-with-provisioned-concurrency/
- https://serverless.com/blog/aws-lambda-provisioned-concurrency/

For v1-beta and onwards I think we should deprecate. Thoughts?

**Comment by lmammino** [comment]
That's a very good point and I agree. Before deprecating we should update the readme with some sort of migration guide

**Comment by willfarrell** [comment]
I've been playing around with it using `serverless`, it's not as simple as their blog post makes it look and no additional docs on their side.

To be able to do it "correct";
- Deploy your function w/ a version tag (not done by default)
- Apply an alias to that new version
- Attach provisionedConcurrency to that alias

Each of these steps is poorly documented. So, I would say keep an eye out for blog posts on this. 

I did try in `terraform` as well, brain dead easy to apply.

**Comment by lmammino** [comment]
Yeah, i guess it's still a bit too early to have a decent body of documentation.
In any case i am very supportive of this. if we can put together few lines (and maybe some doc links) that would be more than enough to provide guidance for the migration
