### ISSUE TITLE
Lazy loading aws-sdk performance anti-pattern

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#436]
I'm in the process of building https://github.com/middyjs/middy/issues/428. While refactoring it to follow some of the patterns from `ssm`, I noticed warmup/coldstart times spiked.

After adding timers everywhere I found that lazy loading the `aws-sdk` as seen in `ssm` https://github.com/middyjs/middy/blob/master/src/middlewares/ssm.js#L166 added up to 4.5sec duration to a warmup/coldstart. Moving the declaration to the global scope removed the 4.5sec.

I'm running NodeJS v12.x w/ 128MB Memory.

Anyone else running into this? Maybe AWS improved something under the hood removing the once benefit of needing to lazy load?

cc @lmammino

**Comment by lmammino** [comment]
Wow that's interesting. I wonder if the Lambda runtime does something special to speed up things here. Maybe @theburningmonk knows something (or knows who to ask to get some clarity about this)...

**Comment by willfarrell** [comment]
Created a bare-bones example to test this. https://github.com/willfarrell/middy-serverless-perf

Using: NodeJS v12.x in `ca-central-1`
Testing on:
- *With* or *Without* `aws-sdk` as a dependency
- Lambda is *serverless* or *VPC*
- Dependency is used at the *global*, *option*, or *function* level scope.

<img width="1224" alt="Screen Shot 2019-12-09 at 08 54 19" src="https://user-images.githubusercontent.com/1097020/70450830-a0ca8c00-1a61-11ea-9a16-4ea6b9e60ef5.png">

Results show that there is indeed a jump up in execution time when a dependency is declared inside `before`, `after`, `onError`. Declaring in at the `global` level is generally a little faster than the `option` level.

I'm going to keep it running all day to get more data points. Declaring at the global and option level seem to flipflop on which is faster, I expect them to average out to be the same over time.

**Comment by willfarrell** [comment]
This is a 1 hour avg, also added *warm* vs *cold* to see how that looks too (just in case). It's pretty clear that attaching a dependency in `before`, `after`, `onError` has a penalty. I'm happy to update `ssm`, and any others that have this pattern,  if you like.

Ran every 16min
<img width="1224" alt="Screen Shot 2019-12-09 at 10 28 24" src="https://user-images.githubusercontent.com/1097020/70458179-cd38d500-1a6e-11ea-962c-c0d53e69ab37.png">

Ran every 14min
<img width="1222" alt="Screen Shot 2019-12-09 at 10 28 31" src="https://user-images.githubusercontent.com/1097020/70458187-d0cc5c00-1a6e-11ea-8757-b13d24204b95.png">

**Comment by lmammino** [comment]
Amazing research @willfarrell! Happy to go ahead with the changes :)

**Comment by vladgolubev** [comment]
Could be related: https://medium.com/@hichaelmart/shave-99-93-off-your-lambda-bill-with-this-one-weird-trick-33c0acebb2ea
