### ISSUE TITLE
New JSON error handler and validation middlewares

### ISSUE THREAD

**Issue by dbartholomae** [middyjs/middy#468]
I have just released two additional middlewares which might still change in the coming days as they are not yet in use in production. As usual I'm happy about feedback :)

https://github.com/dbartholomae/middy-middleware-class-validator
https://github.com/dbartholomae/middy-middleware-json-error-handler

If there is interest I can set up a PR adding them to the 3rd party middleware list as soon as they are a bit more stable.

**Comment by lmammino** [comment]
Hello @dbartholomae, great work! I am definitely supporting for adding those to the list of third-party middlewares. They already look great so I look forward to seeing how they are going to look like when they reach production-grade! :)

On a side note: I like your work on typescript. There have been a number of conversations on how to improve typings and generic typescript experience with Middy (ref #316).  It would be awesome if you could bring your experience into the conversation and maybe contribute to docs/typings as you see fit :)
