### ISSUE TITLE
provide typings definition to use middy on typescript

### ISSUE THREAD

**Issue by joseSantacruz** [middyjs/middy#48]
Typescript grow a lot this year and is a must-have for the projects where I work to use it and is always more productive and useful if the modules that we use has the typing definition.

**Comment by lmammino** [comment]
Hello @joseSantacruz,
sorry for the late response to your issue.

Having typescript support (as flow typings support) would be amazing, would you have the time/knowledge to contribute to this?

**Comment by joseSantacruz** [comment]
Hi @lmammino,

I just make a PR #53 with a first version of typings.
