### ISSUE TITLE
Add explanation about context.done called twice warning in docs

### ISSUE THREAD

**Issue by rschpdr** [middyjs/middy#480]
Hello, first of all thanks for the amazing tool!

So, I got bit by the aforementioned warning and since it's quite elusive, it was kinda hard to debug. Turns out I was trying to return a `next()` call from an async middleware, because I scanned too quickly past the Promises support part of the docs. 

I think adding a quick FAQ item telling users that this warning is related to that part of the docs, and the fix is to just not use callbacks in async handlers or middlewares would be nice, because currently there's nothing on google about that, and I kind of stumbled in the solution by luck. 

I'm willing to submit a PR if you think this is worth it.

Thanks!

**Comment by lmammino** [comment]
Hello @rschpdr !

This sounds like a great idea to me and a PR would be awesome.

Just as a heads up, it would be best to target the branch 1.0.0-beta as the current 0.x will go soon into maintenance mode.
