### ISSUE TITLE
httpSecurityHeaders stopping logger from working

### ISSUE THREAD

**Issue by zvictor** [middyjs/middy#486]
I have the following lambda code:
```js
exports.handler = middy(async (event, context) => {
  throw new Error(123)
})
  .use(httpErrorHandler())
  //  .use(httpSecurityHeaders()) <--- uncomment this
```

when I invoke it, I have the following printed on the console:

> ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"123","stack":["Error: 123","    at Function.handler (/var/task/index.js:26:9)","    at /var/task/node_modules/@middy/core/index.js:189:44","    at runNext (/var/task/node_modules/@middy/core/index.js:93:14)","    at runMiddlewares (/var/task/node_modules/@middy/core/index.js:99:3)","    at /var/task/node_modules/@middy/core/index.js:172:7","    at new Promise (<anonymous>)","    at Runtime.instance [as handler] (/var/task/node_modules/@middy/core/index.js:158:26)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

---

The problem is that once I uncomment the last line (`.use(httpSecurityHeaders())`), no more messages appear on the console.
Why? Shouldn't `httpErrorHandler` logging be unaffected by other middlewares?

**Comment by willfarrell** [comment]
Keep in mind the order of the middlewares is important. Try putting `.use(httpErrorHandler())` last.
