### ISSUE TITLE
sqs json body parser

### ISSUE THREAD

**Issue by thematrimix** [middyjs/middy#490]
I wonder if a sqs json body parser would be usefull for the project?

Code wise it would look something like the following:

```javascript
const defaultReviver = (_key, value) => {
  return value;
};

const defaultSafeParse = body => {
  try {
    return JSON.parse(body);
  } catch (err) {
    return body;
  }
};

const sqsJsonBodyParserBefore = ({ reviver, safeParse }) => (handler, next) => {
  const { event: { Records = [] } = { Records: [] } } = handler || {};

  Records.forEach(record => {
    record.body = safeParse(record.body, reviver);
  });

  next();
};

const middleware = ({ reviver = defaultReviver, safeParse = defaultSafeParse } = {}) => ({
  before: sqsJsonBodyParserBefore({
    reviver,
    safeParse
  })
});

module.exports = middleware;
```

If this would be usefull I would love to wrap it up, meeting the code standards of the project and PR it.

**Comment by willfarrell** [comment]
I was thinking about this just last week. Can you put a PR together?

**Comment by thematrimix** [comment]
Indeed I should be able to have one in a day or so. I have to rework test and update docs mostly.

**Comment by thematrimix** [comment]
testing complete will get docs updates ASAP

**Comment by thematrimix** [comment]
PR is up: https://github.com/middyjs/middy/pull/491
