### ISSUE TITLE
Validator accepts undefined as inputSchema

### ISSUE THREAD

**Issue by kangastus** [middyjs/middy#495]
Validator accepts undefined as inputSchema [1] and outputSchema.

This allows unintentional skipping of validation by pointing to an undefined schema.

Would there be interest in changing the behaviour? Or would it be better to create a new custom validator that would be safer to use?

For example checking if the key exists instead of checking its' value would resolve the issue. This would not be backward compatible and might work in a different way than some Javascript developers would expect. Maybe this behaviour could be optional but then it would be easy to forget to enable it.

[1]: https://github.com/middyjs/middy/blob/master/src/middlewares/validator.js#L50, 1.x branch: https://github.com/middyjs/middy/blob/1.0.0-beta/packages/validator/index.js#L50

**Comment by lmammino** [comment]
I like the idea in principle, but I would love to keep the feature backward-compatible if possible.

Something that comes to my mind is that we can add 2 extra options:

`failOnUndefinedInputValidator` and `failOnUndefinedOutputValidator` (or similar names).

Those would be `false` by default, but if they are `true` the new (more restrictive) behaviour will apply.

What do you think?

**Comment by willfarrell** [comment]
I think a simple:
```
if (inputSchema === undefined) { console.warn('inputSchema is undefined.') }
```
would be all that's needed.

Personally, I'd rather not have it included in the middleware. Having automated tests that check the inputs (ie fail checks) of the API should be in place and would catch this developer error.

**Comment by kangastus** [comment]
Thank you for your comments. 

Having non-default settings or warning logging would risk invalid code going unnoticed. Maybe a custom validator or a wrapper would do the job.

However we are moving to Typescript and that partially resolved this issue for us in an elegant way.
