### ISSUE TITLE
error-logger example in README incorrect

### ISSUE THREAD

**Issue by grempe** [middyjs/middy#500]
See:

https://github.com/middyjs/middy/tree/1.0.0-beta/packages/error-logger

The example in the README specifies:

```
const inputOutputLogger = require('@middy/error-logger')
```

and it should instead be:

```
const errorLogger = require('@middy/error-logger')
```

**Comment by ivanvs** [comment]
I would say this is fixed now: https://github.com/middyjs/middy/tree/master/packages/error-logger. There is no `1.0.0-beta` branch anymore, v1 is on master now. And documentation is fixed. 

Could we close this issue?
