### ISSUE TITLE
Middy breaks requests made with Nock

### ISSUE THREAD

**Issue by matt-sanders** [middyjs/middy#501]
Hey guys

Firstly thanks heaps for the work you guys have done on this project. Super helpful stuff!

I'm working on a project which uses middy and we have a custom middleware set up to validate auth tokens sent with Auth0. As part of this Auth0 makes an external request. I've been using [Nock](https://github.com/nock/nock) to mock these requests. What I'm finding is that if I test a function that is not wrapped in `middy()`, Nock works as expected and intercepts the request. However, if I try to test the function wrapped in `middy()` ( e.g. to ensure that all middlewares are being applied correctly ) then it fails. I've set up a very very basic example [here](https://github.com/matt-sanders/middy-nock-error). It just tests two functions, exactly the same, one wrapped and one not wrapped. Notice how as soon as the function is wrapped, something happens which causes Nock to not apply the interceptor correctly. I assume this is an issue with Middy and not with Nock as Nock seems to work fine without it.

Let me know if you need any more info!

**Comment by willfarrell** [comment]
Sorry for lack of response on this. I'm not familiar with `nock` and how it works to even assist with this. I plan to start working on v2 of middy soon. I see value in having it work with testing tools like this. Added to the roadmap

**Comment by willfarrell** [comment]
Tested with v2 alpha, seems to handle just fine. Thanks for the detailed test, was useful to have.

FYI there was a typo in the test that may have been a contributing factor https://github.com/matt-sanders/middy-nock-error/blob/master/index.test.js#L16
