### ISSUE TITLE
Async/Await handlers need do-not-wait-for-empty-event-loop middleware to be used.

### ISSUE THREAD

**Issue by vikasgarghb** [middyjs/middy#505]
Looks like there is a gap in the documentation on `Async/Await` handlers. I had an async function which when run using `sam local invoke` would just hang and never return. After some debugging, I found that middy was receiving some callback from somewhere which was then preventing it to resolve the correct response.

After I added `context.callbackWaitsForEmptyEventLoop = false` to my function it worked fine. Turns out `@middy/do-not-wait-for-empty-event-loop` middleware already does that, so I included that in my function and everything is fine.

The version of middy I am using is: 1.0.0-beta.8.
Node version: 12.x

Some details on my function, it makes a db call to get the data.

Something similar is reported her: https://github.com/middyjs/middy/issues/420 and https://github.com/middyjs/middy/issues/198

**Comment by lmammino** [comment]
Thanks a lot @vikasgarghb for compiling this detailed report. Would you be able to share some code with which we could reproduce the issue?

**Comment by marianoc84** [comment]
> Looks like there is a gap in the documentation on `Async/Await` handlers. I had an async function which when run using `sam local invoke` would just hang and never return. After some debugging, I found that middy was receiving some callback from somewhere which was then preventing it to resolve the correct response.
> 
> After I added `context.callbackWaitsForEmptyEventLoop = false` to my function it worked fine. Turns out `@middy/do-not-wait-for-empty-event-loop` middleware already does that, so I included that in my function and everything is fine.
> 
> The version of middy I am using is: 1.0.0-beta.8.
> Node version: 12.x
> 
> Some details on my function, it makes a db call to get the data.
> 
> Something similar is reported her: #420 and #198

Would have read this post 3 hours ago :)

**Comment by ChrisSargent** [comment]
I'm not sure if this is related but I am having issues with a function using async / await.

Simple code:
```js
const axios = require("axios");
const middy = require("@middy/core");
const doNotWaitForEmptyEventLoop = require("@middy/do-not-wait-for-empty-event-loop");

const users = async (event, context) => {
  console.log(context.callbackWaitsForEmptyEventLoop);
  const response = await axios.get(
    "http://dummy.restapiexample.com/api/v1/employees"
  );
  return response.data.data;
};

const handler = middy(users);

module.exports = { handler };
```

The above code doesn't wait for the handler (I'm running it in AWS Amplify Mock Mode). If I just do: `module.exports = { handler: users };` it works as expected.

I've also tried `const handler = middy(users).use(doNotWaitForEmptyEventLoop());` but it also didn't work. Logging `context.callbackWaitsForEmptyEventLoop` is 'false'

**Comment by ChrisSargent** [comment]
Actually, you can ignore this. I tried deploying and it all worked fine. Seems there is an issue with AWS Amplify mocking: https://github.com/aws-amplify/amplify-cli/issues/4019

**Comment by willfarrell** [comment]
Glad to hear you found the root cause.
