### ISSUE TITLE
middy validator does not work with JSON schema 2019-09

### ISSUE THREAD

**Issue by mindhaq** [middyjs/middy#520]
What are the steps to reproduce this issue?
-------------------------------------------
1. Validate using a JSON-schema with

```JSON
{
      "$schema": "http://json-schema.org/draft/2019-09/schema#"
}
```

What happens?
-------------

Fails with exception:

```
no schema with key or ref "http://json-schema.org/draft/2019-09/schema#"
at Ajv.validate (node_modules/ajv/lib/ajv.js:93:19)
      at Ajv.validateSchema (node_modules/ajv/lib/ajv.js:174:20)
      at Ajv._addSchema (node_modules/ajv/lib/ajv.js:307:10)
      at Ajv.compile (node_modules/ajv/lib/ajv.js:113:24)
      at Object.<anonymous>.module.exports [as default] (node_modules/@middy/validator/index.js:45:43)
```

What were you expecting to happen?
----------------------------------
It should validate with that schema version. It does with

```JSON
{
        "$schema": "http://json-schema.org/draft-07/schema#",
}
```

What versions of software are you using?
----------------------------------------
**Node.js Version:** 13.12.0

**Middy Version:** 1.0.0

**AWS SDK Version:** 2.665.0

**Comment by willfarrell** [comment]
`ajv`, the dependency used in this middleware, doesn't have support for `2019-09` yet. See https://github.com/ajv-validator/ajv/issues/1198

You'll have to build your own validator middleware and use a different dependency if you require this `2019-09` to be supported or wait for `ajv` support.
