### ISSUE TITLE
Documentation inconsistent about order of http-error-handler and http-response-serializer

### ISSUE THREAD

**Issue by k-nut** [middyjs/middy#523]
The documentation for the [http-error-handler ](https://github.com/middyjs/middy/tree/master/packages/http-error-handler) currently says:
> This middleware should be set as the last error handler.

The documentation for the [http-response-serializer](https://github.com/middyjs/middy/tree/master/packages/http-response-serializer) says:
> This middleware does work with http-error-handler. To serialize error responses, ensure the httpErrorHandler middleware is configured before httpResponseSerializer.

I guess it makes sense to change the documentation for http-error-handler to  
> This middleware should be set as the last error handler unless you also want to register the http-reponse-serializer. If so, this middleware should come second-last and the http-response-serializer should come last.

What do you think?

**Comment by willfarrell** [comment]
Looks good to me. If you can submit a PR, I'd be happy to approve it.

**Comment by k-nut** [comment]
@willfarrell created a PR: #546 let me know if you would like anything changed.
