### ISSUE TITLE
[@middy/db-manager] Add option for fetching secrets from AWS Secrets Manager.

### ISSUE THREAD

**Issue by munierujp** [middyjs/middy#526]
[[@middy/db-manager](https://github.com/middyjs/middy/tree/master/packages/db-manager)] Add option for fetching secrets from [AWS Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html).

### Simple
Just write your secret name.

```js
handler.use(dbManager({
  config: {
    client: 'mysql'
  },
  secrets: {
    name:  'my_db_credentials'
  }
}))
```

### Normalize keys for client
You can normalize keys for client by mapping function.

```js
handler.use(dbManager({
  config: {
    client: 'mysql'
  },
  secrets: {
    name:  'my_db_credentials',
    // normalize keys for client
    map: ({ host, port, username, password, dbname }) => ({
      host,
      port,
      user: username,
      password,
      database: dbname
    })
  }
}))
```

## Pros
- Unlike [@middy/secrets-manager](https://github.com/middyjs/middy/tree/master/packages/secrets-manager), Don't pollute context
- Can normalize keys for client by mapping function

## See also
- [AWS Templates You Can Use to Create Lambda Rotation Functions - AWS Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html)

**Comment by willfarrell** [comment]
Thanks for sharing this with us. `db-manager` has options to remove those secrets from the context, I believe it's enabled by default when `secretsPath` is used. However, I think that's for ssm, not sure if it can also work with secrets-manager as well. Have you tested this approach already? Maybe we just need to update the documentation to address this use case.

Alternatively, you could use the `rdsSigner` approach. It's more secure and faster than `ssm` and `secrets-manager`.

**Comment by willfarrell** [comment]
In middy v2 we plan to have secrets manager be able to store to context. this would then allow db-manager to pull from the same context without the need for additional code for every source a password can come from.

Sneak peak: https://github.com/willfarrell/middy/blob/release/2.x/packages/secrets-manager/index.js => https://github.com/willfarrell/middy/blob/release/2.x/packages/db-managerr/index.js

Of course this is still in early development and need lots of testing still.
