### ISSUE TITLE
Make it possible to reverse the order of error handling

### ISSUE THREAD

**Issue by Shamshiel** [middyjs/middy#529]
First of all thanks for the amazing engine!

I'm struggling in implementing a request logging middleware that has the following requirements:

> Before has to be called first
> After has to be called last
> Error has to be called last

Currently it is like this:

> Before is called first
> After is called last
> Error is called first

If I didn't miss anything in the documentation it would be nice to reverse the order in which the Errors are handled. 

Is there a reason why the first middleware is currently the first to handle the error?

**Comment by willfarrell** [comment]
@lmammino this one is for you.

@Shamshiel if the order were to change it would be considered a major change. Do you have an example/use-case in mind?

**Comment by Shamshiel** [comment]
I wanted to write a request logging middleware that gets called first and called last in all cases so it can log the request times as accurately as possible. 

The problem is that it is currently called first in an error case and that leads to incorrect request times because there could be another middleware that is executed after my request logging middleware.

My proposal wouldn't be to change the default order but to make it possible to change the order if the user wants to change it.

**Comment by lmammino** [comment]
Hello @Shamshiel and thanks for opening this issue. 

> Is there a reason why the first middleware is currently the first to handle the error?

This was an arbitrary design decision originally (we thought that was the most intuitive approach).

One thing you could try is to create different middleware for different steps (one with the `before` bit, one with the `after` bit and one with the `error` bit). This way you should be able to register them in the order that works best for you.

You could also use the shortcuts `middyHandler.before(...)`, `middyHandler.after(...)`, `middyHandler.error(...)`.

This is probably counter-intuitive and hacky, but it might just work for your particular use case.

What do you think?
