### ISSUE TITLE
[@middy/db-manager] Add option for custom cleanup function

### ISSUE THREAD

**Issue by munierujp** [middyjs/middy#530]
[[@middy/db-manager](https://github.com/middyjs/middy/tree/master/packages/db-manager)] Add option for custom cleanup function.
For example, [TypeORM](https://typeorm.io/#/connection-api) uses async `close` function.

## Sample usage

```js
handler.use(dbManager({
  config: {
    client: 'mysql',
    connection: {
      host: '127.0.0.1',
      user: 'your_database_user',
      password: 'your_database_password',
      database: 'myapp_test'
    } 
 },
  cleanup: async (db) => {
    await db.close()
  }
}))
```

## Related Issue
- #531

**Comment by willfarrell** [comment]
I knew one day someone would ask for this and #531.

I imagined the next version of this not including `knex` pre-bundled (the version should be managed by the user), but have a way to map and trigger everything properly for most other ORMs out there.

I'm open to a PR to see what you have in mind. It will introduce duplicate options (`forceNewConnection`) but I think people can live with that. Just be aware other may still be using it.

**Comment by willfarrell** [comment]
Is there still a need for this. I'm now feeling you might as well build your own custom middleware to fit your needs. Please reopen if you feel this isn't the case.
