### ISSUE TITLE
[@middy/db-manager] Add option for custom initialize function

### ISSUE THREAD

**Issue by munierujp** [middyjs/middy#531]
[[@middy/db-manager](https://github.com/middyjs/middy/tree/master/packages/db-manager)] Add option for custom initialize function.
For example, [TypeORM](https://typeorm.io/#/connection-api) uses async `createConnection` function.

## Sample usage

```js
import {createConnection} from 'typeorm'

handler.use(dbManager({
  config: {
    client: 'mysql',
    connection: {
      host: '127.0.0.1',
      user: 'your_database_user',
      password: 'your_database_password',
      database: 'myapp_test'
    }
  },
  initialize: async (config) => {
    const db = await createConnection(config)
    return db
  }
}))
```

## Related Issue
- #530

**Comment by willfarrell** [comment]
Is there still a need for this. I'm now feeling you might as well build your own custom middleware to fit your needs. Please reopen if you feel this isn't the case.
