### ISSUE TITLE
@middy/db-manager/index "has no call signatures"

### ISSUE THREAD

**Issue by musicaljoeker** [middyjs/middy#533]
What are the steps to reproduce this issue?
-------------------------------------------
1. Import `db-manager` using typescript
```import dbManager from '@middy/db-manager';```
2. Try to call the db manager function
```
exports.handler = middy(handler)
.use(httpErrorHandler())
.use(jsonBodyParser())
.use(validator({ inputSchema: inputSchema }))
.use(
    dbManager({ // this is where it fails
        config: dbConfig,
    })
);
```

What happens?
-------------
Receive error saying db-manager/index has no call signatures.

What were you expecting to happen?
----------------------------------
I was expecting the db-manager function to operate like other pieces of this middleware. jsonBodyParser is working just fine, for example.

Any logs, error output, etc?
----------------------------
Test suite failed to run
```
    src/myFile/index.ts:16:9 - error TS2349: This expression is not callable.
      Type 'typeof import("/path/to/my/project/node_modules/@middy/db-manager/index")' has no call signatures.

    16         dbManager({
               ~~~~~~~~~
 FAIL  src/myFile/myTest.test.ts
  ● Test suite failed to run
```

What versions of software are you using?
----------------------------------------
**Typescript Version:** 3.2.4

**Middy Version:** 1.0.0

**Serverless:** 1.70.1

**Comment by munierujp** [comment]
@middy/db-manager's type definition is incomplete. (see #536)
You can create wrapper function like this.

```ts
import { DbManagerOptions } from '@middy/db-manager'
const dbManager = require('@middy/db-manager')

/**
* Wrapper of @middy/db-manager
* @see https://www.npmjs.com/package/@middy/db-manager
*/
export default function (options: DbManagerOptions) {
  return dbManager(options)
}
```
