### ISSUE TITLE
Promises and multiple error handlers

### ISSUE THREAD

**Issue by christophgysin** [middyjs/middy#541]
What are the steps to reproduce this issue?
-------------------------------------------
According to the examples, it should be possible to pass an error from one error handler to the next:

https://github.com/middyjs/middy#promises-and-error-handling
> If onError promise resolves to a truthy value, this value is treated as an error and passed further down the pipeline.

Let's try this:

```js
const middy = require('@middy/core')

const middleware1 = {
  onError: (handler) => {
    console.log('middleware1')
    console.log(handler.error.message)
    // If onError promise resolves to a truthy value, this value is treated as an error and passed further down the pipeline.
    return Promise.resolve(new Error('from middleware 1'))
  }
}

const middleware2 = {
  onError: (handler) => {
    console.log('middleware2')
    console.log(handler.error.message)
    return Promise.resolve()
  }
}

const handler = middy(() => {
  throw new Error('from handler')
})

handler.use(middleware1).use(middleware2)

handler()
```

What happens?
-------------
```sh
$ node error-handling.js
middleware1
from handler
middleware2
from handler
```

What were you expecting to happen?
---------------------------------
```sh
$ node error-handling.js
middleware1
from handler
middleware2
from middleware 1
```

Any other comments?
-------------------
To make to above work, handler.error needs to be set explicitly, and any truthy value returned:
```js
const middleware1 = {
  onError: (handler) => {
    console.log('middleware1')
    console.log(handler.error.message)
    // workaround
    handler.error = new Error('from middleware 1')
    return Promise.resolve(true)
  }
}
```

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.4.0
**Middy Version:** 1.0.0
**AWS SDK Version:** -

**Comment by willfarrell** [comment]
Looks like the docs could be more explicit on handling this. Would you be able to submit a PR to share your finding?

FYI AWS Lambda doesn't support node v14 yet. 

@lmammino The above solution is the expected expectation, right?

**Comment by christophgysin** [comment]
IMO the documented behaviour seems more logical, so I would consider this a bug and fix the implementation, instead of just changing the documenting to match the current behaviour.

**Comment by willfarrell** [comment]
I'm working on v2 and ran into the test for this specifically. The current test can be found at https://github.com/middyjs/middy/blob/e17f9a410d799b0aee5ac0bc6be7a83055c82bbe/packages/core/__tests__/index.js#L688

The error on the middleware should be the primary error, with `.originalError` set to the error of the handler. When promises are involved in v1.x things can sometimes feel a little inconsistent. I'm hoping to feel more intuitive in v2.

How I've written v2 current, below should return what you expect.
```
import middy from '@middy/core'

const middleware1 = {
  onError: (handler) => {
    console.log('middleware1')
    console.log(handler.error.message)
   
   handler.error = new Error('from middleware 1')
  }
}

const middleware2 = {
  onError: (handler) => {
    console.log('middleware2')
    console.log(handler.error.message)
    return {}
  }
}

const handler = middy(() => {
  throw new Error('from handler')
})

handler.use(middleware1).use(middleware2)

await handler()
```
v2 is still in early dev and subject to change. But your above case will be supported.
