### ISSUE TITLE
[Question] Interrupt middleware execution if the handler is async

### ISSUE THREAD

**Issue by diego1686** [middyjs/middy#547]
Hi! I've a quick question... the documentation says that in order to interrupt the middleware execution, we should call `handler.callback`. But what if the handler is async? In that case the callback function is not defined. Is there a way to doing this without raising an error?

Thanks!

**Comment by demsey2** [comment]
I had the same problem and couldn't find anything. At the moment, in my middleware, I reject a promise 
```
if (!shouldContinue) {
      return Promise.reject(new EBRequestCompletedError());
}
```
and then in my global error middleware onError I check for that error type and skip if EBRequestCompletedError

I would like to know if there is a better solution
