### ISSUE TITLE
Link to upgrade guide broken on npmjs

### ISSUE THREAD

**Issue by hsks** [middyjs/middy#554]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
Try to access the upgrade guide for middy 0.x to middy 1.x on [middy's npmjs page](https://www.npmjs.com/package/middy).

What happens?
We get a 404
…

What were you expecting to happen?
A documentation for upgrading from 0.x to 1.x
…

Any logs, error output, etc?
----------------------------
The url for the upgrade guide on npmjs seems to be a wrong one. It's mentioned as https://github.com/middyjs/middy/blob/1.0.0-beta/UPGRADE.md
but it should probably be https://github.com/middyjs/middy/blob/master/UPGRADE.md

**Comment by hsks** [comment]
> Great catch @hsks , would you like to submit a PR to fix this? :)

Definitely! Happy to do it.

**Comment by hsks** [comment]
@lmammino I've raised a PR on branch 0.x for the same. Request you to review it.
https://github.com/middyjs/middy/pull/555

Thank you.

**Comment by willfarrell** [comment]
Thank you
