### ISSUE TITLE
[@middy/validator] webpack monorepo module not found error

### ISSUE THREAD

**Issue by kamaz** [middyjs/middy#564]
What are the steps to reproduce this issue?
-------------------------------------------
1. [Clone Repository](https://github.com/kamaz/serverless-middy-webpack)
2. Follow [reproduce steps](https://github.com/kamaz/serverless-middy-webpack#reproduce-steps)

What happens?
-------------
Error is thrown `Module not found`.

What were you expecting to happen?
----------------------------------
Application package correctly.

Any logs, error output, etc?
----------------------------
```text
ERROR in /Users/kamilzuzda/Projects/Cabiri/repo/test-repo/node_modules/@middy/validator/node_modules/ajv-errors/node_modules/ajv/scripts/bundle.js
Module not found: Error: Can't resolve 'uglify-js' in '/Users/kamilzuzda/Projects/Cabiri/repo/test-repo/node_modules/@middy/validator/node_modules/ajv-errors/node_modules/ajv/scripts'
resolve 'uglify-js' in '/Users/kamilzuzda/Projects/Cabiri/repo/test-repo/node_modules/@middy/validator/node_modules/ajv-errors/node_modules/ajv/scripts'
  Parsed request is a module
  using description file: /Users/kamilzuzda/Projects/Cabiri/repo/test-repo/node_modules/@middy/validator/node_modules/ajv-errors/node_modules/ajv/package.json (relative path: ./scripts)
    resolve as module
```

Any other comments?
-------------------
I believe the issue is related to https://github.com/middyjs/middy/issues/560 and PR https://github.com/middyjs/middy/pull/561

While debugging the problem I found the proposed solution works well in a single service repo. However, if you try to use module in `monorepo` it starts breaking with webpack (haven't tested without webpack). The main reason for that is that webpack creates a [require context](https://webpack.js.org/guides/dependency-management/#context-module-api) and tries to process all the files matching regex, in this case, it is `sync ^ajv\-.*$`.  That start breaking:

- when you have large mono repos it can take a few minutes to build and requires a lot of memory 6GB
- when dependency are added inside other dependencies that results in the error that you can see in the example repository
- because resolution uses relative directory structure it may not refer to `module` 

IMO adding modules explicitly could be a better option. What do you think about it? I'm happy to contribute if you see that as a viable solution.

What versions of software are you using?
----------------------------------------
**Node.js Version:** - v12.16.3

**Middy Version:** - 1.4.0

**AWS SDK Version:**  - N/A

**Comment by willfarrell** [comment]
I remember this change and the solution never felt quite right. The idea was to not include dependencies not required for "performance" but the lazy load just got hacky. I've addressed this in v2 thanks to ajv latest major version (v7) which was a complete refactor. You could use an older version of the middleware before the change, it should work just fine.

https://github.com/willfarrell/middy/blob/release/2.x/packages/validator/index.js
