### ISSUE TITLE
Move `@types/aws-lambda` to devDependencies

### ISSUE THREAD

**Issue by baileytincher** [middyjs/middy#566]
https://github.com/middyjs/middy/blob/e17f9a410d799b0aee5ac0bc6be7a83055c82bbe/packages/core/package.json#L39

Semantics issue, but since typedefs get compiled out when you build with Babel it makes more sense to leave them in devDependencies. At the moment serverless throws warnings even though it isn't a true dependency.

**Comment by willfarrell** [comment]
I'm open to a PR for this.

**Comment by jirayui** [comment]
Is it fixed yet?

**Comment by willfarrell** [comment]
Will be in next release
