### ISSUE TITLE
Explicitly set error handler content-type to text plain

### ISSUE THREAD

**Issue by gpoole** [middyjs/middy#568]
I'm not sure if this is a bug caused by using Middy with Serverless, but I think the error handler needs to explicitly set the response `Content-Type` header to `text/plain`, as currently I see it as `application/json`.

What are the steps to reproduce this issue?
-------------------------------------------
Set up Middy with Serverless framework and the following handler:

```js
// handler.js
const middy = require('@middy/core');
const httpErrorHandler = require('@middy/http-error-handler');

class CustomError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 403;
  }
}

module.exports.error = middy(async () => {
  throw new CustomError('an error');
}).use(httpErrorHandler());

```

The Serverless config is:

```yml
#serverless.yml

functions:
  ping:
    handler: handler.error
    events:
      - http:
          path: error
          method: get
```

What happens?
-------------

I get the following response:

```http
HTTP/1.1 403 Forbidden
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 8
Date: Mon, 19 Oct 2020 06:15:06 GMT
Connection: close

an error
```

What were you expecting to happen?
----------------------------------
The content-type should be `text/plain` instead of `application/json`.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 12.16.1

**Middy Version:** 1.4.0

**Serverless Version:** 2.6.0

**AWS SDK Version:** 2.771.0

**Comment by willfarrell** [comment]
Good catch, I'd be open to adding in an option to set the content-type or even better adding in logic to detect if json, if not fallback to `plain/text`. Changing it to `text/plain` always would be considered a breaking change. Would you be open to submitting a PR?

Personally, I usually run a custom error middleware to give me more control over how it's returned (ie using jsonapi or Odata). So haven't run into this.

For those wanting to use the above module w/ json, try something like `throw new CustomError('{"type":"error", "code":"403", "message":"---"}');`

**Comment by gpoole** [comment]
Sure, could you outline the logic you'd expect for detecting JSON @willfarrell? My thinking with it always being set to `text/plain` was mainly that the current logic is strictly only ever outputting the error message, which for most exceptions is a plain text string.

My take would be an option to the middleware like you mentioned:

```js
class CustomError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 403;
    this.additionalField = "hello"
  }
}

module.exports.error = middy(async () => {
  throw new CustomError('an error');
}).use(httpErrorHandler({ json: true }));
```

And the response logic might be updated to something like:

```js
let body;
if (json) {
  body = JSON.stringify({
    ...error,
    message: error.message
  });
} else {
  body = error.message;
}
```

The output for that error being this:

```
HTTP/1.1 403 Forbidden
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 8
Connection: close

{"statusCode":403,"additionalField":"hello","message":"an error"}'
```

What do you think?

**Comment by willfarrell** [comment]
Thanks for putting this together. I did some research into `fetch` and other into how they handle this. This would be way less of a breaking change than originally expected. Because of this, I don't think we need to detect json as a special case (`try { JSON.parse(str)}catch(e){}` is a way one could detect json). 

With that, I think we change the default `contentType` to `plain/text`, but add in an option to override `contentType` for those that are using customized error handling.
