### ISSUE TITLE
[@middy/ssm] [feature] Add the ability to assume a role before retrieving SSM parameters

### ISSUE THREAD

**Issue by dragosmc** [middyjs/middy#569]
I'm opening this issue as I want to gather some opinions and views on the following feature: allow the possibility of assuming a role before fetching SSM parameters. This feature might not be that popular, but in some cases, a lambda could be requiring the use of SSM parameters stored in a different AWS account, achieved through assuming a role in that account.

Currently, the `@middy/ssm` component allows users to pass AWS credentials to the SSM client, including temporary credentials from assuming roles. Although the work of fetching temporary credentials can be done in a wrapper like 

```
.use(((assumeRoleParameters) => {
    return {
        before: (handler, next) => {
            sts.assumeRole(params).then(assumedRole => {
                ssm({
                    cache: true,
                    names: {
                        MY_PARAMETER: '/my/parameter'
                    },
                    awsSdkOptions: {
                        credentials: {
                            accessKeyId: assumedRole.Credentials.AccessKeyId,
                            secretAccessKey: assumedRole.Credentials.SecretAccessKey,
                            sessionToken: assumedRole.Credentials.SessionToken
                        }
                    }
                }).before(handler, next);
            }
        }
    }
})())
```
it's obvious that lot of such duplicate code would have been written by people who need this feature. (this is just a hack and it doesn't allow, in its current form, to pass down the parameters required by the ssm middleware).

Since this could be reused by different lambdas in different projects I'm proposing the following change to the ssm middleware parameter interface.

What were you expecting to happen?
----------------------------------
The proposed solution is to augment the current `ISSMOptions` interface with the addition of an `assumeRoleArn` parameter.

```
interface ISSMOptions {
  onChange?: () => void;
  cache?: boolean;
  cacheExpiryInMillis?: number;
  paths?: { [key: string]: string; };
  names?: { [key: string]: string; };
  awsSdkOptions?: Partial<SSM.Types.ClientConfiguration>;
  setToContext?: boolean;
  paramsLoaded?: Boolean;
  getParamNameFromPath?: (path: string, name: string, prefix: string) => string;
  stsOptions?: ISTSOptions; 
}

interface ISTSOptions {
  assumeRoleOptions: Partial<STS.Types.AssumeRoleRequest>;
  awsSdkOptions?: Partial<STS.Types.ClientConfiguration>
}
```
If the new `stsOptions` is present, a call to STS will be done to fetch the temporary credentials that will then be injected in the `awsSdkOptions`. 

Any other comments?
-------------------
Given the AWS SDK is already a dependency of the `@middy/ssm` I see no changes in terms of packet size for users that don't require this feature.

This is something I work on at the moment, and I'm willing to submit as a PR to the main `@middy` project. If this is something that is out of scope for the current `@middy/ssm` I shall raise a PR for a community maintained middleware.

- :heavy_check_mark: willing to submit a PR

What versions of software are you using?
----------------------------------------
**Middy Version:** 1.4.0

**Comment by willfarrell** [comment]
Interesting use case, I'm wondering if a separate middleware might have more value to other use cases in the future. ie Secrets manager, SQS. What are your thought on this?

**Comment by dragosmc** [comment]
Yes, I was thinking about this as well, but the way the middlewares are written, especially the `ssm` one, we would end up with an implicit dependency between them. For example, in the `ssm` middleware there is no way to pass properties down from a previous middleware, in this case `sts`, and the pattern would have to be the same: either write the temporary credentials as environment variables or put them in the context. Either way, this creates an implicit and immutable dependency between `sts` and `ssm` since the user can't change the internals of `ssm` to specify how and where the middleware looks for the temporary credentials. (what if that environment variable clashes with another user-defined one; also, what if the user doesn't want to write the temporary credentials anywhere due to security reasons?). Unless I'm mistaken I believe there is no way to address those concerns with two separate middlewares.

Regarding Secrets Manager and SQS, and other AWS services, I assume it depends on the patterns. An `sts` middleware does make sense to be used within the main lambda, but I'm afraid it'll just be the same scenario I described above if it needs to be used with other middlewares.

Another thought I had was to create a new middleware called `ssm-enhanced` (or something along those lines) which is basically the code I've posted in my the issue description that wraps the `ssm` middleware. If this makes sense I am then wondering if it's worth having it in the main repo, or as a community-supported middleware?

**Comment by dragosmc** [comment]
@willfarrell any thoughts on the above? I'm currently holding the merge until we find the best solution for this. Thanks :)

**Comment by willfarrell** [comment]
This pattern you describe above already exists with `secret-manager` and `db-manager`. In this case RDS creds are stores in  `secret-manager` and are passed into `db-manager` middleware. Currently, there is an option to delete the secrets in `db-manager`. I see your request as a very similar pattern to this, and have set a precedent on how it can be handled. To be consistent and keep code size down for the most common use cases, I'll have to say that we should go with keeping them separate. Those that need to assume roles, more advanced users, are more likely to read the docs in detail and understand that they need an extra middleware to cover their edge case.

Proposal:
- [ ] `sts` will takes a `roles` object something like:`{ 'keyName':'RoleArn'}`. this allows for a simple mapping to the `context.sts` or `context.credentials`. This will also allow people to request multiple roles and use them for different middleware if they choose. An alternative idea here is that it only requests a single role and the middleware is used multiple times right before it is used. This would be more secure.
- [ ] `ssm` adds in an option to pass in a credentials object `stsRole`. I'm open to a good name for it. Where the value would map to the keyName above.
- [ ] `ssm` adds in a `removeSecrets` option that will delete that specific `sts` credential object when `stsRole` and `removeSecrets` are truthy, as seen at the end of the db-manage middleware.

This pattern could then be applied to other middleware easily and consistently

What do you think overall? What are your thoughts on the alternative for `sts`? It would simplify the codebase. When requesting sts can you request multiple roles at once to save on request latency?

**Comment by willfarrell** [comment]
So I wrote it, still in development and needs lots of testing, but I think I have the idea mostly there. I'm putting it into middy v2 for whenever node 14 is released on AWS.

Sneak peek at: https://github.com/willfarrell/middy/blob/release/2.x/packages/sts/index.js => https://github.com/willfarrell/middy/blob/release/2.x/packages/ssm/index.js

**Comment by willfarrell** [comment]
@dragosmc I'm working on a `sts` middleware for v2. Use case question for you. Do you ever see someone needing to request multiple roles for later use?

**Comment by dragosmc** [comment]
Hi @willfarrell ,

Unfortunately, I cannot view the 2 files you posted before. Regarding your question about `sts` I do not have this requirement now, but I can see a use case in which a user would want to have a lambda that orchestrates various other services from other accounts. At the same time, though, I am not sure how sought after that feature will be given even the feature in this issue is not something others have asked for.

**Comment by willfarrell** [comment]
Thanks for the reply, this is helpful feedback. I'll leave it in for now. Hopefully someone will find it useful one day. It did require an extra hook for other middleware downstream so I'm glad I added it in now for this specific use case.
