### ISSUE TITLE
[Question] Why are errors without a statusCode ignored?

### ISSUE THREAD

**Issue by zvictor** [middyjs/middy#575]
I noticed some of the errors in my lambda functions were going "unnoticed", so I tried running the following: 
 
```js
module.exports = middy((event, context) => {
  throw new Error('hello world!')
}).use(httpErrorHandler())
```

Which then produces an object like below:
```json
{"errorType":"Error","errorMessage":"hello world!","stack":["Error: hello world!","    at Object.handler (/var/task/index.js:25:9)","    at /var/task/node_modules/@my-lambda/lambda-wrapper/node_modules/@middy/core/index.js:190:44","    at runNext (/var/task/node_modules/@my-lambda/lambda-wrapper/node_modules/@middy/core/index.js:93:14)","    at runMiddlewares (/var/task/node_modules/@my-lambda/lambda-wrapper/node_modules/@middy/core/index.js:99:3)","    at /var/task/node_modules/@my-lambda/lambda-wrapper/node_modules/@middy/core/index.js:173:7","    at new Promise (<anonymous>)","    at Runtime.instance [as handler] (/var/task/node_modules/@my-lambda/lambda-wrapper/node_modules/@middy/core/index.js:159:26)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
```

This object doesn't contain a `statusCode`, which is a prerequisite for `@middy/http-error-handler`:
https://github.com/middyjs/middy/blob/122ab43ca3cfa47a962de1fb84ecf9cb97fad594/packages/http-error-handler/index.js#L12

---

Why does `@middy/http-error-handler` ignore errors with no `statusCode` defined? I assume there is a proper reason why the community decided to go that way and I would like to understand the thoughts behind that 🙂

**Comment by willfarrell** [comment]
This predates me, @lmammino do you remember?

**Comment by willfarrell** [comment]
After reviewing the codebase for middy v2, I believe it because this is an `http` error handler and not a general error handler.

**Comment by zvictor** [comment]
Right, that makes sense. Thanks for taking a look into that!

Now the question becomes: Should Middy have yet another but more generic error handler? Something that wraps the HttpErrorHandler but also treats other types of errors, avoiding a "silent error" scenario?

Just for reference, that's what I am currently using to achieve such goal:
```js
    .use({
      onError: (handler, next) => {
        if (handler.error && !handler.error.statusCode) {
          handler.error.statusCode = 500
        }

        return next(handler.error)
      },
    })
    .use(httpErrorHandler())
```

**Comment by willfarrell** [comment]
I don't think we need yet another middleware. I just learned about inline middlewares today, making that even smaller still.

```js
.use(...)
.onError((handler, next) => {
        if (handler.error && !handler.error.statusCode) {
          handler.error.statusCode = 500
        }

        return next(handler.error)
      })
.use(...)

```

**Comment by zvictor** [comment]
That's cool! And I agree that we don't need yet another middleware just for this use case, but I would change my mind if more use cases arise related to this topic.

Overall I understand that httpErrorHandler should not do tasks beyond its intended scope, but at the end of the day it's also important that middy presents itself as a straightforward and cohesive api that covers basic needs. Standardising how errors are handled falls into  "_Convention over configuration_", which creates unity and keeps the community moving together.

**Comment by zvictor** [comment]
And although I am fine with the presented solution, I would like to ask your opinion on one more alternative.
What do you think of adding an option to the HttpErrorHandler to make it catch all errors?

```js
.use(httpErrorHandler({ catchAllErrors: true }))
```

It could be called something else: `catchNonHttp`, `convertNonHttp`, `catchGenericErrors` ...
It could also be a fallback function instead, giving us the chance to take action instead of just ignoring the error:

```js
.use(httpErrorHandler({  fallback: (e) => { error.statusCode = 500 } }))
```

**Comment by willfarrell** [comment]
I was thinking about this before bed. I think we do need a hook to catch all. I opted for `fallbackMessage`

How about this: https://github.com/willfarrell/middy/blob/release/2.x/packages/http-error-handler/index.js

**Comment by zvictor** [comment]
It looks good, but I added some comments directly at the [commit](https://github.com/willfarrell/middy/commit/d925eb2a5825d0b419fa557dcc63e1642c345bf9)
