### ISSUE TITLE
Better example showing how to get httpMultipartBodyParser to upload file both in lambda and offline

### ISSUE THREAD

**Issue by tom-thorne** [middyjs/middy#576]
Is there a complete example that shows how to use serverless and httpMultipartBodyParser to upload a binary file via AWS Api Gateway and Lambda, and that works both on Lambda and in offline mode using serverless-offline?  The current example here https://github.com/middyjs/middy/tree/master/packages/http-multipart-body-parser only shows a simple key value example that is already base64 encoded.

Is there an example that shows this uploading a binary file in offline mode testing from POSTMAN or curl?

My endpoint works fine with the simple example or simple text form data, but when I try and sending a binary file from POSTMAN, I get 400 Bad Request and my handler isn't called

I am guessing I have to simulate what the API Gateway is doing and encode the multipart request as base64 - but how?

**Comment by tom-thorne** [comment]
Turns out that there is an issue with POSTMAN.  Using the equivalent `curl` command works fine.

**Comment by willfarrell** [comment]
Glad you were able to resolve this.
