### ISSUE TITLE
[Question] Best way of passing data to the next middleware?

### ISSUE THREAD

**Issue by jdiegosierra** [middyjs/middy#577]
As we know in Express.js [there is an object](http://expressjs.com/en/api.html#res.locals) that contains local variables so we can use it to passing data to the next middlewares. My first approach with middy is to use a reserved field in the event. However I'm wondering if there is a better solution... What do you think?

```javascript
const validateUserMiddleware = () => ({
  before: async (handler, next) => {
    handler.event.locals.userInfo = decipherToken(handler.event.token);
    next();
  },
});
```

**Comment by willfarrell** [comment]
There is a `context` object that gets passed to the handler. I would suggest adding your local variables to that.

**Comment by MrRhodes** [comment]
This may be something that is being addressed with the Typescript changes coming into V2, but do you need to define a custom context type in your handler that will expect this changes you're adding to context?

**Comment by willfarrell** [comment]
In v2 we added in a new way for sharing data only with other middleware. This was implemented to prevent the pollution of `context` and to prevent secrets from leaking into the baseHandler. `handler.internal` can be used and has a `util` function `getInternal` to can resolve promises and pull nested values if so desired. Its lifecycle and scope is a single request.
