### ISSUE TITLE
Typescript docs + example

### ISSUE THREAD

**Issue by StErMi** [middyjs/middy#578]
Hi everyone, I'm new to middy and I would like to create an official middleware for MikroORM (a typescript ORM I'm using). I'm using typescript on my project but I cannot find any typescript example on how to correctly use middleware with typings and lambda or an example of custom middleware developed with typescript. Is there someone that has already done that and can share some example/process?

**Comment by willfarrell** [comment]
Hi, glad to hear your building a middleware to share with others. Besides checking out our existing middleware that do support typescript, I can't offer any additional support. All of our TypeScript code/docs are full community driven. When you're done your middleware, you are welcome to add an example to our documentation for others. I'd be happy to merge that PR.
