### ISSUE TITLE
Correctly handle error with JSON body

### ISSUE THREAD

**Issue by StErMi** [middyjs/middy#579]
I would like to handle the handler response with errors in this format:

```
{
    statusCode: statusCode,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Credentials': true,
      'Access-Control-Allow-Headers': 'Authorization'
    },
    body: JSON.stringify(body)
  }
``` 

is it possible to do that with middy? I've tried to use the `httpErrorHandler` middleware but it seems to not support it

**Comment by willfarrell** [comment]
`httpErrorHandler` is super simple by design, most need something custom allowing `httpErrorHandler` to be used as an example to build off of. Also checkout the `cors` middleware.
