### ISSUE TITLE
Show onError execution order

### ISSUE THREAD

**Issue by Eomm** [middyjs/middy#580]
Hi,
I'm not good in design, but I would like to ask if it worth for you extending the actual "onion-image" to show the `onError` processing too?

An awful example:

![image](https://user-images.githubusercontent.com/11404065/100379073-99a2e200-3014-11eb-9a9b-3f5e3a98e90a.png)

**Comment by willfarrell** [comment]
Something like this?
<img width="723" alt="Screen Shot 2020-12-28 at 23 19 36" src="https://user-images.githubusercontent.com/1097020/103262790-2ff35c00-4963-11eb-9845-7a8fb743c31c.png">

**Comment by Eomm** [comment]
This is really nice!

I would just improve the message that whenever the error happens in the `before` or `after` stage the `onError` process is the same, maybe by removing the dotted line on the `onError` line?

**Comment by willfarrell** [comment]
Good call, I think we have it.
<img width="685" alt="Screen Shot 2020-12-29 at 01 40 40" src="https://user-images.githubusercontent.com/1097020/103271257-f298c980-4976-11eb-822c-d0c6ae9495e3.png">

**Comment by willfarrell** [comment]
I've included in the v2 docs along with the `.sketch` file if you'd like it in vector format. https://github.com/willfarrell/middy/tree/release/2.x/docs/img

**Comment by Eomm** [comment]
Thanks a lot!
