### ISSUE TITLE
Bundle type definitions with packages instead of definitely-typed

### ISSUE THREAD

**Issue by baileytincher** [middyjs/middy#591]
A mild nuance, but since the type definitions for middy are maintained by middy it is recommended to bundle with source https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Hopefully this could further simplify deployments

**Comment by willfarrell** [comment]
I have no plans on removing the type definitions from the packages. Are you referring to `@types/middy` comment? If bundled with the code is recommended then we'll keep doing that.
