### ISSUE TITLE
New Middleware Proposal: DynamoDB

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#595]
Proposal for a new DynamoDB middleware that could pull string or json from a DynamoDB index and store to internal.

See `ssm` for what it could look like: https://github.com/middyjs/middy/tree/main/packages/ssm

Please 👍🏻  this issue if it would have value to you. I'll build it if there > 10 👍🏻

If you can comment with your use case below, that would be helpful.

**Comment by jcandrade** [comment]
Authentication/authorization ✌🏻

**Comment by willfarrell** [comment]
@jcandrade would you like to expand on your use case? Maybe with an example on what you're thinking?

**Comment by willfarrell** [comment]
Closing, been year without enough interest. Happy to add a community middleware if someone has one they can share.

**Comment by willfarrell** [comment]
Re-opening based on a comment from the powertools team (https://github.com/middyjs/middy/issues/948#issuecomment-1336476055).

**Comment by KillDozerX2** [comment]
I think this makes sense. We use one internally at Oneforce and Distinction Dev, but we're still on middy v2

**Comment by willfarrell** [comment]
I've created PR #963 for this. Please feel free to comment or contribute types.
