### ISSUE TITLE
Plugin Support Proposal

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#599]
Currently, there is support for a profiler ([PROFILING.md](https://github.com/middyjs/middy/blob/release/2.x/docs/PROFILING.md)). This does not need to ship in v2, but would be nice to have.

@lmammino has proposed a plugin approach (something like `middy(handler).plugin(timeProfiler)`) which I'm warming up to. There is also a hook approach outlined by fastify https://www.fastify.io/docs/latest/Hooks/

Opening up the discussion here to hear what everyone else thinks, and what use case you might have for such a functionality.

**Comment by baileytincher** [comment]
I would be in support of the plugin approach, however, I don't see how there would be any functional difference between it and hooks. Semantically calling it plugins would fit with the patterns the Serverless Framework uses.

When I first started using Middy the main concern of the project seemed to have been remaining as lightweight as possible. V2 is introducing a lot of cool new features, but how much overhead is that going to add and should that be a concern at all?

**Comment by willfarrell** [comment]
Thanks for your feedback @baileytincher. Keeping middy light weight is super important to us. The key focus for v2 is performance and security by default without compromising developer experience. I think this has been met up to now.

As for overhead, this does add in some extra optional chaining statements (basically boolean if statements) to where the hooks are. For optimal performance developer should be bundling lambda packages, removing any unused code like these hooks.

**Comment by willfarrell** [comment]
After discussions with @lmammino, we've decided we're going to keep how the profiler gets attached to middy (`middy(handler, profiler)`). We see value in allowing multiple profilers, however we want to know how the community uses these hooks first before adding in extra code to handler multiple profilers first. So, if you have a use case, please share.

The names of the hooks have been updated to be more descriptive (beforePrefetch, requestStart, beforeMiddleware, afterMiddleware, beforeHandler, afterHandler, requestEnd). To allow the ability to send logs/metrics elsewhere, `requestEnd` will resolve before the response is returned.

More feedback on this is welcome.

**Comment by baileytincher** [comment]
Why would a different pattern from how multiple middlewares are applied be necessary for profilers? Conceptually they seem rather similar

**Comment by nponeccop** [comment]
Your https://github.com/middyjs/middy/blob/main/docs/PROFILING.md link in the post is broken.

**Comment by willfarrell** [comment]
@nponeccop Thanks, it's been reported in #638
