### ISSUE TITLE
New Middleware Proposal: WebSockets Response

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#602]
Proposal to add in a middleware to manage websocket responses through API Gateway.

Please 👍🏻 this issue if it would have value to you.

If you can comment with your use case below, that would be helpful.

Ref:
- https://www.youtube.com/watch?v=ZuoZpf3JnY8
- https://ably.com/blog/introducing-the-websocket-handbook

**Comment by KillDozerX2** [comment]
👍🏽
A few questions.

- What are some of the use-cases that you have in mind
- Do you want more help with it?

**Comment by willfarrell** [comment]
At DataStream.org we process large dataset files. I was thinking for the next iteration of our app (whenever that happens) that we could use ws to push progress indicators. Browser push notifications may also work, but I haven't used them before, and may have extra costs. Lots of scoping to do still.

I'm always looking for help. If you have a more near term use case you're welcome start a PR.

**Comment by KillDozerX2** [comment]
We had a simpler use case where we take the response body and use the connection ID from the event, stringify it and send it to the user

**Comment by willfarrell** [comment]
Closing, see PR #787
