### ISSUE TITLE
lambda goes in timeout because it's stuck on ssm fetching parameters

### ISSUE THREAD

**Issue by allemanfredi** [middyjs/middy#608]
Hello guys, i'm having problems with `ssm`.

What are the steps to reproduce this issue?
-------------------------------------------
```js
const authorize = async (_event, _context) => {
  try {
    return {
      statusCode: 200,
      body: JSON.stringify(true)
    }
  } catch (_err) {
    console.error(_err)
    return {
      statusCode: 500,
      body: 'error'
    }
  }
}

export default middy(authorize)
  .use(warmup({ waitForEmptyEventLoop: false }))
  .use(doNotWaitForEmptyEventLoop({ runOnError: true }))
  .use(httpSecurityHeaders())
  .use(
    ssm({
      cache: true,
      names: {
        cacheHost: process.env.SSM_CACHE_HOST,
        cachePort: process.env.SSM_CACHE_PORT
      },
      setToContext: true,
    })
  )
```

What happens?
-------------
Essentially what happens is that (randomly) the lambda times out and it looks like it's a `ssm` problem.

Any logs, error output, etc?
----------------------------

```
2021-01-28T22:48:39.412+01:00 | START RequestId: 2c691dce-092f-4523-a56c-fada075d57de Version: $LATEST
-- | --
  | 2021-01-28T22:49:09.445+01:00 | END RequestId: 2c691dce-092f-4523-a56c-fada075d57de
  | 2021-01-28T22:49:09.445+01:00 | REPORT RequestId: 2c691dce-092f-4523-a56c-fada075d57de Duration: 30030.37 ms Billed Duration: 30000 ms Memory Size: 512 MB Max Memory Used: 47 MB
```

What versions of software are you using?
----------------------------------------
**Node.js Version:** 12.x

**Middy Version:** 1.4.0

**AWS SDK Version:** 2.771.0

**Comment by willfarrell** [comment]
From what you've described, it sounds like an AWS issue. I would open a support ticket. You're only requesting 2 params and it randomly times out. You could try creating your own ssm request in the originalHandler to test and see.

**Comment by allemanfredi** [comment]
@willfarrell Thanks for your response, do you mean of using aws-sdk function to fetch a ssm parameter instead of using `middy-ssm`?

**Comment by willfarrell** [comment]
Yep. Just to test if it's middy or something in your AWS env. Or keep it (less code is always faster :))

You can use this as a start:
```js
const SSM = require('aws-sdk/clients/ssm.js')

const client = new SSM()
await client
        .getParameters({ Names:[...], WithDecryption: true })
        .promise()
      .then(resp => {
          if (resp.InvalidParameters?.length) {
            throw new Error(
              `InvalidParameters present: ${resp.InvalidParameters.join(', ')}`
            )
          }
          return Object.assign(
            ...resp.Parameters.map(param => {
              // Don't sanitize key, mapped to set value in options
              return { [param.Name]: parseValue(param) }
            })
          )
        })
```

**Comment by allemanfredi** [comment]
@willfarrell thanks a lot! in the meantime i tried this code and it never goes in timeout
```js
const authorize = async (_event, _context) => {
  try {

    const ssm = new SSM({
      maxRetries: 6, // lowers a chance to hit service rate limits, default is 3
      retryDelayOptions: { base: 200 }
    })

    const params = {
      Names: [process.env.SSM_CACHE_HOST, process.env.SSM_CACHE_PORT],
      WithDecryption: true
    }

    const fetch = () => new Promise(resolve => {
      ssm.getParameters(params, function(err, data) {
        if (err) resolve(err, err.stack); // an error occurred
        else     resolve(data);           // successful response
      })
    })

    const res = await fetch()

    return {
      statusCode: 200,
      body: JSON.stringify(res)
    }
  } catch (_err) {
    console.error(_err)
    return {
      statusCode: 500,
      body: 'error'
    }
  }
}

export default middy(authorize)
  .use(warmup({ waitForEmptyEventLoop: false }))
  .use(doNotWaitForEmptyEventLoop({ runOnError: true }))
  .use(httpSecurityHeaders())
```

**Comment by willfarrell** [comment]
Interesting. Now I'm curious if the v2 implementation is affected by this mysterious issue.

PS Also curious why you're using warmup over provisioned concurrency.

**Comment by allemanfredi** [comment]
@willfarrell Thanks! in theory i reverted back to warmup from provisioned concurrency because i had some problems, where do you see that i'm using provisioned concurrency?

**Comment by allemanfredi** [comment]
I don't know if [this](https://stackoverflow.com/questions/65951537/aws-lambda-ssm-calls-randomly-goes-in-timeout) solves the problem but after having changed from 

```js
const ssm = new SSM({
      maxRetries: 6, // lowers a chance to hit service rate limits, default is 3
      retryDelayOptions: { base: 200 }
    })
```

to:

```js
const ssm = new SSM()
```

it seems to work better!

**Comment by allemanfredi** [comment]
Could be [this](https://stackoverflow.com/questions/65951537/aws-lambda-ssm-calls-randomly-goes-in-timeout) solves the error?

**Comment by willfarrell** [comment]
We've deprecated the warmup middleware in v2 so when I see someone using it I have to ask. Just in case I missed a usecase that could justify keeping it. 

Interesting, looking forward to the follow up questions. I think there is value in adding a note into the docs around this. Sounds like you're confirmed it's some limit being hit in your environment. X-Ray might be able to help in this case.

@lmammino do you recall when these preferred setting were put in place for `SSM` (see below)? I'm thinking there may be value in removing them and documenting this use case instead. Thoughts?

```
{
    maxRetries: 6, // lowers a chance to hit service rate limits, default is 3
    retryDelayOptions: { base: 200 } // default is 100
  }
```
