### ISSUE TITLE
Can't install @middy/validator in a Lambda environment due to using Node 12.20.1

### ISSUE THREAD

**Issue by ffxsam** [middyjs/middy#609]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. `yarn add @middy/validator`

What happens?
-------------
`error @middy/validator@2.0.0-alpha.2: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.20.1"`

What were you expecting to happen?
----------------------------------
I definitely didn't expect a Node >= 14 requirement, since Lambda is running 12.x.

**Node.js Version:**
12.20.1

**Middy Version:** …
@middy/core@1.5.2
@middy/validator@2.0.0-alpha.2

**AWS SDK Version:** …
n/a

**Comment by willfarrell** [comment]
Thanks for reporting. I think it's just the package.json preventing node v12 from when I first started the rewrite. I'll push an update later today.

**Comment by ffxsam** [comment]
@willfarrell Awesome, thanks!

**Comment by willfarrell** [comment]
Should be deployed now. Let me know if it's still not working.

**Comment by willfarrell** [comment]
FYI You can't use `@middy/validator@v2.x` with `@middy/core@v1.x`. They all need to be the same major version.

**Comment by ffxsam** [comment]
Got it - thank you!
