### ISSUE TITLE
clc : Continuation Local Storage

### ISSUE THREAD

**Issue by antoinechamot** [middyjs/middy#620]
I use https://www.npmjs.com/package/node-cls to propagate context through async call. But it seems that the context is lost when i use middy middlewares. Is there a way to propagate such context with middy ?

**Comment by willfarrell** [comment]
Can you share a simple code example with an expected output?

**Comment by antoinechamot** [comment]
Lets say i have a simple middleware to set a context linked to my request

const cls = require("node-cls");

module.exports = ({ logger = console } = {}) => ({
  before: (handler, next) => {
    let context = cls.create("myContext");
    context.name = "George";
    return next();
  },
  after: (handler, next) => {
    console.log(cls.get("myContext").name);
    return next();
  },
});

This will result in an error as the context is not propagated by middy. When i do it with express i have no problem and my context is propagated.  I typically use it to implement the MDC pattern on logging

**Comment by willfarrell** [comment]
I can't comment on `node-cls` as I've never used it. Based on your example I fail to see how middy is expected to propagate your custom context or how it could prevent it from working as expected. However, I don't think this dependency is needed for your example.

You can use the lambda context:
```js
const defaults = {
  logger: console
}
module.exports = (opts) => {
  const options = {...defaults, ...opts}
  return ({
    before: (handler) => {
      handler.context.myContext = {name: 'George'}
    },
    after: (handler) => {
      options.logger.log(handler.context.myContext.name)
    }
  })
}
```

Alternatively, if you wanted a private context within this middleware you could create a variable at the same level at options. Or share with all just the middleware using `handler.internal` in middy v2.

Note: in middy v2 `next` has been deprecated.

**Comment by antoinechamot** [comment]
The solution you propose is not as elegant as using async hook as i need to pass the object context myself everywhere i want to use it which is really annoying. 
But by checking the way this framework is build it seem to prevents propagation  with async hook so i have no other choice or switch to another framework

**Comment by willfarrell** [comment]
Sorry middy isn't able to meet your needs right now. I'm not familiar with async hooks, probably because it's still experimental in node. I'll keep it in mind for future versions. Thanks for sharing your use case.
