### ISSUE TITLE
Should input-output-logger also implement onError?

### ISSUE THREAD

**Issue by bboure** [middyjs/middy#621]
Hi,

I am using the [input-output-logger](https://github.com/middyjs/middy/tree/master/packages/input-output-logger), but I also have a custom middleware that catches and handles errors.
I noticed that when an error is caught and handled, I do not get any output (response) log. I would expect the generated response from the error handler to still be logged.

To put an example, a common and similar use case for that would probably be when using the `http-error-handler`. One might still expect to see an output log like the following:

```
{
  response: {
    statusCode: 404,
    body: "Not Found",
  }
}
```

Since the `after` middlewares are not being called when an error is thrown, the generated response is never logged by `input-output-logger`

Of course, there is the `error-logger`, but IMHO, it's not the same. I expect to see the actual `handler.response` content.

I was wondering if it would make sense to change the `input-outout-logger` and add something like this:

(untested, speudocode)
```ts
    onError: (handler, next) => {
      if (handler.__handledError && typeof logger === 'function') {
          omitAndLog({ response: handler.response })
      }

      return next()
    },
```

By placing it further down the middleware chain, it would log responses after a handled Error.

If that is something that makes sense to you and that you might consider, I'd be happy to open a PR.

Thank you!

**Comment by willfarrell** [comment]
Thanks for reporting. This use case is addressed in v2 which is currently in alpha (soon to be beta). Does this meet your needs? https://github.com/middyjs/middy/blob/release/2.x/packages/input-output-logger/index.js
