### ISSUE TITLE
Typescript issue with v2 Beta 1: This expression is not callable

### ISSUE THREAD

**Issue by markcarroll** [middyjs/middy#628]
Installed v2 Beta 1 and converted middleware functions over to new mechanism, all good. 

However, with current Typescript definition it is not possible to locally execute the handler function, either from a local file to debug, or from unit tests, without getting a Typescript error: 
```
This expression is not callable.
  Type 'MiddyfiedHandler<APIGatewayProxyEvent, APIGatewayProxyResult, Error>' has no call signatures.
```

I _believe_ the issue is that the Typescript definition of the MiddyfiedHandler does not extend the Lambda Handler so is not a callable function. 

To fix this I have changed the Typescript definition from:
```ts
interface MiddyfiedHandler<TEvent = any, TResult = any, TErr = Error> {
  use: UseFn<TEvent, TResult, TErr>
  applyMiddleware: AttachMiddlewareObj<TEvent, TResult, TErr>
  before: AttachMiddlewareFn<TEvent, TResult, TErr>
  after: AttachMiddlewareFn<TEvent, TResult, TErr>
  onError: AttachMiddlewareFn<TEvent, TResult, TErr>
  __middlewares: {
    before: Array<MiddlewareFn<TEvent, TResult, TErr>>
    after: Array<MiddlewareFn<TEvent, TResult, TErr>>
    onError: Array<MiddlewareFn<TEvent, TResult, TErr>>
  }
} 
```
to
```ts
interface MiddyfiedHandler<TEvent = any, TResult = any, TErr = Error> extends LambdaHandler<TEvent, TResult>{
  use: UseFn<TEvent, TResult, TErr>
  applyMiddleware: AttachMiddlewareObj<TEvent, TResult, TErr>
  before: AttachMiddlewareFn<TEvent, TResult, TErr>
  after: AttachMiddlewareFn<TEvent, TResult, TErr>
  onError: AttachMiddlewareFn<TEvent, TResult, TErr>
  __middlewares: {
    before: Array<MiddlewareFn<TEvent, TResult, TErr>>
    after: Array<MiddlewareFn<TEvent, TResult, TErr>>
    onError: Array<MiddlewareFn<TEvent, TResult, TErr>>
  }
} 
```

and now everything seems to work correctly. 

Can anyone confirm if they have hit this same problem and if this does indeed solve it for everyone?

**Comment by willfarrell** [comment]
Thanks for reporting, @lmammino wrote the definitions so he may be able to comment on this. Would you be willing to open a PR for this?

**Comment by markcarroll** [comment]
Happy to.  I would just like someone else to confirm.
