### ISSUE TITLE
[v2][http-error-handler] cors header went missing after an HttpError is thrown

### ISSUE THREAD

**Issue by leesiongchan** [middyjs/middy#635]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
```javascript
const handler = middy((event, context) => {
  throw new createError.UnprocessableEntity()
});

handler
  .use(httpErrorHandler())
  .use(cors())
```

What happens?
-------------
The cors header is gone!

What were you expecting to happen?
----------------------------------
The cors header should remain.

Any other comments?
-------------------
The [README](https://github.com/middyjs/middy/tree/release/2.x/packages/http-cors) stated to use `httpErrorHandler` before `http-cors`, but it seems that [there is](https://github.com/middyjs/middy/blob/release/2.x/packages/http-error-handler/index.js#L34) a [side-effect](https://github.com/middyjs/middy/blob/release/2.x/packages/util/index.js#L150) will reset the headers after `httpErrorHandler` been executed. And since `httpErrorHandler` will run after `cors` so cors header will be reset after the `httpErrorHandler` middleware been executed.

What versions of software are you using?
----------------------------------------
**Node.js Version:** node14

**Middy Version:** 2.0.0-beta.0

**AWS SDK Version:** …

**Comment by willfarrell** [comment]
Thanks for reporting. I think that note is really old from v0 and no longer applies. I'll remove it.
