### ISSUE TITLE
GitHub Page links resolve to 404

### ISSUE THREAD

**Issue by shellscape** [middyjs/middy#638]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Visit the main site
2. Click on https://middy.js.org/docs/.yarnclean
3. Behold, 404

What happens?
-------------
Zee 404

What were you expecting to happen?
----------------------------------
Zee 200

Any logs, error output, etc?
----------------------------
Nein

Any other comments?
-------------------
I'd be super keen to see the file.

What versions of software are you using?
----------------------------------------
**Node.js Version:** …

**Middy Version:** …

**AWS SDK Version:** …

**Comment by nponeccop** [comment]
Where do you see the broken link?

**Comment by willfarrell** [comment]
Thanks for reporting. We want to redo the GitHub Pages at some point. All of the link should work from the README itself. Did you want to update them to be absolute urls?

**Comment by willfarrell** [comment]
Closing in favour of #780
