### ISSUE TITLE
Lighter and faster middleware

### ISSUE THREAD

**Issue by nponeccop** [middyjs/middy#641]
This is a variation of performance issues reported in #639 

I have a prototype which has faster versions of:

- `@middy-validator` (that is #639)
- ~~`@middy/http-json-body-parser`~~ (already fixed by #643)
- `@middy/http-response-serializer`

It also validates that `@middy/core` and `@middy/http-error-handler` are already fast enough or at least that their performance impact is much less than of the three other middlewares.

The key achievement is that `serverless-offline` reports `Duration: 20 ms` while it's ~250 ms with current `@middy/*`

However the 12x+ achievement doesn't come for free: my versions perform less work than the upstream versions, and they have fewer features. They need to be polished still - e.g. the header issues are solved by hacks and don't work well. And of course we need an official benchmark to catch strange performance regressions in the future.

I guess a nearly zero overhead would be a very nice marketing feature for `@middy`. Of course we'd likely need full-fledged but slower versions too, for those needing extra features, or a way to customize the light middleware to plug in extra functionality. 

These are of course breaking changes, so it's for 3.x

**Comment by willfarrell** [comment]
Looking forward to seeing them when they're ready.

**Comment by willfarrell** [comment]
Pushed some optimizations for `@middy/http-response-serializer` to the main branch. https://github.com/middyjs/middy/commit/5278f7f47cb9fe34169a559a12ad4f3bb2fdf2d0

**Comment by willfarrell** [comment]
Went digging into the flame graphs, Most of `@middy/http-response-serializer` time is spent inside `@hapi/accept`.

I'm going to close this issue. Now that we have tools in place to analyze the perf, there will be more improvements coming this year.
