### ISSUE TITLE
Cold start profiling

### ISSUE THREAD

**Issue by nponeccop** [middyjs/middy#642]
The current doc/PROFILING.md only measures per request performance after a cold start. But in Lambda cold start time is important too. So we need some way to catch major cold start time performance regressions.

How we can test that? For #641 I did completely unscientific testing by looking at the time reported by `serverless-offline`. But there is LocalStack reproducing the runtime environment byte to byte, and many other ways. Is there a general benchmarking tool for AWS Lambda on npm yet?

**Comment by willfarrell** [comment]
I wrote a plugin that I used for testing v2. You can check it out here: https://github.com/middyjs/middy/blob/main/plugin/time.js

It's a start, but not a proper benchmarking tool. Also, check out https://clinicjs.org.

**Comment by willfarrell** [comment]
See PR #649 for a first step towards this.

**Comment by willfarrell** [comment]
Closing for now. Please re-open if you feel we need more.
