### ISSUE TITLE
TS: "import type" doesn't work

### ISSUE THREAD

**Issue by nponeccop** [middyjs/middy#645]
The following TS idiom doesn't work with `@middy/core` because the types are exported using the `namespace` syntax, which is currently reserved for things not coming from explicit modules, such as the `process` object in node.js.

```ts
import type { MiddyfiedHandler } from '@middy/core'
```

So my suggestion is:

- in 2.x, add normal exports in addition to the namespace exports, to preserve backward compatibility
- in 3.x, remove the namespace exports

I can provide a PR at some point. However, right now I'm evaluating the general state of TS support in `@middy`, so I can determine the best course of corrective actions.

**Comment by lmammino** [comment]
Hey @nponeccop, your help on this matter would be highly appreciated. The core middy team doesn't have a hell of a lot of experience with TypeScript. I tried to revamp the typings definition in V2 but, most likely, I did a lot of silly mistakes :)

**Comment by MelvinVermeer** [comment]
I was facing the same issue in a project that I am currently working on. I created this PR to fix the issue. 

A little backstory for people landing here by searching for the specific error:

```ts
export const handler = commonMiddleware(lambdaHandler);
```

Without the fix, TypeScript developers might encounter:

> Exported variable 'handler' has or is using name 'MiddyfiedHandler' from external module "../node_modules/@middy/core/index" but cannot be named.

A quick and dirty work around for this is to add the following import 

```ts
import middy from '@middy/core';
```
