### ISSUE TITLE
New Middleware Proposal: DynamoDB Event

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#652]
Normalize DynamoDB object into flatter representation

https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html

See `sqs-json-body-parser` for what it could look like: https://github.com/middyjs/middy/tree/main/packages/sqs-json-body-parser

Please 👍🏻 this issue if it would have value to you. I'll build it if there > 10 👍🏻

If you can comment with your use case below, that would be helpful.

**Comment by willfarrell** [comment]
will be in v2.1.0

**Comment by ifielder** [comment]
This would be amazing!

**Comment by willfarrell** [comment]
@ifielder It's supported :)
See https://middy.js.org/docs/middlewares/event-normalizer
