### ISSUE TITLE
httpErrorHandler doesn't return the correct error

### ISSUE THREAD

**Issue by rubfergor** [middyjs/middy#653]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a handler and middify it with the following middlewares: 
```
[
    httpHeaderNormalizer(),
    httpContentNegotiation({
      availableMediaTypes: ['application/json'],
      parseMediaTypes: true,
      failOnMismatch: true
    }),
    httpEventNormalizer(),
    httpJsonBodyParser(),
    httpSecurityHeaders(),
    ssm({cacheExpiry: 600000, fetchData: options.parameters, setToEnv: true}),
    eventLogger(),
    httpErrorHandler()
  ];
```
2. Use them on a lambda
3. Whenever the lambda fails, a 502 error is shown, even if we specify another like this:
` throw createError(422, "Validation error");` or `throw new createError.UnprocessableEntity("Validation error")`

What happens?
-------------
Whenever we throw an error, instead of the correct error it gives me:
`{"message": "Internal server error"}` (with status code 502)

What were you expecting to happen?
----------------------------------
It should throw the appropriate error

Any logs, error output, etc?
----------------------------
None, everything seems fine on middy (and the lambda itself runs and throw appropriately)

What versions of software are you using?
----------------------------------------
**Node.js Version:** v14.16.0

**Middy Version:** 2.0.1

**AWS SDK Version:** 2.884.0

**Comment by willfarrell** [comment]
Do you have a stack track from the logs?

**Comment by nponeccop** [comment]
Also, to track lambda runtime failures, it is useful to turn on the ApiGateway logs. There are 502s which happen due to problems outside of the handler, and the `middy` can't catch outside erros as it's inside. Then you collect 2 HTTP Header IDs from your 502 response and search for them in the Lambda and ApiGateway logs respectively.

**Comment by rubfergor** [comment]
I'll have to check if API Gateway is getting logs (it is a CDK app and I'm not sure it is activated by default). I can share the logs I got from the event logger, but as I said, there isn't any error there other than the error the app itself throw (which is correct):

```
2021-04-13T22:38:42.104Z	749346b7-8954-4a4d-960f-6eb95b296b57	ERROR	UnprocessableEntityError:
{"message": "Client KYC data is missing, but your account specify it as needed","code": "missing_client_data" }
at Uv (/libs/src/utils.ts:151:10)
at CGr (/controller.ts:49:11)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at WKr (/handler.ts:38:18)
at /node_modules/@middy/core/index.js:31:30
```

This error get somehow lost and just a 502 internal error is thrown. If the function execute correctly, it returns the correct data, so it does seems to be related to how the error is returned to the gateway that make it crash?

**Comment by rubfergor** [comment]
I think I saw the cause of the error (pun intended). When I throw an error using `createError` from `http-errors`, it gets in the request like this:
```
"error":{"message":"{\n  \"message\": \"Client KYC data is missing, but your account specify it as needed\",\n  \"code\": \"missing_client_data\"\n}"}
```

The error that createError returns doesn't have a `statusCode` in the "error" property, so 
```
if (request.error?.statusCode && request.error?.expose === undefined) {
      request.error.expose = request.error.statusCode < 500
    }
```

Will not set the expose property as true, and even if it did,
```
request.response.statusCode = request.error?.statusCode
``
will always return an undefined statusCode in the request.

I've tried with both `createError(422, {"message": "Client KYC data is missing, but your account specify it as needed","code": "missing_client_data" })` and `new createError.UnprocessableEntitity(JSON.stringify({"message": "Client KYC data is missing, but your account specify it as needed","code": "missing_client_data" }))` with identical results.

It wasn't seeing this errors in 1.5.x, but it seems that http-error isn't propagating the statusCode :/

**Comment by rubfergor** [comment]
My bad, I was logging incorrectly with Pino. Everything seems fine on the request! This is the request it sends to the gateway:
```
{
    headers: {
        'X-DNS-Prefetch-Control': 'off',
        'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
        'X-Download-Options': 'noopen',
        'X-Content-Type-Options': 'nosniff',
        'Referrer-Policy': 'no-referrer',
        'X-Permitted-Cross-Domain-Policies': 'none',
        'Content-Type': 'application/json'
    },
    statusCode: 422,
    body: {
        message: 'Client KYC data is missing, but your account specify it as needed',
        code: 'missing_client_data'
    }
}
```

However, it throws a 502 nevertheless :/

**Comment by rubfergor** [comment]
@willfarrell Just solved it!

You need to stringify the response of the body. I was using finally using this when I noticed:
```
httpErrorHandler(),
    httpResponseSerializer({
      serializers: [
        {
          regex: /^application\/json$/,
          serializer: (request) => JSON.stringify(request.body, null, 2)
        },
        {
          regex: /^text\/(html|plain)$/,
          serializer: ({body}) => body
        }
      ],
      default: 'application/json'
    })
```
It seems that http-error-handler does this:
```
      request.response.body = jsonSafeParse(request.error?.message);
      request.response.headers['Content-Type'] =
        typeof request.response?.body === 'string'
          ? 'plain/text'
          : 'application/json';
```
As the message is a JSON, it gets parsed and the ['Content-Type'] is set to 'application/json'. However, in httpResponseSerializer, we have this:
```
    // skip serialization when content-type is already set
    if (
      request.response.headers['Content-Type'] ||
      request.response.headers['content-type']
    ) {
      return
    }
```
As content-type is already set, the serializer doesn't pick the response and don't apply the serializer, thus the returned body is an `object` instead of a `string` and API Gateway fails to read it and fails with a 502. So if you use it as the last middleware, it will fail because the body is an object, and if you use it with the serializer as specified in the docs (using this second to last, with the serializer last), it will fail because the serializer will exit early when it sees the content-type header.

**Comment by CodeVision** [comment]
@willfarrell Isn't this actually a bug?

I'm running into the same problem, except I'm not using a serializer. 

I'm sending a JSON string in an error, which is correctly recognized as such by:

https://github.com/middyjs/middy/blob/54787a929b5c539369ddc327a75f3f0a16fc2cf3/packages/http-error-handler/index.js#L36-L40

and therefor it get's the right `content-type` header (`application/json`). However the body in the process is also changed to an object, which means API gateway will complain (and throw a 522) since it expects the body of a response with `content-type: application/json` to be a JSON string.

This can be corrected by using a serializer, but this wasn't required prior to 2.0. Could be I missed that it is now?

**Comment by SwagStork** [comment]
Agreed, I am also running into this same issue as well.

**Comment by willfarrell** [comment]
@CodeVision @SwagStork I pushed a bug fix to `main`, which will be in the next release.
