### ISSUE TITLE
httpResponseSerializer does not propagate errors correctly

### ISSUE THREAD

**Issue by c-ciobanu** [middyjs/middy#654]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a handler like this
```
import middy from "@middy/core";
import httpResponseSerializer from "@middy/http-response-serializer";

const handler = () => {
	throw new Error("Test");
};

export default middy(handler).use(
	httpResponseSerializer({
		serializers: [
			{
				regex: /^application\/json$/,
				serializer: ({ body }) => JSON.stringify(body)
			},
			{
				regex: /^text\/plain$/,
				serializer: ({ body }) => body
			}
		],
		default: "application/json"
	})
);
```
2. Invoke lambda

What happens?
-------------
You get a successful response with status code 200

What were you expecting to happen?
----------------------------------
A 502 response

Any logs, error output, etc?
----------------------------
None, the lambda should throw but it doesn't

What versions of software are you using?
----------------------------------------
**Node.js Version:** v14.16.1

**Middy Version:** 2.0.1

**Comment by willfarrell** [comment]
Thanks for reporting. This middleware has an `onError` that will set a default response. It won't set the `statusCode` but the default is `200`. You need a middleware to catch your error and format the response properly. Checkout: https://github.com/middyjs/middy/blob/main/packages/http-response-serializer/__tests__/index.js#L240

I will update the docs to include this.

This kind of edge case related to error handling is something we're working on for the next version of middy.

**Comment by willfarrell** [comment]
Thanks for reporting. I've added in a new test for this and a patch that should fix it. I will be in the next release sometime in the next week.
