### ISSUE TITLE
cloudwatch-metrics installation command ?

### ISSUE THREAD

**Issue by niko-achilles** [middyjs/middy#655]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. npm install --save @middy/metrics

What happens?
-------------
npm package cannot be found, hence not installed

What were you expecting to happen?
----------------------------------
should install the package of cloudwatch-metrics middleware 

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
in order to install the package of cloudwatch-metrics middleware i used the command npm install @middy/cloudwatch-metrics, 
The documentation of middy for cloudwatch-metrics package provides the information  that i should use the command npm install @middy/metrics
https://github.com/middyjs/middy/tree/main/packages/cloudwatch-metrics 

What versions of software are you using?
----------------------------------------
**Node.js Version:** v14.16.0

**Middy Version:** 2.0.1

**AWS SDK Version:** 2.888.0

**Comment by willfarrell** [comment]
Thanks for reporting. we changed the name during the PR, looks like this was missed.

`npm install --save @middy/cloudwatch-metrics` should work for you

Docs are now updated.
