### ISSUE TITLE
@middy/secrets-manager does not throw Error

### ISSUE THREAD

**Issue by serverlesspolska** [middyjs/middy#659]
Hello,

Is it normal that Middy does not throw any Error when it can't access Secrets in Secret Manager (my Lambda function does not have any rights to read `rdsPassword`. Yet somehow it does not fail.

following configuration 
```JavaScript
const middy = require('@middy/core')
const sm = require('@middy/secrets-manager')

const handler = async (event, context) => {
  console.log('Context', context.SECRET)
  return { connected: true, context: context.SECRET }
}

const secretsConfig = {
  cache: true,
  secrets: {
    SECRET: 'rdsPassword'
  },
  setToContext: true
}

module.exports.handler = middy(handler)
  .use(sm(secretsConfig))
```

In logs I see `ERROR   failed to refresh secrets from Secrets Manager`, however this is just a message and not an actual Error. Lambda ends successfully which makes it **hard to find errors**.

Is it possible to configure `@middy/secrets-manager` in a way to force the error to be thrown?

**Comment by willfarrell** [comment]
Thanks for reporting. I would expect it to. If the AWS SDK doesn't throw an error it won't get caught currently. Could you catch the response and paste it here, we can add in logic to handle this.

This is the line to put the logging https://github.com/middyjs/middy/blob/main/packages/secrets-manager/index.js#L39

**Comment by willfarrell** [comment]
Just wanted to follow up on this. Any luck creating a test for this? I was unable to find anything in the AWS SDK docs to indicate them returning an error over throwing one.

**Comment by willfarrell** [comment]
Please re-open if are able to run into this again.
