### ISSUE TITLE
Add @DavidWells to the core team

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#66]
Hello all, 
after a PR and a private discussion i would like to propose @DavidWells from the Serverless framework to be part of the core team of this project so that he can contribute more and, most importantly, help on voting features and getting them merged.

Please add your 👍 or 👎 or 😐 . If we get 3 👍  i will consider this to be commonly agreed. If you are against this or don't like this way of voting, please provide some rationale so that we can try to create a better framework for these kind of decisions in the future 😉

CC @acambas @dkatavic @peterjcaulfield @padraigobrien @techfort

**Comment by acambas** [comment]
👍

**Comment by dkatavic** [comment]
👍 @DavidWells welcome on board :)

**Comment by techfort** [comment]
👍

**Comment by lmammino** [comment]
And so it is :) welcome on board @DavidWells

**Comment by DavidWells** [comment]
Woohoo! 🎉

Thanks everyone 😄
