### ISSUE TITLE
can't have multiple ssm middlewares

### ISSUE THREAD

**Issue by theburningmonk** [middyjs/middy#661]
What are the steps to reproduce this issue?
-------------------------------------------
1. configure 2 `ssm` middleware for one function (they require different caching duration, and one should go to context and the other env var). 

What happens?
-------------
The first `ssm` middleware fetches the parameter correctly, but the second always returns `undefined`

What were you expecting to happen?
----------------------------------
The two `ssm` middleware should operate independently of each other.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.15.2

**Middy Version:** 2.0.1

**AWS SDK Version:** 2.892.0

**Comment by willfarrell** [comment]
Do they have different `cacheKey` values?

What is the use case for having the ssm middleware twice?

**Comment by theburningmonk** [comment]
They have different cache duration and one should go to the `context` and the other in the environment variables.

Didn't specify `cacheKey`, that could be it. `cacheKey` feels like a leaky abstraction, it's an internal implementation detail, even the description says "Internal cache key".

**Comment by willfarrell** [comment]
Thanks for the use case feedback.

`cacheKey` needs to be unique across all middleware, maybe the term `internal` is too ambigous. I'll update the docs.

**Comment by willfarrell** [comment]
Please re-open if this is still unsolved.
