### ISSUE TITLE
New Middleware Proposal: joi-validator

### ISSUE THREAD

**Issue by nolde** [middyjs/middy#668]
New validator using the amazing [joi](https://www.npmjs.com/package/joi).

**Comment by willfarrell** [comment]
I've heard great things about joi. We can definitely add in a link to a community-built one if you're thinking of building one. I don't foresee adding another validator into the middy core at this time. However, I'm happy to reconsider based on community feedback on this thread.

**Comment by cosminmindru** [comment]
+1 for Joi, I'm using a custom validator middleware using Joi so official support would be amazing 😄

**Comment by willfarrell** [comment]
Closing in favour of adding a community built one.
