### ISSUE TITLE
onError is ignored if a previous middleware's onError creates a response

### ISSUE THREAD

**Issue by romeroadrian** [middyjs/middy#671]
Looks like the `onError` stage of a middleware is ignored if a previous `onError` middleware handled the error by returning a response. 

My understanding is that it should still be called since the docs say so:

> When a middleware handles the error and creates a response, the execution is still propagated to all the other error middlewares and they have a chance to update or replace the response as needed. At the end of the error middlewares sequence, the response is returned to the user.

I've noticed this using `http-cors` with `http-error-handler`.  If `http-error-handler` comes first, it will create a response and the cors mid won't be called.

What are the steps to reproduce this issue?
-------------------------------------------

Minimal code to reproduce the issue:

```
const middy = require('@middy/core');
const { normalizeHttpResponse } = require('@middy/util');

const middleware1 = () => ({
  onError: (request) => {
    console.log('middleware1 onError');

    request.response = normalizeHttpResponse(request.response);
    request.body = 'something bad happened';
    return request.response;
  },
});

const middleware2 = () => ({
  onError: () => {
    console.log('middleware2 onError');
  },
});

const handler = middy(async () => {
  throw new Error('oops');
});

handler
  .use(middleware1())
  .use(middleware2());

module.exports = { handler };
```

What happens?
-------------
middleware2 onError isn't called if middleware1 onError handlers the error and returns a response.

What were you expecting to happen?
----------------------------------
middleware2 onError gets called.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.16

**Middy Version:** 2.2.0

**AWS SDK Version:** 2.876.0

**Comment by willfarrell** [comment]
This is the expected behaviour. In the `http-error-handler` documentation it states `This middleware should be set as the last error handler`. Why this happens is because `http-error-handler` returns the response, short-circuiting the middleware stack. This technique can be applied to `before` and `after`. It is planned to remove this in v3 making it easier to use in common use cases.

**Comment by Nebulis** [comment]
@willfarrell then why the documentation examples show the opposite => https://github.com/middyjs/middy/tree/main/packages/http-cors ?

I can help to update the doc if necessary

**Comment by willfarrell** [comment]
Those docs look right, the ordering of middleware is especially important for `after` and `onError` currently. This use case is the most popular issue people have, which makes me feel like I should release an alpha of v3 for those to address it.

**Comment by Nebulis** [comment]
Hum ok I'm not sure to understand then. What's the best order to use cors and http-error-handler then ? Is the following correct?

```js
handler.use(cors())
       .use(httpErrorHandler())
```

**Comment by willfarrell** [comment]
That is the current best order, and what I personally use.

success
```
- cors.before // *
- httpErrorHandler.before // *
- handler
- httpErrorHandler.after // *
- cors.after
```
error (<=2.x
```
- cors.before // *
- httpErrorHandler.before // *
- handler
- cors.onError
- httpErrorHandler.onError
```
\* May not exist in this example

The `onError` call stack is reversed compared to `after`. This is a legacy decision going back to v0.x. This can lead to edge cases that are tricky to resolve when you have many middlewares in place. Changing the `onError` order to match `after` would likely resolve this frustration.
