### ISSUE TITLE
Adding context.AwsRequestId to custom logs from pino logger

### ISSUE THREAD

**Issue by s1mrankaur** [middyjs/middy#675]
Trying to use cls-proxify with middy. 

This is what common-middleware.js looks like:

```
import {setClsProxyValue, clsProxifyNamespace} from 'cls-proxify';
export default handler => middy(handler).
  before((async () => {
    const { context } = handler
    clsProxifyNamespace.run(() => {
      const loggerProxy = {
        debug: (msg) => `${context.awsRequestId}: ${msg}`,
      }
      setClsProxyValue('requestId', loggerProxy);
    });
   }))
   .use([
    loggerMiddleware({ logger: logger }),
    //..OTHER MIDDLEWARES
    autoProxyResponse(),
    // Easier error handling in each lambda
    httpErrorHandler(),
]);
```

This is what our `pino-logging.ts` file  looks like:
```

import pino from "pino";
import { clsProxify } from 'cls-proxify'

//level:trace=10,debug=20,info=30,warn=40,error=50,fatal=60,silent=Infinity
const pinoLogger = pino({
    name: 'viewLinc',
    level: process.env.STAGE == 'prod' ? 'info' : 'debug'
});

const logger = clsProxify('requestId', pinoLogger)

export default logger;

```

This is how we add custom logs in the application:
```

import logger from './pino-logging';
logger.debug('DUMMY DEBUG LOG');
```

The log messages however do not have the `requestId` in the traces and thus no` corelationId/custom logs `appears in the traces in Servicelens

**Comment by willfarrell** [comment]
I can see value in having access to the requestId for custom message formatting and/or using 3rd party logging services. Passing in the requestId to the logger function should be pretty easy to do. I can extend the object to include context, is there anything else you feel should be included. I think `functionName` should be included. Thoughts?

**Comment by s1mrankaur** [comment]
@willfarrell  Having access to all the AWS context values would be really really awesome :)

**Comment by willfarrell** [comment]
I can add this over the weekend. `omitPaths` can be used to remove parts of the context, all be sure to add it in before the omit code.

**Comment by willfarrell** [comment]
Checkout #677, let me know what you think.

**Comment by s1mrankaur** [comment]
@willfarrell  Looks awesome! Thank you so much :) Look forward to it being released.
