### ISSUE TITLE
SSM - SecureString params support

### ISSUE THREAD

**Issue by rcoundon** [middyjs/middy#679]
We've just come across Middy and it looks very interesting indeed. Apologies this isn't a structured issue report but I wanted to ask the question of whether the SSM middleware supports the retrieval of securestring parameters from Parameter Store before we embarked upon building Middy into our applications.
I couldn't see anywhere else to ask the question hence posting here. 

A quick look at the source code suggests it does but would just like to confirm officially - thank you

```
     batchReq = client        .getParameters({ Names: batchFetchKeys, WithDecryption: true })
```

**Comment by willfarrell** [comment]
Yes, it does.
