### ISSUE TITLE
Request Documentation For Validator

### ISSUE THREAD

**Issue by PresidentPolk** [middyjs/middy#685]
Working with Middy validator. I am having issues knowing all the different filters that are available.

Is there a more documented version of the input and output schemas available?

**Comment by willfarrell** [comment]
The `validator` use [`ajv`](https://ajv.js.org/) to validate JSON schema. It can be whatever you need to for your use case. If you're using events triggers by AWS like API Gateway you'll need to follow the format AWS has in their documentation (ie https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html).

**Comment by PresidentPolk** [comment]
Thank you!
