### ISSUE TITLE
Typescript build time dependencies aren't installed

### ISSUE THREAD

**Issue by nponeccop** [middyjs/middy#686]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a TypeScript project using `@middy/http-error-handler`

What happens?
-------------
The project fails to build

What were you expecting to happen?
----------------------------------
The project buids

Any logs, error output, etc?
----------------------------
```
node_modules/@middy/http-error-handler/index.d.ts:1:27 - error TS2307: Cannot find module 'http-errors' or its corresponding type declarations.
```

Any other comments?
----------------------
AFAIK this issue is unfixable unless they improve `package.json` format. `@types/http-errors` is a special type of dependency, that is currently impossible to specify. Namely, each Typescript project depending on `@middy/http-error-handler` must have `@types/http-errors` as a development dependency.
As this is impossible to specify in the metadata and have `npm` do it, the only possible solution is to specify this extra dependency in the documentation.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.x

**Middy Version:** 2.4.1

**AWS SDK Version:** irrelevant

**Comment by willfarrell** [comment]
Thanks for reporting! Looking at the type def, it's passed into the logger. Technically this could be anything (but likely an HttpError or native Error). 

Would updating the def to the following resolve the issue?
```ts
import middy from '@middy/core'

interface Options {
  logger?: (error: any) => void
  fallbackMessage?: string
}

declare function httpErrorHandler (options?: Options): middy.MiddlewareObj

export default httpErrorHandler
```

**Comment by choliveira** [comment]
@willfarrell, yes that solved the issue for me. Any plans to update the library with the fix?

**Comment by willfarrell** [comment]
Change pushed to `main`. Not sure when the next release will go out. Maybe a week or so.
