### ISSUE TITLE
Where can we use the processCache function in a middleware typescript file?

### ISSUE THREAD

**Issue by KirbyAbadilla** [middyjs/middy#688]
Given that I created a custom middleware in a typescript file, I wanted to use the processCache function but in the latest version, it requires now a third parameter with a type of Request. How can I use now the processCache function if I want to call it outside the MiddlewareObject function such as before, after, onError. Please see sample code below:

`import middy, { MiddlewareObj } from "@middy/core";
import {
  canPrefetch,
  processCache,
  Options,
} from "@middy/util";

const defaultOptions: Options<any, any> = {
  fetchData: {}, // { internalKey: params }
  disablePrefetch: false,
  cacheKey: "custom",
  cacheExpiry: -1,
  setToEnv: false,
  setToContext: false,
};

export default (options: Options<any, any>): MiddlewareObj => {
  const opts = { ...defaultOptions, ...options };

  const fetch = () => {
    return {
      person: {
        firstName: "Kirby",
        lastName: "Abadilla",
      },
    };
  };

  if (canPrefetch(opts)) {
    processCache(opts, fetch, request)
  }

  const before = async (request: middy.Request) => {

  };

  return {
    before,
  };
};
`

What were you expecting to happen?
----------------------------------
I expected that the third parameter in `processCache(opts, fetch, request)` is optional in typescript implementation

Any logs, error output, etc?
----------------------------
`processCache(opts, fetch, request)` have a third parameter now as oppose to the documentation in which the processCache can accept two arguments, option and fetch

What versions of software are you using?
----------------------------------------

**Middy Version:** 2.4.1

**Comment by willfarrell** [comment]
Thanks for your question.

When using `processCache(opts, fetch, request)`, `request` is only required if your `fetch` function requires it. If the TypeScript definition requires updating to allow this, I'd be happy to review a PR for this change.

Within the supported middlewares, this is most commonly used when reaching out to external services. [rds-signer](https://github.com/middyjs/middy/blob/main/packages/rds-signer/index.js) is a simple example.
