### ISSUE TITLE
event-normalizer depends on aws-sdk

### ISSUE THREAD

**Issue by nponeccop** [middyjs/middy#691]
What are the steps to reproduce this issue?
-------------------------------------------
1. Build a small app using SNS without `event-normalizer`
2. Add `event-normalizer`

What happens?
-------------
sls package creates a huge deployment zip file

What were you expecting to happen?
----------------------------------
The deployment image size remains reasonable

Any other comments?
-------------------
The reason for that is that the normalizer uses `aws-sdk` to normalize DynamoDB events. However I don't want to normalize DynamoDB events at all. So it's better to move this normalizer into a separate package as it has a huge size impact. Modules such as `aws-sdk\lib\xml\builder.js` are actually loaded during startup, which impacts cold start performance in addition to .zip size.

In my particular case I use a third-party API to forward the SNS messages elsewhere, so it's not the case that the `aws-sdk` is needed anyway.
 
What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.x

**Middy Version:** 2.4.2

**AWS SDK Version:** irrelevant

**Comment by willfarrell** [comment]
Thanks for the suggestion and continued feedback on how we can make middy better. 

When creating this middleware there was a lengthy discussion on having a single middleware vs middleware for every type of normalization. Balancing developer ease of use vs ultimate performance can be tricky to do. Hopefully, when we update to use `aws-sdk-v3` (which requires it to be included within Lambda and have esm support) this will be less of an issue.

If you're only using SNS without nested events I would recommend not using any normalizer middleware at all and perform `JSON.parse(event.Records[0].Sns.Message)` within the `handler`. This approach would outperform `event-normalizer` with your recommended change.

Happy to include a middleware that only does SNS in the community list if you'd like to submit one.

PS When bundling code you don't need to include the `aws-sdk` dependency. It's already included in the nodejs runtime.

**Comment by nponeccop** [comment]
The main problem here is that the DynamoDB normalizer has an unusually high space cost. E.g. with every other normalizer the cost is negligible. My main complaint is that `middy` is supposed to be minimal and don't bring you dependencies you don't even need. The `event-normalizer` middleware without the DynamoDB normalizer satisfies that constraint. Only the addition of DynamoDB is a violation, as it's fat. So my vote is an event-normalizer for anything which can be normalized without a big space impact. And fat normalizers can be bundled separately.

I think you can have something like @middy/tiny module which bundles many one-line middlewares. The advantage is that those are reusable and maintained one-liners.  Or you could make `aws-sdk` an optional dependency, document that it's required for DynamoDB normalization, and only require it once a DynamoDB event comes.

Also note that I got a really huge zipfile, 270 MB of dependencies, 90 MB when zipped, due to other problems. The real impact of including `aws-sdk` was not measured by me and it's probably much smaller, especially with the modular 3.x SDK. But by excluding `@middy/event-normalizer` I was able to reduce the size to ~50 kB.
 
> I would recommend not using any normalizer middleware at all and 
> perform `JSON.parse(event.Records[0].Sns.Message)` within the handler

Well, a one-line inline middleware is definitely a better choice. Doing something in the handler is counterproductive as there are typically many handlers reusing the same stack, and the handler is supposed only to deal with the business logic. And moreover if you look at the source of `event-normalizer`, the production-ready logic there is more elaborated than a mere `JSON.parse`.

So the current solution is to copy-paste parts of event-normalizer code into custom middleware.

> When bundling code you don't need to include the aws-sdk dependency. It's already included in the nodejs runtime.

There are several problems here:

- Then you need a fully custom deployment using `patterns` in `serverless.yml`. `serverless` does bundle `aws-sdk` out of the box as it's a dependency
- Which version of `aws-sdk`? There are 2.x and 3.x. And then you are forced to always use the version shipped with the runtime. What if it's buggy or incompatible?
