### ISSUE TITLE
Validator Custom Error Response

### ISSUE THREAD

**Issue by PresidentPolk** [middyjs/middy#699]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

Attempting to create custom response error however it is creating cors errors on the front end. As seen below 
Curious if we are handling this incorrectly. Any info would be helpful.

```javascript
return middy(handler)
    .use(CaidValidationMiddleware())
    .use(OamAuthenticationHeaders())
    .use(httpJsonBodyParser())
    .use(httpEventNormalizer())
    .use(validator({ inputSchema }))
    .onError((request) => {
      console.dir(request);
      const response = {};
      if (typeof body === 'undefined') {
        body = {};
      }
      response.statusCode = 400;
      response.body = body;
      response.body.errors = validationErrorHandler(request.error);
      response.body = JSON.stringify(response.body);

      return response;
    })
    .use(httpErrorHandler())
    .use(cors());
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Node.js Version:** … 14.x

**Middy Version:** … 2.4

**AWS SDK Version:** …

**Comment by willfarrell** [comment]
The order for `after` and `onError` are different. In cases like this can cause confusion. We plan to fix this in v3.

For your use case above, try moving `.use(cors())` above `.use(validator(...))`. That should do the trick.

**Comment by PresidentPolk** [comment]
Thank you. That definitely did it.

On a side note, do you know how backwards compatible v3 is/will be compared to 2.x?

**Comment by willfarrell** [comment]
What will be included isn't finalized yet (https://github.com/middyjs/middy/issues/626), so impossible to say. We hope to only push breaking changes once a year that are inline with new version of nodejs being supported on AWS. But this onError issue is tripping a lot of people up, we might make an exception or have a long running `alpha` until next April.

People with custom error handlers, like yourself, will need to make a small change (ie remove `return response`), maybe change the order of some middleware. Everyone else should be fine for the most part.
