### ISSUE TITLE
TypeScript: aws-lambda Handler type error

### ISSUE THREAD

**Issue by denovodavid** [middyjs/middy#703]
What are the steps to reproduce this issue?
-------------------------------------------
1. Defined a handler using `Handler` type from `aws-lambda`
2. Middify it:
```ts
// handler.ts
import middy from '@middy/core';
import type { Handler } from 'aws-lambda';

const handler: Handler = () => {};

export const main = middy(handler);
```

What happens?
-------------
You get a type error:

```
Argument of type 'Handler<any, any>' is not assignable to parameter of type '(event: any, context: Context) => Promise<any>'. ts(2345)
```

What were you expecting to happen?
----------------------------------
Any valid `Handler` type is accepted by `middy`.

Any other comments?
-------------------
It seems the changes in #696 don't fully wrap the `Handler` type from `aws-lambda`.
Specifically, the `callback` parameter is missing, and `void` is not in the return type.

`Handler` from `aws-lambda`:
```ts
export type Handler<TEvent = any, TResult = any> = (
    event: TEvent,
    context: Context,
    callback: Callback<TResult>,
) => void | Promise<TResult>;
```

`MiddlewareHandler` from `@middy/core`:
```ts
declare type MiddlewareHandler<THandler extends LambdaHandler<any, any>, TContext> =
  THandler extends LambdaHandler<infer TEvent, infer TResult> // always true
    ? (event: TEvent, context: TContext) => Promise<TResult>
    : never
```

Updating the middy type to the following should work I believe:

```ts
import {
  Callback as LambdaCallback,
  Context as LambdaContext,
  Handler as LambdaHandler
} from 'aws-lambda'

// other stuff...

declare type MiddlewareHandler<THandler extends LambdaHandler<any, any>, TContext> =
  THandler extends LambdaHandler<infer TEvent, infer TResult> // always true
    ? (event: TEvent, context: TContext, callback: LambdaCallback<TResult>) => void | Promise<TResult>
    : never
```

What versions of software are you using?
----------------------------------------
**Middy Version:** `@middy/core@2.5.0`

**TypeScript Version:** `typescript@4.3.5`

**AWS Lambda Types Version:** `@types/aws-lambda@8.10.81`

**Comment by willfarrell** [comment]
Thanks for reporting. Would you be able to put a PR together?

cc @mbarton @JimiPedros

**Comment by mbarton** [comment]
Sorry for the missed case @denovodavid and thanks for the PR. The changes look good
