### ISSUE TITLE
Throwing an exception (using @middy/http-error-handler) has no effect and Lamda times out

### ISSUE THREAD

**Issue by ryantomaselli** [middyjs/middy#711]
What are the steps to reproduce this issue?
-------------------------------------------
1. Add a handler wrapped with middy using the http-error-handler middleware
2. Throw an exception (for example createError.UnprocessableEntity()) in the handler

`export const handler = middy(async () => {
  throw new createError.UnprocessableEntity()
}).use(httpErrorHandler())
`

What happens?
-------------
Lambda times out

What were you expecting to happen?
----------------------------------
A 422 http response

Any logs, error output, etc?
----------------------------
None

Any other comments?
-------------------
Configured with the Serverless framework

What versions of software are you using?
----------------------------------------
**Node.js Version: Node.js 12.x

**Middy Version: 2.5.1

**AWS SDK Version: 2.610.0

**Comment by willfarrell** [comment]
That should return `422` (See https://github.com/middyjs/middy/blob/main/packages/http-error-handler/__tests__/index.js#L117). Unsure why it's timing out.

Check out more examples at https://github.com/middyjs/middy/blob/main/packages/http-error-handler/__tests__/index.js

**Comment by ryantomaselli** [comment]
Thanks for your response @willfarrell. So a bit of trial and error and I found that if I don't include the "logger" option the Lambda times out whereas if I do the exception flow is tripped as expected.

So following does NOT work:
`httpErrorHandler()`

Whereas the following DOES work:
`httpErrorHandler({ logger: false })`

Thanks to all contributors for conjuring this library!

**Comment by willfarrell** [comment]
`logger` defaults to `console.error` that should not casue a timeout. 

```
if (typeof options.logger === 'function') {
      options.logger(request.error)
    }
```

Nothing fancy here that could cause a timeout. Is console being overriden else where in the code?
