### ISSUE TITLE
SSM - Confusing how to use

### ISSUE THREAD

**Issue by ed-sparkes** [middyjs/middy#712]
The @middy/ssm documentation says that `setToContext` and `setToEnv` are legacy and should not be used, but the documentation is unclear on how to actually use it as the first example uses `setToContext` and the second example replicates the code of `setToContext` in a custom middleware ? 

What is the recommended secure way to use this middleware now?

Many thanks,

**Comment by andreafalzetti** [comment]
hey @ed-sparkes, I am just a user of @middy so I might be wrong, but - I've been upgrading recently from Middy 1.x to 2.5.x in my side project and I think I can clear your doubts..

Before, I used to append to context the secrets coming from SSM.. Now, like you said, it's not recommended and the way to access the secrets is using the function `getInternal` exported from `@middy/util`.

Check out this example, which helped me understanding: https://github.com/middyjs/middy/tree/main/packages/ssm#sample-usage

It's working for me so I assume the answer is correct.. I'll cc @lmammino in case he wants to correct me.

**Comment by willfarrell** [comment]
@andreafalzetti thanks for jumping in here. I can add some more details. There are two examples:
1. using `setToContext:true`; This applies all fetch data to the context and for simple use cases this is safe to use
2. using `getInternal(...)`; This is best practice, though may not be obvious why:
  - Allow for multiple middleware that `fetchData` to allow run asynchronously
  - Allow for whitelisting of what should be included in the context
  
Hope this helps.
