### ISSUE TITLE
MiddyInputHandler now requires callback property

### ISSUE THREAD

**Issue by jkinghed** [middyjs/middy#715]
What are the steps to reproduce this issue?
-------------------------------------------
1. Upgrade to version 2.5.1

What happens?
-------------
My unit tests fail due to missing *required* `callback` property when calling handler. This happens after #704 was merged and published as version 2.5.1, where the `MiddyInputHandler` type was changed to include callback as third property.

**2.5.0**
```
type MiddyInputHandler<TEvent, TResult, TContext> = (event: TEvent, context: TContext) => Promise<TResult>
```
**2.5.1**
```
type MiddyInputHandler<TEvent, TResult, TContext extends LambdaContext = LambdaContext> = (event: TEvent, context: TContext, callback: LambdaCallback<TResult>) => void | Promise<TResult>
```

**Working code in 2.5.0**
```
const handler = middy(async (event: any, context: any) => {
    return {
        event,
        context,
        dummy: 'foo'
    };
});

handler.use(someMiddleware());

const response = await handler(myEvent, myContext);
```

Could you recommend an approach to resolve this? I would like to avoid callbacks. I've reverted to version 2.5.0 for now.

**Comment by willfarrell** [comment]
Like to submit a PR to make callback optional?

**Comment by jkinghed** [comment]
> Like to submit a PR to make callback optional?

Will do :)

**Comment by willfarrell** [comment]
Closing, but feel free to open a PR when you're ready.
