### ISSUE TITLE
How to conditionally pass the schemaValidator in the middleware, using .validator()

### ISSUE THREAD

**Issue by 09abhishek** [middyjs/middy#717]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … I want to conditionally pass the schema validator.
2. …
3. …

What happens?
-------------
… Currently, it's just accepting only one schema at a time.

What were you expecting to happen?
----------------------------------
… Expecting to pass schema conditionally or programmatically.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Node.js Version:** … 11

**Middy Version:** … 2.0.1

**AWS SDK Version:** …

**Comment by willfarrell** [comment]
You have 2 options:
a) Conditionally include the `validator` middleware.
```
if (true) {
  hander.use(validator({...})
}
```

b) Set `inputScheme` to `{"type":"object"}`
```
if (false) {
  inputScheme = `{"type":"object"}
}
```
