### ISSUE TITLE
Examples of using middy/http-multipart-body-parser to retrieve texts and files in multipart/form-data? 

### ISSUE THREAD

**Issue by PhuongDTran** [middyjs/middy#721]
Does anyone have examples of using middy/http-multipart-body-parser to retrieve texts and files in AWS Lambda Functions? I am able to get texts but not file. There is no docs about it as I'm aware of.

**Comment by willfarrell** [comment]
If you do find a way, would you be able to open a PR or post it here?

**Comment by willfarrell** [comment]
Any luck? Please re-open if there is still a need for this.
