### ISSUE TITLE
http-cors.httpCorsMiddlewareAfter fails because path to httpMethod is wrong

### ISSUE THREAD

**Issue by ellucianBret** [middyjs/middy#723]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
use @middy/http-cors middleware

What happens?
-------------
The after function returns before doing any work because request?.event?.httpMethod is undefined.

What were you expecting to happen?
----------------------------------
I am expecting my passed in getOrigin function to be called.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
N/A

Any other comments?
-------------------
For current versions of AWS Lambda the path should be request?.event?.requestContext?.http?.method

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.17.6

**Middy Version:** 2.5.1

**AWS SDK Version:** N/A not using directly in this case

**Comment by willfarrell** [comment]
@ellucianBret Are you using API Gateway v2? Looks like it was only checking for v1, I've updated `main` to check for both now.

**Comment by ellucianBret** [comment]
Yes, I am using V2.

Thx,
Bret

**Comment by willfarrell** [comment]
Perfect, just wanted to make sure. I should have a release out in the next week.
