### ISSUE TITLE
Ability to access the baseHandler or cleanup the existing middlewares

### ISSUE THREAD

**Issue by JoaquinFernandez** [middyjs/middy#724]
What are the steps to reproduce this issue?
-------------------------------------------
Import the middy instance on another file (i.e. integration test file).

What happens?
-------------
Can't access de baseHandler that was used with middy.

What were you expecting to happen?
----------------------------------
There would be a way to access the baseHandler **or** cleanup the existing middlewares.

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------

When building integration tests, like my case, I use [nock](https://github.com/nock/nock) to do and reproduce a whole call to the baseHandler. However, there are some middlewares which I use i.e. for authentication or accessing env vars stored in ssm that I do not want to be part of those integration tests, not execute them, not store their fixtures.

For that use case, and in order to keep the baseHandler non exported in the original file as it shouldn't be exposed, it would be very useful if I could access the baseHandler, or if the instance of middy would have a method cleanup() to remove all existing handlers and go back to the original state.

I would like to know if there is someway to access the original handler (I tried but I am not able to find a way), if not I would like to know which would be your preferred option in this matter (exposing the baseHandler somehow or adding a cleanup method or whatever you can come up with) and, finally, if this is something you would be able to do, or accept a PR on the issue.

What versions of software are you using?
----------------------------------------
**Node.js Version:** v12.22.6

**Middy Version:** 1.5.2

**AWS SDK Version:** 2.819.0

**Comment by willfarrell** [comment]
There is `middy.__middlewares` which contains the `before`, `after` and `onError` middlewares that you could manipulate. However, initializing your handler with a flag to exclude certain middleware would be a cleaner approach. There is  also `@middy/util` that has `modifyCache` and `clearCache` function that you can use to modify middleware cache globally. Additionally you can export the baseHandler along with the handler to get direct access to it for testing (`module.exports = {handler, baseHandler}`).

Note: `__middlewares` will likely be deprecated in the future.

PS For security purposes, setting ENV from `ssm` is not recommended. `setToEnv` will be deprecated in the future.

**Comment by JoaquinFernandez** [comment]
Thank you for the comprehensive response, to your points:
- Using ```middy.__middlewares``` was my first approach, it works but it does not seem like a clean way, less if it's going to be deprecated.
- I don't understand how ```modifyCache```/```clearCache``` can help in this case, can you please elaborate? 
- I would rather not export the baseHandler, since it is not supposed to be exported, it doesn't seem to be the right option

I dont understand the PS, what does ssm have to do with all of this?

So I take it either way you feel the baseHandler being exposed is not something that makes sense for middy?

**Comment by willfarrell** [comment]
> I don't understand how modifyCache/clearCache can help in this case, can you please elaborate?
Depending on what you're trying to clear, these might help. Fetch promises created during `before` are stored here.
> I would rather not export the baseHandler, since it is not supposed to be exported, it doesn't seem to be the right option
Agreed, but is an option. I believe there are testing packages that can expose private functions. The name of which is escaping me right now (rewire?).
> I dont understand the PS, what does ssm have to do with all of this?
You mentioned "i.e. for authentication or accessing env vars stored in ssm" that why

> So I take it either way you feel the baseHandler being exposed is not something that makes sense for middy?
I don't for see that happening. However, I will reflect on this use case. I see value in including an example of e2e testing in our documentation.

**Comment by JoaquinFernandez** [comment]
> Agreed, but is an option. I believe there are testing packages that can expose private functions. The name of which is escaping me right now (rewire?).
> 
> >

Oh yes, maybe I can elaborate on this. I was using ```rewire```, actually [babel-plugin-rewire-ts](https://github.com/rosswarren/babel-plugin-rewire-ts), until now, and I did as you were thinking. However, our code base grew, and I moved from the _standard_ ```webpack``` building (```serverless + jest + babel + webpack```) to using [esbuild](https://esbuild.github.io/), and all those solutions do not work with ```esbuild``` since there is no ```rewire esbuild``` plugin. Thought of building one but then ```rewire``` looks unmaintained (latest release 3+ old years) and the effort is huge for legacy.

> You mentioned "i.e. for authentication or accessing env vars stored in ssm" that why
> 
> >

I see, thank you very much for pointing out, I am actually using it and should move to context.

> I don't for see that happening. However, I will reflect on this use case. I see value in including an example of e2e testing in our documentation.
> 
> >

Thanks for considering, if you may need my help, ping me, I'd be happy to help with a PR.

**Comment by JoaquinFernandez** [comment]
Hi @willfarrell,

Opening up again this issue since I can't seem to hack my way around removing middlewares (or accesing base function) in middy 3.x

I believe you were going to give it a thought, but either it didn't happen or I can't seem to find a way, can you please advise?

**Comment by willfarrell** [comment]
I have 2 related solutions:

1. single file that exports both
```
export const baseHandler = (event) => ...
export const handler = middy(baseHandler)...
```
2. multi-file where the base handler is in one, and the lambdaHandler is in the the other that imports the baseHandler.

In both cases exporting the baseHandler so it can be used in tests directly without middleware. If there is a package that can make it cleaner, it's not coming to mind.

**Comment by JoaquinFernandez** [comment]
I see, not the ideal solution but would work. Either way it feels natural to me that you could clean middlewares or access original handler in a full featured middleware solution.

Thank you for the quick response and your help.
