### ISSUE TITLE
Cannot find module 'aws-xray-sdk'

### ISSUE THREAD

**Issue by iDVB** [middyjs/middy#728]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. `import ssm from '@middy/ssm'` in a TS project 

What happens?
-------------
building causes the following error....
```
node_modules/@middy/ssm/index.d.ts:2:34 - error TS2307: Cannot find module 'aws-xray-sdk' or its corresponding type declarations.
2 import { captureAWSClient } from 'aws-xray-sdk'
```

What were you expecting to happen?
----------------------------------
No errors. Definitely not relating to types for a dependency's dependency.

Other Thoughts
----------------
We are using aws-sdk v3 for our own needs aside from middy.... I don't see any peer or dep on the sdk in `@middy/core` or `@middy/ssm` surprisingly.... does this mean it just uses the default provided by AWS?

What versions of software are you using?
----------------------------------------
**Node.js Version:** v14.15.1
**Middy Version:** v2.5.1
**AWS SDK Version:** v3
    "@aws-sdk/client-firehose": "^3.34.0",
    "@aws-sdk/client-s3": "^3.34.0",

**Comment by willfarrell** [comment]
`middy` does use aws-sdk v2 over v3 (See https://github.com/middyjs/middy/issues/584). `@middy/ssm` does include `aws-xray-sdk` in it's `devDependencies`, not sure why it's would throw an error. Happy to review a PR if you're able to resolve this for typescript developers.

**Comment by J4YF7O** [comment]
I realize that my PR #749 is closing this ticket... :)
