### ISSUE TITLE
How to pre compile ajv

### ISSUE THREAD

**Issue by omer-to** [middyjs/middy#732]
Hello,

This is not a bug report, but rather a question. In some of the middy packages, it is stated that pre-compiling `ajv` is highly recommended for performance reasons. I'm not sure what that means and what process to go through.

Is it possible to elaborate it?

**Comment by willfarrell** [comment]
See https://github.com/willfarrell/middy-ajv

`ajv` has a high cold start cost, pre-warming or pre-compiling are the two option to mitigate this.
