### ISSUE TITLE
Example request for credit card payment example

### ISSUE THREAD

**Issue by crushingCodes** [middyjs/middy#743]
What are the steps to reproduce this issue?
-------------------------------------------
Create the demo payment example from readme.md and post request using following body:

```
{
    "creditCardNumber": "1234123412341234",
    "expiryMonth": 12,
    "expiryYear": 2023,
    "cvc": "111",
    "nameOnCard": "joe blogs",
    "amount": 123
}
```

What happens?
-------------
There is no example request that I could see, so based on my guess I used the above request using Postman and the input schema from the Readme.md using @middy/validator
and the response is:

`Event object failed validation`

What were you expecting to happen?
----------------------------------
`{"result":"success","message":"payment processed correctly"}`

Any logs, error output, etc?
----------------------------

```
  details: [
    {
      instancePath: '/body/creditCardNumber',
      schemaPath: '#/properties/body/properties/creditCardNumber/pattern',
      keyword: 'pattern',
      params: [Object],
      message: 'must match pattern "d+"'
    }
  ]
```

Any other comments?
-------------------
I ended up using following input schema by removing pattern

```
const inputSchema = {
    type: 'object',
    properties: {
        body: {
            type: 'object',
            properties: {
                creditCardNumber: {type: 'string', minLength: 12, maxLength: 19},
                expiryMonth: {type: 'integer', minimum: 1, maximum: 12},
                expiryYear: {type: 'integer', minimum: 2017, maximum: 2027},
                cvc: {type: 'string', minLength: 3, maxLength: 4},
                nameOnCard: {type: 'string'},
                amount: {type: 'number'}
            },
            required: ['creditCardNumber'] // Insert here all required event properties
        }
    }
}
```

Using the same request as above I then get

`{"result":"success","message":"payment processed correctly"}`

What versions of software are you using?
----------------------------------------
**Node.js Version:** …
v16.9.1

**Middy Version:** …
    "@middy/core": "^2.5.2",
    "@middy/http-cors": "^2.5.2",
    "@middy/http-error-handler": "^2.5.2",
    "@middy/http-json-body-parser": "^2.5.2",
    "@middy/validator": "^2.5.2",

**AWS SDK Version:** …
N/A
    "serverless": "^2.64.1",

**Comment by willfarrell** [comment]
Thanks for reporting, Looks like it was missing an extra escape for the backslash. I've pushed an update for it.

**Comment by crushingCodes** [comment]
@willfarrell thanks for that
