### ISSUE TITLE
Typescript validation error when using a custom context in onError of a MiddlewareObj

### ISSUE THREAD

**Issue by guillaumeduboc** [middyjs/middy#744]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
```typescript
import middy from '@middy/core';
import { Context as LambdaContext } from 'aws-lambda';

export interface CustomContext extends LambdaContext {
  customContextKey: string;
}

export const customMiddleware = (): middy.MiddlewareObj<
  any,
  any,
  Error,
  CustomContext
> => {
  return {
    onError: async request => {
      console.log(request.context.customContextKey);
    },
  };
};
```

What happens?
-------------
```TSError
Property 'customContextKey' does not exist on type 'Context'.
```

What were you expecting to happen?
----------------------------------
I expected `onError` to apply my `CustomContext` to the request

Any logs, error output, etc?
----------------------------
```TSError
Property 'customContextKey' does not exist on type 'Context'.
```

Any other comments?
-------------------
...

What versions of software are you using?
----------------------------------------
**Node.js Version:** v14.18.1

**Middy Version:** v2.5.2

**AWS SDK Version:** 2.1014.0

**Comment by willfarrell** [comment]
Would you like to open a PR to resolve?

**Comment by jbialobr** [comment]
I believe that #761 fixes this issue.

**Comment by willfarrell** [comment]
I'm going to close for now. Please re-open if this is not the case.
