### ISSUE TITLE
SSM middleware: Missing AWS Lambda trace data for X-Ray

### ISSUE THREAD

**Issue by fredericbarthelet** [middyjs/middy#746]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Use `@middy/ssm` middleware as the only middleware
2. Add `awsClientCapture` option in middleware configuration using `captureAWSClient` from `aws-xray-sdk`
3. Add a dummy parameter to recover from SSM

What happens?
-------------
Error `Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler` is thrown. This does not prevent lambda from successfully returning, but no segment is generated for SSM call on X-Ray.

What were you expecting to happen?
----------------------------------
To have the corresponding(s) call(s) to SSM show in X-Ray

Any logs, error output, etc?
----------------------------
`Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler`

Any other comments?
-------------------
Tracing is enable on Lambda.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14

**Middy Version:** 2.5.3 (both for core and ssm)

**AWS SDK Version:** 2.952.0

**AWS XRay SDK Version:**  3.3.3

**Comment by willfarrell** [comment]
Thanks for opening an issue for this. I've run into this myself but haven't gotten around to resolving yet. I'd be open to reviewing and testing a PR if you have more time to look into it.

**Comment by fredericbarthelet** [comment]
Hey @willfarrell, I dived a bit on this issue.
From [AWS X-Ray documentation](https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html):
>⚠️ Important
In Lambda, you can use the X-Ray SDK to extend the Invocation subsegment with additional subsegments for downstream calls, annotations, and metadata. You can't access the function segment directly or **record work done outside of the handler invocation scope.**

With the current implementation of the SSM middleware, the SSM call is done during Lambda's `Initialization` phase, before handler's code is actually invoke. I understand that by design, [the SSM client bootstrap](https://aws.amazon.com/fr/blogs/compute/operating-lambda-performance-optimization-part-2/) and the cache JS object have to be initialized booth during this `Initialization` phase, in order not to be repeated on subsequent invocation of the same Lambda instance.

I see 2 options in order to move forward with this issue :
- move cache fetch or SSM fetch logic in lambda's handler somehow (not sure how to proceed here)
- remove captureAWSClient option from SSM middleware in order not to allow capture of this call

WDYT ?

**Comment by willfarrell** [comment]
That's a bummer. I wonder if they'll address this in the future.

> move cache fetch or SSM fetch logic in lambda's handler somehow (not sure how to proceed here)

It is possible to move all SSM fetch inside the handler by using `disablePrefetch: true`

> remove captureAWSClient option from SSM middleware in order not to allow capture of this call

Instead of removing, adding in documentation that states `prefetch` and `captureAWSClient` can't be used together :(. Additional logic to not apply X-Ray in this case can easily be added in.

```js
// @middy/util
const createPrefetchClient = (options) => {
  const awsClientOptions = {
    ...awsClientDefaultOptions,
    ...options.awsClientOptions
  }
  const client = new options.AwsClient(awsClientOptions)

  // AWS XRay
  if (options.awsClientCapture && !options.disablePrefetch) {
   console.warn('Unable to apply X-Ray outside of handler invocation scope. Add `disablePrefetch: true` to options')
  } else if (options.awsClientCapture) {
    return options.awsClientCapture(client)
  }

  return client
}
```
What do you think of this?

**Comment by willfarrell** [comment]
@fredericbarthelet ☝🏻  Thoughts?

**Comment by willfarrell** [comment]
This is now included in the v3 branch and will be release later this month.
