### ISSUE TITLE
Question SSM - access to the specific parameter

### ISSUE THREAD

**Issue by fzanfolim** [middyjs/middy#748]
Hello,
I would like to clear a doubt, I am trying to access an ssm parameter through middy and I already have the parameter name and the path, however when I try to access a permission error occurs (ssm:GetParameters on resource: arn:aws:ssm:{ {region}}:{{account}}:* because no identity-based policy allows the ssm:GetParameters action) . As I understand it, it asks for access to the entire account, but I would just like to release access to the specific parameter. I have been using serverless.

Below how I'm recovering:

       ssm({
                fetchData: {
                    param: `${.STAGE}/parameter`,
                },
                setToContext: true,
                cacheExpiry: 15 * 60 * 1000,
                cacheKey: 'ssm-secrets',
            });

**Comment by willfarrell** [comment]
AWS IAM does allow that by suffixing with the path `:parameter/path/to/var`. https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html
