### ISSUE TITLE
Passing invalid schema doesn't produce error

### ISSUE THREAD

**Issue by shelou** [middyjs/middy#751]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Call middy function
2. … Pass the handler to the function  .middy(handler)
3. … Pass the same handler to the .use(validator({handler})
ex: 
middy(handler).use(middyJsonBodyParser())
        .use(validator({handler}))
        .use(httpErrorHandler())

What happens?
-------------
… middy calls the handler twice instead of throwing an "invalid schema" error

What were you expecting to happen?
----------------------------------
… I was expecting an error on the schema

Any logs, error output, etc?
----------------------------
no logs

What versions of software are you using?
----------------------------------------
**Node.js Version:** … v14.17.0

**Middy Version:** … ^2.5.2

**AWS SDK Version:** … ^2.919.0

**Comment by aedris0** [comment]
Same issue here

**Comment by willfarrell** [comment]
Your example should throw with the message `Middleware must be an object containing at least one key among "before", "after", "onError"` because neither `inputSchema` or `outputSchema` options are set.

```js
test('It should warn about missing schema', async (t) => {
  const handler = middy((event, context) => ({}))

  t.throws(() => { handler.use(validator({ handler })) }, {instanceOf: Error, message: 'Middleware must be an object containing at least one key among "before", "after", "onError"'})
})
```
