### ISSUE TITLE
[Failed to get parameters from SSM]  Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by orr-levinger** [middyjs/middy#757]
What are the steps to reproduce this issue?
----------------------------------------

1. install "@middy/core": "^1.5.2",
2. intall "@middy/ssm": "^1.5.2",
3. install "middy": "^0.36.0",
4. install "aws-sdk": "^2.778.0",
5: wrap hanlder:
```
export const handler = middy(async (event: DynamoDBStreamEvent, context): Promise<void> => {
}).use(
  ssm({
    cache: true,
    cacheExpiryInMillis: 5 * 60 * 1000, // 5 mins
    names: {
      ALGOLIA_ADMIN_API_KEY: `serverless-algolia-admin-api-key`,
    },
    setToContext: true,
    throwOnFailedCall: true,
  })
);
```

What happens?
----------------------------------------

When running the lambda locally (NOT on aws)
i get:

>   console.error
>     [Failed to get parameters from SSM]  Cannot convert undefined or null to object
> 
>       at node_modules/@middy/ssm/index.js:87:19
> 
> 
> TypeError: Cannot convert undefined or null to object
> 
>     at Function.assign (<anonymous>)
>     at /Users/orrlevinger/bc/blind-chat-backend/node_modules/@middy/ssm/index.js:76:18
>     at Array.forEach (<anonymous>)
>     at /Users/orrlevinger/bc/blind-chat-backend/node_modules/@middy/ssm/index.js:75:22
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

What were you expecting to happen?
----------------------------------------

 I expect it to work normally 

Any logs, error output, etc?
----------------------------------------

>   console.error
>     [Failed to get parameters from SSM]  Cannot convert undefined or null to object
> 
>       at node_modules/@middy/ssm/index.js:87:19
> 
> 
> TypeError: Cannot convert undefined or null to object
> 
>     at Function.assign (<anonymous>)
>     at /Users/orrlevinger/bc/blind-chat-backend/node_modules/@middy/ssm/index.js:76:18
>     at Array.forEach (<anonymous>)
>     at /Users/orrlevinger/bc/blind-chat-backend/node_modules/@middy/ssm/index.js:75:22
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

What versions of software are you using?
----------------------------------------
**Node.js Version: v12.18.0

**Middy Version: "middy": "^0.36.0", "@middy/core": "^1.5.2", "@middy/ssm": "^1.5.2",

**AWS SDK Version: "aws-sdk": "^2.778.0",

**Comment by willfarrell** [comment]
First you're installing `middy@0.36.0` which isn't needed when using `@middy/core`. I hope that resolves your issue. If not, how are you running it locally? Just using `node lambda.js` or a 3rd party dependency?

Note that middy is currently on v2, with a v3-alpha planned for next month.

**Comment by orr-levinger** [comment]
removing the middy@0.36.0 didnt help
simply executing the js file with event and context on my machine no third party

**Comment by willfarrell** [comment]
When you invoke yourself using a simple script you'll need to handle AWS credentials or stub out the SSM call yourself.

**Comment by willfarrell** [comment]
Please re-open if issue persists
