### ISSUE TITLE
throwOnFailedCall remove from secrets-manager 

### ISSUE THREAD

**Issue by JimiPedros** [middyjs/middy#758]
Hi there, not an issue but more so a question; Is the any documentation for why throwOnFailedCall was removed from secrets-manager?
I am upgrading from version 1.0 to 2.5.3

**Comment by willfarrell** [comment]
v2 was a complete rewrite, especially the middlewares that interact with aws. The `throwOnFailedCall` option no longer made sense after the rewrite. We felt the additional complexity to continue supporting `{throwOnFailedCall:false}` didn't make sense. In the current version when `setToContext` (or setToEnv) is `true` it will throw an exception from the request when it fails. However, if you don't want it to fail (not sure why) you can still by handling the the setting to the context yourself.

**Comment by JimiPedros** [comment]
ok cheers Will, I've gone ahead and appended `.use(middyHttpErrorHandler())` to my middified handler
