### ISSUE TITLE
ajv packages version

### ISSUE THREAD

**Issue by Enase** [middyjs/middy#759]
Why ajv packages [version forced](https://github.com/middyjs/middy/blob/690884d43b9cd632aeca9a5eba1612160b987cd4/packages/validator/package.json#L49)?

It results in package duplicate almost for everyone how use it. Consode to use `"ajv": "^8.6.3"` instead.

**Comment by willfarrell** [comment]
It's best practice for stability and security. Prior to all releases we review all changes to every dependency prior to updating to ensure no breaking changes or inclusion of malicious code.

**Comment by Enase** [comment]
> It's best practice for stability and security.
It's totally true for the end user project and your approach makes it impossible.
