### ISSUE TITLE
http-multipart-body-parser can break UTF-8 encoded field content

### ISSUE THREAD

**Issue by ecdavis** [middyjs/middy#760]
What are the steps to reproduce this issue?
-------------------------------------------
1. Use the `http-multipart-body-parser` middleware with a handler.
2. Have the handler extract a field from the body and pass its content to `JSON.parse`
3. Send a valid multipart request containing a UTF-8 encoded field (not a file) containing a JSON object with a string containing a multi-byte character where at least one of the bytes is a control character. Which is another way of saying send a multipart request where this is one of the parts:
```
Content-Disposition: form-data; name=PartName
Content-Type: application/json; charset=utf-8

{"foo":"bar–"}
```
NB: ^ that's an en dash. There are other characters that trigger this behavior, too. Many of the characters on [this list](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Unicode_symbols), ditto the first two rows of [this list](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Letterlike_Symbols). Any two-byte character where the first byte is a printable latin1 character on its own and the second byte is a latin1 control character on its own is a decent test case.

What happens?
-------------
You get an error like `SyntaxError: Unexpected token  in JSON at position 11`

What were you expecting to happen?
----------------------------------
The multi-byte UTF-8 character to be preserved as part of the string in the JSON object.

Any logs, error output, etc?
----------------------------
Nah, but here's some code to repro:

*repro.js*:
```js
const middy = require("@middy/core");
const httpMultipartBodyParser = require("@middy/http-multipart-body-parser");
 
const baseHandler = async (event) => {
  const {
    body: {
      PartName: partContent,
    },
  } = event;
  return {
    statusCode: 200,
    body: JSON.stringify(
      JSON.parse(
        partContent,
      ),
    ),
  };
}
 
const handler = middy(baseHandler)
  .use(httpMultipartBodyParser());
 
module.exports = { handler };
```

*repro.test.js (the second test will fail)*:
```js
const { handler } = require("./repro");
 
describe("repro", () => {
  it("doesn't crash when a part contains an ASCII dash", async () => {
    const response = await handler(
      {
        headers: {
          "content-type": "multipart/form-data; boundary=TEST",
        },
        isBase64Encoded: false,
        body: `--TEST\r\nContent-Disposition: form-data; name=PartName\r\nContent-Type: application/json; charset=utf-8\r\n\r\n{"foo":"bar-"}\r\n--TEST--`,
      },
    );
    expect(response.body).toBe(`{"foo":"bar-"}`);
    expect(response.statusCode).toBe(200);
  });
 
  it("shouldn't crash when a part contains an en dash, but it does", async () => {
    const response = await handler(
      {
        headers: {
          "content-type": "multipart/form-data; boundary=TEST",
        },
        isBase64Encoded: false,
        body: `--TEST\r\nContent-Disposition: form-data; name=PartName\r\nContent-Type: application/json; charset=utf-8\r\n\r\n{"foo":"bar–"}\r\n--TEST--`,
      },
    );
    expect(response.body).toBe(`{"foo":"bar–"}`);
    expect(response.statusCode).toBe(200);
  });
});
```

Any other comments?
-------------------
In node.js, the `binary` encoding used by the middleware when writing to busboy's stream is actually an alias for `latin1`.

https://github.com/middyjs/middy/blob/main/packages/http-multipart-body-parser/index.js#L78
https://github.com/nodejs/node/blob/85d4cd307957bd35e7c723d0f1d2b77175fd9b0f/lib/buffer.js#L708

We've worked around this issue by vendoring the middleware and patching it to use the `utf-8` encoding when writing to busboy, but this really only works because we can rely on only ever receiving `utf-8` encoded fields, never files.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.16.1

**Middy Version:** `@middy/core` 2.5.2, `@middy/http-multipart-body-parser` 2.5.2

**AWS SDK Version:** N/A

**Comment by willfarrell** [comment]
Thanks for reporting.

I would have expected the default to be `utf8` to be consistent with the Busyboy options (`defCharset`). I'll write some unit tests see if this can be fixed within v2.x. I have a feeling it might have to wait for v3 to be safe for everyone.

**Comment by ecdavis** [comment]
Thanks for the prompt response @willfarrell, much appreciated.

**Comment by willfarrell** [comment]
Thanks you for doing such detailed investigation. Super helpful!

**Comment by willfarrell** [comment]
Change pushed to `main`, will be released under v3 (next few weeks)

**Comment by ecdavis** [comment]
Thanks again @willfarrell!
