### ISSUE TITLE
Extending error logging

### ISSUE THREAD

**Issue by shivang007** [middyjs/middy#766]
How can we extend the logging in the middleware?
As in, we want our own logger to log the stacks after attaching the mata data that we need, to index it in Elasticsearch, to be able to visualise it in Kibana.

**Comment by shivang007** [comment]
Continuation of our discussion at https://github.com/middyjs/middy/pull/762#issuecomment-1001889020

**Comment by willfarrell** [comment]
Have you checked out [`@middy/error-logger`](https://github.com/middyjs/middy/tree/main/packages/error-logger)? You can customize the `logger` option to transform and ship logs where ever you need. If you'd like to create a community middleware, please open a PR to add it to the list.

**Comment by shivang007** [comment]
Hi @willfarrell, 
yes I tested out @middy/error-logger, customising the logger option fulfils our requirements 👍
