### ISSUE TITLE
Content-Type header names should be handled as case-insensitive strings

### ISSUE THREAD

**Issue by rdelcampog** [middyjs/middy#767]
## What are the steps to reproduce this issue?
     1. Use `@middy/http-urlencode-body-parser` or `@middy/http-json-body-parser` middleware as the only middlewares
     2. Send a 'Content-type' header with mixed case

 ## What happens?

Body is not parsed as the middleware only handles `Content-Type` or `content-type` strict header names.

 ## What were you expecting to happen?

To parse the body even if the header contains non-standard header names (as header names should not be case sensitive according to [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html))

 ## What versions of software are you using?

 **Node.js Version:** 14

 **Middy Version:** 2.5.4

**Comment by willfarrell** [comment]
There is already a middleware that takes care of this for you, and reduces the need to duplicate code in multiple middlewares. See https://github.com/middyjs/middy/tree/main/packages/http-header-normalizer. You could also do this with ajv w/ the `transform` keyword (it supports mixed case enum coerce)
