### ISSUE TITLE
Slow processing of queue

### ISSUE THREAD

**Issue by ebisbe** [middyjs/middy#770]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Use sqs-partial-batch-failure package
2. Use the recommended usage
```
const middy = require("@middy/core")
const sqsBatch = require("@middy/sqs-partial-batch-failure")
const sqsJsonBodyParser = require("@middy/sqs-json-body-parser")

const originalHandler = ({ Records }) => {
  const recordPromises = Records.map(async ({ body }) => processEvent(body))
  return Promise.allSettled(recordPromises)
}

module.exports = {
  handler: middy(originalHandler).use([sqsJsonBodyParser(), sqsBatch()])
}
```

What happens?
-------------
The queue is processed super slow.  See screenshot. The queue starts processing all events with the above code and it's very slow. The moment I switch to not using the sqs-partial-batch-failure with 
```
module.exports.handler = async ({ Records }) => {
  const failedMessageIds = []
  let batch = {}

  for (const record of Records) {
    try {
      console.log(`Processing ${record.messageId}`)
      const bodyData = JSON.parse(record.body)
      await processEvent(bodyData, batch)
    } catch (e) {
      console.log(e)
      failedMessageIds.push(record.messageId)
    }
  }
  await table.batchWrite(batch)
  await flushQueue()

  return {
    batchItemFailures: failedMessageIds.map(id => ({ itemIdentifier: id }))
  }
}
``` 
The queue goes faster. The second iteration at 12 is with the fast code. 
![Screenshot 2022-01-04 at 13 15 23](https://user-images.githubusercontent.com/6747962/148197559-b70645c0-bb10-453a-97d4-373e20bb8cae.png)

What were you expecting to happen?
----------------------------------
Process queue should go faster.

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
The process event is exactly the same so I'm not sure what's happening. 

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14

**Middy Version:**  "@middy/core@^2.5.1": version "2.5.3"
"@middy/sqs-partial-batch-failure@^2.5.1": version "2.5.3"
**AWS SDK Version:** 2.1047.0 // 2.1031.0"

**Comment by willfarrell** [comment]
I did some refactoring to reduce the number of iteration over the `response` array (https://github.com/middyjs/middy/blob/release/3.x/packages/sqs-partial-batch-failure/index.js) which should help. However, with an array length of 10 I don't think that was the issue. I don't imagine the `Promise.allSettled` being the issue, it should the same or faster based on what code is run for each item.

When all are successful we allow lambda to handle the removal from the queue, I'm wondering if that is the issue. What does your `flushQueue()` do?

**Comment by ebisbe** [comment]
My `flushQueue()` is

```
const flushQueue = async () => {
  const messages = []
  for (const QueueUrl in Entries) {
    if (Entries[QueueUrl].length === 0) {
      console.log(`no events to flush for [${QueueUrl}]`)
      continue
    }
    do {
      const params = {
        Entries: Entries[QueueUrl].splice(0, 9),
        QueueUrl
      }
      messages.push(sqs.sendMessageBatch(params).promise())
    } while (Entries[QueueUrl].length > 0)
    console.log(`flushing all events for [${QueueUrl}]`)
  }
  const resp = await Promise.allSettled(messages)
  console.log(
    `all events flushed`,
    resp.filter(({ status }) => status !== "fulfilled")
  )
  Id = 1
}
```

Maybe just flushing the Queue and doing `batchWrites` instead of `put`s outside the `parseEvent()` is the real speed up. The `batchSize` is 5. So There are max 5 messages in the `flushQueue` and max 10 put operations on the `batchWrite`.

**Comment by willfarrell** [comment]
Thanks for sharing. I'm in the middle of writing v3, so now is the time to do breaking changes :).

Was `batchItemFailures` added as part of https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/? I think this is the source of the huge perf gains based on what I'm reading. I just pushed a change to https://github.com/middyjs/middy/blob/release/3.x/packages/sqs-partial-batch-failure/index.js, way simpler! Still needs to be tested, but take a look and let me know what you think.

**Comment by ebisbe** [comment]
> Was `batchItemFailures` added as part of https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/?

Yes. You can catch the error and send which events have failed like in the first sample code. 

I will take a look at that file later.

**Comment by ebisbe** [comment]
I don't know why yesterday I didn't saw your last commit. Yes that change is exactly what we need ( after some testing ).

**Comment by willfarrell** [comment]
Perfect! Thanks so much for testing! It will be in the v3-alpha release.

**Comment by ebisbe** [comment]
> Perfect! Thanks so much for testing! It will be in the v3-alpha release.

OPS! I didn't meant that I did any tests. I meant that some tests should be needed apart from reading the code

**Comment by willfarrell** [comment]
lol, don't worry I wrote unit tests and ran an e2e/benchmark test on a live system already :).

**Comment by ebisbe** [comment]
I'd like to see those benchmarks pre/post if they are somehow available.

**Comment by willfarrell** [comment]
I'd have to re-run it. It was >25% faster (11min -> 8min to clear queue) for a real world use case that batch resizes images. I can see a controlled benchmark being much better (closer to what you're seeing).
