### ISSUE TITLE
Typescript support to override getOrigin function

### ISSUE THREAD

**Issue by garbray** [middyjs/middy#776]
https://github.com/middyjs/middy/blob/bb910c81f85e62b3a0e78d3355a4e7330d309872/packages/http-cors/index.d.ts#L3

Currently is not possible to override the `getOrigin` function if you are using typescript since the interface doesn't have it, I believe this is the missing piece:

```javascript
  getOrigin?: (incommingOrigin: string, options: Options) => string
```

**Comment by willfarrell** [comment]
Would you like to open a PR to fix this?
