### ISSUE TITLE
Type mismatch for default type of Request.error

### ISSUE THREAD

**Issue by nem035** [middyjs/middy#791]
In the code, the request is [initialized with `error` being `undefined`](https://github.com/middyjs/middy/blob/main/packages/core/index.js#L13) but in the types the error is [defined as `TErr | null`](https://github.com/middyjs/middy/blob/main/packages/core/index.d.ts#L25), which doesn't cover `undefined`.

This means that, if we use the types from the library, we cannot define request objects without the `error` field or with the `error` field being `undefined`, even though the code itself allows it.

Instead of making them both `|| null`, it seems that it would be more accurate to make them `|| undefined`? 

```ts
interface Request<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext> {
  event: TEvent
  context: TContext
  response: TResult | null
  error: TErr | null // <-- here should account for undefined
  internal: {
    [key: string]: any
  }
}
```

[Here's a TS playground to demonstrate the problem
](https://www.typescriptlang.org/play?ssl=23&ssc=1&pln=24&pc=1#code/JYWwDg9gTgLgBAbwFBzgYQgOxgUwB7wCGAznADKEgBGAJoRtvjADRIC+cAZlBCHAOSEA7sQC0AG0q1C-ANxJQkWHBDAaNAJ5ceffgAFV6jQHoAxtBxykSc5mLxbuAnAC8iFHFOFx4qoVMA1gDqhMAwxABi0ACi4DAa0QBuONhkEBBgAFxwMFAArjisqJx5mKYwwFgAcpQ42fw0eSAgGvxFXKXllZgAajhQxN31jc2t7cCYiRABODQRnRVYAIJQmMNNLW0eIDgg0BpkoGEAkpgAsgBC66NbqMLEAEo4AI4F9sc015vt4hAA5gBxHh5MA1HZfMYeX5-ADKuRwlDBdQEI2+Hj+OBgTxAoUwEz+ABVQDhTmdgD5gMRsgAKACUrgAfHAAMztGhYZF0xmINjtTihcQ0+kuJkIXkeYh5UymHCzIXcsWsNjyGxYexwKAvN4wbKGTQAOierxw6rcyFQ-R4UGypRoOE4E1m7U1xEgdmRtvtjpo7RwyWw2UVHkcTHGjFW3kDbCQxmMcAACjwwP14gJLdB+HBKSpKYNMH8s5gchpkwIEHA-SkdTzZJ4sE5q+WvD4-IEQmFIjE4gl-TA0hlsrkCrWSmVFpgkdl7FB8SOFt0+gMhnBp7PC1MZnN58tVlPcmudnsoAcjjBSVcV-v87X7kbtR89zPr3BoUCICDJ5en39a-q-3AABYVAsOA-31WtJWlWVPjgLkRTgKY1FrZUNRNN1iA9TA7QdTBZlrCZcAjQUazgNhMyoPJ4E1V5gE1GhC2LUt+DvE0YAAHkITANGYOBOO4uBoigK0eIYBsGX4fVqQAJgAdgAgBGWl2CAA)

Technically, the correct type should most likely be `any`, as explained in the reasoning for [TS1196](https://typescript.tv/best-practices/error-ts1196-catch-clause-variable-type-annotation/).

**Comment by nem035** [comment]
Let me know if this issue makes sense and I'll make a PR :+1:

**Comment by willfarrell** [comment]
`undefined` is on purpose to keep the code self documenting and mark as unset. `null` could be a valid value someone want to set the error or response to so shouldn't be used as a default. You'll see this pattern all through middy.

I'm open to a PR to update the TypeScript defs to make them more accurate.

**Comment by calvin-summer** [comment]
@nem035 good catch. the fix would be to update `Request` to either have `error?: TErr | null` or `error: TErr | null | undefined`
i'm not familiar enough with the usage of this interface to know which is more appropriate.
I modified you TS Playground with something equivalent to demonstrate [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYQgOxgUwB7wCGAznADKEgBGAJoRtvjADRIC+cAZlBCHAOSEA7sQC0AG0q1C-ANxJQkWHBDAaNAJ5ceffgAFV6jQHoAxtBxykSc5mLxbuAnAC8iFHFOFx4qoVMA1gDqhMAwxABi0ACi4DAa0QBuONhkEBBgAFxwMFAArjisqJx5mKYwwFgAcpQ42fw0eSAgGvxFXKXllZgAajhQxN31jc2t7cCYiRABODQRnRVYAIJQmMNNLW0eIDgg0BpkoGEAkpgAsgBC66NbqMLEAEo4AI4F9sc015vt4hAA5gBxHh5MA1HZfMYeX5-ADKuRwlDBdQEI2+Hj+OBgTxAoUwEz+ABVQDhTmdgD5gMRsgAKACUrgAfHAAMztGhYZF0xmINjtTihcQ0+kuJkIXkeYh5UymHCzIXcsWsNjyJDxMA4OBnCA0YCcYCzJ6vHD2VxwADyqhgAB5DJoAHSGt4sAT9HhQfhMgBk7lQrugAH5sraNA6Xk6ANr8P3ugC67GsthNUDDxpg2S1Or1BpTJrcyF9UDd2VKNBwesws3ayeIkDsyJLZYmlY8OGS2Gyio8jiY40Yq28HbY7CAA).

regarding [TS1196](https://typescript.tv/best-practices/error-ts1196-catch-clause-variable-type-annotation/), it might be more accurate to adjust the type default to be `TErr = unknown`, although that type isn't very helpful.
