### ISSUE TITLE
`event-normalizer` should parse SNS-SQS messages

### ISSUE THREAD

**Issue by vicary** [middyjs/middy#793]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a SQS that subscribes to an SNS topic.
2. Adds a Lambda trigger to the SQS queue.
3. Log the message body.

What happens?
-------------
`event-normalizer` only unwraps the SQS part of the message. It is a common practise as a event-driven, fanout design that events are sent to a SNS FIFO topic, and then for each consumer Lambda, there will be a FIFO SQS queue in between.

These lambdas receive a doubly encoded message, where the first layer is the SQS Record with `Records: [...]`, inside the records `body`, there is a single `SNSMessage` (neither `SNSEvent` nor `SNSEventRecord`) as a JSON encoded string.

What were you expecting to happen?
----------------------------------
I think `event-normalizer` should also parse the SNS Message such that I can directly access the contents with `event.Records[0].body.Message`.

Any logs, error output, etc?
----------------------------
`npx sls invoke local -f MyTestFunction -d '{"Records":[{"body":"{\"Message\":\"{\\\"foo\\\":\\\"bar\\\"}\"}"}]}'`

Any other comments?
-------------------
N/A

What versions of software are you using?
----------------------------------------
**Node.js Version:** 17.3.1

**Middy Version:** 3.0.0-alpha.5 for both `@middy/core` and `@middy/event-normalizer`

**AWS SDK Version:** 2.982.0

**Comment by willfarrell** [comment]
`event-normalizer` should be recursive for certain events that can be nested. Here is a test we have for this: https://github.com/middyjs/middy/blob/release/3.x/packages/event-normalizer/__tests__/index.js#L31

Is there another type of SNS event we're missing or miss detecting? Can you include the a link to the AWS documentation showing the event that isn't working?

**Comment by vicary** [comment]
From the quoted test, the `.Sns` part in `.Sns.Message` is extraneous; from TypeScript perspective, it is `SNSEventRecord`.

But what I got in SNS-SQS chains is the only `.Message`, which is `SNSMessage`.

```ts
snsEvent.Records[0].Sns.Message = JSON.stringify(sqsEvent)
```
https://github.com/middyjs/middy/blob/release/3.x/packages/event-normalizer/__tests__/index.js#L39

To explain in terms of test code, it should go like this:

```ts
const snsEvent = createEvent.default('aws:sns')
snsEvent.Records[0].Sns.Message = JSON.stringify({foo:"bar"})
const sqsEvent = createEvent.default('aws:sqs')
sqsEvent.Records[0].body = JSON.stringify(snsEvent.Records[0].Sns);
```

**Comment by willfarrell** [comment]
Thanks for sharing, I'll have to whip up a test in AWS and maybe reach out to AWS to see why it deviates from the docs (https://docs.aws.amazon.com/lambda/latest/dg/with-sns.html).

**Comment by willfarrell** [comment]
Fix has been pushed to `release/3.x`. Thanks again.
