### ISSUE TITLE
[v2.5.6] @middy/utils has been published differently (breaking)

### ISSUE THREAD

**Issue by maximepichou** [middyjs/middy#794]
Hello,

I'm here to report a problem with the lib @middy/utils@2.5.6.

The lib has been published differently from previous version.

For example in index.js of the version 2.5.5 we have :
```javascript
const canPrefetch = options => {
  return !(options !== null && options !== void 0 && options.awsClientAssumeRole) && !(options !== null && options !== void 0 && options.disablePrefetch);
}; // Internal Context

```
But in the version 2.5.6 we have :
```javascript
const canPrefetch = (options) => {
  return !options?.awsClientAssumeRole && !options?.disablePrefetch
}
```
Because of these changes, my project can't be transpiled with babel normally:
```
ERROR in ./node_modules/@middy/util/index.js 61:18
Module parse failed: Unexpected token (61:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const canPrefetch = (options) => {
>   return !options?.awsClientAssumeRole && !options?.disablePrefetch
| }
| 
 @ ./node_modules/@middy/http-json-body-parser/index.js 30:12-34
 @ ./node_modules/myproject/lib/lambda/http-handler.js
 @ ./node_modules/myproject/lib/index.js
 @ ./src/functions/transcripts/get.js
```

Do you know what happened with this particular version ?

Thank you for your time,

Kind regards,
Maxime

What versions of software are you using?
----------------------------------------
**Node.js Version:** : 14.17.3

**Middy Version:** 2.5.6

**AWS SDK Version:** 2.897.0

**Comment by willfarrell** [comment]
Thanks for reporting! I published manually and I guess I forgot to transpiling first. I'll make it a priority to get a new release out to fix this.

**Comment by rreubenreyes** [comment]
Hi there, just wanted to report that this is affecting us too, but with a slightly different failure condition: There is optional chaining in the package source which cannot be interpreted by Node 12.

```js
/node_modules/@middy/util/index.js:61
  return !options?.awsClientAssumeRole && !options?.disablePrefetch
                  ^

Uncaught SyntaxError: Unexpected token '.'
```

We've got Node 12 runtimes with a hard dependency lock on `@middy/validator@2.5.3`, which transitively requires `@middy/util@^2.5.3`. We don't have a way to lock this down in the very short term.

Digging into the dependency graph, the engine requirement on `>=2.5.6` is `node >= 12`. It sounds like a transpile step is involved; is it correct to assume that this transpile step will make future minor/patch versions safe on Node 12 again, or should we act as if the minimum version is now 14, as suggested by this issue?

Thanks.

**Comment by willfarrell** [comment]
Turns out I did transpile, just with new build dependencies causing the issue. Sorry about that, and thank you for you patience. `2.5.7` now published. I also made all deps strict, no mater where they are from, ensuring unexpected updated don't break peoples use of middy.

Please re-open if `2.5.7` is causing any further issues.
