### ISSUE TITLE
http-cors: Add "Vary: Origin" if "cacheControl" option is set

### ISSUE THREAD

**Issue by TPME** [middyjs/middy#796]
As documented on https://httptoolkit.tech/blog/cache-your-cors/, it would be good to receive the `Vary: origin` header if the `cacheControl` option is set. This is required for CDN Caches of CORS.

Edit: Actually, I found that as I'm using AWS, the CORS request never hits my lambda. So I have to solve my problem somewhere else. However, it could potentially still be a good addition to this middleware?

**Comment by TPME** [comment]
This has been requested before: https://github.com/middyjs/middy/issues/374

**Comment by willfarrell** [comment]
CORS requests can reach your lambda depending on your architecture and configuration. I've been successful passing it through CloudFront -> API Gateway -> Lambda

I think it has value in being included. Would you like to open a PR against the `release/3.x` branch?

**Comment by TPME** [comment]
> CORS requests can reach your lambda depending on your architecture and configuration. I've been successful passing it through CloudFront -> API Gateway -> Lambda

Do you mind sharing how you accomplished this? I'd be very interested.

> think it has value in being included. Would you like to open a PR against the release/3.x branch

Sure, let me get back to you soon.

**Comment by willfarrell** [comment]
You have to whitelist the `Origin` header have `OPTIONS` in the allowed methods in CloudFront, I think that was it.

I saw you like #374, we do allow `{ getOrigin: () => {} }` would this also allow you to achieve this? If this logic is part of the standard it should be the default built into the middleware.

**Comment by willfarrell** [comment]
I've added some new logic, see https://github.com/middyjs/middy/blob/release/3.x/packages/http-cors/index.js#L73
