### ISSUE TITLE
http-cors: Return Vary header when specific Access-Control-Allow-Origin value is set

### ISSUE THREAD

**Issue by teuber789** [middyjs/middy#797]
**Is your feature request related to a problem? Please describe.**
According to MDN, the server should return a `Vary` header when returning an `Access-Control-Allow-Origin` header with an explicit domain (see [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching)). Currently, middy/http-cors isn't doing this when configured to return a specific domain (or a list of domain).

**Describe the solution you'd like**
Whenever middy/http-cors is configured with a specific value (either the `origin` or `origins` properties), a `Vary` header containing the allowed origin is returned with the server response.

**Comment by willfarrell** [comment]
Thanks for reporting! Would you be able to put a PR together for this change against `feature/3.x`?

Something like this?
```
...
if (!existingHeaders.includes('Access-Control-Allow-Origin')) {
      const eventHeaders = request.event.headers ?? {}
      const incomingOrigin = eventHeaders.origin ?? eventHeaders.Origin
      const allowOrigin = options.getOrigin(incomingOrigin, options)
      request.response.headers[
        'Access-Control-Allow-Origin'
      ] = allowOrigin
      if (allowOrigin !== '*') {
        request.response.headers.Vary = 'Origin'
    }
    ...
```

Looks like this might be related to #796

**Comment by willfarrell** [comment]
Just reading through https://httptoolkit.tech/blog/cache-your-cors/

maybe we need a new option `{ vary: 'Origin' }` to allow overriding when necessary.

**Comment by willfarrell** [comment]
I've added some new logic, see https://github.com/middyjs/middy/blob/release/3.x/packages/http-cors/index.js#L73
