### ISSUE TITLE
Unrelated error when providing null/undefined logger to InputOutput middleware

### ISSUE THREAD

**Issue by naorpeled** [middyjs/middy#799]
**Describe the bug**
When providing a null/undefined logger to the InputOutput middlware,
the error I'm getting is: `Middleware must be an object containing at least one key among "before", "after", "onError"`
instead of a more specific error.
I've encountered this while using several middlewares and it took me some time to realize that this middleware has caused the crash. 

**To Reproduce**
How to reproduce the behaviour:
1.
```typescript
use(inputOutputLogger({ logger }))
```
2. Input 
```typescript
  const logger = null;
```

3. Unit test 
```typescript

test('It should not log anything in case of a null/undefined logger', async (t) => {
  const logger = null;

  const handler = middy((event, context) => {
    return { message: 'hello world' }
  })

  try {
    handler.use(inputOutputLogger({ logger }))
  } catch (e) {
    t.is(
      e.message,
      'Middleware must be an object containing at least one key among "before", "after", "onError"'
    )
  }
})


```
4. Thrown error
'Middleware must be an object containing at least one key among "before", "after", "onError"'

**Expected behaviour**
I expect one of the two following options:
1) no-op functions in before/after/onError.
I think doing nothing makes more sense than throwing an error in case someone doesn't want any logs in specific scenarios.
2) a more precise error.

Would love to create a pull request that handles this scenario if you think one of those directions fit.

**Comment by willfarrell** [comment]
Thanks for reporting. Improving error messaging is something we're working on for v3. I'd be happy to receive a PR for this (branch from `release/3.x`).

I would say update `if (typeof logger !== 'function') logger = null` to throw an error instead with a message starting with `[input-output-logger] ...`. This will allow the option of a noop function, which can be added to the README.

remove the logic base on logger being null
```
return {
    before: logger ? inputOutputLoggerMiddlewareBefore : undefined,
    after: logger ? inputOutputLoggerMiddlewareAfter : undefined,
    onError: logger ? inputOutputLoggerMiddlewareOnError : undefined
  }
```

I think that should do it. What do you think?

**Comment by naorpeled** [comment]
> Thanks for reporting. Improving error messaging is something we're working on for v3. I'd be happy to receive a PR for this (branch from `release/3.x`).
> 
> I would say update `if (typeof logger !== 'function') logger = null` to throw an error instead with a message starting with `[input-output-logger] ...`. This will allow the option of a noop function, which can be added to the README.
> 
> remove the logic base on logger being null
> ```
> return {
>     before: logger ? inputOutputLoggerMiddlewareBefore : undefined,
>     after: logger ? inputOutputLoggerMiddlewareAfter : undefined,
>     onError: logger ? inputOutputLoggerMiddlewareOnError : undefined
>   }
> ```
> 
> I think that should do it. What do you think?

Sounds good, created a PR that implements it. Let me know what you think.
