### ISSUE TITLE
"Missing Content-Type" due to case sensitive check while using @middy/http-multipart-body-parser

### ISSUE THREAD

**Issue by ptruskowski** [middyjs/middy#803]
**Describe the bug**
When using the `http-multipart-body-parser` plugin, I receive a "Missing Content-Type" even when the Content-Type header exists on the request. 

I was able to determine there is a case-sensitive bug in the dependent package, BusBoy, that is unable to parse my Pascal case "Content-Type" because it expects a lowercase "content-type". 

![image](https://user-images.githubusercontent.com/18731994/152470450-5292d3cc-6d94-482e-8bd9-1233d47d448a.png)

I can workaround this by making the Content-Type lowercase, but it took me some time to track down the culprit. 

![image](https://user-images.githubusercontent.com/18731994/152470614-8aa8008f-18b2-4ce1-8e6d-a0de095eaba7.png)

I am currently using the latest version of the multipart package: 
* https://www.npmjs.com/package/@middy/http-multipart-body-parser

![image](https://user-images.githubusercontent.com/18731994/152470726-49b3e863-79cf-4d58-9330-6588bcf80002.png)

**To Reproduce**
How to reproduce the behaviour:
1. Setup middy using `.use(httpMultipartBodyParser())`
2. Setup middy using `middyHandler.onError(...)`
3. Send a multipart body from Insomnia/Postman with pascal case `Content-Type=multipart/form-data`
4. Observe the `onError` method is invoked with the message "Missing Content-Type"

![image](https://user-images.githubusercontent.com/18731994/152470855-8bafc558-ad70-48b9-b585-f35968005a09.png)

![image](https://user-images.githubusercontent.com/18731994/152471135-14c8f7fa-2da6-4b28-a0b5-9ed4e496a0e4.png)

**Expected behaviour**
Middyjs appears to allow uppercase and lowercase from my debugging. 

![image](https://user-images.githubusercontent.com/18731994/152471533-856f23e0-e581-4913-8a8b-600b17a30600.png)

However, once it creates a BusBoy object, the Content-Type is now case sensitive. 

I realize this isn't a bug in the Middy code. However, I thought of a couple options: 
1. Can Middy code a patch to force case insensitivity?
2. Could Middy pass the Content-Type as lowercase in when passing the headers to BusBoy?
3. Does a BusBoy fix already exist and Middy needs to update the package version? 

If none of these apply, I can submit a request to BusBoy to fix and then request Middy update the package. 

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy:
   - "@middy/core": "^1.5.2"
   - "@middy/http-multipart-body-parser": "^2.5.7"
 - AWS SDK: 
   - "aws-sdk": "^2.991.0"

**Additional context**
N/A

**Comment by ptruskowski** [comment]
I discovered that the Middy package is using an older version of `busboy: "0.50"`
- https://github.com/middyjs/middy/blob/2.5.7/packages/http-multipart-body-parser/package.json

However, the main Busboy page is currently on v1.40. 
- https://www.npmjs.com/package/busboy

Although from the looks of it, they still require lowercase: 
- https://github.com/mscdex/busboy/blob/v1.4.0/lib/index.js

![image](https://user-images.githubusercontent.com/18731994/152472557-dd7adcf0-bc69-4554-a3eb-eb790b4aa80e.png)

**Comment by willfarrell** [comment]
Thanks for reporting, and with such detail. 

We have already corrected this in v3.0.0-alpha.x (https://github.com/middyjs/middy/blob/release/3.x/packages/http-multipart-body-parser/index.js#L43) to allow for both of the most likely cases. It think there is value in this logic being apart of busboy for those not using middy.

busyboy only recently received a burst of releases. We try to keep all dependencies up to date to mitigate security risks. These updates are applied to the `release/3.x` branch.
