### ISSUE TITLE
Middy SSM Should Warn or Fail when name is used instead of fetchData

### ISSUE THREAD

**Issue by ksparakis** [middyjs/middy#805]
**Describe the bug**
In using an older version of middy/ssm we were using "name" instead of "fetchData"
with the update where things switched to fetchData, middy ssm should throw an error or warning, instead of failing quietly. 
Took way too long of scratching around to figure out that it was ssm failing us, then figuring out why.

**To Reproduce**
How to reproduce the behaviour:

`      ssm({
        cache: true,
        name: {
          SECERET_RETRIEVED: 'key/location'
        },
        setToContext: true,
      })`

**Expected behaviour**

Since name seems to have been deprecated, we should be getting an error or warning that this has occurred. To warn fellow developers to update, and have an idea of whats going on. :) 

**Environment (please complete the following information):**
 - Node.js: LTS/Fermium
 - Middy: 2.5.7
 - AWS SDK 2.723.0

**Additional context**

**Comment by willfarrell** [comment]
Sorry to hear you had to go digging to find a breaking change. 

We try to draw attention to breaking changes in our upgrade documentation, but, like all documentation it can be better.  I started adding `[Breaking Change]` beside items that change in the [UPGRADE.md](https://github.com/middyjs/middy/blob/release/3.x/docs/UPGRADE.md) for v3. 

That said, I would love have to have a way to add stricter option validation and developer guidance built in. I see lots of value in bringing more attention to breaking changes at runtime. The trick is how without affecting bundle size and cold start performance. 

For both approaches I'm open to ideas on how we can improve middy.

**Comment by willfarrell** [comment]
Had an idea. We could include something like this in each middleware:

```javascript
export const migrationOptionsCheck = (opts) => {
  if (process.env.DEBUG !== 'middy') return options

    if (options.oldName !== undefined) {
      console.warn(`oldName has been renamed to newName`)
      options.newName = options.oldName
    }
    // ...
 
  return options
}

const middleware = (opts) => {
  const options migrationOptionsCheck({...defaults, ...opts})
  // ...
}
```

I would want to confirm that popular tree sharking libs could remove this extra code that doesn't need to be in production. Thoughts? 

cc @lmammino

**Comment by willfarrell** [comment]
After multiple discussions on this we have decided to not include option checking for those migrating between major releases.

Summary of our reasoning:
1. Adds additional logic that should not be needed in production
2. increases bundle size
3. We do provide TypeScript definitions
4. We provide a detailed list of breaking changes in our upgrade documentation
5. You should have integration or end-2-end testing in place that should catch any changes.

We acknowledge that documentation can always be better and is something we're continuously working on. Thanks again for raising this issue, we may revisit it as Middy grows.
