### ISSUE TITLE
UnprocessableEntityError in JsonBodyParser

### ISSUE THREAD

**Issue by abdelrhmanmostafa** [middyjs/middy#811]
**Describe the bug**
I'm having an issue with the JsonBody Parser middle ware 

**the code**
`export const handler = middy(async (event: MiddyEvent, context: MiddyContext): Promise<APIGatewayProxyResultV2> => {`
`	try {`
`		const { db } = context;`
`		return successfulResponse({ health: 'ok', event: event.body });`
`	} catch (e) {`
`		console.error(e);`
`		return internalServerError((e as any).message);`
`	}`
`})`
`	.use(httpJsonBodyParser())`
`	.use(KnexConnection());`
i'm using SAM to serve the endpoints locally and i'm calling the end-point using post-man with this payload
`{
	"title": { "en": "test title en", "ar": "test title ar"},
	"body": { "en": "test body en", "ar": "test body ar" },
	"redirection": "aubsahcbjasahbkajk",
	"scheduled_time": 1645527952697,
	"author_id": "6208fd15bc9d380068f1de08"
}`
with the header `Content-Type : application/json`

if the content-type header is present the end-point throws 502 with error

`{'errorType': 'UnprocessableEntityError', 'errorMessage': 'Content type defined as JSON but an invalid JSON was provided', 'trace': ['UnprocessableEntityError: Content type defined as JSON but an invalid JSON was provided', '    at ye (/var/task/index.js:1:6930)', '    at before (/var/task/index.js:1:7601)', '    at w (/var/task/index.js:1:2532)', '    at _ (/var/task/index.js:1:1917)', '  
  at Runtime.a [as handler] (/var/task/index.js:1:1314)', '    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)']}`

if not the function succeed but the body is not parsed

**Environment :**
 - Node.js: 16
 - Middy/Core and JsonBodyParser: 2.5.7

**Comment by willfarrell** [comment]
All `http-json-body-parser` does is `JSON.parse(event.body)`. I'm not familiar running SAM locally so cannot help there. Can you write a unit test that can that can reproduce this outside of SAM? Logging before `.use(httpJsonBodyParser())` will better show what the root issue is.
