### ISSUE TITLE
setTimeout executes the "before" middleware after handler

### ISSUE THREAD

**Issue by nikoskous** [middyjs/middy#812]
**Describe the bug**
I am coming from NodeJS with express. 
Based on middy documentation the pipeline of middlewares is executes from before to after.
By adding a setTimeout with 5 sec delay on a "before" middleware, it executes first the handler and after the middleware.
I think its a problem because there is no ".next()" like express, in order to allow to middleware to continue.
Is there any way to run the middlewares like promises or something like that?

**Additional context**
`const isAdmin = (): middy.MiddlewareObject<APIGatewayProxyEvent, APIGatewayProxyResult> => {

  const before: middy.MiddlewareFunction<APIGatewayProxyEvent, APIGatewayProxyResult> = async (
    request
  ): Promise<void> => {
    const token = request.event.headers['x-auth']
    if (!token) {
      setTimeout(() => {
        console.log("error")
      }, 1000)
    } else {
      
      setTimeout(() => {
        console.log(token)
      }, 1000)
    }
  }

  return {
    before
  }
}`

**Comment by willfarrell** [comment]
Middy is working as intended. We deprecated legacy callbacks over a year ago. If you want to wait using `setTimeout`, it needs to be a promise and `await`ed.

```js
// import {setTimeout} from 'timers/promises` // if availible
// polyfill
const setTimeoutAsync = (delay) => new Promise((resolve) => {
	setTimeout(() => {
		resolve()
	}, delay)
})

const timeoutMiddleware = () => {
  const beforeTimeoutMiddleware = async () => {
    await setTimeoutAsync(1000)
  } 
}
```

However, it looks like you're trying to ensure your authentication call has a consistent minimum duration. In this case you might want to set it the timeout in the `before` and `await` in the `after`. This will ensure no matter what logic runs, the await will fill in the remaining duration before returning.
