### ISSUE TITLE
Can i use other middleware in my custom middleware 

### ISSUE THREAD

**Issue by abdelrhmanmostafa** [middyjs/middy#813]
**Is your feature request related to a problem? Please describe.**
i'm creating handler that serves 4 HTTP methods ['POST', 'GET', 'DELETE', 'PUT'] 2 of them which needs input validation i.e ['POST', 'PUT'] while the other 2 doesn't need input validation

**Describe the solution you'd like**
i'd like to be able to pass schema per method to the validator 

**Describe alternatives you've considered**
i tried creating a custom middleware that checks the event method and assign input schema based on the method but i'd like to be able to use the validation middleware inside my custom middleware

it would be helpful for the validation middleware to have either and option for a specific method validation or to have an option to receive the schema from an internal variable that i can set from another middleware

**Comment by willfarrell** [comment]
Checkout the new `http-router` coming in v3 (https://github.com/middyjs/middy/tree/release/3.x/packages/http-router). How to do this is in the example. For security reason you should always validate your inputs, checking if there are no additional properties is still validation. See [ASVS 5.1 Input Validation](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v51-input-validation)

On the question of nested middleware, I wouldn't recommend it.

**Comment by abdelrhmanmostafa** [comment]
the `http-router` is great. this is exactly what i need. 

the issue with the current validator is what if a method doesn't require input at all(the current situation), what if 2 methods requires 2 different schemas, the current validator accept only one schema and i need to change the schema based on the method of the request so this can only be achieved through nested middleware.

**Comment by willfarrell** [comment]
`http-router` allows the `handler` to be a response from `middy().use(...).handler(...)`. This means you can have different validation middleware on each routable handler while having shared middleware connected the `http-router`. It's kinda hard to put in to words.
