### ISSUE TITLE
Document cacheExpiry

### ISSUE THREAD

**Issue by kaihendry** [middyjs/middy#819]
It's not clear when I read how cacheExpiry works https://github.com/middyjs/middy/blob/main/packages/ssm/index.js

Basically my issue is that I need to fetch/cache https://example.com/.well-known/jwks.json for an hour.

It's not super clear how I do that with middy. 😅

Perhaps an example could be added to https://github.com/middyjs/middy#request-caching--internal-storage ?

**Comment by willfarrell** [comment]
cacheExpiry is how long fetch data responses should be cached for. `-1` to cache forever, `0` to never cache, 60*60*1000: cache for 1 hour in ms.

**Comment by kaihendry** [comment]
Sorry I don't understand, say I need to cache:

* 1hr https://example.com/.well-known/jwks.json
* 1min http://worldtimeapi.org/api/timezone/Asia/Singapore

Is this the construct I should be leveraging? Or is there other middleware I can look at please?

**Comment by willfarrell** [comment]
`cacheExpiry` is an option that applies to certain middleware only (ie ssm, sts). If you need to cache data not stored in an AWS service you'll need to create your own middleware to fetch and cache.

**Comment by kaihendry** [comment]
Is there any examples of how to do that I could please look at?
