### ISSUE TITLE
Proposed Middleware: HTTP Form Method Override

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#820]
When building forms using progressive enhancement, html only allows submission using `GET` or `POST`. It's common practice to use `_method` to override the method before routing. This middleware could be used before `@middy/http-router` in these use cases. See https://kit.svelte.dev/docs/routing#endpoints-http-method-overrides for more details.

**@middy/http-form-method-override**
```javascript
const defaults = {
  overrideParameter: '_method'
}

const httpFormMethodOverride = (opts = {}) => {
  const options = { ...defaults, ...opts }

  const httpFormMethodOverrideBefore = async (request) => {
    const { queryStringParameters, body, version } = request.event
    const method = queryStringParameters?.[options.overrideParameter] ?? body?.[options.overrideParameter]
    if (!method) return
    
    if (version === '2.0) {
      event.requestContext.http.method = method
      event.requestContext.routeKey = event.requestContext.routeKey.replace(/^[A-Z]+ /, `${method} `)
    } else {
      request.event.httpMethod = method
    }
  }
  
  return {
    before: httpFormMethodOverrideBefore
  }
}
```

**Comment by lmammino** [comment]
It makes a lot of sense to have something like this.

Only one question: should we limit the values for the parameter to a subset of methods (e.g. `PUT`, `PATCH`, `DELETE`) and/or make the subset configurable?

**Comment by willfarrell** [comment]
Methods can be limited at the API Gateway layer or during the input validation. What do you think about the middleware name? Remove `form`?

**Comment by willfarrell** [comment]
Closing for now. If you're reading this and think it would be helpful, please comment or open a PR to include.
