### ISSUE TITLE
Add white background to middy-middleware-engine.png

### ISSUE THREAD

**Issue by munierujp** [middyjs/middy#821]
**Is your feature request related to a problem? Please describe.**
README images are difficult to see for dark theme users.

**Describe the solution you'd like**
Add white background to `middy-middleware-engine.png`.

**Describe alternatives you've considered**
no

**Additional context**
<img width="851" alt="スクリーンショット 2022-03-31 19 21 00" src="https://user-images.githubusercontent.com/20086673/161034120-7d387784-b474-44c7-91b9-99cac097d110.png">

**Comment by willfarrell** [comment]
Thanks for reporting. We are aware of this. We're working on a new documentation site that will take this into consideration.

**Comment by willfarrell** [comment]
https://middy.js.org/docs/intro/how-it-works
