### ISSUE TITLE
Struggling to mock middleware

### ISSUE THREAD

**Issue by kaihendry** [middyjs/middy#823]
**Describe the bug**
I need to mock away @middy/secrets-manager in order to test a function

**To Reproduce**
https://github.com/kaihendry/jest-mock-middleware

  ● Test suite failed to run

    Cannot find module 'aws-sdk/clients/secretsmanager' from 'node_modules/@middy/secrets-manager/index.js'

**Expected behaviour**

Test to run

**Comment by willfarrell** [comment]
You can view mocking examples within the tests. This is why we allow the ability to pass in sdk client. You'll still need to have `aws-sdk` installed as a devDependency.

sinon: https://github.com/middyjs/middy/blob/main/packages/secrets-manager/__tests__/index.js
jest: https://github.com/middyjs/middy/blob/1.x/packages/secrets-manager/__tests__/index.js

**Comment by kaihendry** [comment]
Thanks! I got there in there end, once I was careful to mock before importing the handler.

https://github.com/kaihendry/jest-mock-middleware/blob/main/index.test.js
