### ISSUE TITLE
tRPC middleware

### ISSUE THREAD

**Issue by DaniAkash** [middyjs/middy#826]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
[tRPC](https://trpc.io/) provides an easy way to build end to end typesafe APIs. We would like to have a middleware to easily add tRPC to our existing lambda functions.

**Describe alternatives you've considered**
Currently building a middleware ourselves in our team, would be happy to share if we have any success with it

**Additional context**
Existing tRPC middlewares:
- Express: https://trpc.io/docs/express
- Fastify: https://trpc.io/docs/fastify

**Comment by willfarrell** [comment]
Thanks for the request! Looks like a cool project. I don't think including tRPC as part of core middy packages is a good fit at this time. However, I think others would find value in using such a middleware. Happy to accept a PR to include it as part of our community middleware once it's ready, if you're willing to share.
