### ISSUE TITLE
Unit tests is failing with TypeError: Cannot read property 'unmarshall' of undefined

### ISSUE THREAD

**Issue by justin-umesh** [middyjs/middy#830]
**Describe the bug**
Unit tests is failing with TypeError: Cannot read property 'unmarshall' of undefined 

**To Reproduce**
How to reproduce the behaviour:
1. .use(eventNormalizer())
2. npm run test
3. TypeError: Cannot read property 'unmarshall' of undefined 

**Expected behaviour**
Unit tests should be passed

**Environment (please complete the following information):**
 - Node.js: 14+
 - Middy: 2.5.7
 - AWS SDK 1.143.0

**Additional context**
Jest unit test is failing if I use 'use(eventNormalizer())' middleware in the lambda.

node_modules/@middy/event-normalizer/index.js
const {
  Converter: {
    unmarshall
  }
} = require('aws-sdk/clients/dynamodb'); // v2
// const { unmarshall } = require('@aws-sdk/util-dynamodb') // v3

if I enable the V3 code then test is getting passed.

**Comment by willfarrell** [comment]
Thanks for reporting, sounds like you're missing `aws-sdk` as a devDependency.

**Comment by justin-umesh** [comment]
Even after installing "aws-sdk": "^2.1134.0" as a devDependency I'm facing the same issue.

**Comment by willfarrell** [comment]
v3 of middy has just released and has esm support. This might help. If not, I'm not sure what the issue might be.
