### ISSUE TITLE
question(@middy/validator): can ajv validate queryStringParams as non-string types? 

### ISSUE THREAD

**Issue by A-ndy-git** [middyjs/middy#841]
**Describe the bug**

Take an example JSON schema that verifies the `queryStringParamaters` contains a `string` called `someKey`. The below schema will only validate that `someKey` is sent, disregarding whatever type it is.

```json
{
    "type": "object",
    "required": [
        "queryStringParameters"
    ],
    "properties": {
        "queryStringParameters": {
            "type": "object",
            "required": [
                "someKey"
            ],
            "additionalProperties": false,
            "properties": {
                "someKey": {
                    "type": "string"
                }
            }
        }
    }
}
```

**To Reproduce**

Send a request to an API endpoint with the above schema, using **ANY** type within `someKey`. For example:

```javascript
// this will pass validation, note it is not a string
{
        "queryParams": {
            "someKey": true
        }
    }
```

```javascript
// this will pass validation, note it is not a string
{
        "queryParams": {
            "someKey": { "someOtherKey": "someVal" }
        }
    }
```  

```javascript
// this will pass validation, note it is not a string
{
        "queryParams": {
            "someKey": true
        }
    }
```  

Same for any type, you get the picture.

**Expected behaviour**

`@middy/validator` should throw an error if the `someKey` property is **NOT** a string.

**Additional context**

An old issue #403 seemed to have a similar issue and was confirmed this is the general best-approach for the majority of Middy users. 

It appears this may be able to be resolved by overriding the default AJV options property `coerceTypes`, however after trying multiple variations it still passes validation every time.

Could anyone please shed some light on how we can use non-string properties in query params?

Thank you!

**Comment by willfarrell** [comment]
Your examples use `queryParams ` instead of `queryStringParameters` as mentioned in your schema. You would probably want `"additionalProperties": false,` at the root as well. Let's hope it's that simple. Otherwise it would be an `ajv` bug.

`coerceTypes` is enabled by default primarily for queryStringParameters to cast their strings to other types.

**Comment by A-ndy-git** [comment]
Thanks for the reply @willfarrell.

The `queryParams` field comes from the AWS API GW SDK. API GW will transform this to `queryStringParameters` at request time.

`"additionalProperties": false` at the root level will cause schema validation to fail (other properties such as `body`, 'httpMethod' etc exist.

It seems this may be a `ajv` bug as you suggested.

**Comment by A-ndy-git** [comment]
Looks like this is not a bug, but in fact intended execution order of `ajv`. From the offical docs: 

```text 
Type coercion only happens if there is type keyword and if without coercion the validation would have failed. 

If coercion to the required type succeeds then the validation continues to other keywords, otherwise the 
validation fails.
```

Source - https://ajv.js.org/coercion.html
