### ISSUE TITLE
Validator parsing value

### ISSUE THREAD

**Issue by gabbrieu** [middyjs/middy#849]
**Describe the bug**
Validator is parsing any value sent on request to string when property in input schema is defined as a string

**To Reproduce**
How to reproduce the behaviour:
1. Define a property in input schema with the desired type
2. Send a request with the wrong type in body
4. The property is converted into the type defined in input schema

**Expected behaviour**
I expect middy to throw an error when a different type is sent on the request with a message like: "expected property ... to be a boolean"

**Environment (please complete the following information):**
 - Node.js: v14.19.3
 - Middy: 3.0.3
 - AWS SDK: 2.1130.0

**Comment by willfarrell** [comment]
Middy overrides the ajv default to better reflect lambda use cases (See https://github.com/middyjs/middy/blob/main/packages/validator/index.js#L11). You can set `coerceTypes:false` to disable the type coercion and get the expected error.
