### ISSUE TITLE
Unable to pass in custom error to the middyjs onError middleware

### ISSUE THREAD

**Issue by JustCabyr** [middyjs/middy#852]
**Describe the bug**
I wouldn't necessarily call this a bug. There's a possibility I'm missing something.

**To Reproduce**
How to reproduce the behaviour:
1. Sample code '...'
`domainValidationMiddleWare.ts` - Houses the middleware
```
import { APIGatewayEvent, APIGatewayProxyResult } from 'aws-lambda';
import { HandlerLambda, MiddlewareObject } from 'middy';
import { forbiddenError } from '../../../lib/helpers/responses';
import middy from '@middy/core';

const onError = async (request: any): Promise<any> => {
  console.log(request.error)
    if (request.error.statusCode == 403) return forbiddenError('Unauthorized Request');
  return;
};

const before = async (request: any): Promise<any> => {
  const integratorPk = '';
  if (integratorPk) {
    console.log('Success');
    return;
  }

  return forbiddenError('Unauthorized Request');
};

export function domainValidationMiddleWare(): MiddlewareObject<
  APIGatewayEvent,
  APIGatewayProxyResult
> {
  return {before, onError
  };
}
```

`handler.ts` - The handler 
```
import { APIGatewayProxyEvent, Handler, APIGatewayProxyHandler } from 'aws-lambda'
import middy from '@middy/core'
import { domainValidationMiddleWare } from '../../../../../packages/middleware'

const handlerFunction: Handler = async (event: APIGatewayProxyEvent) => {
}
const getOperators: APIGatewayProxyHandler = middy(
    handlerFunction,
).use(domainValidationMiddleWare())

export { getOperators }
```

2. Scenerios
If we pass in a any value to `integratorPk`, let's assume `const integratorPk = 'value'`, this is a SUCCESS scenario and as such will be returned to the handler and the handler will execute whatever action it has been designed to perform.
However, whenever `integratorPk` is null as we have in the code shown above, a `403` is supposed to be thrown. 

3. Thrown error
The middleware automatically calls the `onError` function, it successfully logs `request.error` but doesn't return `403` to the handler. It just throws a 502. What I want to achieve is to pass the `403` back to the handler.

**Expected behaviour**
I'm expecting that whatever error is defined in the `onError` function should be returned to the handler. 

**Environment (please complete the following information):**
 - Node.js: [v16.15.1]
 - Middy: [^3.0.4]
 - AWS SDK [^2.1096.0]

**Additional context**
N/A

**Comment by willfarrell** [comment]
Here is an example of an error handler middleware: https://github.com/middyjs/middy/blob/main/packages/http-error-handler/index.js

You most likely want to set `request.response = forbiddenError('Unauthorized Request')`. This will allow other `onError` middlewares to add additional changes.
