### ISSUE TITLE
Question: How to unit test with middy (jest)

### ISSUE THREAD

**Issue by gabbrieu** [middyjs/middy#853]
I want to know how do I do the unit tests with middy and TypeScript, since we export the const with the middy validations, not the handler itself.

With that in mind, how do I call my handler function in a jest unit test file to expect an answer?

I use middy with TS, with no callback approach.

**Comment by willfarrell** [comment]
This questions isn't middy specific. I usually have my business logic in a separate file to allow for easy unit testing. Then have a few integration tests for the handler with middleware.

**Comment by robin-glimp** [comment]
@willfarrell Are there any public examples of the integration tests?
