### ISSUE TITLE
Context wanted around `http-event-normalizer` throwing behaviour on non-http events in 3.x

### ISSUE THREAD

**Issue by gsingh1** [middyjs/middy#857]
Hi @willfarrell,

I just wanted to ask for a bit of context and reasoning behind why the breaking change was introduced with middy 3.x here: 

https://github.com/middyjs/middy/blob/3.0.0/packages/http-event-normalizer/index.js#L7-L9.

Cheers

**Comment by willfarrell** [comment]
Please re-open if further discussion is needed.

**Comment by gsingh1** [comment]
> Do you have a use case where you need this middleware included, but are not sending http events? If so, why?
> 
> It could easily have been (and sill could be) a pass through when not an http event, but I felt the error would be caught early in the development cycle so that the middleware could be removed when not adding value and act as an early detection of malformed requests.

Thanks for the reply, and it makes sense. In one of our projects, we have various lambda hooked up to multiple event sources - http and non-http - and we were applying our list of various middleware using a centralised file. When we upgraded to v3, we had to conditionally apply the http middlewares as a workaround which is fine. Ref: https://github.com/fourTheorem/slic-starter/blob/main/slic-tools/middy-util.js#L21-L28

We'll probably end up refactoring so that middlewares are explicitly defined per lambda instead.

**Comment by willfarrell** [comment]
A shared middleware file is fine, but you'll want to have a separate one for each event type imo. I've been working on some docs to showcase this: https://middy.js.org/docs/events/intro
