### ISSUE TITLE
http-event-normalizer option payloadFormatVersion

### ISSUE THREAD

**Issue by Puppo** [middyjs/middy#862]
**Describe the bug**
Hi @willfarrell, in the http-event-normalizer package, there is an inconsistency. In the documentation, there is an option called `payloadFormatVersion`, but in the codebase, this option never appears. Is there a mistake in the documentation? or is there a bug in the code?
Let me know, so if you want, I can fix it.

**Comment by willfarrell** [comment]
`payloadFormatVersion` was deprecated in v3 due to it no longer being needed. Thanks for all of the fixes.
