### ISSUE TITLE
multipart: filename is double nested

### ISSUE THREAD

**Issue by nick-zh** [middyjs/middy#864]
**Describe the bug**
In my lambda, i am using:
```
handler
  .use(httpHeaderNormalizer())
  .use(httpMultipartBodyParser())
```
And in a previous function when i log the event body i got this:
```
{
  file: {
    filename: 'image.png',
    mimetype: 'image/png',
    encoding: '7bit',
    truncated: false,
    content: <Buffer>
  }
}
```
But now somehow i am getting:
```
{
  file: {
    filename: {
      filename: 'image.png',
      encoding: '7bit',
      mimeType: 'image/png'
    },
    mimetype: undefined,
    encoding: undefined,
    truncated: false,
    content: <Buffer>
  }
}
```

**Expected behaviour**
Nesting level is the same as in `2.5.7`

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: 3.0.4
 - AWS SDK: 2.1154.0

**Comment by nick-zh** [comment]
Will do, thx @willfarrell

**Comment by nick-zh** [comment]
@willfarrell it seems that the file signature has been changed in `v1.x`

**Comment by willfarrell** [comment]
Thanks for following up with them. Feels odd to have `filename.filename` to me. Would you like to create a PR to flatten the object to the way it was and create a test for this?

I imagine the code change will look something like this
```
  ...
  return new Promise((resolve, reject) => {
    busboy
      .on('file', (fieldname, file, filename) => { // change
        const {encoding, mimetype} = filename // new
        filename = filename.filename // new
        const attachment = {
          filename,
          mimetype,
          encoding
        }
        ...
 ```
