### ISSUE TITLE
http-json-body-parser: Error when headers are missing in event

### ISSUE THREAD

**Issue by nick-zh** [middyjs/middy#866]
I am not sure if this can be considered as bug per se, but if i have an event that is missing headers
i am getting: `TypeError: Cannot read property 'Content-Type' of undefined`
Now this might happen if i have a scheduler for my function to keep it warm.
i can fix this by adding `headers: null` to my scheduled event, but i was wondering if adding `undefined` to that if would be reasonable as well

**Comment by willfarrell** [comment]
There is a commented out line in `http-event-normalizer` that would correct this. However, I didn't think it was possible to receive an http event without headers. How is the lambda setup? Able to share the event? I haven't tested with the new Function URLs, maybe that's it?

**Comment by nick-zh** [comment]
Awesome, sry i missed that :v:

**Comment by willfarrell** [comment]
All good
