### ISSUE TITLE
Warmup and ssm handlers not compatible?

### ISSUE THREAD

**Issue by ricott** [middyjs/middy#870]
**Describe the bug**
After enabling the warmup handler we see ~100 of these errors per week for one of our Lambdas. Warmup runs using EventBridge every 5 mins during hours 7-23 CET.
We added warmup for another Lambda that doesn't use the ssm handler and here we don't see this error.

Sounds like the Lambda exits before the single key it reads from ssm is done? The key value is however some ~1700 chars, it is the private key for CloudFront URL signing.
```
"errorType": "TimeoutError",
"errorMessage": "Client network socket disconnected before secure TLS connection was established",
"code": "TimeoutError",
"message": "Client network socket disconnected before secure TLS connection was established",
"path": null,
"host": "ssm.eu-north-1.amazonaws.com",
"port": 443,
"time": "2022-07-05T17:55:31.942Z",
"region": "eu-north-1",
"hostname": "ssm.eu-north-1.amazonaws.com",
"retryable": true,
"stack": [
   "Error: Client network socket disconnected before secure TLS connection was established",
   "    at connResetException (node:internal/errors:692:14)",
   "    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)",
   "    at TLSSocket.emit (node:events:539:35)",
   "    at TLSSocket.emit (node:domain:475:12)",
   "    at endReadableNT (node:internal/streams/readable:1345:12)",
   "    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
```
About frequency we got this error today at these times
07:35, 8:10, 8:50, 11:50, 12:25, 13:00, 16:30, 18:45, 19:25, 19:55

**To Reproduce**
How to reproduce the behaviour:

```
exports.handler = middy(async (event, context) => {
})
    .use(warmup({
        isWarmingUp: e => e.isWarmingUp === true,
        onWarmup: e => "It's warm!"
    }))
    .use(jsonBodyParser())
    .use(validator({ eventSchema: pdfSchema.mergePdfSchema }))
    .use(
        ssm({
            cacheExpiry: 60 * 60 * 1000, // 60 mins
            fetchData: {
                SSM_PARAMS: process.env.SSM_PARAM_PATH
            },
            setToContext: true
        })
    )
    .use(errorHandler({
        logger,
        exposeStackTrace: logStackTrace()
    }
    ));
```

**Expected behaviour**
No exception

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: 3.1
 - AWS SDK: Only AWS SDK v3 packages in package.json

**Comment by willfarrell** [comment]
`ssm` during cold start will prefetch values in preparation for the first request which is why it's triggered. You can disable this with `disablePrefetch: true`.

`Error: Client network socket disconnected before secure TLS connection was established` sounds like a network issue with AWS, you should open a support ticket with them, that shouldn't be happening.

**Comment by ricott** [comment]
Thanks for the quick reply!
I'll try with the `disablePrefetch: true` and also remove 60 mins `cacheExpiry`.

**Comment by ricott** [comment]
Seem to work, no errors so far today 👍
