### ISSUE TITLE
TS: Convert internal from [key: string]: any to Generic Type Variable

### ISSUE THREAD

**Issue by vinceniko** [middyjs/middy#872]
**Is your feature request related to a problem? Please describe.**
Currently, there appears to be no way to type-check `internal` in a middy request without first type-casting prior to every use

**Describe the solution you'd like**
Add a Generic Type Variable to the Request interface i.e.
```
interface Request<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext, TInternal> {
  event: TEvent
  context: TContext
  response: TResult | null
  error: TErr | null
  internal: TInternal | {
    [key: string]: any
  }
}
```

**Describe alternatives you've considered**
Without this, internal would need to be typecast in every handler and middleware

**Comment by vinceniko** [comment]
Correction, to get proper type checking the interface can probably look something like:

```
type TInternalDefault = Record<string, any>;

interface Request<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext, TInternal = TInternalDefault> {
  event: TEvent
  context: TContext
  response: TResult | null
  error: TErr | null
  internal: TInternal
}

declare type MiddlewareFn<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext, TInternal = TInternalDefault> = (request: Request<TEvent, TResult, TErr, TContext, TInternal>) => any
```

This should allow the user to specify their own internal type or use the prior default

**Comment by willfarrell** [comment]
Would you like to open a PR to add this to `core`?

**Comment by willfarrell** [comment]
Please re-open if you plan to submit a PR for this.
