### ISSUE TITLE
http-router needs stage name in path for routes declaration

### ISSUE THREAD

**Issue by shivangag** [middyjs/middy#873]
**Describe the bug**
I'm using http-router to route GET, POST and DELETE request to `/products/{productId}` path to different handlers. I've also defined a stage dev in the API Gateway.

**To Reproduce**
How to reproduce the behaviour:
The following routes definition without stage name throws 404:
```
const routes = [
  {
    method: "GET",
    path: "/products/{productId}",
    handler: getHandler,
  },
  {
    method: "POST",
    path: "/products/{productId}",
    handler: postHandler,
  },
  {
    method: "DELETE",
    path: "/products/{productId}",
    handler: deleteHandler,
  },
];
```
While routes with stage name hard-coded in it works:
```
const routes = [
  {
    method: "GET",
    path: "/dev/products/{productId}",
    handler: getHandler,
  },
  {
    method: "POST",
    path: "/dev/products/{productId}",
    handler: postHandler,
  },
  {
    method: "DELETE",
    path: "/dev/products/{productId}",
    handler: deleteHandler,
  },
];
```

**Expected behaviour**
Ideally the stage name shouldn't be involved while defining the routes.

**Environment (please complete the following information):**
 - Node.js: [14.x]
 - Middy: [^3.1.0]
 - AWS SDK [v3]

**Comment by willfarrell** [comment]
What version of API Gateway are you using?

**Comment by shivangag** [comment]
I'm using HTTP(v2). Here is a sample event:
```  version: '2.0',
  routeKey: 'GET /products/{productId}',
  rawPath: '/dev/products/01G7EP5M2V3XCE2SVEYMTK8KT0',
  rawQueryString: '',
  headers: {
    accept: 'application/json, text/plain, */*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.5',
    'content-length': '0',
  },
  requestContext: {
    http: {
      method: 'GET',
      path: '/dev/products/01G7EP5M2V3XCE2SVEYMTK8KT0',
      protocol: 'HTTP/1.1',
    },
    routeKey: 'GET /products/{productId}',
    stage: 'dev',
  },
  pathParameters: { productId: '01G7EP5M2V3XCE2SVEYMTK8KT0' },
  isBase64Encoded: false
}
```

**Comment by willfarrell** [comment]
`routeKey` returns the allowed method, not the request method and could be `ANY` (https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-example-event).

This change would be a breaking change for everyone using it with HTTP events, it might have to wait till the next major release, if at all. Both REST and HTTP event should work the same, how will require some reflection. This makes me wonder why they included the stage within the path in v2 of the event -- maybe hinting at separation of environment using sub-accounts, making stage useless.

As a workaround you could have your routes passed into httpRouter to be prefixed with a `/{stage}` like this: `/{stage}/products/{productId}`
The path you pass in is converted to a RegExp for matching with the path.

Let me know how that works for you. If so, yourself or I can update the docs to let others know.

**Comment by KGAdamCook** [comment]
I believe Lambda Function URLs have the same event schema as the HTTP v2 event. I'll try to see what the event looks like when it's coming from an ALB. 

Perhaps the regex lookup could allow for an optional stage prefix like so? 
```
path = new RegExp(`^(\/${stage})?${path}$`);
```

**Comment by willfarrell** [comment]
Reviewing this again while putting a draft together for v4. I've opted to have it mentioned in the docs (already done) instead of handling within the code. AWS Best Practice says to have a different account per environment, so to keep things simple, we're prioritize this as the preferred approach.
