### ISSUE TITLE
Tests fail after adding middy wrapper handler

### ISSUE THREAD

**Issue by barnu5** [middyjs/middy#876]
My code before:

```
export const theLamdaFunction: APIGatewayProxyHandlerV2<
  ArrayItem[] | undefined
> = async () => {
// ...
}
```

My code after:

```
export const theLamdaFunction: APIGatewayProxyHandlerV2<ArrayItem[] | undefined> =
  middyHandler(async () => {
//...
})
```

Middy handler:
```
// export const middyHandler = (x: any) =>
//   middy(x).use(logMetrics(metrics, metricsOptions));

```

Unfortunately this now fails my jest test:

```
// Something to do with aws lamda event context
    TypeError: Cannot read properties of null (reading 'getRemainingTimeInMillis')
```

The question is, for the [provided TypeScript example](https://middy.js.org/docs/intro/typescript), how can I update my jest test to now mock the wrapper handler function? 

The original test passes, but now I need to mock the additional middy wrapper function to make it not fail.

Note if [the provided example](https://middy.js.org/docs/intro/typescript) included a jest test, that would make this much easier!

**Environment (please complete the following information):**
 - Node.js: [e.g. 16] v16.11.1
 - Middy: [e.g. 3.0.0]     "@middy/core": "^3.1.0",
 - AWS SDK [e.g. 2.1000.0]

**Comment by willfarrell** [comment]
I'm guessing that you're mocking out the context and it's set to `null`. In that case you need to mock out the context and include `getRemainingTimeInMillis` as per the error message. Alternatively you can pass in `{ timeoutEarlyInMillis: 0 }` to the plugin/options argument of `middy(x, {...})`. In v3 Middy started handling timeout errors to allow for safe aborting of your lambdaHandler.

**Comment by barnu5** [comment]
Thanks @willfarrell, fairly new to lamda.

This is great. I mocked event context and fixed the issue!
