### ISSUE TITLE
Serverless is giving a timeout error even after using callbackWaitsForEmptyEventLoop

### ISSUE THREAD

**Issue by awais000** [middyjs/middy#880]
Serverless is giving a timeout error even after using callbackWaitsForEmptyEventLoop. I consoled the value of callbackWaitsForEmptyEventLoop and it's `false`.

Here is my code.

This is the error stack. 

`{
      "errorMessage": "Timeout",
      "errorType": "Error",
      "stackTrace": [
          "Error: Timeout",
          "at Object.timeoutEarlyResponse (F:\\UpworkClient\\Zack\\gf-public-backend\\node_modules\\@middy\\core\\index.cjs:11:15)",
          "at F:\\UpworkClient\\Zack\\gf-public-backend\\node_modules\\@middy\\core\\index.cjs:97:35",
          "at async runRequest (F:\\UpworkClient\\Zack\\gf-public-backend\\node_modules\\@middy\\core\\index.cjs:89:32)",
          "at async InProcessRunner.run (file:///F:/UpworkClient/Zack/gf-public-backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:121:28)"
      ]
  }`

**Environment (please complete the following information):**
 - Node.js: 16.15.1 || 14.20.0  tried both
 - Middy: 3.1.0
 - AWS SDK 2.1177.0

I am relatively new to Serverless and I'm kinda stuck at the moment.

This is what i have tried so far. 
dynamodb+ middy => timeout
!dynamodb + middy => success
dynamodb + !middy => success
!dynamodb + !middy => success

**Comment by willfarrell** [comment]
@middy/core is triggering the timeout early, things to check:
- context.getRemainingTimeInMillis() is not working as expected (might be a bug in serverless-offline not passing it in properly)
- or set `middy(handler, {timeoutEarlyInMillis:0})` to disable the timeout


If you deploy to AWS it will run as expected.

**Comment by awais000** [comment]
Thank you so much for the help it totally fixed it.
