### ISSUE TITLE
Validator documentation might be wrong

### ISSUE THREAD

**Issue by ElMarmos** [middyjs/middy#881]
Hi I think you might have an error in the validator documentation, it says the following:

> If you'd like to have the error details as part of the response, it will need to be handled separately. You can access them from request.error.details, the original response can be found at request.error.response.

I was able to capture the validation errors in a custom middleware with the onError function, but the actual details are inside **request.error.cause** not **request.error.details**.

Am I doing something wrong?

Thanks, hope it is clear.

**Comment by willfarrell** [comment]
You are correct, must have been missed during an update. Would you like to submit a PR to correct?

**Comment by ElMarmos** [comment]
Sure, no problem.

**Comment by ElMarmos** [comment]
Just checked out the code and the documentation is actually right, the problem is in the website middy.js.org

**Comment by ElMarmos** [comment]
Never mind just found out that the docs of the website are handled separately.
