### ISSUE TITLE
error-logger middleware doesn't work

### ISSUE THREAD

**Issue by skined90** [middyjs/middy#887]
I'm using the error-logger middleware but no errors are logged in CloudWatch. I even tried to remove all other middlewares to make sure that some of them are not creating issues. When I throw an error inside lambda handler, logging works, but if I throw an error inside another file, it doesn't work as expected.

**To Reproduce**

Lambda handler
```
async function lambdaHandler(event: APIGatewayProxyEventV2): Promise<APIGatewayProxyStructuredResultV2> {
  try {
    const body = JSON.parse(event.body!);

    const email = await Email.sendEmail(body);

    return HttpResponse.buildSuccess(200, email);
  } catch (e: any) {
    if (e.code === Errors.ERR_VALIDATION_FAILED) {
      return HttpResponse.buildError(400, e);
    } else {
      return HttpResponse.buildError(500, e);
    }
  }
}

export const handler = middy(lambdaHandler).use(middlewares);
```

Email class
```
export class Email {
  /**
   * Sends an email.
   * @param sendEmail The send email object
   * @returns void Returns void promise
   */
  public static async sendEmail(sendEmail: SendEmail): Promise<void> {
    Validators.validateSendEmail(sendEmail);

    const sesHelper = SESHelper.getInstance();

    const sendEmailCommand = new SendEmailCommand({
      Message: {
        Subject: {
          Data: sendEmail.subject
        },
        Body: {
          Html: {
            Data: sendEmail.body
          }
        }
      },
      Destination: {
        ToAddresses: sendEmail.to
      },
      Source: ''
    });

    try {
      await sesHelper.send(sendEmailCommand);
    } catch (e: any) {
      throw new Error(Errors.ERR_SENDING_EMAIL);
    }
  }
}
```

**Expected behaviour**
Expecting to see error in the CloudWatch

**Environment (please complete the following information):**
 - Node.js: 14
 - Middy: 3.1.0
 - AWS SDK: 3.1

**Additional context**
Could someone please post how this should work?

**Comment by willfarrell** [comment]
The error thrown within `Email` is caught by your `lambdaHander` try/catch, which then returns a response. The `lambdaHandler` needs to throw the 400/500 error so that the `onError` middleware stack is used. `error-logger` is only applied to the `onError` middleware stack.
