### ISSUE TITLE
`http-error-handler` does not respect headers set for an HTTP Error

### ISSUE THREAD

**Issue by squ1b3r** [middyjs/middy#892]
**Describe the bug**
`createError` function from the [http-errors](https://npm.im/http-errors) package allows setting HTTP headers to be sent to the client. `http-error-handler` however, ignores those.

**To Reproduce**
How to reproduce the behaviour:
```ts
async function getTheThing() {
  throw createError(404, { message: 'Failed to get the thing', headers: { foo: 'bar' } });
}

async function theThingHandler(event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> {
  const theThing = await getTheThing();

  return {
    statusCode: StatusCodes.HTTP_STATUS_OK,
    body: JSON.stringify(theThing),
  };
}

const handler = middy(theThingHandler).use(httpErrorHandler());
```
**Current behaviour**

```JSON
{"Content-Type": "application/json"}
```

**Expected behaviour**
```JSON
{"Content-Type": "application/json", "foo": "bar"}
```

**Environment (please complete the following information):**
 - Node.js: 14.18.2
 - Middy: 3.2.2
 - AWS SDK: 2.1097.0

**Comment by willfarrell** [comment]
Should be easy to add in support for this. Would you like open a PR to have it included?

**Comment by squ1b3r** [comment]
> Should be easy to add in support for this. Would you like open a PR to have it included?

I probably could if you can point me in the right direction. I've spent some time going through the source code trying to understand how internals work, to make sure those headers are in fact ignored. I got the information that I needed but I don't think I have the full picture.
 
> Out of curiosity, what headers are you planning to attach?

We have a specific case (can't tell details, unfortunately) where if an error happens we need to pass a certain thing to the client. And due to the very long deprecation period of our clients, we have to support this for quite some time.

**Comment by willfarrell** [comment]
Likely changes are needed here:
https://github.com/middyjs/middy/blob/main/packages/http-error-handler/index.js#L36
https://github.com/middyjs/middy/blob/main/packages/http-error-handler/index.js#L42

Basically add in the spread operator for request.error.headers. A unit test will also be needed.

> We have a specific case (can't tell details, unfortunately) where if an error happens we need to pass a certain thing to the client. And due to the very long deprecation period of our clients, we have to support this for quite some time.

Fair enough

**Comment by squ1b3r** [comment]
Is there documentation somewhere about how to contribute? I cloned the repo, ran `npm install`, and then `npm run test:unit`. It spawned a few hundred node processes and locked the system to a point where I had to hard reset. Am I missing something?

**Comment by willfarrell** [comment]
It for sure shouldn't lock up a computer. `npm test` will run all tests.

I put together a quick PR for you to review an test. https://github.com/middyjs/middy/pull/893
