### ISSUE TITLE
Http-Router Middleware: Will this support APIGatewayProxyHandlerV2?

### ISSUE THREAD

**Issue by yannickrocks** [middyjs/middy#895]
**Is your feature request related to a problem? Please describe.**
I am wanting to use Aws functions URL which support V2 types. Will this middleware be upgraded ? 

The existing code is as follows:
```
import middy from '@middy/core'
import {
  APIGatewayProxyEvent,
  APIGatewayProxyResult,
  Handler as LambdaHandler
} from 'aws-lambda'

export type Method = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'ANY'

export interface Route {
  method: Method
  path: string
  handler: LambdaHandler<APIGatewayProxyEvent, APIGatewayProxyResult>
}

declare function httpRouterHandler (routes: Route[]): middy.MiddyfiedHandler

export default httpRouterHandler


```

**Comment by codyfrisch** [comment]
Well the v2 isn't as much an upgrade as it is a variant for the API Gateway for HTTP API, vs the older REST API.

The bigger problem here is the terrible TypeScript support throughout Middy, which is enough reason I am abandoning using it. The example using typescript doesnt even work for creating a middleware, as its type doesnt match what is required for a .use statement.

**Comment by willfarrell** [comment]
@yannickrocks `http-router` does support v2 (https://github.com/middyjs/middy/blob/main/packages/http-router/index.js#L88-L97), however, the type definitions may not as they are fully developed and maintained by the community. A PR to add support is most welcome.

I've replied to @codyfrisch comment over here https://github.com/middyjs/middy/issues/769#issuecomment-1235650192 . I'm happy to review a PR to improve TypeScript support across Middy.

**Comment by vicary** [comment]
@yannickrocks The router is the one I intentionally left alone in my PR, because it requires multiple levels of type inference and I have no good way to defer an easy usage here. I think I'd like your input on how it's supposed to be used for both V1 and V2 users.

This is my best idea, you may improve from here. So, given the updated type definitions below:

```ts
import middy from '@middy/core'
import {
  APIGatewayProxyEvent,
  APIGatewayProxyEventV2,
  APIGatewayProxyResult,
  APIGatewayProxyResultV2,
  Handler as LambdaHandler
} from 'aws-lambda'

export type Method = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'ANY'

export interface Route<TEvent> {
  method: Method
  path: string
  handler: LambdaHandler<TEvent, APIGatewayProxyResult>
}

declare function httpRouterHandler <TEvent extends APIGatewayProxyEvent | APIGatewayProxyEventV2 = APIGatewayProxyEvent>(routes: Route<TEvent>[]): middy.MiddyfiedHandler

export default httpRouterHandler
```

With the documented usage, the router handler knows nothing about the inferred event properties.

```ts
middy().use(...).use(...).handler(httpRouterHandler([
  // You only get APIGatewayProxyEvent here and inherits nothing from the `.use()` events
]));
```

You may hint a V2 in your handler like this, but you are creating a whole new handler for each request.

```ts
middy().handler((event, context) => httpRouterHandler<typeof event>([...])(event, context));
```

What's your thoughts?

**Comment by yannickrocks** [comment]
@vicary Thanks for the reply.

It looks good! I like the use case. Thanks for the reply everyone!

**Comment by vicary** [comment]
@willfarrell PR created.

**Comment by carlnordenfelt** [comment]
Late to the party but I have a question on the typed interfaces.

I get a typescript error when I type:
```
{
  method: 'GET',
  ...
}

// Types of property 'method' are incompatible.         
// Type 'string' is not assignable to type 'Method'.
```

Typing this solves the problem but is a little construed:
```
import { Method } from '@middy/http-router';

{
  method: 'GET' as Method,
  ...
}
```

**Two questions:**
1. Am I missing something syntactically in the above?
2. Why not instead declare `Method` as an `string-enum` and adress it as below, this would be the natural choice to me:
```
import { Method } from '@middy/http-router';

{
  method: Method.Get
}
```

Where Method is:
```
export enum Method {
  Get = 'GET',
  Post = 'POST',
  ...
```

**Comment by codyfrisch** [comment]
You're missing something. The project doesn't care about TypeScript and should just remove it until it does actually care so it doesn't break things for everyone that actually uses it.

**Comment by willfarrell** [comment]
PRs to improve TypeScript support are always welcome.

**Comment by carlnordenfelt** [comment]
I'll PR tomorrow :)

**Comment by naorpeled** [comment]
> Late to the party but I have a question on the typed interfaces.
> 
> I get a typescript error when I type:
> ```
> {
>   method: 'GET',
>   ...
> }
> 
> // Types of property 'method' are incompatible.         
> // Type 'string' is not assignable to type 'Method'.
> ```
> 
> Typing this solves the problem but is a little construed:
> ```
> import { Method } from '@middy/http-router';
> 
> {
>   method: 'GET' as Method,
>   ...
> }
> ```
> 
> **Two questions:**
> 1. Am I missing something syntactically in the above?
> 2. Why not instead declare `Method` as an `string-enum` and adress it as below, this would be the natural choice to me:
> ```
> import { Method } from '@middy/http-router';
> 
> {
>   method: Method.Get
> }
> ```
> 
> Where Method is:
> ```
> export enum Method {
>   Get = 'GET',
>   Post = 'POST',
>   ...
> ```

`method: 'GET' as const `

Should do the trick
