### ISSUE TITLE
Incorrect typescript type in @middy/http-header-normalizer

### ISSUE THREAD

**Issue by aldex32** [middyjs/middy#898]
**Describe the bug**
In version 3.2.0, a typescript type was introduced in `httpHeaderNormalizer` function. [See](https://github.com/middyjs/middy/commit/47f5f00e00d246bd1006a15e8b1de45b3979b156)
```typescript
export interface Event {
  rawHeaders: Record<string, string>
}

declare function httpHeaderNormalizer (
  options?: Options
): middy.MiddlewareObj<Event>
```
As far as I can understand, the return type of the function is incorrect. It states that the event of the MiddlewareObj is of type `Event` which is not true since the API Gateway lambda event does not have a property `rawHeaders`. `rawHeaders` is added by the middleware to the result, so probably it needs to be part of the result type.

**To Reproduce**
How to reproduce the behaviour:
1. Sample code
```typescript
const before: middy.MiddlewareFn<APIGatewayProxyEvent, APIGatewayProxyResult> = async (request): Promise<void> => {
        httpHeaderNormalizer().before?.(request);
       ...
}
```
2. Compiling error
```bash
TS2345: Argument of type 'Request<APIGatewayProxyEvent, APIGatewayProxyResult, Error, Context>' is not assignable to parameter of type 'Request<Event, any, Error, Context>'.   Property 'rawHeaders' is missing in type 'APIGatewayProxyEventBase<APIGatewayEventDefaultAuthorizerContext>' but required in type 'Event'. 
```

**Expected behaviour**
I would at least expect that the event type should be correct and not include the `rawHeaders` field, and the result type should not be narrowed to just `Event`, since it is broader than just it. Maybe something like this (not sure if it is correct):
```typescript
declare function httpHeaderNormalizer (
  options?: Options
): middy.MiddlewareObj<unknown, any & Event>
```

**Environment (please complete the following information):**
 - Node.js: [16]
 - Middy: [3.2.0]
 - AWS SDK [2.1211.0]
 - AWS lambda type - @types/aws-lambda [8.10.103]

**Comment by willfarrell** [comment]
cc @vicary

**Comment by vicary** [comment]
I am not sure I understand the sample code, the intended usage is like this:

```ts
import { APIGatewayProxyEvent } from 'aws-lambda'

export const handler = middy<APIGatewayProxyEvent>()
  .use(httpHeaderNormalizer())
  .handler(async (event) => {
    // here, `event` will be `APIGatewayProxyEvent & httpHeaderNormalizer#Event`
  });
```

@aldex32 Please elaborate on your use case, are you writing a middleware or inline middleware?

**Comment by aldex32** [comment]
@vicary your example seems to be correct.
I am creating a custom middleware which uses this middleware. As you can see in the **before** function of my middleware I am trying to call the before function of `http-header-normalizer`.
```typescript
const myMiddleware = (): MiddlewareObj<APIGatewayProxyEvent, APIGatewayProxyResult> => {

    const before: middy.MiddlewareFn<APIGatewayProxyEvent, APIGatewayProxyResult> = async (request): Promise<void> => {
        // compilation failure
        // TS2345: Argument of type 'Request<APIGatewayProxyEvent, APIGatewayProxyResult, Error, Context>' is not assignable to parameter of type 'Request<Event, any, Error, Context>'. 
        // Property 'rawHeaders' is missing in type 'APIGatewayProxyEventBase<APIGatewayEventDefaultAuthorizerContext>' but required in type 'Event'.
        await httpHeaderNormalizer().before?.(request);

        // my middleware logic
    };

    return {
        before,
    };
};
```
To me looks like that the **before** function in `httpHeaderNormalizer` is expecting an argument of type `Request<Event, any, Error, LambdaContext>` instead of `Request<APIGatewayProxyEvent, any, Error, LambdaContext>`. 
Maybe I completely misunderstand how the middleware works.

**Comment by vicary** [comment]
For what I know, middlewares should work independently from one another. Typically your middleware should not wrap others, it should define only the event type it expects.

For example if your middleware expects a `APIGatewayProxyEvent`, you write it without `http-header-normalizer` 

```ts
export const myMiddleware = (): MiddlewareObj<APIGatewayProxyEvent, APIGatewayProxyResult> => ({
  before: async (request) => {
    // your middleware logic
  }
});
```

And then compose your handlers via `.use()` with `http-header-normalizer` before yours.

```ts
export const handler = middy<APIGatewayProxyEvent>()
  .use(httpHeaderNormalizer())
  .use(myMiddleware())
  .handler(async (request) => {
    // your handler logic
  }));
```

There may be a legit use case where you want to "replace" some existing middlewares for inserting intermediate logics before it returns. But with your sample, simply calling `before` doesn't allow that. So I guess this is not your intention?

**Comment by aldex32** [comment]
The intention is to extend the middleware in question, by calling the **before** function inside another middleware. Apparently it is not supposed to work like this. Can you also confirm this @willfarrell ?
Sometime it is also nice to group different middlewares that have related logic, and avoid declaring all the middlewares to use in every handler. I know that this can be solved by exporting an array of middlewares and inject it to the handler directly. But still extending would allow to add some logic in between.

**Comment by vicary** [comment]
Oh I get it now, thanks for the explanation!

Grouping certain middlewares for usability should be possible with a new middleware under the current type system, but adding logics in-between is certainly out of that boundary.

If it was legit in JavaScript but not in TypeScript, for the immediate moment an easy escape would be casting the `request` to `any`, or simply write that single file in `.js`.

@willfarrell I'll let you decide if this should be documented, I'll update the type system around it.

**Comment by willfarrell** [comment]
Having each middleware do only one thing is best practice. Nesting middleware is possible, but I don't think it's worth the maintenance overhead and unsure how/if TypeScript will allow this easily. 

A pattern I use for my APIs is to have a shared module/library that exports an array of middleware that are the same for all lambdas (what I think @aldex32 suggested). The complexity of this approach depends on your code structure and  build process.

```js
import httpMiddlewares from '../../lib/httpMiddlwares'
...
export const handler = middy().use(...).use(httpMiddlewares).use(...).handler(...)
```

I'm curious what functionality you're wanting to extend httpHeaderNormalizer with and if it's suitable for a PR or if a self maintained fork is a better approach.

All additional documentation and examples are welcome if you think they add value to the community.

**Comment by willfarrell** [comment]
Is a PR needed for this? Or can I close?

**Comment by vicary** [comment]
I believe no type change is needed.
