### ISSUE TITLE
Issue with middy : Cannot find module '@libs/lambda' from 'src/functions/hello/handler.ts'

### ISSUE THREAD

**Issue by rzorgani** [middyjs/middy#900]
**Describe the bug**
After creating a new project with serverless and typescript, I'm trying to set up jest unit test and I have this error 

```
src/tests/hello.test.ts
  ● Test suite failed to run

    Cannot find module '@libs/lambda' from 'src/functions/hello/handler.ts'

    Require stack:
      src/functions/hello/handler.ts
      src/tests/hello.test.ts

      1 | import type { ValidatedEventAPIGatewayProxyEvent } from '@libs/api-gateway';
      2 | import { formatJSONResponse } from '@libs/api-gateway';
    > 3 | import { middyfy } from '@libs/lambda'
        | ^
      4 |
      5 | import schema from './schema';
      6 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:487:11)
      at Object.<anonymous> (src/functions/hello/handler.ts:3:1)
      at Object.<anonymous> (src/tests/hello.test.ts:1:1)
```
      
**To Reproduce**
1. Create new project with serverless 3 and typescript 
` serverless create --template aws-nodejs-typescript`
2. Add the npm required for jest  

3. jest.config.js
```
module.exports = {
  presets: ["ts-jest"],
  verbose: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageProvider: "v8",
  testEnvironment: "node",
  testTimeout: 20000,
  transform: {
    "^.+\\.(ts|tsx|js)$": "ts-jest",
  },
};
```
4. tsconfog.json
```
{
  "extends": "./tsconfig.paths.json",
  "compilerOptions": {
    "lib": ["ESNext"],
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "ES2020",
    "outDir": "lib"
  },
  "include": [
    "src/**/*.ts", 
    "serverless.ts",
    "src/tests/**/*.ts", // include tests directory
  ],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*",
    "_warmup/**/*",
    ".vscode/**/*"
  ],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```
5. hello.test.ts
```
import { main } from "../functions/hello/handler";

describe('Unit test for hello file', () => {
    it('shoud return function', async () => {
        expect(true).toBeTruthy();
        expect(typeof main).toBe('function');
    });
})
```
More details on this GitHub repo : [https://github.com/rzorgani/jest-test]

**Expected behaviour**
unit test pass without error

**Environment (please complete the following information):**
 - "node": ">=14.15.0"
 -  "@middy/core": "^2.5.3",
 -  "@middy/http-json-body-parser": "^2.5.3",

**Additional context**

**Comment by willfarrell** [comment]
Have you tried with the latest version of Middy? I'm no longer maintaining v2.x.

**Comment by rzorgani** [comment]
@willfarrell no, because when I create the project with serverless 3 and typescript I have these dependencies by default on package.json
```
"dependencies": {
    "@middy/core": "^2.5.3",
    "@middy/http-json-body-parser": "^2.5.3",
    "ramda": "^0.28.0"
  }, 
```

**Comment by willfarrell** [comment]
Are you unable to change the versions? It also looks like you're pulling from a wrapper, `@libs/lambda`, that may be introducing this issue. It says `Cannot find module @libs/lambda`, does it exist?

PS can you share the template you're using, the maintainer may not know there is a new version of middy.

**Comment by rzorgani** [comment]
@willfarrell all project on this repo : https://github.com/rzorgani/jest-test

**Comment by fernandocarrera7** [comment]
me  funciono con : 
import { formatJSONResponse } from '../../libs/api-gateway';
import { middyfy } from '../../libs/lambda';

y en tsconfig.json:

 "compilerOptions": {    
    "lib": ["ESNext"],
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "ES2020",
    "outDir": "lib",
    "allowSyntheticDefaultImports": true, 
    "esModuleInterop": true,
  },
