### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by davideicardi** [middyjs/middy#902]
On page [Upgrade 2.x -> 3.x](https://middy.js.org/docs/upgrade/2-3#core) I see:
> onError middleware stack order reversed to match after

while on [Handling Errors](https://middy.js.org/docs/intro/handling-errors) page I see:
> When there is an error, the regular control flow is stopped and the execution is moved back to all the middlewares that implemented a special phase called onError, following the order they have been attached.

From my tests it looks like `onError` callbacks are executed in reverse order, so the "Handling Errors" section is wrong and must be updated.
Correct?

In that case I think that we should also update [http-error-handler](https://middy.js.org/docs/middlewares/http-error-handler):
> This middleware should be set as the last error handler unless you also want to register the http-response-serializer. If so, this middleware should come second-last and the http-response-serializer should come last.

I expect that `http-error-handler.onError` should be called before the `http-response-serializer.onError`, to allow the serializer to format also error responses. So the suggested order should be:
- use `http-response-serializer`
- use `http-error-handler`

Con you please confirm? Thanks!

**Comment by willfarrell** [comment]
Thanks for bringing attention to this inconsistency in the documentation.

> When there is an error, the regular control flow is stopped and the execution is moved back to all the middlewares that implemented a special phase called onError, following the order they have been attached.

You are correct, this is incorrect for v3 and needs to be updated.

Would you like to create a PR to update the documentation you've identified to be incorrect?

**Comment by HazemAbdelalim** [comment]
I think should be updated soon , it's really confusing this way .
