### ISSUE TITLE
Lambda Handler type is not up-to-date

### ISSUE THREAD

**Issue by eranelbaz** [middyjs/middy#905]
**Describe the bug**
with middy v3 and the new way to handle [timeouts using AbortController](https://middy.js.org/docs/writing-middlewares/timeouts)
the lambda handler function signature has been changed to accept `{ signal }`, but, middy accepts lambda handler that accepts `Callback` as the third argument to the function - https://github.com/middyjs/middy/blob/8f4a4fec7cdd827441ed33e2b20611f5518f2767/packages/core/index.d.ts#L77

**To Reproduce**
How to reproduce the behaviour:
1. Sample code - [middy example](https://middy.js.org/docs/writing-middlewares/timeouts) with the above middy definition to accept `LambdaHandler` where the third argument is `Callback<Result>`

**Expected behaviour**
Types should be up to date and specify the relevant parameters handler function should accept with the new abort controller behaviour

**Environment (please complete the following information):**
 - Node.js: 16.10.0
 - Middy: middy core 3.3.4
 - AWS SDK (`@types/aws-lambda`) 8.10.104

**Additional context**

**Comment by eranelbaz** [comment]
Hey @willfarrell 
we'll open one in the near future

**Comment by willfarrell** [comment]
Just an FYI, we're getting close to a first alpha for middy v4. Once that happens, only security patches will be applied to v3.

**Comment by willfarrell** [comment]
Closing due to lack in interest in implementing. Please re-open if able to submit a PR.
