### ISSUE TITLE
Expose more types and provide more Typescript examples

### ISSUE THREAD

**Issue by gruckion** [middyjs/middy#907]
**Is your feature request related to a problem? Please describe.**

Serverless Framework has a template `aws-nodejs-typescript`

Which provides a function `middyfy`

```ts
import middy from "@middy/core"
import middyJsonBodyParser from "@middy/http-json-body-parser"

export const middyfy = (handler) => {
  return middy(handler).use(middyJsonBodyParser())
}
```

This is used to `middyfy` the handler.

```ts
import type { ValidatedEventAPIGatewayProxyEvent } from '@libs/apiGateway';
import { formatJSONResponse } from '@libs/apiGateway';
import { middyfy } from '@libs/lambda';

import schema from './schema';

const hello: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async (event) => {
  return formatJSONResponse({
    message: `Hello ${event.body.name}, welcome to the exciting Serverless world!`,
    event,
  });
}

export const main = middyfy(hello);
```

**Describe the solution you'd like**

1. Note that `middyfy = (handler)` has no return type nor a type for the handler parameter. I am attempting to add types to this but it appears that some times are not exposed within `index.d.ts`. So I can not access `MiddlewareHandler`

2. Even though `MiddyfiedHandler<TEvent, TResult, TErr, TContext>` is made available I run into the following issue.

Using

```ts
export const middyfy = <
  TEvent = any,
  TResult = any,
  TErr = Error,
  TContext extends LambdaContext = LambdaContext
>(
  handler: any
): MiddyfiedHandler<TEvent, TResult, TErr, TContext> => {
  return middy(handler).use(middyJsonBodyParser());
};
```

I get this;

```
Type 'MiddyfiedHandler<unknown, any, Error, any>' is not assignable to type 'MiddyfiedHandler<TEvent, TResult, TErr, TContext>'.
  Types of property 'before' are incompatible.
    Type 'AttachMiddlewareFn<unknown, any, Error, any>' is not assignable to type 'AttachMiddlewareFn<TEvent, TResult, TErr, TContext>'.
      Type 'unknown' is not assignable to type 'TEvent'.
        'TEvent' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.ts(2322)
```

Where is the requirement that `TEvent = unknown` coming from?

3. If I declare a local copy of `MiddlewareHandler`

```ts
import {
  Context as LambdaContext,
  Handler as LambdaHandler,
  Callback as LambdaCallback,
} from "aws-lambda";

type MiddyInputHandler<
  TEvent,
  TResult,
  TContext extends LambdaContext = LambdaContext
> = (
  event: TEvent,
  context: TContext,
  callback: LambdaCallback<TResult>
) => void | Promise<TResult>;

declare type MiddlewareHandler<
  THandler extends LambdaHandler<any, any>,
  TContext extends LambdaContext = LambdaContext
> = THandler extends LambdaHandler<infer TEvent, infer TResult> // always true
  ? MiddyInputHandler<TEvent, TResult, TContext>
  : never;
```

I get;

```
Type 'MiddyfiedHandler<unknown, any, Error, any>' is not assignable to type 'MiddyfiedHandler<TEvent, TResult, TErr, TContext>'.
  Types of property 'before' are incompatible.
    Type 'AttachMiddlewareFn<unknown, any, Error, any>' is not assignable to type 'AttachMiddlewareFn<TEvent, TResult, TErr, TContext>'.
      Type 'unknown' is not assignable to type 'TEvent'.
        'TEvent' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.ts(2322)
```

Again where are these unknowns coming from? The `aws-lambda` `Handler` type supports `Handler<TEvent = any, TResult = any>`. So I am not sure why it is being locked down to `unknown`. 

**Describe alternatives you've considered**

Just using `any`

**Additional context**

To be clear all I am trying to do here is make a `TYPED` function called `middyfy` which I can wrap all my lambdas with to apply a predefined set of middleware.

**Comment by willfarrell** [comment]
After some digging, it looks like serverless marked this template as legacy. It also looks like it's using an old version of Middy, which might be the source of these TypeScript errors. Serverless mentions they will accept PR to update legacy templates.

https://github.com/serverless/examples/blob/v3/legacy/aws-nodejs-typescript/package.json

**Comment by willfarrell** [comment]
PR opened to update template.
