### ISSUE TITLE
HTTP Router does not find route, if it ends with slash

### ISSUE THREAD

**Issue by Bart1909** [middyjs/middy#910]
When using the @middy/http-router and calling the lambda with a link, which ends with a slash (e.g. /mypath/{variableA}/files/) it says, the route can not be found.

The trailing slash is removed when the route is added:
https://github.com/middyjs/middy/blob/main/packages/http-router/index.js#L16

Is there any way to use the http-router instead for routes with trailing slash?

**Comment by willfarrell** [comment]
Great question, `http-router` was written with APIG in mind which, as far as I know, strips out the trailing slash during parsing. Are you using Function URLs? We're planning to move `http-router` to prefer Function URLs, they were just too new when we released the last major version.

Should be easy to add in to be more flexible, give me a few.

**Comment by willfarrell** [comment]
Will be in the next release, there is another `http-router` update planned. I'll release them together.

**Comment by Bart1909** [comment]
Thank you very much! 
No, I‘m not using function URLs.
But I‘ve another route with /mypath/{variableA}/files/{prefix+} and the calling application only skip the prefix, so the trailing slash remains..
