### ISSUE TITLE
how to create safe custom middleware 

### ISSUE THREAD

**Issue by ahmad-ali14** [middyjs/middy#911]
- I want to create a safe custom middleware, what ever happens inside this middleware should **NOT** stop the flow.
- middleware code: 

```ts
export const customMiddleWare = (options = {}) => {
  const before = async (request) => {
    // request.event is available
    try {
      console.log("🎬 🎬 🎬before", request.event);
      const event = request.event;
      const userId = event?.requestContext?.authorizer?.userId;
      if (userId) {
        try {
          throw new Error('this error should not stop the flow');
        } catch (error) {
          console.error(error);
        }
      }
    } catch (e) {
      console.error(e);
      request.error = null;
    }
  };
  const after = async (request) => {
    // request.response is available
    console.log("✅ ✅ ✅after", request.response);
  };

  const onError = (request) => {
    // request.error is available
    console.log("❌ ❌ ❌onError", request.error);
    console.error(request.error);
    // clear the error from request, so the request can continue
    request.error = null;
  };

  return {
    before,
    after,
    onError,
  };
};

```
- other middleware used:

```ts 
export function useMiddy(handler) {
  return middy(handler).use([jsonBodyParser(), httpErrorHandler(), cors(), customMiddleWare()]);
}

```
- I tried to change the order of middlewares, it did not help.
- I also catched the error at multiple levels, it did not help.
- I'm always getting 500 Internal server error
- looks like the catch block never executed at any level, is this right?
- what I'm doing wrong? 
- according to [here](https://github.dev/middyjs/middy/blob/c9fc8fce2e0b15a5b4f1d1f65b95946a779488d5/packages/core/index.js#L151) catching the error should be just fine.

**Comment by willfarrell** [comment]
`request.error = null` doesn't do anything. Other middlewares look to see if `request.response` is set, indicating `onError` is handled. In the order you're using, `httpErrorHandler` will fail to run because it expects an error object.

In v3 `after` and `onError` run from the bottom up. You want to handler the error first, see below.
```
export function useMiddy(handler) {
  return middy()
    .use([
      jsonBodyParser(), 
      cors(), 
      customMiddleWare(),
      httpErrorHandler()
    ])
    .handler(handler);
}
```

**Comment by ahmad-ali14** [comment]
@willfarrell Thank you very much; it turns out that the error is happening in the global scope during the import statement; that's why it is not being caught. 

Thanks again.
