### ISSUE TITLE
Distinguish between before and after in middleware type signatures

### ISSUE THREAD

**Issue by cyberixae** [middyjs/middy#914]
The current type signatures present in Middy core force middlewares to use the same event and result type before and after each middleware. This makes it impossible to write any properly typed middleware modules. Done correctly, the type checker should know whether or not the individual middlewares and the handler core stacked in a particular order are compatible with each other or not. Howver, that is not the case with the current type signatures.

Lets consider a JSON body parser middleware that only operates on input and converts input property `body` from a string to an arbitrary JSON structure. It should be impossible to add this middleware in the stack on the outerside of a stack that does not accept an input event with property `body` being an arbitrary JSON structure. Furthermore, it should be impossible to add other middlewares on the outerside of the extended stack, unless the new additions are able provide an input where the property `body` has type `string` ( and presumably contains serialized JSON ).

The only way to get around the problem without fixing the core type signatures is to create a mega union between all possible types that we could have at any given point throughout the stack like `{ body: string | Json }`. Because of the union type the JSON body parser needs to take into account that the body could already be parsed before the JSON body parser is called. Even worse, any middleware and the core handler need to take into account that the body might not be parsed, since the middleware can not remove `string` from type as the body is parsed.

Fixing this would require rewriting the core type signatures and making a new release that most likely breaks any compatibility with existing type signatures. I wrote some example code for a simplified JSON body parser middleware. I'm hoping this could serve as a starting point for anyone who wishes to take a jab at fixing the type signatures. Note, however, that my example is simplified and does not share the exact shape of Middy middleware calls.

The example code below includes some ideas from a loosely related [discussion](https://stackoverflow.com/questions/73758208/defining-a-generic-typescript-type-with-argument-injection/73759498) on StackOverflow.
```ts
/* Utils */

type Merge<A, B> = Omit<A, keyof B> & B;

/* Shared Definitions  */

class MiddlewareError extends Error {}

type Handler<I, O> = (i: I) => Promise<O>;

type Middleware<I, O, MI, MO> = (next: Handler<I, O>) => Handler<MI, MO>;

/* Json Body Parser */

type JsonRecord = Record<string, unknown>;

class JsonBodyParserError extends MiddlewareError {}

function assertJsonRecord(u: unknown): asserts u is JsonRecord {
  const type = Object.prototype.toString.call(u);
  const expected = '[object Object]';

  if (type !== expected) {
    throw new JsonBodyParserError(
      `Parsed Json body has type "${type}", expected type "${expected}".`,
    );
  }
}

function parseJsonRecord(s: string): JsonRecord {
  const candidate: unknown = JSON.parse(s);
  assertJsonRecord(candidate);
  return candidate;
}

type JsonBodyParserSettings = {
  strict: boolean;
};
const jsonBodyParserSettings = <S extends JsonBodyParserSettings>(s: S) => s;

type JsonBodyParserMiddleware<_S extends JsonBodyParserSettings> = <
  H extends Handler<I, O>,
  O,
  I extends { body: JsonRecord } = Parameters<H>[0],
>(
  f: H & Handler<I, O> & ({ body: JsonRecord } extends Pick<I, 'body'> ? unknown : never),
) => Handler<Merge<I, { body: string }>, O>;

type _WithJsonBodyParser = <S extends JsonBodyParserSettings>(
  s?: S,
) => JsonBodyParserMiddleware<S>;
const withJsonBodyParser: _WithJsonBodyParser = (settings) => {
  const strict = settings?.strict ?? false;

  return (next) => async (mi) => {
    const body = parseJsonRecord(mi.body);
    if (strict && Object.keys(body).length < 1) {
      throw new JsonBodyParserError(`Strict mode: Refusing empty root object.`);
    }
    const i = { ...mi, body };
    return next(i as any);
  };
};

// this infers the handler type from the settings type and core type
type WithJsonBodyParser<
  H extends Handler<any, unknown>,
  _S extends JsonBodyParserSettings | undefined = undefined,
> = H extends Handler<infer I, infer O>
  ? I extends { body: JsonRecord }
    ? Handler<Merge<I, { body: string }>, O>
    : never
  : never;

/* Usage Example */

type HelloCore = Handler<{ header: Array<string>; body: JsonRecord }, 'hello'>;
const helloCore: HelloCore = async (event) => {
  console.log('start core');
  console.log(event);
  console.log('end core');
  return 'hello';
};

type Settings = JsonBodyParserSettings & { strict: false };
const settings: Settings = jsonBodyParserSettings({ strict: false });

// type language has no curry :(
type HelloHandler = WithJsonBodyParser<HelloCore, Settings>;
const helloHandler: HelloHandler = withJsonBodyParser(settings)(helloCore);

type Main = () => Promise<void>;
const main: Main = async function () {
  const exampleInput = { header: ['foo', 'bar'], body: '{"quux": 123}' };
  console.log(exampleInput);
  const exampleOutput = await helloHandler(exampleInput);
  console.log(exampleOutput);
};

main();
```

Here is a schematic describing the model that the above code is based on.
![middy](https://user-images.githubusercontent.com/1158275/193613461-e6c81415-5267-4244-b4de-ec9f93e485d5.png)

**Comment by willfarrell** [comment]
I'm open to a breaking change to the typedefs in v4 (release date depends on AWS). I have a draft of v4 that I hope to make into an alpha in the coming weeks. At which point it will be safer to update typedefs with less risk of refactoring.

Inviting @vicary @david-preece @CaveSeal @otahontas @Puppo who have contributed to the typedefs in the past to contribute to the discussion.

**Comment by vicary** [comment]
I am all for it, the only reason I haven't done this in my last PRs is solely for v3 compatibility.

@cyberixae Would you like to start a PR? Just pick a scope you are comfortable with, I'll see what I can do after that.

**Comment by david-preece** [comment]
Great idea, I have come across this very issue before. I had no idea on where to start with this but I am happy to help contribute if we have a plan.

**Comment by vicary** [comment]
A very rough idea is to start from `core/index.d.ts`, split up the current `TEvent = any` generic into `TInputEvent` and `TOutputEvent`; `TContext` should receive the same treatment. We may even wrap them with one more abstraction, e.g. `TInputShape<TEvent, TContext>` and `TOutputShape<TEvent, TContext>`.

I can imagine a lot of interlocking nitty gritty bits popping up from there, which is only discoverable when someone actually work on it.

I don't think I have enough time to crawl through every bits by myself in the near future, but I can definitely help in a Draft PR even if it's half-way done.

**Comment by cyberixae** [comment]
I worked on a code base with Middy for a while, and filed this issue based on that experience. However, I am not working with Middy at the moment, and can't justify spending time on fixing the problem.

**Comment by willfarrell** [comment]
Closing due to lack in interest in implementing. Please re-open when able to submit a PR.

**Comment by cyberixae** [comment]
You might want to add a warning about broken type signatures to the parts of Middy documentation that mention TypeScript support. That would help people evaluate whether or not to use Middy in a TypeScript project. Or you could simply mention that there is no interest in maintaining the type signatures, and they might or might not work.

**Comment by willfarrell** [comment]
TypeScript support is 100% from the community. Any broken types are an opportunity for someone to contribute back to the OSS community. I'm happy to spend my free time reviewing PRs, including type improvements.
