### ISSUE TITLE
Failed after bundling by serverless-esbuild

### ISSUE THREAD

**Issue by vekaev** [middyjs/middy#916]
**Describe the bug**
I use serverless-esbuild to bundle and minify my project, but I received this error on CI
```
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read properties of undefined (reading 'Accept')",
  "trace": [
    "TypeError: Cannot read properties of undefined (reading 'Accept')",
    "    at httpResponseSerializerMiddlewareAfter (/var/task/src/functions/swagger.js:33581:54)",
    "    at runMiddlewares (/var/task/src/functions/swagger.js:31167:27)",
    "    at runRequest (/var/task/src/functions/swagger.js:31144:17)"
  ]
}
```

**To Reproduce**
How to reproduce the behaviour:

middify.js
```javascript
const middify = (handler) =>
    middy(handler)
        .use(httpHeaderNormalizer())
        .use(jsonBodyParser())
        .use(cors(CorsConfig))
        .use(
            httpResponseSerializer({
                defaultContentType: 'application/json',
                serializers: [
                    {
                        regex: /^application\/json$/,
                        serializer: (res) => JSON.stringify(res.body || res),
                    },
                ],
            }),
        );
```

serverless.yml
```yml
...
custom:
  esbuild:
    installExtraArgs: ['--legacy-peer-deps']
    external:
      - dd-trace
      - events
```

**Expected behaviour**

**Environment (please complete the following information):**
 - Node.js: [e.g. 16]
 - Middy: [e.g. 3.0.0]
 - AWS SDK [e.g. 2.1000.0]

**Additional context**

**Comment by willfarrell** [comment]
I would expect this kind of error during runtime and not during bundling. The error indicates that your request doesn't have `request.event.headers`. All real http requests have at least one header. Does your CI run any e2e test without full http request event?

**Comment by vekaev** [comment]
No, I got different errors in depends of commenting middleware
Also had this error 
`Cannot read properties of undefined (reading 'Accept')`

**Comment by vekaev** [comment]
I changed config but still got this issue
`{
  "errorType": "TypeError",
  "errorMessage": "Cannot read properties of undefined (reading 'Content-Type')",
  "trace": [
    "TypeError: Cannot read properties of undefined (reading 'Content-Type')",
    "    at httpJsonBodyParserMiddlewareBefore (/var/task/src/functions/swagger.js:31114:36)",
    "    at runMiddlewares (/var/task/src/functions/swagger.js:30579:27)",
    "    at async runRequest (/var/task/src/functions/swagger.js:30535:9)"
  ]
}`
```yml
  esbuild:
    installExtraArgs: ['--legacy-peer-deps']
    external: [
      'dd-trace',
      // NodeJS modules
      'events', // @middy/core
      'https', // @middy/s3-object-response @middy/util
      'stream', // @middy/http-content-encoding @middy/s3-object-response
      'util', // @middy/http-content-encoding
      'zlib', // @middy/http-content-encoding
      // AWS SDK
      'aws-sdk/clients/apigatewaymanagementapi.js', // @middy/ws-response
      'aws-sdk/clients/rds.js', // @middy/rds-signer
      'aws-sdk/clients/s3.js', // @middy/s3-object-response
      'aws-sdk/clients/secretsmanager.js', // @middy/sercrets-manager
      'aws-sdk/clients/servicediscovery.js', // @middy/service-discovery
      'aws-sdk/clients/ssm.js', // @middy/ssm
      'aws-sdk/clients/sts.js' // @middy/sts
    ]
```

**Comment by willfarrell** [comment]
Ran a quick test with `esbuild`, and it didn't throw the error you're getting above. 

**index.js**
```javascript
import httpResponseSerializer from '@middy/http-response-serializer'
export const middify = (handler) =>
  middy(handler).use(
    httpResponseSerializer({
      defaultContentType: 'application/json',
      serializers: [
        {
          regex: /^application\/json$/,
          serializer: (res) => JSON.stringify(res.body || res)
        }
      ]
    })
  )
  ```
  ```
  $ npx esbuild index.js --bundle --platform=node --format=esm --minify 
  ```
  
  `serverless-esbuild` is doing something it shouldn't be, or something else in your CI is running e2e tests with an invalid event.
  
  Closing, root issue is not in middy.
