### ISSUE TITLE
Documentation on deprecation of setToEnv

### ISSUE THREAD

**Issue by tstackhouse** [middyjs/middy#917]
**Is your feature request related to a problem? Please describe.**

There is no clear documentation on the depreciation of the setToEnv option on AWS middlewares. Having to refactor a large amount of nested code in order to then add additional options to pass through with layers of code that doesn’t need those options is tedious, where setting an environment variable keeps the call stack very clean. 

**Describe the solution you'd like**
Additional documentation in the upgrade docs outlining the rationale of the removal of the option, as well as alternative solutions. (I get that I could make my handler itself set the env or make my own middleware to do it, but that adds more boilerplate than simply having the option. 

**Describe alternatives you've considered**
I’ve searched the issues and PRs and the only discussion I’d a nebulous nod to security, which if the lambda os compromised then it doesn’t really matter where that is stored.

**Comment by willfarrell** [comment]
The deprecation of `setToEnv` is documented in the upgrade documentation along with a small snippet for those that still need the functionality (https://middy.js.org/docs/upgrade/2-3#notes).

I'll leave it to others on the web to discuss the details of why this is a security issue. https://duckduckgo.com/?q=security+risks+of+storing+secrets+in+env&atb=v337-1&ia=web

**Comment by tstackhouse** [comment]
I can’t use a reaction to 👍 that reply for some reason, but thanks for getting back on this 😄

**Comment by randomhash** [comment]
@willfarrell can we have back the actual set to env functionality?
Assumption that it's not secure within lambda env is not really applicable ^_^
