### ISSUE TITLE
Documentation for validator middleware schema flexibility

### ISSUE THREAD

**Issue by dnicolson** [middyjs/middy#918]
**Is your feature request related to a problem? Please describe.**
The ability to provide the validator schema via a function and also asynchronously. 

**Describe the solution you'd like**
Update the documentation with something to the effect of:

Existing:
```js
handler.use(validator({
  inputSchema: schema
}))
```

Alternative:
```js
const validationMiddleware = {
    return validator({
      inputSchema: responseSchema,
    }).before?.call(null, handler);
}
handler.use(validationMiddleware)
```

Full async TypeScript example:
```ts
const validationMiddleware: middy.MiddlewareObj<APIGatewayProxyWithEvent> = {
  before: async (handler: middy.Request<APIGatewayProxyWithEvent>) => {
    const responseSchema = await getSchema();

    return validator({
      inputSchema: responseSchema,
    }).before?.call(null, handler);
  },
};
```

I am wondering if there is a use case that would apply to other middlewares?

**Comment by willfarrell** [comment]
Where is `getSchema` getting the schema from that it needs to await? A URL? You could use top level await.

```
handler.use(validator({
  inputSchema: await getSchema()
}))
```

FYI nesting middlewares is not recommended.

**Comment by dnicolson** [comment]
The method `getSchema` reads from a file, some object mutations are also made. The use case doesn't necessarily need to be asynchronous though.

What would be the best practice approach here?

**Comment by willfarrell** [comment]
What I wrote above is best practice, wrapping the middleware is not needed. If you want to modify the functionality of a middleware forking it would be recommended.

**Comment by dnicolson** [comment]
Just to clairfy, I don't think that approach can be used as access to the event is needed. The use case is support for dynamic form fields, here is a more detailed example:

```ts
const validationMiddleware: middy.MiddlewareObj<APIGatewayProxyWithEvent> = {
  before: async (handler: middy.Request<APIGatewayProxyWithEvent>) => {
    const formRequest = handler.event.body as unknown as { [key: string]: string };
    const responseSchema = await getSchema(formRequest.formId);

    return validator({
      inputSchema: responseSchema,
    }).before?.call(null, handler);
  },
};
```

**Comment by willfarrell** [comment]
dynamically choosing the json schema is very different from async load a schema. Without know all the details, I'm going to guess you have a choose-your-own-adventure form (very technical term). You could create a single schema to handle all permutation using the keyword `dependencies` and `if/then` in an `allOf` where necessary (ex. https://github.com/datastreamapp/schema/blob/main/schemas/data/src/primary.json#L148). You could also use a `oneOf` with all the permutation you have. This approach also allow for it to be used client side if beneficial in your use case.

**Comment by dnicolson** [comment]
Thanks for the idea but unfortunately, that solution is not tenable. The current solution is effective, and if documenting it is against current opinion then this issue might at least help someone in a similar situation.

Also, top level async with TypeScript is no walk in the park.
