### ISSUE TITLE
Using @middy/validator adds over 1.9MB to my Lambda file size 

### ISSUE THREAD

**Issue by serverlesspolska** [middyjs/middy#920]
Hello,

First of all, great work. I've been using Middy for a few years, and it's great!

I wonder if there is a way to make `@middy/validator` smaller in terms of file size?

Adding it to my Lambda / Serverless Framework project as a dependency makes the whole `zip` file bigger by approx. 1.9MB. That's a lot.

How do you deal with that in your Lambda functions?

**Comment by willfarrell** [comment]
ajv is for the most part, a transpiler. But, also needs formats, keywords, and translation files ... There is a lot. I've addressed this by building [middy-ajv](https://github.com/willfarrell/middy-ajv) that requires pre-transpiling resulting in a much smaller bundle. I've taken this idea an integrated it into v4 (draft PR). In v4 you'll have to opt into transpiling during cold start, but still possible for those that don't want to add in an extra build step. You can view what it will likely look like in this PR (https://github.com/middyjs/middy/pull/912)
