### ISSUE TITLE
Question: How to get a path variable when using @middy/http-router 

### ISSUE THREAD

**Issue by chanan** [middyjs/middy#924]
**Describe the bug**
Trying to use @middy/http-router with serverless framework. In my serverless.yml I set ANY /{Proxy+} to point to a function that uses @middy/http-router. My roue has a variable like in the example here: https://middy.js.org/docs/routers/http-router. However, the AWS event object does not return the variable in the pathParameters object. It only has the "proxy" parameter for example:

```
pathParameters: { proxy: 'companies/597ef920-d830-4f57-95a5-7d034fe3a7e8' },
```

**To Reproduce**
1. Setup serverless with a proxy variable
2. Setup @middy/http-router
3. Setup a route the routes array with a variable
4. Question: How do you obtain the value of that variable?

**Expected behaviour**
A way to get the path variables of a route 

**Environment (please complete the following information):**
 - Node.js: 16.18
 - Middy: 3.6.0
 - Serverless 3.x

**Additional context**
Running in serverless-offline. Shouldnt matter, but just in case...

Middy middleware:

```
function applyMiddleware(handler) {
  return middy(handler)
    .use(httpErrorHandler())
    .use(cors())
    .use(jsonBodyParser())
    .use(httpEventNormalizer())
    .use(httpHeaderNormalizer())
    .use(httpSecurityHeaders());
```

**Comment by chanan** [comment]
This line seems to be the problem: https://github.com/middyjs/middy/blob/main/packages/http-router/index.js#L46
```
event.pathParameters ??= match.groups
```

The problem is that pathParameters is not empty, it already contains "proxy"

**Comment by chanan** [comment]
Adding this custom middleware has fixed it for now:

```
const removeProxy = () => {
  const removeProxyBefore = async (request) => {
    const { event } = request;
    event.pathParameters = undefined;
  };
  return {
    before: removeProxyBefore,
  };
};

const handler = middy().use(removeProxy()).handler(httpRouterHandler(routes));
```

**Comment by willfarrell** [comment]
First, I don't think we pare the proxy to pathParams within `http-router`, so that should be added in.

I'm guessing you're using API Gateway which means there are 2 solutions
a) Switch to using lambda Functions URLs
b) Add the path you want parsed to APIG and have multiple endpoints point to the same lambda
c) set pathParmas to undefined

We used the below notation to ensure we didn't introduce any breaking changes.
```
event.pathParameters ??= match.groups
```
Since APIG already does routing and parsing, you probably shouldn't be within the lambda for performance and security reasons.

**Comment by willfarrell** [comment]
>  I don't think we pare the proxy to pathParams within http-router, so that should be added in.
done, will be in next release

Since you have a work around and I don't feel middy needs any changes I will close this. Please re-open if you feel differently.
