### ISSUE TITLE
TypeError: callback is not a function at terminate (node_modules/middy/src/middy.js:152:16)

### ISSUE THREAD

**Issue by EmmanDizon** [middyjs/middy#925]
Error Encountered when running jest testing framework with middy.

test.js: 
        describe('test', () => {
          describe('GET /data', () => {
            test('should return data.', async () => {
         
          const result = await handler();
    
          const body = JSON.parse(result.body);
    
          expect(result.statusCode).toBe(200);
          expect(body.data.length).toBe(1);
        });
      });
    });

handler:

    exports.handler= middy(async (event) => {
        // logic from db calling data 
    });

middy: 

    module.exports = (fn) => {
      return middy(fn).use(jsonBodyParser()).use(httpEventNormalizer());
    };

upon running yarn run jest, the error occurs.
but when I remove the middy on handler, my test cases succeed.

**Comment by willfarrell** [comment]
Looks like you're using an old version of middy. Please upgrade by using `@middy/core` and re-try. `middy` (v0) was deprecated years ago and is no longer supported.

**Comment by EmmanDizon** [comment]
Thanks @willfarrell, will try
