### ISSUE TITLE
@middy/http-event-normalizer does not support Lambda "TEST" or Cloudwatch invocations anymore

### ISSUE THREAD

**Issue by TPME** [middyjs/middy#926]
**Describe the bug**
When I use the `@middy/http-event-normalizer` middleware, lambda test invocations (e.g. clicking on "test" in the AWS lambda console) are not supported anymore. The same applies to invocations through Cloudwatch (i.e., cronjobs). The following error is thrown:

```
{
  "errorType": "Error",
  "errorMessage": "[http-event-normalizer] Unknown http event format",
  "trace": [
    "Error: [http-event-normalizer] Unknown http event format",
    "    at httpEventNormalizerMiddlewareBefore (/var/task/node_modules/@middy/http-event-normalizer/index.cjs:16:19)",
    "    at runMiddlewares (/var/task/node_modules/@middy/core/index.cjs:126:27)",
    "    at runRequest (/var/task/node_modules/@middy/core/index.cjs:86:15)",
    "    at Runtime.middy [as handler] (/var/task/node_modules/@middy/core/index.cjs:40:16)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1028:29)"
  ]
}
```

**To Reproduce**
How to reproduce the behaviour:
1. Add `@middy/http-event-normalizer` to your middy stack.
2. Execute a basic lambda function on AWS using the "test" button.

**Expected behaviour**
As with previous versions of `@middy/http-event-normalizer`, execution works as usual and no error is thrown.

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: 3.6.0
 - AWS SDK: ^2.1231.0

**Additional context**
If this is not considered a bug, I'd be pleased about information about how to manage this use case properly. As especially Cloudwatch invocations are a big part of my applications, this is very important to me (and likely many others).

**Comment by david-preece** [comment]
I could be wrong here but from the [documentation page](https://middy.js.org/docs/middlewares/event-normalizer) it looks like a Lambda triggered by EventBridge(cron job) the `@middy/http-event-normalizer` is not needed. Like I said it could be outdated or wrong.

What is the Event JSON you are sending to your Lambda when test invoking?

**Comment by TPME** [comment]
> I could be wrong here but from the [documentation page](https://middy.js.org/docs/middlewares/event-normalizer) it looks like a Lambda triggered by EventBridge(cron job) the `@middy/http-event-normalizer` is not needed. Like I said it could be outdated or wrong.
> 
> What is the Event JSON you are sending to your Lambda when test invoking?

The event JSON is empty.

I see that argument. But how would I solve the issue considering that aspect?

**Comment by david-preece** [comment]
First, sorry I was looking in the wrong documentation:

- https://middy.js.org/docs/middlewares/http-event-normalizer/ is only used by APIGateway invocations. If you wanted to use the AWS Test feature for this you will need to input a valid APIGateway event structure.
- https://middy.js.org/docs/middlewares/event-normalizer/ is used for most of the other invocation event types. ie, SQS or SNS. It will parse the `Record/Message` of the events going into your Lambda.

So it will depend on which event(s) your Lambda is trigger by, if it is by an APIGateway use `http-event-normalizer` otherwise use `event-normalizer`. But remember that these middlewares expect a certain event structure and as such you should input that structure in the Test JSON in the AWS console.

**Comment by TPME** [comment]
I just saw in the release notes of `3.x` the following line:

> Will now throw error if not an http event in http-event-normalizer

So I take it this is not considered a bug. However, I would like to have some clarification about how to move forward with this, especially for routes that are invoked both by HTTP as well as Cloudwatch.

**Comment by david-preece** [comment]
Looking at the source for `http-event-normalizer` it will check to see if the `event.version` is either `'1.0'` or `'2.0'`. This will determine if you are using APIGateway v1 or v2.
It will then check the code below:

```javascript
const isVersionHttpEvent = {
  '1.0': (event) => typeof event.httpMethod !== 'undefined',
  '2.0': (event) => typeof event.requestContext.http.method !== 'undefined'
}
```

### V1:
It will look for the property `event.httpMethod` so use this in your Test JSON in AWS:
```JSON
{
  "version": "1.0",
  "httpMethod": "GET"
}
```

### V2:
It will look for the property `event.requestContext.http.method`. In this case use:
```JSON
{
  "version": "2.0",
  "requestContext": {
    "http": {
      "method": "GET"
    }
  }
}
```

Try to remember that in the context of your Lambda there is no difference between a "**_real_**" invocation and a "**_test_**" invocation. It will always require the bare minimum input to run successfully.

I hope this helps.
