### ISSUE TITLE
[chore] bump busboy dependency version

### ISSUE THREAD

**Issue by fbergeret95** [middyjs/middy#927]
Hello! Opened a blank issue since it's not a bug, but a vulnerability issue.

Current middy version depends on `busboy@0.3.1` which has a vulnerable dependency (`dicer`): https://github.com/advisories/GHSA-wm7h-9275-46v2

Checked newer versions of the `busboy` package and since `v1.0.0` that it does not have that dependency. Here is a list of breaking changes of v1: https://github.com/mscdex/busboy/issues/266

Maybe someone with the understanding of how is this package is used can estimate the impact of upgrading it?

Thanks

**Comment by willfarrell** [comment]
The latest version of `middy`, 3.6.1, already uses the latest version of `busboy`, 1.6.0, https://github.com/middyjs/middy/blob/main/packages/http-multipart-body-parser/package.json#L66
