### ISSUE TITLE
Unable to normalize/parse StringSet attribute of DynamoDB trigger event with eventNormalizerMiddleware

### ISSUE THREAD

**Issue by Nxtra** [middyjs/middy#928]
**Describe the bug**
The result from normalizing a DynamoDB trigger event that contains a StringSet attribute, contains and empty result for this attribute even though the StringSet has values

**To Reproduce**
How to reproduce the behaviour:
1. Sample code '...'
```
const eventNormalizerMiddleware = require('@middy/event-normalizer').default
const middy = require('@middy/core')

const handler = async (event, context) => {
  const events = event.Records

  for (const evt of events) {
    if (evt.eventName === 'INSERT') {
      const group = evt.dynamodb.NewImage
      Log.debug('New group', { group }) // This group contains the StringSet (SS) attribute
      ... 
    } else {
      return true
    }
  }
}

module.exports.handler = middy(handler)
  .use(eventNormalizerMiddleware())
```
2. Input '....'
The particular event looks like this:
```
{
      eventID: '5cd9587e141357168cb2606bab0814c5',
      eventName: 'INSERT',
      eventVersion: '1.1',
      eventSource: 'aws:dynamodb',
      awsRegion: 'eu-west-1',
      dynamodb: {
        ApproximateCreationDateTime: 1666960800,
        Keys: {
          groupId: {
            S: '01GGXXXXXXXXXX6K36'
          }
        },
        NewImage: {
          sports: {
            L: [
              {
                S: 'Basketball'
              }
            ]
          },
          name: {
            S: 'YoOOh'
          },
          groupId: {
            S: '01GGXXXXXXXXXX6K36'
          },
          admins: {
            SS: ['0e9c050b-3242-134c-b2f0-090a55f73096']
          }
        },
        StreamViewType: 'NEW_AND_OLD_IMAGES'
      }
    }
```
3.  Error
The outcome looks like this : 
```
    {
        "sports": [
            "Basketball"
        ],
        "name": "YoOOh",
        "groupId": "01GGXXXXXXXXXX6K36",
        "admins": {}
    }
```

**Expected behaviour**
I would expect the admins to contain the array of ids in the original events

```
    {
        "sports": [
            "Basketball"
        ],
        "name": "YoOOh",
        "groupId": "01GGXXXXXXXXXX6K36",
        "admins": Set([0e9c050b-3242-134c-b2f0-090a55f73096])
    }
```

**Environment (please complete the following information):**
 - Node.js: [node14]
 -  "@middy/core": "^3.6.2",
 - "@middy/event-normalizer": "^3.6.2",
 - "@middy/ssm": "^3.6.2",

**Additional context**
Did I configure the middleware correctly?
Maybe I need to pass some options to `eventNormalizerMiddleware()`?
Something else I did wrong?

**Comment by willfarrell** [comment]
Thanks for reporting. Looking at the test, https://github.com/middyjs/middy/blob/main/packages/event-normalizer/__tests__/index.js#L169, which does check SS is normalized correctly. I tried the test using `NewImage` and `OldImage` with the same correct results. I event added in the event you provided above and it normalized to what you expected. not sure what you're running into that is causing the malformed event.

Did I configure the middleware correctly? Looks like it
Maybe I need to pass some options to eventNormalizerMiddleware()? Nope
Something else I did wrong? Doesn't look like it

Nothing more I can do, unless you can make a failing unit test.

**Comment by Nxtra** [comment]
@willfarrell , thanks for the quick reply.
I ran the unit tests and extended with some specific tests for my case. 
Indeed, they all succeed! 
Gonna do some more research now and will come back if I find something.

Do you have a launch config that allows you to run and debug a specific test file in vscode? (would help me to go faster)

**Comment by willfarrell** [comment]
Sorry, I don't use VSCode. But you can run `PACKAGE=event-normalizer npm run test:unit`

PS Always surprising to hear that people use VSCode, I hope you read the fine print. https://ghuntley.com/fracture/

**Comment by Nxtra** [comment]
FYI, it was a mistake on my side. 
I used the logger from "@dazn/lambda-powertools-logger".
And this does not print out attributes of type set.
Which made me think that the result of the normalizer was empty.
