### ISSUE TITLE
The default write format value if the content is not base64encoded causes images to upload with error

### ISSUE THREAD

**Issue by rodrigomf24** [middyjs/middy#932]
**Describe the bug**
Using the `htmlMultipartBodyParser` for handling image uploads on a lambda properly parses the file, but if the file is an image the content has errors. I noticed that the default data type in this line https://github.com/middyjs/middy/blob/8318e22b7e0de530443a5b48fc54e152790b2c04/packages/http-multipart-body-parser/index.js#L95 is utf8, this is causing the image to have errors, if I swap it for binary it works. It would be great if this can be configurable.

**To Reproduce**
How to reproduce the behavior:

- create a serverless lambda with middy and inject the `htmlMultipartBodyParser` middleware
- in your lambda store the file to a temp folder and notice the image contains errors

**Expected behavior**
- the uploaded image file should be parsed without errors

**Environment (please complete the following information):**
 - Node.js: [e.g. 16]
 - Middy: [e.g. 3.0.0]
 - AWS SDK [e.g. 2.1000.0]

**Additional context**

**Comment by willfarrell** [comment]
Thanks for reporting. It used to be `binary` until someone filed a bug and became a breaking change in v3. I'd be open to a PR to the v4 branch to add in an option to override `utf8`.

**Comment by willfarrell** [comment]
New option added to the v4 branch. Big thanks to @salesh for adding in this functionality.
