### ISSUE TITLE
V4 doesn't have typescript declarations for @middy/validator/transpile

### ISSUE THREAD

**Issue by thehenrymcintosh** [middyjs/middy#944]
**Describe the bug**
When trying to migrate from v3 to v4 in a typescript project, this error occurs: TS7016: Could not find a declaration file for module '@middy/validator/transpile'.

**To Reproduce**
How to reproduce the behaviour:
1. Install middy & validator in a ts project
2. Use transpileSchema: `import { transpileSchema } from "@middy/validator/transpile";`
3. Thrown error

**Expected behaviour**
The [package.json ](https://github.com/middyjs/middy/blob/main/packages/validator/package.json#L28) file says there should be a `transpile.d.ts` file but [there isn't one in the directory](https://github.com/middyjs/middy/tree/main/packages/validator)

**Environment:**
 - Node.js: 16.13.1
 - Middy: 4.0.0

**Comment by thehenrymcintosh** [comment]
I'm not 100% sure but I think this is causing a bigger issue, which is that when importing this in typescript project, it uses the .cjs version of transpile, which requires `ajv-cmd`, and then causes `SyntaxError: Cannot use import statement outside a module` at runtime inside `ajv-cmd/index.js`

**Comment by willfarrell** [comment]
Thanks for reporting. Would you be able to create a TS file for `@middy/validator/transpile`?

**Comment by willfarrell** [comment]
I've started PR https://github.com/middyjs/middy/pull/950, please take a look and let me know if this meets your needs. Please feel free to add to it, I hacked it together.

**Comment by willfarrell** [comment]
If the PR meets your needs I can have it released this week ... just need to know from anyone ...

**Comment by thehenrymcintosh** [comment]
Hi Will, sorry for the delay getting onto this. Did a few exploratory tests with the new types and looks like they're working ok, thank you for the fix :)
