### ISSUE TITLE
Discussion: How to handle `rawBody` deprecation?

### ISSUE THREAD

**Issue by adesso-os** [middyjs/middy#945]
I was surprised to see that `rawBody` is deprecated. The [documentation describes](https://middy.js.org/docs/middlewares/http-json-body-parser) a use case that I currently have and for which I am using `rawBody` as suggested:

> If the body has been parsed as JSON, you can access the original body (e.g. for webhook signature validation) through the `request.event.rawBody`.

As this code path seems to be deprecated, I didn't see how to properly replace this with another approach.

On Gitter, it was suggested that I should just verify the payload before parsing it. However, that would require pretty drastic restructuring of how our lambdas are currently constructed. Understanding why the current use case is apparently problematic, might also help us in creating a better scaffold for ourselves for the future.

Given that our existing use case is covered in the documentation and is still part of the current version of the documentation, I assumed that a clear migration path would be offered for consumers of the existing `rawBody` approach. Ideally, I would just copy that suggested approach :)

**Comment by adesso-os** [comment]
After giving this a bit more thought, I have built a middy middleware that acts before the body parser has done its work, validates the payload, parses the event and places the result on the `context` object so I can work with it in my function body later. So far, so good.

I was looking into this approach earlier already, but the types around `middy.MiddlewareFn` are very confusing for me still. Most of the time, I'm dealing with `any` right now and have to perform loads of validation.

This is especially annoying, because in my previous solution I was purely dealing with already validated and parsed input data.

- When I want to validate the payload, I need a key from an HTTP header.
- To safely access that header value, it must have been validated.
- To validate it, I need the validator middleware, which validates not only the headers, but the entire event.
- For that to pass, the event has to be parsed already. 
- For that to happen, I need the body-parser, which replaces the `event.body` (and, with future changes, the `event.rawBody` will be gone).

I feel like this forces me into running multiple validation passes to achieve something that was fairly simple with `rawBody` still being available.

**Comment by willfarrell** [comment]
The main reason `rawBody` was removed was to be consistent with all of the other middlewares that modify the body/message/event. When dealing with dozens of different AWS event structures I felt it was would be better to not modify the event outside of the purpose of the middleware. In this case add `rawBody` when the purpose is to parse `body`. 

Having multiple validation isn't a bad thing. Starting with a simple one that validates the AWS event structure (a collection of JSON schema for all AWS events is something I've thought about putting together), then another validator for just the parsed data would allow separation of what is AWS and what is custom making maintenance easier.

Alternatively you could have a small middleware that copies the rawBody before it's parsed to anywhere you'd like.

**Comment by adesso-os** [comment]
That makes a lot of sense. Thank you for sharing those thoughts. I feel like I also agree with the thinking behind it, as manipulating other types (by adding a `rawBody` property) is something I consider to be avoided.

What deters me from running multiple validations is that I really like how comfortable the current approach is. I write a single JSON schema for the event and I can use [json-schema-to-ts](https://www.npmjs.com/package/json-schema-to-ts) to construct an amazing development experience around that single schema.

If I want to validate in two passes, I feel like that forces me to
a) author 2 JSON schemas, or
b) validate already validated data
**a** complicates the development experience and **b** might just slightly impact execution duration on the lambda and increase cost (not sure if I'm overestimating the impact of this).

That being said, your suggestion to just store the raw body myself in any way I please in a dedicated middleware is something I never considered. I will likely follow that suggestion in the short-term just to get the deprecation off my mind. Thanks :)

However, I want to note that I only recently adopted middy and was very positively surprised by what you can achieve by "just plugging middy middlewares together". Integrating middy was trivial and the benefits were enormous. In contrast, writing my first own middy middleware (in TypeScript) was a horrible experience. I am happy to blame my lack of experience in the area, but this change _felt_ like a step back to a lambda/middy newbie.

I don't want to argue to keep `rawBody`, but painting a clear picture documentation-wise on how to solve the same problem would go a long way. I'm happy to share my approach once it's complete, in case it could serve as an example.

**Comment by willfarrell** [comment]
Thanks for sharing, always useful to hear how others are using middy. 

Re: validate in two passes
a) ideally the first would be static and provided by AWS or Middy
b) the second schema would only have the validation of the parsed/modified parts of the event/context
Then, you could use a deepMerge on the two schemas before converting to ts. I haven't use dual schemas yet myself, just something I've been pondering on. If there is interest, we should open a new issue for it.

I can't help with TS, but here is a quick middleware you or others can use:
```js
export const handler = middy()
  .before((request) => {
    request.event.rawBody = request.event.body
  })
  .use(...)
  ...
  .handler(baseHandler)
```
I've added this to the migration docs and linked to this discussion to help others.

PRs to improve documentation are always welcome.

I feel we've resolved the discussion on rawBody so I'll close this issue. Please re-open if you feel otherwise.
