### ISSUE TITLE
New Middleware Proposal: AppConfig

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#949]
Proposal for a new AppConfig middleware that could pull json from multiple sources through AppConfig to internal.

See ssm for what it could look like: https://github.com/middyjs/middy/tree/main/packages/ssm

Please 👍🏻 this issue if it would have value to you. I'll build it if there > 10 👍🏻

If you can comment with your use case below, that would be helpful.

**Comment by harish-lifex** [comment]
Currently using AppConfig for some feature gating. This would be really useful.

**Comment by willfarrell** [comment]
I've created PR #962 for this. Please feel free to comment or contribute types.
