### ISSUE TITLE
Middleware must be an object containing at least one key among “before”, “after”, “onError”

### ISSUE THREAD

**Issue by vidaljuanp** [middyjs/middy#952]
**Describe the bug**
I’m trying to get started with Middy to validate input schema on AWS lambda.
The lambda function keeps throwing this error:
Middleware must be an object containing at least one key among “before”, “after”, “onError”

**To Reproduce**
How to reproduce the behaviour:
import middy from "@middy/core";
import validator from "@middy/validator";
import httpErrorHandler from "@middy/http-error-handler";
import jsonBodyParser from "@middy/http-json-body-parser";

const baseHandler = (event) => {
    const { fname, lname } = event.body;
    return {
      statusCode: 200,
      headers: { "Content-Type": "text/plain" },
      body: `Hello, ${fname}-${lname}.`,
    };
  };

const inputSchema = {
    type: "object",
    properties: {
      body: {
        type: "object",
        properties: {
          fname: { type: "string" },
          lname: { type: "string" },
        },
        required: ["fname", "lname"],
      },
    },
  };

const handler = middy(baseHandler)
    .use(jsonBodyParser())
    .use(
        validator({
        inputSchema,
        })
    )
    .use(httpErrorHandler());

export { handler };

**Expected behaviour**
I expected that the validator throws an error when the input parameters are not provided to the function.
But all it does is throwing the same  ERROR  Middleware must be an object containing at least one key among “before”, “after”, “onError”

**Environment (please complete the following information):**
    Node v18.12.1
    "@middy/core": "^4.0.2",
    "@middy/http-error-handler": "^4.0.2",
    "@middy/http-json-body-parser": "^4.0.2",
    "@middy/validator": "^4.0.2",
    "@serverless-stack/cli": "^1.17.1",
    "@serverless-stack/resources": "^1.17.1",
    "aws-cdk-lib": "2.50.0",

**Additional context**
I'm using SST framework to build the lambda and api

**Comment by willfarrell** [comment]
Change `inputSchema` to `eventSchema`. The name was changed in v3, and fully removed in v4.

See: https://middy.js.org/docs/upgrade/3-4

**Comment by vidaljuanp** [comment]
> Change `inputSchema` to `eventSchema`. The name was changed in v3, and fully removed in v4.
> 
> See: https://middy.js.org/docs/upgrade/3-4

Thanks for pointing this out. It works now.

**Comment by miladezzat** [comment]
@willfarrell you must update docs for this 😄
