### ISSUE TITLE
Improve / Fix Typescript Types in HttpRouter

### ISSUE THREAD

**Issue by dsmyda** [middyjs/middy#969]
Hey all, with the recent changes that @mdstaff did, we've been digging into properly typing our code.
It appears the current example in docs,  https://middy.js.org/docs/routers/http-router/, is not compatible with the Typescript types currently defined.

1. We should support the MiddyfiedHandler type in Route. Currently, only LambdaHandler is supported. As a result, the child middy() handlers in the example work at runtime but are not supported at type checking time. 
2. ALBEvent was recently added, we should add ALBResult as one of accepted return types. Currently, only APIGatewayProxyResult is defined.

I'll cut a PR for these changes. Thank you for the awesome open source lib!

**Comment by willfarrell** [comment]
PR welcome!

**Comment by dsmyda** [comment]
Done!

**Comment by willfarrell** [comment]
Will be in next release.
