### ISSUE TITLE
`.use()` adds 1.5s cold start time

### ISSUE THREAD

**Issue by vicary** [middyjs/middy#972]
**Describe the bug**
Recently we are doing last mile optimization on a number of functions.

We found that ANY kind of `.use()` would increase our cold start from ~400ms to ~1800ms without any obvious reason.

It does not depend on any one of the middleware used, either those come with middy (e.g. @middy/http-header-normalizer), or our own custom one triggers this issue.

We also found that a simple `middy(() => {})` or `middy().handler(() => {})` does not trigger this one, only `.use()` does it.

**To Reproduce**

1. Deploy a simple function `module.exports.handler = middy.use(cors()).handler(() => {});`
2. Run it
3. Observe the cold start time
4. Remove the middleware from the same function `module.exports.handler = middy.handler(() => {});`
5. Deploy and run it
6. Observe the difference in cold start time

**Expected behaviour**
I expect the difference in cold start time to be smaller than 50ms, instead of ~1400ms.

**Environment (please complete the following information):**
 - Node.js: Both 16 and 18
 - Middy: 3.6.2
 - AWS SDK: Stock version in Lambda

**Additional context**
N/A at the moment, will be added on investigation process.

We need help in narrowing down the searching area.

**Comment by willfarrell** [comment]
That should not be happening. There is a built-in way to debug slow middleware, just not really documented.

```
// https://github.com/middyjs/middy/blob/main/plugin/time.js
import plugin from './middleware-plugin-time.js'

const middleware = middy(plugin())
.use(...)
.handler(...)

```

One middleware that can have slow cold starts is `validator`, however, there is documentation on how to avoid this.

**Comment by willfarrell** [comment]
That is very strange, something for others to check if they run into this.
