### ISSUE TITLE
`http-response-serializer` should skip serialization if for a `content-type` header is set too right?

### ISSUE THREAD

**Issue by randytarampi** [middyjs/middy#978]
**Describe the bug**

Per the title, I think we should be checking for the lower cased and canonical https://github.com/middyjs/middy/blob/3.x/packages/http-response-serializer/index.js#L14-L15

This looks like a regression in https://github.com/middyjs/middy/commit/8db4b8cca6e43b43da1006c23c566c686484a391#diff-2a0ce32c2477551e674580840db1f401086a52fc58ead282f0a7ed9f2b160c54L16, which was fixed in [`http-json-body-parser`](https://github.com/middyjs/middy/commit/ced86fba4c6d31fee8a1c9a96ff7367274a4f087#diff-ca203e5ad9276745f9782c25c95e987d1f06e00955ac962dce5c10b342461f04) and [`http-multipart-body-parser`](https://github.com/middyjs/middy/commit/ced86fba4c6d31fee8a1c9a96ff7367274a4f087#diff-2a0ce32c2477551e674580840db1f401086a52fc58ead282f0a7ed9f2b160c54) and [`http-urlencode-body-parser`](https://github.com/middyjs/middy/commit/ced86fba4c6d31fee8a1c9a96ff7367274a4f087#diff-9f54fdd2ca6721ab5e035b6f5daf45886bf92c5f828073f77605fd2dc9861a99), but not `http-response-serializer`.

Is this an issue? Or should I upgrade my calling code to set `request.response.headers['Content-Type']` instead of `request.response.headers['content-type']`?

I'm trying to return a CSV, but I'm falling into the serializer specified by the `defaultContentType` – in this case an `application/json` `JSON.stringify`.

**To Reproduce**

1. Configure `http-response-serializer` with ``httpResponseSerializer({
          serializers: [
            {
              regex: /^application\/json$/,
              serializer: ({ body }) => JSON.stringify(body),
            },
          ],
          defaultContentType: 'application/json',
        })``
1. Return an API Gateway response with ``{
      statusCode: 200,
      body: `woof,woof\nmeow,meow\n`,
      headers: {
        'content-type': 'text/csv',
        'content-disposition': `attachment; filename=foo.csv`,
      },
    }``
1. You get a response with the headers correctly set, but with the body run through the stringifier – `"\"woof,woof\\nmeow,meow\\n\"" `

**Expected behaviour**

Steps as above, but in the final step the result is the text isn't `JSON.stringify`ed:

```
woof,woof
meow,meow

```

**Environment (please complete the following information):**

 - Node.js: 16
 - Middy: 3.6.2
 - AWS SDK: 2.1246.0

**Additional context**

N/A.

**Comment by willfarrell** [comment]
> I think we should be checking for the lower cased and canonical
totally agree, it is a regress. Want to put a quick PR together for it?

**Comment by randytarampi** [comment]
Ah, very good. I'll push something in the morning.

**Comment by willfarrell** [comment]
Thanks. You might need to add some logic to handle `request.response.headers['Content-Type'] = type` to ensure case is maintain.

**Comment by randytarampi** [comment]
Re: https://github.com/middyjs/middy/issues/978#issuecomment-1371197850:

@willfarrell, why would I need to consider casing when I'm setting it? My fix in https://github.com/middyjs/middy/pull/980 should totally short-circuit before we get to https://github.com/middyjs/middy/blob/main/packages/http-response-serializer/index.js#L39, right?

**Comment by willfarrell** [comment]
You are totally right, was thinking of something else. So many middlewares.
