### ISSUE TITLE
AsyncLocalStorage Support

### ISSUE THREAD

**Issue by Aaron-Zhao-Asurion** [middyjs/middy#986]
**Is your feature request related to a problem? Please describe.**
It seems like node async local storage store is lost in the call chain, it was working fine with middy v1 when we still have next(). Is there a way to expose the next call back to a middleware function? 

v1 (working version)
```
const contextStore = new AsyncLocalStorage();
const loggerContext = () => ({
  before: (handler, next) => {
    contextStore.run(new Map(), () => {
      next();
    });
  }
});
```

v2 (context store "new Map()" is lost without the next() callback)
```
const contextStore = new AsyncLocalStorage();
const loggerContext = () => ({
  before: (handler) => {
    contextStore.run(new Map(), () => {
      //
    });
  }
});
```

**Describe the solution you'd like**
Support AsyncLocalStorage in Middy if not already

**Describe alternatives you've considered**
n/a

**Additional context**
https://nodejs.org/api/async_context.html#class-asynclocalstorage

**Comment by willfarrell** [comment]
Adding `await` to your example should do the trick according to the NodeJS docs.

```
const contextStore = new AsyncLocalStorage();
const loggerContext = () => ({
  before: async (handler) => {
    await contextStore.run(new Map(), () => {
      //
    });
  }
});
```

NodeJS Docs:
```
async function fn() {
  await asyncLocalStorage.run(new Map(), () => {
    asyncLocalStorage.getStore().set('key', value);
    return foo(); // The return value of foo will be awaited
  });
}
```

**Comment by Aaron-Zhao-Asurion** [comment]
I tried that but unfortunately it did not work.

**Comment by willfarrell** [comment]
I'm not that familiar with `AsyncLocalStorage`. Could you not wrap the entire handler?

```
import { AsyncLocalStorage } from 'node:async_hooks'
test('Should allow use of AsyncLocalStorage in before middleware', async (t) => {
  const asyncLocalStorage = new AsyncLocalStorage()
  const middleware1 = () => ({
    before: () => {
      t.deepEqual(asyncLocalStorage.getStore(), new Map())
    }
  })

  const lambdaHandler = middy(() => {
    return true
  }).use(middleware1())

  const hander = (event, context) =>
    asyncLocalStorage.run(new Map(), () => lambdaHandler(event, context))

  await hander(event, context)
})
```

**Comment by willfarrell** [comment]
Closing, please re-open if the above approach is not working for you.
