### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by AtaTaheri** [middyjs/middy#987]
Ran into this Webpack error trying to deploy my SLS app. (Using typescript)

Just normal usecase 
```export const handler = middy(lambdaHandler).use(injectLambdaContext(logger));```

**Expected behaviour**
Should

**Environment (please complete the following information):**
 - Middy: [e.g. 4.1.0]
 - AWS SDK [e.g. 2.1294.0]

Log: 
```
ERROR in ./node_modules/@middy/core/index.js 19:26
Module parse failed: Unexpected token (19:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     };
|     plugin.timeoutEarly = plugin.timeoutEarlyInMillis > 0;
>     plugin.beforePrefetch?.();
|     const beforeMiddlewares = [];
|     const afterMiddlewares = [];
 @ ./src/functions/api.ts 2:0-32 53:23-28
 

```

**Comment by willfarrell** [comment]
What node version are you transpiling too? If it's < 16 you may want to use an older version of Middy that has better support for that node version or update your runtime and build script. I recommend the later, cause you'll have to do it eventually anyway. `?.` from `plugin.beforePrefetch?.()` is a newer syntax in node.

**Comment by AtaTaheri** [comment]
I'm using v16.13.2 on my machine and using node16 for my lambda function too

**Comment by willfarrell** [comment]
But are you transpiling to NodeJS 16 as well?

**Comment by AtaTaheri** [comment]
I was transpiling to v14
Upgraded to 16
Sadly the problem still exists

**Comment by willfarrell** [comment]
That's all of the ideas that I have. You'll have to ask the webpack team what you're missing. I'll leave open for a day or two incase others would comment.

**Comment by dave-irvine** [comment]
Shouldn't you be setting the middy packages as external? Then they never pass through webpack for transpilation.

If you don't want to do that, have you got a loader setup for `.js` files? I'm assuming as you're writing a typescript project you have a loader for `.ts`, but the middy dependency has `.js` extensions, although having said that I don't think you should need a loader for native .js syntax... my webpack is rusty.
