### ISSUE TITLE
CommonJS undefined "default" in cloudwatch-metrics middleware

### ISSUE THREAD

**Issue by ohjann** [middyjs/middy#988]
### Describe the bug
It seems that in the cloudwatch-metrics middleware the .cjs version of this package is returning `undefined` when it attempts to access the `default` property of the `aws-embedded-metrics` package.

_@middy/cloudwatch-metrics/index.cjs:_
```
...
const _awsEmbeddedMetrics = _interopRequireDefault(require("aws-embedded-metrics"));
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
const defaults = {};
const cloudwatchMetricsMiddleware = (opts = {})=>{
    const { namespace , dimensions  } = {
        ...defaults,
        ...opts
    };
    const cloudwatchMetricsBefore = (request)=>{
        const metrics = _awsEmbeddedMetrics.default.createMetricsLogger(); // <--- default undefined here
...
```

Doing a console.log of the `_awsEmbeddedMetrics` above does indeed confirm that there's no `default` property exported:
```
{
  MetricsLogger: [Getter],
  LocalSink: [Getter],
  AgentSink: [Getter],
  metricScope: [Getter],
  createMetricsLogger: [Getter],
  Unit: [Getter],
  Configuration: {
    agentEndpoint: undefined,
    debuggingLoggingEnabled: false,
    logGroupName: undefined,
    logStreamName: undefined,
    serviceName: undefined,
    serviceType: undefined,
    environmentOverride: '',
    namespace: 'aws-embedded-metrics'
  }
}
```
[The ESM index.js version of this file](https://github.com/middyjs/middy/blob/main/packages/cloudwatch-metrics/index.js) looks like it would work though we have our tsconfig setup for commonjs and it would be a big headache to change everything to ESM just for this.

This seems to be a similar issue to what has been [reported](https://github.com/middyjs/middy/issues/964) as a bug [previously](https://github.com/middyjs/middy/issues/886), though this issue is only occurring with the `cloudwatch-metrics` middleware and none of the other middy middlewares installed, I was hoping someone could shed some light onto why.

#### Sample code:
_addCloudwatchMetrics.ts:_
 ```
import cloudwatchMetrics from '@middy/cloudwatch-metrics';
import middy from '@middy/core';

export = (handler: middy.MiddyfiedHandler) => {
  handler.use(cloudwatchMetrics({
    namespace: 'our-embedded-metrics',
    dimensions: [],
  }));
};
```
#### Thrown error:
```
"TypeError: Cannot read properties of undefined (reading 'createMetricsLogger')","    at cloudwatchMetricsBefore (/Users/ohjann/Programming/our-program/node_modules/@middy/cloudwatch-metrics/index.cjs:23:53)
```

### Expected behaviour
No error occurs

### Environment (please complete the following information):
 - Node.js: v16.16.0
 - Middy: 4.0.9 (though same error occurs on middy 3)
 - AWS SDK: 2.1066.0
 - `tsc -v` : 4.8.4
_tsconfig.json:_
```
{
  "compilerOptions": {
    "lib": ["es2021"],
    "module": "commonjs",
    "target": "es2021",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "resolveJsonModule": true,
    "allowJs": true,
    "useUnknownInCatchVariables": false,
    "declaration": false,
    "strictNullChecks": true,
    "incremental": true
  },
  ...
}
```

**Additional context**
Other middy middlewares installed which work without issue, each at version 4.0.9:
- @middy/do-not-wait-for-empty-event-loop
- @middy/http-cors
- @middy/http-header-normalizer
- @middy/http-security-headers
- @middy/ssm
- @middy/sts

**Comment by willfarrell** [comment]
Not sure why swc transpiled to use that notation. Added in another cjs hack to the build process ... Let me know if you think it will meet your needs #993

**Comment by ohjann** [comment]
@willfarrell thanks for the speedy response here. That seems to have fixed it okay. Unfortunately I encountered a subsequent bug with this middleware which I've opened a new bug report for here: https://github.com/middyjs/middy/issues/998
