### ISSUE TITLE
Various Middlewares

### ISSUE THREAD

**Issue by i-am-kenny** [middyjs/middy#99]
Hey folks! I came across Middy a few days ago, and I've been slowly reorganizing one of my applications to take advantage of it. I've also generated a small library of middleware that someone else may be interested in. Take a look and feel free to give me some feedback.

https://github.com/i-am-kenny/remiddy

**Comment by lmammino** [comment]
Very very impressive job :) lots of useful middlewares in there!
It would be nice to have some of them as default middlewares directly embedded in middy. For example, your [`withDefaultHttpEvent`](https://github.com/i-am-kenny/remiddy/blob/master/src/middleware/withDefaultHttpEvent.js) would close a long time outstanding issue (#35).

Feel free to submit a PR for it!

**Comment by kevinrambaud** [comment]
hey @lmammino what about decentralizing middlewares and try to keep middy core as small as possible ? It would facilitate contribution.

**Comment by vladgolubev** [comment]
See discussion in https://github.com/middyjs/middy/issues/78#issuecomment-357492871 and below, this is where it moves

**Comment by kevinrambaud** [comment]
Great
