### ISSUE TITLE
Middy 4.1.0 causes Jest test runner to never exit. 

### ISSUE THREAD

**Issue by edgenard** [middyjs/middy#990]
**Describe the bug**
Functions that are tested with Jest test running never exit. Jest just hangs. The test runs and exits fine if the function is not wrapped.

**To Reproduce**
1. Install Middy version 4.1.0
2. Wrap a function with middy
3. Run a test with Jest
**Expected behaviour**
I expected the Jest to exit. Without wrapping the function in middy the test runs and Jest exits.

**Environment (please complete the following information):**
 - Node.js:v18.12.1
 - Middy: 4.1.0
 - AWS-SDK: ^2.1295.0,
 - Jest:^29.3.1

**Additional context**

**Comment by willfarrell** [comment]
I personally don't use Jest, so can't be much help here. I know other use Middy with Jest, so will leave open for a while to allow others to comment.

Including a sample test would be helpful for others to assist you.

**Comment by stephenkilbourn** [comment]
i see similarly.  

```
module.exports.handler = middy(async (event, context) => {
  const restaurants = await getRestaurants(context.config.defaultResults)
  const response = {
    statusCode: 200,
    body: JSON.stringify(restaurants)
  }
  return response
}).use(ssm({
  cache: true,
  cacheExpiry: 1 * 60 * 1000, // 1 mins
  setToContext: true,
  fetchData: {
    config: `/${serviceName}/${stage}/get-restaurants/config`
  }
}))
```

test file 
```
  it(`Should return an array of 8 restaurants`, async () => {
    const res = await when.we_invoke_get_restaurants()

    expect(res.statusCode).toEqual(200)
    expect(res.body).toHaveLength(8)

    for (let restaurant of res.body) {
      expect(restaurant).toHaveProperty('name')
      expect(restaurant).toHaveProperty('image')
    }
  })
```

and output from jest --detectOpenHandles

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      26 |   }
      27 |   return response
    > 28 | }).use(ssm({
         |        ^
      29 |   cache: true,
      30 |   cacheExpiry: 1 * 60 * 1000, // 1 mins
      31 |   setToContext: true,

      at processCache (node_modules/@middy/util/index.cjs:130:43)
      at ssmMiddleware (node_modules/@middy/ssm/index.cjs:126:43)
      at Object.ssm (functions/get-restaurants.js:28:8)
      at require (tests/steps/when.js:11:19)
      at Object.viaHandler [as we_invoke_get_restaurants] (tests/steps/when.js:91:20)
      at Object.we_invoke_get_restaurants (tests/test_cases/get-restaurants.test.js:13:28)
```

Node v18.12.1
  "devDependencies": {
    "@aws-sdk/client-ssm": "^3.252.0",
  "dependencies": {
    "@middy/core": "^4.0.10",
    "@middy/ssm": "^4.0.10",

**Comment by willfarrell** [comment]
@stephenkilbourn looks like you need to mock the ssm client. https://github.com/middyjs/middy/blob/main/packages/ssm/__tests__/index.js#L29

**Comment by stephenkilbourn** [comment]
@willfarrell is it not possible to use the retrieved values in my integration tests? If I mock it, wouldn't I possibly have incorrect parameter paths?

**Comment by willfarrell** [comment]
Anything is possible, but you'll likely need different configs (ie `disablePrefetch`) and the ssm to already exists in AWS which might defeat the purpose of the test. Does the lambda IAM policy need to be tested as part of the integration test? Without a lot more context, I can't advise more on a testing strategy, plus people testing goals are different.

You can specify the request params that must match for the mock.
```
mockClient(SSMClient)
      .on(GetParametersByPathCommand, {
        Path: '/dev/service_name/',
        NextToken: undefined,
        Recursive: true,
        WithDecryption: true
      })
      .resolvesOnce({
        NextToken: 'NextToken',
        Parameters: [{ Name: '/dev/service_name/key_name', Value: 'key-value' }]
      })
 ```

**Comment by stephenkilbourn** [comment]
oh, in my instance, it was the cache timer breaking the test. removing 
```
  cache: true,
  cacheExpiry: 1 * 60 * 1000
```
stops the jest open handle.

**Comment by lmserrano** [comment]
Thank you for sharing your solution @stephenkilbourn . I've also come across this issue and I've opened PR [Update Testing docs with importance of disabling cache #996](https://github.com/middyjs/middy/pull/996) with associated Testing page documentation changes, to make it easier for people to converge to this.
