### ISSUE TITLE
Middy 4.1.0 doesn't work unless aws-sdk/client-ssm is installed

### ISSUE THREAD

**Issue by edgenard** [middyjs/middy#991]
**Describe the bug**

**To Reproduce**
How to reproduce the behaviour:
1. `npm i @middy/core && npm i @midd/ssm`
2. Wrap a function with middy and use ssm
3. Error :  `Cannot find module '@aws-sdk/client-ssm' from 'node_modules/@middy/ssm/index.cjs'`

**Expected behaviour**
I expected Middy to run without having to install `@aws-sdk/client-ssm` separately.

**Environment (please complete the following information):**
 - Node.js: v18.12.1
 - Middy: ^4.1.0
 - AWS SDK: ^2.1295.0,

**Additional context**

**Comment by willfarrell** [comment]
Please see the docs: https://middy.js.org/docs/middlewares/ssm#install . As of v4 we've switch to using the new SDK version to match the new node.js runtime which only includes @aws-sdk/*.  Like previous version of Middy, the AWS SDK continues to be a dev dependency to give you full control over the version and whether you'd like to bundle it or not.
