### ISSUE TITLE
Could not read source map: source maps not bundled, but referenced

### ISSUE THREAD

**Issue by squidfunk** [middyjs/middy#997]
**Describe the bug**

Source maps are not bundled with Middy.js, but referenced via `sourceMappingURL`, which results in errors when debugging in IDEs like Visual Studio Code that use source maps for mapping breakpoints to their original locations:

```
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/util/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/util/index.js.map'
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/http-error-handler/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/http-error-handler/index.js.map'
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/http-header-normalizer/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/http-header-normalizer/index.js.map'
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/http-json-body-parser/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/http-json-body-parser/index.js.map'
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/http-response-serializer/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/http-response-serializer/index.js.map'
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/http-router/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/http-router/index.js.map'
Could not read source map for file:///Users/squidfunk/.../node_modules/%40middy/http-urlencode-body-parser/index.js: ENOENT: no such file or directory, open '/Users/squidfunk/.../bot/node_modules/@middy/http-urlencode-body-parser/index.js.map'
```

**To Reproduce**

No reproduction, since I'm not sure what you need here. It's basically just a launch configuration (which sadly I can't share) for a simple Lambda function using Middy.js

**Expected behaviour**

No errors.

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: 4.2.1 (latest)
 - AWS SDK: not relevant

**Additional context**

The problem can be fixed by removing the `sourceMappingURL` at the end of each file:

```
//# sourceMappingURL=index.js.map
```

I'm not sure where those lines are added in the build/release process, since Middy.js appears to be written in JavaScript, but either bundling the source maps with the release, or removing the line will fix the issue 😊 Happy to PR with a little guidance!

**Comment by squidfunk** [comment]
I believe the error might be triggered during the release:

https://github.com/middyjs/middy/blob/28916ee964f27e7eb02ae703aa589d7144729357/.github/workflows/release.yml#L38-L45

**Comment by willfarrell** [comment]
Because nodejs doesn't support source maps (yet?), they are removed during build to keep package sizes lean.

I wasn't able to figure out how to tell swc to bundle and have source maps be external (in esbuild it's done with `--sourcemap=external`). Having a PR to update the config to not include the comment or source maps entirely would be my preferred approach.

**Comment by squidfunk** [comment]
Node.js added source map support in v12. They can be enabled with the [`--enable-source-maps`](https://nodejs.org/docs/latest-v16.x/api/cli.html#--enable-source-maps) runtime flag. However, I understand that you might not want to bundle them and will look into whether we can tell SWC to omit the comment.

**Comment by squidfunk** [comment]
It seems to be related to SWC ignoring the source maps setting. I filed an issue upstream.

**Comment by squidfunk** [comment]
🎉 The upstream issue was fixed – looks like it was a bug in SWC's CLI. Thus, one of the next releases should automatically resolve this issue, as source maps are already correctly configured as disabled.

**Comment by willfarrell** [comment]
Thanks for this!

**Comment by willfarrell** [comment]
When `[--enable-source-maps](https://nodejs.org/docs/latest-v16.x/api/cli.html#--enable-source-maps)` is enabled by default, we can add add source maps in.
