### ISSUE TITLE
Undefined error in aws-embedded-metrics when following cloudwatch-metrics docs

### ISSUE THREAD

**Issue by ohjann** [middyjs/middy#998]
**Describe the bug**
The [cloudwatch-metrics docs](https://middy.js.org/docs/middlewares/cloudwatch-metrics/#options) mention:
> You can provide an empty array to record all metrics without dimensions.

when using the middleware. Unfortunately this causes an error with the `aws-embedded-metrics` package where [`aws-embedded-metrics-node/src/utils/Validator.ts`](https://github.com/awslabs/aws-embedded-metrics-node/blob/master/src/utils/Validator.ts#L35) expects an object but [what's passed by the middy middleware is undefined](https://github.com/middyjs/middy/blob/main/packages/cloudwatch-metrics/index.js#L17).

**To Reproduce**
How to reproduce the behaviour:
1. Sample code:
```
const middy = require('@middy/core')
const cloudwatchMetrics = require('@middy/cloudwatch-metrics')

const handler = middy((event, context) => {
  context.metrics.putMetric('ProcessingLatency', 100, 'Milliseconds')
  context.metrics.setProperty(
    'RequestId',
    '422b1569-16f6-4a03-b8f0-fe3fd9b100f8'
  )
})

handler.use(
  cloudwatchMetrics({
    namespace: 'myAppliction',
    dimensions: []
  })
)
```
2. Thrown error
```
"TypeError: Cannot convert undefined or null to object","    at Function.keys (<anonymous>)","    at validateDimensionSet (/Users/ohjann/Programming/my_package/node_modules/aws-embedded-metrics/lib/utils/Validator.js:39:16)
```

**Expected behaviour**
Either the docs need to be updated so reflect the fact that passing an empty array is not the correct way to configure this or the code needs to be updated to allow an empty array to work correctly.

**Environment (please complete the following information):**
 - Node.js: 16.16.0
 - Middy: 4.2.1
 - AWS SDK: 2.1066.0

**Additional context**
I was able to get it to work as expected by passing an array with an empty object like so:
```
handler.use(
  cloudwatchMetrics({
    namespace: 'myAppliction',
    dimensions: [{}]
  })
)
```

**Comment by willfarrell** [comment]
Not setting `dimensions` in middy will get your required result, but we should update to having it better match the AWS docs. Would you like to put a PR together, update the default to `dimensions:[]` and the logic to reflect?

**Comment by ohjann** [comment]
@willfarrell PR opened here, let me know if there's any questions or concerns about it https://github.com/middyjs/middy/pull/1000
