### ISSUE TITLE
Making the readme example work for latest AWS

### ISSUE THREAD

**Issue by suntong** [middyjs/middy#999]
AWS default lambda function has moved to ESM module, and the index file is now named `index.mjs`. Here is my `index.mjs`:

```js
import middy from '@middy/core'
import httpRouterHandler from '@middy/http-router'
//import validatorMiddleware from '@middy/validator'

const getHandler = middy()
//  .use(validatorMiddleware({eventSchema: {...} }))
  .handler((event, context) => {
    return {
      statusCode: 200,
      body: '{...}'
    }
  })

const postHandler = middy()
//  .use(validatorMiddleware({eventSchema: {...} }))
  .handler((event, context) => {
    return {
      statusCode: 200,
      body: '{...}'
    }
  })

const routes = [
  {
    method: 'GET',
    path: '/user/{id}',
    handler: getHandler
  },
  {
    method: 'POST',
    path: '/user',
    handler: postHandler
  }
]

export const handler = middy()
  //.use(httpHeaderNormalizer())
  .handler(httpRouterHandler(routes))
```

Basically taken straight from readme, but when I tried it, I got:

```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
    "Require stack:",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
    "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
    "    at async start (file:///var/runtime/index.mjs:1200:23)",
    "    at async file:///var/runtime/index.mjs:1206:1"
  ]
}
```

Why is that and how to fix it pls? thx

**Comment by suntong** [comment]
And I tried the `index.js`
_Originally posted by @willfarrell in https://github.com/middyjs/middy/issues/916#issuecomment-1270706282_

> **index.js**
> 
> ```js
> import httpResponseSerializer from '@middy/http-response-serializer'
> export const middify = (handler) =>
>   middy(handler).use(
>     httpResponseSerializer({
>       defaultContentType: 'application/json',
>       serializers: [
>         {
>           regex: /^application\/json$/,
>           serializer: (res) => JSON.stringify(res.body || res)
>         }
>       ]
>     })
>   )
> ```

and get the exact same error:

    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'

**Comment by willfarrell** [comment]
If you're bundling your package.json, you need to set `"type":"module"` within it. If your lambda is set to `index.handler`, `export const handler = ...` within `index.mjs` should work just fine. Does a lambda work without middy when setup with a similar pattern?

**Comment by suntong** [comment]
Here is how it should be:

![image](https://user-images.githubusercontent.com/422244/215843612-71ca6084-217e-4edf-8318-7355f6cdbb4b.png)

I.e., 

- No need to set "type":"module" within package.json, as there is none
- Use `index.mjs`, as what I did in OP.
- Use `export const handler = async(event) => `

I.e., I don't understand why _"export const handler = ... within index.mjs should work just fine"_, please elaborate with full code. If you meant to change the line `export const middify = (handler) =>` in my OP, then I don't understand why it could be working as the two exports are taking entirely different parameters.

Thanks for your help.

```js
export const handler = async(event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};

```
